// syncfusionejs2_trial/Samples/React/src/card/tile.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.Tile = void 0;
var ReactDOM = require("react-dom");
var React = require("react");
var sample_base_1 = require("../common/sample-base");
var data_source_1 = require("./data-source");
var ej2_dropdowns_1 = require("@syncfusion/ej2-dropdowns");
var ej2_data_1 = require("@syncfusion/ej2-data");
require("./card.component.css");
var card;
var cardEle;
var cardObj = data_source_1.cardBook;
var data = [];
var multiSelectData = [];
var searchData = [];
var searchValCount = 0;
var filterCategory = [{ Name: 'Client-Side', Code: 'client' }, { Name: 'Server-Side', Code: 'server' }, { Name: 'Front-End', Code: 'ui' }];
var emptyData = true;
/*  Initialize MultiSelect component */
var multiselectComp;
function cardRendering(cardObj) {
    var errorContent = document.querySelector('.tile_layout .row.error');
    if (cardObj.length > 0) {
        errorContent.style.display = 'none';
        cardObj.forEach(function (data, index) {
            cardEle = document.getElementById('card_sample_' + (++index));
            if (cardEle) {
                ReactDOM.render(React.createElement(CardRender, { data: data }), cardEle);
            }
        });
    }
    else {
        errorContent.style.display = 'flex';
    }
}
/* Funtion for Destroying Cards */
function destroyAllCard() {
    var cards = document.querySelectorAll('.card-control-section .e-card');
    [].slice.call(cards).forEach(function (el) {
        ReactDOM.unmountComponentAtNode(el.parentElement);
    });
}
var Tile = /** @class */ (function (_super) {
    __extends(Tile, _super);
    function Tile() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Tile.prototype.rendereComplete = function () {
        var _this = this;
        multiselectComp = new ej2_dropdowns_1.MultiSelect({
            // set the local data to dataSource property
            dataSource: filterCategory,
            // map the appropriate columns to fields property
            fields: { text: 'Name', value: 'Code' },
            // set the placeholder to MultiSelect input element
            placeholder: 'Search by categories',
            select: this.multiSelectFun,
            removed: this.multiSelectRemove,
        });
        multiselectComp.appendTo('#local');
        cardRendering(cardObj);
        document.getElementById('search_Card').onkeyup = function (e) {
            if (e.code === 'Tab' || e.code === 'Escape' || e.code === 'ShiftLeft' || (e.code === 'Backspace' && emptyData)) {
                return;
            }
            var inputVal = e.target.value;
            inputVal.length === 0 ? emptyData = true : emptyData = false;
            _this.searchFilter(inputVal);
        };
    };
    /* Remove event function for multiSelect component */
    Tile.prototype.multiSelectRemove = function (e) {
        var cardDa = searchData.length > 0 ? searchData : (multiSelectData.length > 0 ? multiSelectData : cardObj);
        if (multiselectComp.value && multiselectComp.value.length === 0 && searchValCount === 0) {
            multiSelectData = cardDa;
            destroyAllCard();
            cardRendering(cardObj);
        }
        else if (multiselectComp.value.length === 0 && searchValCount > 0) {
            this.searchFilter(document.getElementById('search_Card').value);
        }
        else if (multiselectComp.value.length === 0) {
            destroyAllCard();
            multiSelectData = cardDa;
            cardRendering(cardDa);
        }
        else {
            var keywords = e.itemData.Code.split(',');
            var dublicate_1;
            keywords.forEach(function (key) {
                dublicate_1 = new ej2_data_1.DataManager(cardObj).executeLocal(new ej2_data_1.Query().where('cardImage.tag', 'Contains', key, true));
                dublicate_1.forEach(function (da) {
                    if (cardDa.indexOf(da) !== -1) {
                        cardDa.splice(cardDa.indexOf(da), 1);
                    }
                });
                multiSelectData = cardDa;
            });
            destroyAllCard();
            cardRendering(multiSelectData);
        }
    };
    Tile.prototype.multiSelectFun = function (e) {
        var keywords = e.itemData.Code.split(',');
        var dublicate;
        var cardDa = searchData.length > 0 ? searchData : cardObj;
        if (multiselectComp.value && multiselectComp.value.length === 0 && searchValCount === 0) {
            multiSelectData = [];
        }
        keywords.forEach(function (key) {
            dublicate = new ej2_data_1.DataManager(cardDa).executeLocal(new ej2_data_1.Query().where('cardImage.tag', 'Contains', key, true));
            if (dublicate.length === 0) {
                multiSelectData = [];
                destroyAllCard();
                return;
            }
            dublicate.forEach(function (da) {
                if (multiSelectData.indexOf(da) === -1) {
                    multiSelectData.push(da);
                }
            });
        });
        destroyAllCard();
        cardRendering(multiSelectData);
    };
    /* Function for Filtering Cards */
    Tile.prototype.searchFilter = function (key) {
        searchValCount = key.length;
        var predicate = new ej2_data_1.Predicate('cardContent', 'Contains', key, true);
        predicate = predicate.or('cardImage.title', 'Contains', key, true).or('header_title', 'Contains', key, true).or('header_subtitle', 'Contains', key, true);
        var cardDa = (multiSelectData.length > 0 && multiselectComp.value.length > 0) ? multiSelectData : cardObj;
        searchData = data = new ej2_data_1.DataManager(cardDa).executeLocal(new ej2_data_1.Query().where(predicate));
        destroyAllCard();
        cardRendering(data);
    };
    Tile.prototype.render = function () {
        return (React.createElement("div", { className: 'control-pane' },
            React.createElement("div", { className: "control-section card-control-section tile_layout" },
                React.createElement("div", { className: "row filter" },
                    React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                        React.createElement("div", { className: "e-float-input" },
                            React.createElement("input", { type: "text", required: true, id: "search_Card" }),
                            React.createElement("span", { className: "e-float-line" }),
                            React.createElement("label", { className: "e-float-text", style: { fontSize: '14px' } }, "Enter text to search"))),
                    React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6 tile_search" },
                        React.createElement("input", { type: "text", id: "local" }))),
                React.createElement("div", { className: 'row e-card-layout', style: { textAlign: 'center' } },
                    React.createElement("div", { className: "row" },
                        React.createElement("div", { className: "row error", style: { display: 'none', minHeight: '150px' } },
                            React.createElement("div", { className: "e-error-content", style: { margin: 'auto', height: 'inherit', fontSize: '18px', fontWeight: 500, color: 'inherit' } }, "No results found. Please try a different search.")),
                        React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                            React.createElement("div", { id: 'card_sample_1', className: 'card_sample' })),
                        React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                            React.createElement("div", { id: 'card_sample_2', className: 'card_sample' })),
                        React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                            React.createElement("div", { id: 'card_sample_3', className: 'card_sample' })),
                        React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                            React.createElement("div", { id: 'card_sample_4', className: 'card_sample' })),
                        React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                            React.createElement("div", { id: 'card_sample_5', className: 'card_sample' })),
                        React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                            React.createElement("div", { id: 'card_sample_6', className: 'card_sample' })),
                        React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                            React.createElement("div", { id: 'card_sample_7', className: 'card_sample' })),
                        React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                            React.createElement("div", { id: 'card_sample_8', className: 'card_sample' })),
                        React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                            React.createElement("div", { id: 'card_sample_9', className: 'card_sample' })),
                        React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                            React.createElement("div", { id: 'card_sample_10', className: 'card_sample' })),
                        React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                            React.createElement("div", { id: 'card_sample_11', className: 'card_sample' })),
                        React.createElement("div", { className: "col-xs-6 col-sm-6 col-lg-6 col-md-6" },
                            React.createElement("div", { id: 'card_sample_12', className: 'card_sample' })))),
                React.createElement("div", { id: 'source_link' },
                    "Source: \u00A0",
                    React.createElement("a", { href: "https://www.syncfusion.com/ebooks/", target: '_blank' }, "https://www.syncfusion.com/ebooks"))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null,
                    "This sample demonstrates filter and search of the ",
                    React.createElement("code", null, "card"),
                    " based on categories, and text containing the card. You can use search box to search cards, and you can filter choosing categories in multi-select component.")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null,
                    "Card is a small container in which user can show defined content in a specific structure, and it is flexible and extensible. This sample demonstrates how to render the ",
                    React.createElement("code", null, "Card"),
                    " using",
                    React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/documentation/common/template-engine/" }, " Template Engine"),
                    " and it can be filtered based on",
                    React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/data/getting-started/" }, "data Manager"),
                    "."),
                React.createElement("p", null,
                    "More information about Card can be found in this",
                    React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/card/getting-started/" }, "documentation"),
                    " section."))));
    };
    return Tile;
}(sample_base_1.SampleBase));
exports.Tile = Tile;
var CardRender = /** @class */ (function (_super) {
    __extends(CardRender, _super);
    function CardRender() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    CardRender.prototype.render = function () {
        this.headerTitleSubCheck = this.props.data.header_title.length > 0 || this.props.data.header_subtitle.length > 0;
        this.headerCheck = this.props.data.header_title.length > 0 || this.props.data.header_subtitle.length > 0 || this.props.data.header_img.length > 0;
        this.bgimageUrl = "url(" + this.props.data.cardImage.url + ")";
        return (React.createElement("div", { className: this.props.data.isHorizontal ? 'e-card e-card-horizontal' : 'e-card' },
            this.props.data.cardImage && React.createElement("div", { className: 'e-card-image', style: { backgroundImage: this.bgimageUrl } },
                " ",
                this.props.data.cardImage.title && React.createElement("div", { className: 'e-card-title' }, this.props.data.cardImage.title),
                " "),
            this.props.data.cardTitle && React.createElement("div", { className: 'e-card-title' }, this.props.data.cardTitle),
            this.headerCheck &&
                React.createElement("div", { className: 'e-card-header' },
                    this.props.data.header_img && React.createElement("div", { className: this.props.data.header_img.isRounded ? 'e-card-header-image e-card-corner' : 'e-card-header-image e-card-corner' }),
                    this.headerTitleSubCheck &&
                        React.createElement("div", { className: 'e-card-header-caption' },
                            this.props.data.header_title && React.createElement("div", { className: 'e-card-header-title' }, this.props.data.header_title),
                            this.props.data.header_subtitle && React.createElement("div", { className: 'e-card-sub-title' }, this.props.data.header_subtitle))),
            this.props.data.cardContent && React.createElement("div", { className: 'e-card-content' }, this.props.data.cardContent),
            this.props.data.card_action_btn &&
                React.createElement("div", { className: this.props.data.card_action_btn.isVertical ? 'e-card-actions e-card-vertical' : 'e-card-actions' }, this.props.data.card_action_btn.action_btns.map(function (actBtn) {
                    return actBtn.tag === "a" ? React.createElement("a", { key: actBtn.text, href: actBtn.href, target: actBtn.target, className: 'e-btn e-outline e-primary' },
                        " ",
                        actBtn.text) : React.createElement("button", { key: actBtn.text, className: 'e-card-btn' }, actBtn.text);
                }))));
    };
    return CardRender;
}(React.Component));

// syncfusionejs2_trial/Samples/Vue/public/source/card/tile.vue
<template>
  <div class="control-section card-control-section tile_layout">
    <div class="row filter">
      <div class="col-xs-6 col-sm-6 col-lg-6 col-md-6">
        <div class="e-float-input">
          <input type="text" required="" id="search_Card" v-on:keyup="onInputKeyup" />
          <span class="e-float-line"></span>
          <label class="e-float-text">Enter text to search</label>
        </div>
      </div>
      <div class="col-xs-6 col-sm-6 col-lg-6 col-md-6 tile_search">
        <ejs-multiselect id='local' :dataSource='filterCategory' :fields='multiSelectFields' placeholder='Search by categories' :tagging='filterData' :removed='filterData'>
        </ejs-multiselect>
      </div>
    </div>
    <div class="row e-card-layout" style="text-align:center;">
      <div class="row">
        <div class="row error" v-if="cardData.length === 0 || cardData === null">
          <div class="e-error-content">
            No results found. Please try a different search.
          </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-lg-6 col-md-6" v-for="(item, index) in cardData" v-bind:key="index">
          <div class="e-card" v-bind:class="{ 'e-card-horizontal': item.isHorizontal }">
            <div class="e-card-image" v-if="item.cardImage !== null" v-bind:style="{ backgroundImage: 'url(' + item.cardImage.url + ')' }">
            </div>
            <div class="e-card-header" v-if="item.header_title !== null || item.header_subtitle !== null">
              <div class="e-card-header-caption" v-if="item.header_title !== null || item.header_subtitle !== null">
                <div class="e-card-header-title" v-if="item.header_title !== null">{{item.header_title}}</div>
                <div class="e-card-sub-title" v-if="item.header_subtitle !== null">{{item.header_subtitle}}</div>
              </div>
            </div>
            <div class="e-card-content" v-if="item.cardContent !== null"> {{item.cardContent}} </div>
            <div class="e-card-actions" v-if="item.card_action_btn !== null" v-bind:class="{ 'e-card-vertical': item.card_action_btn.isVertical }">
              <div v-for="(btn, i) of item.card_action_btn.action_btns" v-bind:key="i">
                <a v-if="btn.tag === 'a'" v-bind:href="btn.href" v-bind:target="btn.target">{{btn.text}}</a>
                <button v-else class="e-card-btn">{{btn.text}}</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="source_link">
      Source: <a href="https://www.syncfusion.com/ebooks/" target="_blank">https://www.syncfusion.com/ebooks</a>
    </div>
    <div id="action-description">
      <p>This sample demonstrates filter and search of the <code>card</code> based on categories, and text containing the card. You can use search box to search cards, and you can filter choosing categories in multi-select component.</p>
    </div>
    <div id="description">
      <p>Card is a small container in which user can show defined content in specific structure and it is flexible and extensible. This sample demonstrates to render the <code>Card</code> Using <a target="_blank" href="https://ej2.syncfusion.com/documentation/common/template-engine/">Template Engine</a> and it can be filtered based on <a target="_blank" href="https://ej2.syncfusion.com/documentation/data/getting-started/">data Manager</a>.</p>
      <p>More information about Card can be found in this<a href="https://ej2.syncfusion.com/vue/documentation/card/getting-started/" target="_blank"> documentation</a> section.</p>
    </div>
  </div>
</template>

<style scoped>
  .tile_layout.card-control-section .e-float-text {
    font-size:14px;
  }

  .tile_layout.card-control-section .e-error {
    min-height:150px;
  }

  .tile_layout.card-control-section .e-error-content {
    margin:auto;
    height:inherit;
    font-size:18px;
    font-weight:500;
    color:inherit;
  }

  .tile_layout.card-control-section .row.filter .tile_search {
    justify-content: flex-end;
  }

  .tile_layout.card-control-section .row .e-card {
    text-align: left;
  }

  .tile_layout.card-control-section .control-wrapper {
    padding: 0 20px;
  }

  .tile_layout.card-control-section .row.filter {
    margin: 0;
  }

  .tile_layout.card-control-section .e-card .e-card-actions a {
    border: 1px solid;
    display: block;
    margin: auto;
    width: 100px;
    border-radius: inherit;
  }

  .tile_layout.card-control-section .e-card .e-card-header .e-card-header-caption .e-card-header-title {
    font-size: 18px;
  }

  .tile_layout.card-control-section .e-card .e-card-image {
    height: 165px;
    width: 200px;
  }

  .tile_layout.card-control-section .row.filter .col-xs-6.col-sm-6.col-lg-6.col-md-6 {
    display: inline-flex;
    flex-direction: column;
    width: 100%;
  }

  .tile_layout.card-control-section .col-xs-6.col-sm-6.col-lg-6.col-md-6 {
    width: 100%;
    padding: 10px;
  }

  .card-control-section.tile_layout .e-card-layout {
    margin: auto;
    max-width: 190px;
  }

  #source_link {
    float: right;
    margin-right: 10px;
  }

  @media screen and (max-width: 768px) {
    #source_link {
        margin-right: 0px;
    }
  }
  @media (min-width: 960px) {
    .tile_layout.card-control-section .col-xs-6.col-sm-6.col-lg-6.col-md-6 {
        width: 25%;
    }
    .card-control-section.tile_layout .e-card-layout {
        max-width: 850px;
    }
  }
  @media (min-width: 540px) {
    .tile_layout.card-control-section .row.filter {
        display: flex;
    }
    .tile_layout.card-control-section .e-card .e-card-content {
        min-height: 170px;
        max-height: 170px;
    }
  }
  @media (max-width: 960px) and (min-width: 540px) {
    .tile_layout.card-control-section .col-xs-6.col-sm-6.col-lg-6.col-md-6 {
        width: 50%;
    }
    .card-control-section.tile_layout .e-card-layout {
        max-width: 410px;
    }
  }
</style>

<script>
import { MultiSelectComponent } from '@syncfusion/ej2-vue-dropdowns';
import { Query, DataManager, Predicate } from '@syncfusion/ej2-data';
import data from "./data.json";

export default {
  components: {
    'ejs-multiselect': MultiSelectComponent
  },
  mounted: function() {
    this.emptyData = true;
    this.categoryResult = [];
    this.searchEle = document.getElementById('search_Card');
    this.multiselectComp = document.getElementById('local').ej2_instances[0];
  },
  data: function() {
    return {
      cardData: data.cardBook,
      multiSelectFields: { text: 'Name', value: 'Code' },
      filterCategory: [
        { Name: 'Client-Side', Code: 'client' },
        { Name: 'Server-Side', Code: 'server' },
        { Name: 'Front-End', Code: 'ui' }
      ]
    }
  },
  methods: {
    onInputKeyup: function(e) {
      if (e.code === 'Tab' || e.code === 'Escape' || e.code === 'ShiftLeft' || (e.code === 'Backspace' && this.emptyData)) {
        return;
      }
      var inputVal = e.target.value;
      inputVal.length === 0 ? this.emptyData = true : this.emptyData = false;
      this.filterData()
    },
    filterData: function() {
      var self = this;
      var result = [];
      this.categoryResult = [];
      if (this.multiselectComp.value !== null && this.multiselectComp.value.length > 0) {
        var categoryData = this.multiselectComp.value.toString();
        var category = categoryData.split(',');
        category.forEach(function (key) {
          var datas = new DataManager(data.cardBook).executeLocal(new Query().where('cardImage.tag', 'Contains', key, true));
          if (datas.length === 0) { return; }
          datas.forEach(function (item) {
            self.categoryResult.push(item);
          });
        });
        result = this.categoryResult;
      } 
      if (this.searchEle.value.length > 0) {
        var predicate = new Predicate('cardContent', 'Contains', this.searchEle.value, true);
        predicate = predicate.or('cardImage.title', 'Contains', this.searchEle.value, true).or('header_title', 'Contains', this.searchEle.value, true).or('header_subtitle', 'Contains', this.searchEle.value, true);
        var datas = new DataManager((this.multiselectComp.value === null || this.multiselectComp.value.length === 0) ? data.cardBook : this.categoryResult).executeLocal(new Query().where(predicate));
        if (datas.length === 0) {
          result = [];
        } else {
          this.categoryResult = [];
          datas.forEach(function (item) {
            self.categoryResult.push(item);
          });
          result = this.categoryResult;
        }
      }
      if ((this.multiselectComp.value === null || this.multiselectComp.value.length === 0) && this.searchEle.value.length === 0) {
        result = data.cardBook;
      }
      this.cardData = result;
    }
  }
}
</script>
