// syncfusionejs2_trial/Samples/React/src/schedule/views.jsx
import * as React from 'react';
import { ScheduleComponent, ViewsDirective, ViewDirective, Day, Week, WorkWeek, Month, Inject, Resize, DragAndDrop } from '@syncfusion/ej2-react-schedule';
import { applyCategoryColor } from './helper';
import './schedule-component.css';
import { extend } from '@syncfusion/ej2-base';
import { DropDownListComponent } from '@syncfusion/ej2-react-dropdowns';
import { SampleBase } from '../common/sample-base';
import { PropertyPane } from '../common/property-pane';
import * as dataSource from './datasource.json';
/**
 * Schedule views sample
 */
export class Views extends SampleBase {
    scheduleObj;
    data = extend([], dataSource.zooEventsData, null, true);
    viewOptions = [
        { text: 'Day', value: 'Day' },
        { text: 'Week', value: 'Week' },
        { text: 'WorkWeek', value: 'WorkWeek' },
        { text: 'Month', value: 'Month' }
    ];
    fields = { text: 'text', value: 'value' };
    onViewChange(args) {
        this.scheduleObj.currentView = args.value;
        this.scheduleObj.dataBind();
    }
    onEventRendered(args) {
        applyCategoryColor(args, this.scheduleObj.currentView);
    }
    render() {
        return (<div className='schedule-control-section'>
        <div className='col-lg-9 control-section'>
          <div className='control-wrapper'>
            <ScheduleComponent width='100%' height='650px' ref={schedule => this.scheduleObj = schedule} selectedDate={new Date(2021, 1, 15)} eventSettings={{ dataSource: this.data }} eventRendered={this.onEventRendered.bind(this)}>
              <ViewsDirective>
                <ViewDirective option='Day'/>
                <ViewDirective option='Week'/>
                <ViewDirective option='WorkWeek'/>
                <ViewDirective option='Month'/>
              </ViewsDirective>
              <Inject services={[Day, Week, WorkWeek, Month, Resize, DragAndDrop]}/>
            </ScheduleComponent>
          </div>
        </div>
        <div className='col-lg-3 property-section'>
          <PropertyPane title='Properties'>
            <table id='property' title='Properties' className='property-panel-table' style={{ width: '100%' }}>
              <tbody>
                <tr style={{ height: '50px' }}>
                  <td style={{ width: '100%' }}>
                    <div>
                      <DropDownListComponent style={{ padding: '6px' }} value={'Week'} fields={this.fields} dataSource={this.viewOptions} change={this.onViewChange.bind(this)} placeholder='Current View' floatLabelType='Always'></DropDownListComponent>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </PropertyPane>
        </div>
        <div id='action-description'>
          <p>This demo showcases the usage of basic views available in Scheduler such as Day, Week, Work Week and Month. Here, the wildlife
            events being held in zoos are displayed against its respective timings.</p>
        </div>
        <div id='description'>
          <p>In this demo, Scheduler is showcased with 4 basic views namely
          </p>
          <ul>
            <li>Day</li>
            <li>Week</li>
            <li>Work Week</li>
            <li>Month</li>
          </ul>
          <p>
            The user can navigate between different view options available on the header section just by clicking on it. From any of
            the views, the user can switch back to the day view by clicking dates in the date header section. These view options
            to be displayed on the Scheduler header bar is based on the values ['Day', 'Week', 'WorkWeek', 'Month'] assigned to
            the <code>views</code> property.
          </p>
          <p>
            Looking for the full React Scheduler component overview, features, pricing, and documentation? Visit our <a target="_blank" href="https://www.syncfusion.com/react-components/react-scheduler">React Scheduler</a> component page.
          </p>
        </div>
      </div>);
    }
}

// syncfusionejs2_trial/Samples/Vue/source/schedule/views.vue
<template>
    <div class="schedule-vue-sample">
        <div class="col-md-9 control-section">
            <div class="content-wrapper">
                <ejs-schedule id="Schedule" ref="ScheduleObj" height="650px" :currentView='scheduleView' :selectedDate='selectedDate' :eventSettings='eventSettings' :eventRendered="oneventRendered">
                    <e-views>
                        <e-view option="Day"></e-view>
                        <e-view option="Week"></e-view>
                        <e-view option="WorkWeek"></e-view>
                        <e-view option="Month"></e-view>
                    </e-views>
                </ejs-schedule>
            </div>
        </div>
        <div class="col-lg-3 property-section">
            <table id="property" title="Properties" style="width: 100%">
                <tbody>
                    <tr style="height: 50px">
                        <td style="width: 100%;">
                            <div>
                                <ejs-dropdownlist id='scheduleview' :dataSource='datas' :value='scheduleView' :change='changevalue'
                                    floatLabelType="Always" placeholder="Current View"></ejs-dropdownlist>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div id="action-description">
            <p>
                This demo showcases the usage of basic views available in Scheduler such as Day, Week, Work Week and Month. Here, the wildlife
                events being held in zoos are displayed against its respective timings.
            </p>
        </div>
        <div id="description">
            <p>
                In this demo, Scheduler is showcased with 4 basic views namely
            </p>
            <ul>
                <li>Day</li>
                <li>Week</li>
                <li>Work Week</li>
                <li>Month</li>
            </ul>
            <p>
                The user can navigate between different view options available on the header section just by clicking on it. From any of
                the views, the user can switch back to the day view by clicking dates in the date header section. These view
                options to be displayed on the Scheduler header bar is based on the values ['Day', 'Week', 'WorkWeek', 'Month']
                assigned to the
                <code>views</code> property.
            </p>
            <p>Looking for the full Vue Scheduler component overview, features, pricing, and documentation? Visit our <a href="https://www.syncfusion.com/vue-components/vue-scheduler">Vue Scheduler</a> page.</p>
        </div>
    </div>
</template>
<script>
    import { zooEventsData } from './datasource';
    import { extend } from '@syncfusion/ej2-base';
    import { ScheduleComponent, ViewDirective, ViewsDirective, Day, Week, WorkWeek, Month, Resize, DragAndDrop } from "@syncfusion/ej2-vue-schedule";
    import { DropDownListComponent } from "@syncfusion/ej2-vue-dropdowns";
    
    export default {
        components: {
          'ejs-schedule': ScheduleComponent,
          'e-view': ViewDirective,
          'e-views': ViewsDirective,
          'ejs-dropdownlist': DropDownListComponent
        },
        data: function () {
            return {
                eventSettings: { dataSource: extend([], zooEventsData, null, true) },
                selectedDate: new Date(2021, 1, 15),
                datas: ['Day', 'Week', 'WorkWeek', 'Month'],
                scheduleView: 'Week'
            }
        },
        provide: {
            schedule: [Day, Week, WorkWeek, Month, Resize, DragAndDrop]
        },
        methods: {
            changevalue: function (args) {
                this.$refs.ScheduleObj.ej2Instances.currentView = args.value;
            },
            oneventRendered: function (args) {
                let categoryColor = args.data.CategoryColor;
                if (!args.element || !categoryColor) {
                    return;
                }
                args.element.style.backgroundColor = categoryColor;
            }
        }
    }

</script>
