// syncfusionejs2_trial/Samples/Vue/source/tab/orientation.vue
<template>
    <div class="orientation-tab-section">
        <div class="col-lg-8 control-section">
            <div class="e-sample-resize-container">
            <ejs-tab ref="tabObj" id="tab_orientation" height='320px' :showCloseButton=true heightAdjustMode='Auto'>
                <e-tabitems>
                    <e-tabitem :header='headerText0' :content="'RomeTemplate'"></e-tabitem>
                    <template v-slot:RomeTemplate>
                        <div><div class="content-title"><div class="cnt-text">Employee Info</div></div><div id="rome">
                            <div class="template-container"><div class="left"><img class="empImg" src="https://ej2.syncfusion.com/demos/src/images/employees/1.png" alt="Anne Dodsworth" /></div>
                            <div class="left info"><div class="empname">Anne Dodsworth</div> 
                            <div class="role">Product Manager</div></div></div><div class="template-container"><div class="left">
                                <img class="empImg" src="https://ej2.syncfusion.com/demos/src/images/employees/2.png" alt="Laura Callahan" /></div>
                                <div class="left info">
                                    <div class="empname">Laura Callahan</div> <div class="role">Team Lead</div></div></div>
                                    <div class="template-container"><div class="left">
                                        <img class="empImg" src="https://ej2.syncfusion.com/demos/src/images/employees/3.png" alt="Andrew Fuller" /></div>
                                        <div class="left info"><div class="empname">Andrew Fuller</div> <div class="role">Developer</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </template>
                    <e-tabitem :header='headerText1' :content="'ParisTemplate'"></e-tabitem>
                    <template v-slot:ParisTemplate>
                        <div><div class="content-title"><div class="cnt-text">Employee Info</div></div><div id="rome">
                            <div class="template-container"><div class="left"><img class="empImg" src="https://ej2.syncfusion.com/demos/src/images/employees/4.png" alt="Robert King" /></div>
                                <div class="left info"><div class="empname">Robert King</div> 
                                <div class="role">Team Lead</div></div></div><div class="template-container"><div class="left">
                                    <img class="empImg" src="https://ej2.syncfusion.com/demos/src/images/employees/5.png" alt="Michael Suyama" /></div>
                                    <div class="left info"><div class="empname">Michael Suyama</div> <div class="role">Developer</div></div></div>
                                        <div class="template-container"><div class="left"><img class="empImg" src="https://ej2.syncfusion.com/demos/src/images/employees/6.png" alt="Margaret Peacock" /></div>
                                        <div class="left info"><div class="empname">Margaret Peacock</div> <div class="role">Developer</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </template>
                    <e-tabitem :header='headerText2' :content="'LondonTemplate'"></e-tabitem>
                    <template v-slot:LondonTemplate>
                        <div><div class="content-title"><div class="cnt-text">Employee Info</div></div>
                        <div id="rome"><div id="ripple" class="template-container"><div class="left">
                            <img class="empImg" src="https://ej2.syncfusion.com/demos/src/images/employees/7.png" alt="Janet Leverling" /></div>
                        <div class="left info"><div class="empname">Janet Leverling</div> 
                        <div class="role"> CEO</div></div></div><div class="template-container"><div class="left">
                            <img class="empImg" src="https://ej2.syncfusion.com/demos/src/images/employees/8.png" alt="Steven Buchanan" /></div>
                        <div class="left info"><div class="empname">Steven Buchanan</div> <div class="role">HR</div></div></div>
                        <div class="template-container"><div class="left">
                            <img class="empImg" src="https://ej2.syncfusion.com/demos/src/images/employees/9.png" alt="Nancy Davolio" /></div>
                        <div class="left info"><div class="empname">Nancy Davolio</div> 
                        <div class="role">Product Manager</div></div></div></div></div>
                    </template>
                </e-tabitems>
            </ejs-tab>
            </div>
        </div>
        <div class="col-lg-4 property-section">
            <table id="property" title="Properties">
                <tr>
                    <td style="width:50%; padding-bottom: 10px;">Header Placement:</td>
                    <td style="width:50%; padding-bottom: 10px;">
                        <ejs-dropdownlist ref="dropObj1" id='header-place' width='90%' :dataSource='dataPlace' :change='placeChange' :value='placeValue' :fields='placeFields'>
                        </ejs-dropdownlist>
                    </td>
                </tr>
                <tr>
                    <td style="width:50%; padding-bottom: 10px;">Header Styles:</td>
                    <td style="width:50%; padding-bottom: 10px;">
                        <ejs-dropdownlist ref="dropObj2" id='header-styles' width='90%' :dataSource='dataStyles' :change='styleChange' :value='styleValue' :fields='styleFields'>
                        </ejs-dropdownlist>
                    </td>
                </tr>
            </table>
        </div>
        <div id="action-description">
            <p>This sample demonstrates the <code>header</code> orientation of the <code>Tab</code>. Select option from drop-downs to switch header placement and changing the header style in properties panel.</p>
        </div>
        <div id="description">
            <p>The <code>Tab</code> allows to place the header section inside the Tab component either at <code>top/bottom/left/right</code> position by using <code>headerPlacement</code> property.</p>
            <p>This sample illustrates the use of header placement and <code>showCloseButton</code> property. Users can change the header position by changing the drop-down value options and can close the Tab item by clicking close icon in header.</p>
            <br>
            <p>The User can also view different header styles of Tab component by selecting options from `Header Styles` drop-down. Header styles changed by adding predefined classes in Tab root element and it class names listed below</p>
            <ul>
            <li>Material and Fabric theme differentiates all the available tab header styles such as <code>e-fill, e-background e-accent.</code></li>
            <li>In bootstrap theme, all the styles such as <code>e-fill</code> & <code>e-background e-accent</code> will have the same look with no difference.</li>
            </ul>
            <p>If above classes not included in root element default style will applied in Tab component.</p>
            <p>More information about Tab can be found in this <a aria-label="Tab getting started" href="https://ej2.syncfusion.com/vue/documentation/tab/getting-started/" target="_blank">documentation</a> section.</p>
        </div>
    </div>
</template>
<style>
#tab_orientation .e-content .e-item {
    font-size: 12px;
    padding: 10px;
    text-align: justify;
}

#tab_orientation .e-tab-text {
        display: inherit;
    }



#tab_orientation .e-content .e-item .template-container {
    height: 63px;
    padding: 7px 16px 0 16px;
    border-bottom: 1px solid gainsboro;
}
#tab_orientation .e-content .e-item .template-container:hover {
    background: #eee;
}
.highcontrast #tab_orientation .e-content .e-item .template-container:hover
{
    background: #685708;
}
.bootstrap-dark #tab_orientation .e-content .e-item .template-container:hover,
.bootstrap5-dark #tab_orientation .e-content .e-item .template-container:hover,
.tailwind-dark #tab_orientation .e-content .e-item .template-container:hover,
.tailwind3-dark #tab_orientation .e-content .e-item .template-container:hover,
.fabric-dark #tab_orientation .e-content .e-item .template-container:hover,
.material-dark #tab_orientation .e-content .e-item .template-container:hover,
.fluent-dark #tab_orientation .e-content .e-item .template-container:hover
{
    background: #343a40;
}
.left {
    display: inline-block;
    vertical-align: top;
}
.empImg {
    height: 48px;
    width: 48px;
}
.empname, .role {
    font-size: 15px;
    line-height: normal;
}
.empname {
    font-weight: 500;
    padding: 0px !important;
    bottom: 0px !important;
    margin: 0px !important;
}
.role {
    color: grey;
    font-weight: 100;
}
.info {
    padding: 7px 15px 0 15px;
}
.content-title {
    height: 50px;
    display: table;
    margin: 0 auto;
}
.cnt-text {
    vertical-align: middle;
    display: table-cell;
    font-size: 18px;
    font-weight: 600;
}
.property-panel-content {
    padding: 10px;
}
@media only screen and (min-width: 1824px) {
    .orientation-tab-section .e-sample-resize-container {
        width: 60%;
    }

    .e-bigger .orientation-tab-section .e-sample-resize-container {
        width: 70%;
    }
}

    @media screen and (max-width: 376px) {
        .orientation-tab-section {
            padding: 0 5px;
        }
        #tab_orientation .e-content.sb-sample-content-area .e-item.e-active {
            padding-left: 0;
            padding-right: 0;
        }
        .template-container {
            padding: 7px 5px 0;
        }
        #tab_orientation .e-content .e-item.e-active {
            padding: 10px 0;
        }
        .info {
            padding: 7px 0 0 8px;
        }
    }
</style>
<script>
import { TabComponent, TabItemsDirective, TabItemDirective } from "@syncfusion/ej2-vue-navigations";
import { DropDownListComponent } from "@syncfusion/ej2-vue-dropdowns";

export default {
    components: {
        'ejs-tab': TabComponent,
        'e-tabitems': TabItemsDirective,
        'e-tabitem': TabItemDirective,
        'ejs-dropdownlist': DropDownListComponent,
    },
     data: function(){
        return {
            headerText0: { text: 'Rome' },
            headerText1: { text: 'Paris' },
            headerText2: { text: 'London' },
            dataPlace: [{ id: 'top', position: 'Top' }, { id: 'bottom', position: 'Bottom' },{ id: 'left', position: 'Left' }, { id: 'right', position: 'Right' }],
            dataStyles: [{ id: 'default', class: 'Default' }, { id: 'fill', class: 'Fill' }, { id: 'accent', class: 'Accent' }],
            styleValue: 'default',
            styleFields: { text: 'class', value: 'id' },
            placeValue: 'top',
            placeFields: { text: 'position', value: 'id' },
        }
   },
     methods: {
       placeChange: function(args) {
           this.tabObj = this.$refs.tabObj.ej2Instances;
           var placement = this.$refs.dropObj1.$el.value;
           this.tabObj.headerPlacement = placement;
           this.tabObj.dataBind();
       },
       styleChange: function(args) {
            var name = args.value;
            this.tabObj = this.$refs.tabObj.ej2Instances;
            this.tabObj.element.classList.remove('e-fill');
            this.tabObj.element.classList.remove('e-background');
            this.tabObj.element.classList.remove('e-accent');
            if (name === 'fill') {
                this.tabObj.element.classList.add('e-fill');
            } else if (name === 'accent') {
                this.tabObj.element.classList.add('e-background');
                this.tabObj.element.classList.add('e-accent');
            }
            this.tabObj.refreshActiveBorder();
       }
    }
};
</script>

// syncfusionejs2_trial/Samples/React/src/tab/orientation.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.Orientation = void 0;
var React = require("react");
var property_pane_1 = require("../common/property-pane");
var ej2_react_navigations_1 = require("@syncfusion/ej2-react-navigations");
var ej2_react_dropdowns_1 = require("@syncfusion/ej2-react-dropdowns");
var ej2_react_lists_1 = require("@syncfusion/ej2-react-lists");
var sample_base_1 = require("../common/sample-base");
require("./tab.component.css");
var Orientation = /** @class */ (function (_super) {
    __extends(Orientation, _super);
    function Orientation() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        // Mapping ListView component dataSource property
        _this.romeEmployees = [
            { id: '1', name: 'Anne Dodsworth', role: 'Product Manager' },
            { id: '2', name: 'Laura Callahan', role: 'Team Lead' },
            { id: '3', name: 'Andrew Fuller', role: 'Developer' }
        ];
        // Mapping ListView component dataSource property
        _this.parisEmployees = [
            { id: '4', name: 'Robert King', role: 'Team Lead' },
            { id: '5', name: 'Michael Suyama', role: 'Developer' },
            { id: '6', name: 'Margaret Peacock', role: 'Developer' }
        ];
        // Mapping ListView component dataSource property
        _this.londonEmployees = [
            { id: '7', name: 'Janet Leverling', role: 'CEO' },
            { id: '8', name: 'Steven Buchanan', role: 'HR' },
            { id: '9', name: 'Nancy Davolio', role: 'Product Manager' }
        ];
        // Mapping DropDownList dataSource property
        _this.oData = [
            { 'value': 'top', 'text': 'Top' }, { 'value': 'bottom', 'text': 'Bottom' },
            { 'value': 'left', 'text': 'Left' }, { 'value': 'right', 'text': 'Right' }
        ];
        // Mapping DropDownList fields property
        _this.fields = { text: 'text', value: 'value' };
        //Map the appropriate columns to fields property
        _this.listfields = { text: 'name', id: 'id' };
        // Mapping DropDownList value property
        _this.orientVal = 'top';
        // Mapping DropDownList dataSource property
        _this.hData = [
            { 'value': 'default', 'text': 'Default' }, { 'value': 'fill', 'text': 'Fill' }, { 'value': 'accent', 'text': 'Accent' }
        ];
        // Mapping DropDownList value property
        _this.hdrVal = 'default';
        return _this;
    }
    // Change event funtion for DropDownList component   
    Orientation.prototype.changeOrientationMode = function (e) {
        var placement = document.getElementById('orientation').value;
        this.tabObj.headerPlacement = placement;
        this.tabObj.dataBind();
    };
    // Change event funtion for DropDownList component   
    Orientation.prototype.changeHeaderStyles = function (e) {
        this.removeStyleClass();
        var name = document.getElementById('headerStyles').value;
        if (name === 'Fill') {
            this.tabObj.element.classList.add('e-fill');
        }
        else if (name === 'Accent') {
            this.tabObj.element.classList.add('e-background');
            this.tabObj.element.classList.add('e-accent');
        }
        this.tabObj.refreshActiveBorder();
    };
    Orientation.prototype.removeStyleClass = function () {
        this.tabObj.element.classList.remove('e-fill');
        this.tabObj.element.classList.remove('e-background');
        this.tabObj.element.classList.remove('e-accent');
    };
    Orientation.prototype.templateString = function (data) {
        return (React.createElement("div", { className: "template-container" },
            React.createElement("div", { className: "left" },
                React.createElement("img", { className: 'empImg', src: "src/tab/Employees/".concat(data.id, ".png"), alt: '${data.id}' }),
                React.createElement("div", { className: "left info-div" },
                    React.createElement("div", { className: "name" },
                        " ",
                        data.name),
                    React.createElement("div", { className: "role" },
                        " ",
                        data.role)))));
    };
    Orientation.prototype.render = function () {
        var _this = this;
        function template1() {
            return (React.createElement("div", null,
                React.createElement("div", { className: "content-title" },
                    React.createElement("div", { className: "cnt-text" }, "Employee Info")),
                React.createElement(ej2_react_lists_1.ListViewComponent, { id: "rome", dataSource: this.romeEmployees, template: this.templateString })));
        }
        function template2() {
            return (React.createElement("div", null,
                React.createElement("div", { className: "content-title" },
                    React.createElement("div", { className: "cnt-text" }, "Employee Info")),
                React.createElement(ej2_react_lists_1.ListViewComponent, { id: "paris", dataSource: this.parisEmployees, template: this.templateString })));
        }
        function template3() {
            return (React.createElement("div", null,
                React.createElement("div", { className: "content-title" },
                    React.createElement("div", { className: "cnt-text" }, "Employee Info")),
                React.createElement(ej2_react_lists_1.ListViewComponent, { id: "london", dataSource: this.londonEmployees, template: this.templateString })));
        }
        // Mapping Tab items Header property
        var headertext;
        headertext = [{ text: "Rome" }, { text: "Paris" }, { text: "London" }];
        return (React.createElement("div", { className: 'control-pane' },
            React.createElement("div", { className: 'control-section tab-control-section row' },
                React.createElement("div", { className: 'col-lg-8' },
                    React.createElement(ej2_react_navigations_1.TabComponent, { ref: function (tab) { _this.tabObj = tab; }, cssClass: 'orientation-tab', showCloseButton: true, height: 320 },
                        React.createElement(ej2_react_navigations_1.TabItemsDirective, null,
                            React.createElement(ej2_react_navigations_1.TabItemDirective, { header: headertext[0], content: template1.bind(this) }),
                            React.createElement(ej2_react_navigations_1.TabItemDirective, { header: headertext[1], content: template2.bind(this) }),
                            React.createElement(ej2_react_navigations_1.TabItemDirective, { header: headertext[2], content: template3.bind(this) })))),
                React.createElement("div", { className: 'col-lg-4 property-section' },
                    React.createElement(property_pane_1.PropertyPane, { title: 'Properties' },
                        React.createElement("table", { id: 'property', title: 'Properties', className: 'property-panel-table' },
                            React.createElement("tbody", null,
                                React.createElement("tr", null,
                                    React.createElement("td", { style: { width: '50%' } },
                                        React.createElement("div", null, "Header Placement")),
                                    React.createElement("td", { style: { width: '50%' } },
                                        React.createElement("div", null,
                                            React.createElement(ej2_react_dropdowns_1.DropDownListComponent, { id: 'orientation', dataSource: this.oData, fields: this.fields, value: this.orientVal, width: '90%', change: this.changeOrientationMode.bind(this) })))),
                                React.createElement("tr", null,
                                    React.createElement("td", { style: { width: '50%' } },
                                        React.createElement("div", null, "Header Styles")),
                                    React.createElement("td", { style: { width: '50%' } },
                                        React.createElement("div", null,
                                            React.createElement(ej2_react_dropdowns_1.DropDownListComponent, { id: 'headerStyles', dataSource: this.hData, fields: this.fields, value: this.hdrVal, width: '90%', change: this.changeHeaderStyles.bind(this) }))))))))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null,
                    "This sample demonstrates the ",
                    React.createElement("code", null, "header"),
                    " orientation of the ",
                    React.createElement("code", null, "Tab"),
                    ". Select option from drop-downs to switch header placement and changing the header style in properties panel.")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null,
                    "The ",
                    React.createElement("code", null, "Tab"),
                    " allows to place the header section inside the Tab component either at",
                    React.createElement("code", null, "top / bottom / left / right"),
                    " position by using ",
                    React.createElement("code", null, "headerPlacement"),
                    " property."),
                React.createElement("p", null,
                    "This sample illustrates the use of header placement and ",
                    React.createElement("code", null, "showCloseButton"),
                    " property. Users can change the header position by changing the drop-down value options and can close the Tab item by clicking close icon in header.",
                    React.createElement("br", null),
                    React.createElement("br", null),
                    "The User can also view different header styles of Tab component by selecting options from `Header Styles` drop-down. Header styles changed by adding predefined classes in Tab root element and it class names listed below",
                    React.createElement("br", null)),
                React.createElement("ul", null,
                    React.createElement("li", null,
                        "Material and Fabric theme differentiates all the available tab header styles such as ",
                        React.createElement("code", null, "e-fill"),
                        ", ",
                        React.createElement("code", null, "e-background e-accent"),
                        "."),
                    React.createElement("li", null,
                        "In bootstrap theme, all the styles such as ",
                        React.createElement("code", null, "e-fill"),
                        " & ",
                        React.createElement("code", null, "e-background e-accent"),
                        " will have the same look with no difference.")),
                React.createElement("p", null, "If above classes not included in root element default style will applied in Tab component."),
                React.createElement("p", null,
                    "More information about Tab can be found in this ",
                    React.createElement("a", { "aria-label": "Tab getting started", target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/tab/getting-started/" }, "documentation"),
                    " section."))));
    };
    return Orientation;
}(sample_base_1.SampleBase));
exports.Orientation = Orientation;
