// syncfusionejs2_trial/Samples/React/src/grid/checkbox-selection.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.CheckboxSelection = void 0;
var React = require("react");
var ej2_react_grids_1 = require("@syncfusion/ej2-react-grids");
var data_1 = require("./data");
var sample_base_1 = require("../common/sample-base");
var CheckboxSelection = /** @class */ (function (_super) {
    __extends(CheckboxSelection, _super);
    function CheckboxSelection() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        _this.selectionsettings = { persistSelection: true };
        _this.filterSettings = { type: 'Excel' };
        _this.toolbarOptions = ['Delete'];
        _this.editSettings = { allowDeleting: true };
        return _this;
    }
    CheckboxSelection.prototype.render = function () {
        var _this = this;
        return (React.createElement("div", { className: 'control-pane' },
            React.createElement("div", { className: 'control-section' },
                React.createElement(ej2_react_grids_1.GridComponent, { dataSource: data_1.data, ref: function (grid) { return _this.gridInstance = grid; }, enableHover: false, allowPaging: true, pageSettings: { pageCount: 5 }, allowFiltering: true, filterSettings: this.filterSettings, selectionSettings: this.selectionsettings, toolbar: this.toolbarOptions, editSettings: this.editSettings },
                    React.createElement(ej2_react_grids_1.ColumnsDirective, null,
                        React.createElement(ej2_react_grids_1.ColumnDirective, { type: 'checkbox', width: '50' }),
                        React.createElement(ej2_react_grids_1.ColumnDirective, { field: 'OrderID', isPrimaryKey: true, headerText: 'Order ID', width: '120', textAlign: "Right" }),
                        React.createElement(ej2_react_grids_1.ColumnDirective, { field: 'CustomerName', headerText: 'Customer Name', width: '150' }),
                        React.createElement(ej2_react_grids_1.ColumnDirective, { field: 'OrderDate', headerText: 'Order Date', width: '130', format: 'yMd', textAlign: 'Right' }),
                        React.createElement(ej2_react_grids_1.ColumnDirective, { field: 'Freight', headerText: 'Freight', width: '120', format: 'C2', textAlign: 'Right' }),
                        React.createElement(ej2_react_grids_1.ColumnDirective, { field: 'ShippedDate', headerText: 'Shipped Date', width: '130', format: "yMd", textAlign: "Right" })),
                    React.createElement(ej2_react_grids_1.Inject, { services: [ej2_react_grids_1.Page, ej2_react_grids_1.Selection, ej2_react_grids_1.Toolbar, ej2_react_grids_1.Edit, ej2_react_grids_1.Filter] }))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null, "This sample demonstrates the selection functionality of the Grid using checkbox selection, To select and unselect all rows use header checkbox. To select/unselect particular row, click the desired row. Delete one or more records using the toolbar delete button")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null,
                    "Grid multiple selection can be achieved with help of checkbox in each row. To render checkbox in each grid row, you need to define column type as ",
                    React.createElement("code", null, "checkbox"),
                    " using",
                    React.createElement("code", null,
                        React.createElement("a", { target: "_blank", className: "code", href: "https://ej2.syncfusion.com/react/documentation/api/grid/column/#type" }, "columns->type")),
                    " property."),
                React.createElement("p", null,
                    "Selection can be persisted on all the operations using",
                    React.createElement("code", null,
                        React.createElement("a", { target: "_blank", className: "code", href: "https://ej2.syncfusion.com/react/documentation/api/grid/selectionSettings/#persistselection" }, "selectionSettings-> persistSelection")),
                    " property. For persisting selection on the Grid, any one of the column should be defined as a primary key using",
                    React.createElement("code", null,
                        React.createElement("a", { target: "_blank", className: "code", href: "https://ej2.syncfusion.com/react/documentation/api/grid/column/#isprimarykey" }, "columns->isPrimaryKey")),
                    " property."),
                React.createElement("p", null,
                    "In this demo, Grid multiple selection has been enabled with selection persistance. You can also delete multiple records, by clicking the toolbar\u2019s ",
                    React.createElement("code", null, "Delete"),
                    " button after selecting the checkboxes."),
                React.createElement("p", null,
                    "More information on the checkbox selection configuration can be found in this ",
                    React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/grid/selection/check-box-selection" }, "documentation section"),
                    "."),
                React.createElement("p", null,
                    "Looking for the full React Data Grid component overview, features, pricing, and documentation? Visit our",
                    React.createElement("a", { target: "_blank", href: "https://www.syncfusion.com/react-components/react-data-grid" }, " React Data Grid component"),
                    " page."))));
    };
    return CheckboxSelection;
}(sample_base_1.SampleBase));
exports.CheckboxSelection = CheckboxSelection;

// syncfusionejs2_trial/Samples/Vue/source/grid/grid/checkbox-selection.vue
<template>
<div class="col-lg-12 control-section">
    <div id="action-description">
        <p>This sample demonstrates the selection functionality of the Grid using checkbox selection, To select and unselect all rows use header checkbox.
         To select/unselect particular row, click the desired row.</p>
    </div>
    <div>
        <ejs-grid :dataSource="data" :allowPaging='true' :enableHover="false" :allowSorting='true' :allowFiltering='true' :filterSettings='filterSettings' :allowSelection="true" :selectionSettings="selectOptions" :editSettings='editSettings' :toolbar='toolbar'>
            <e-columns>
                <e-column type='checkbox' width='50'></e-column>
                <e-column field='OrderID' isPrimaryKey='true' headerText='Order ID' width='120' textAlign='Right' ></e-column>
                <e-column field='CustomerName' headerText='Customer Name' width='150'></e-column>
                <e-column field='OrderDate' headerText='Order Date' width='130' format="yMd" textAlign='Right'></e-column>
                <e-column field='Freight' headerText='Freight' width='120' format='C2' textAlign='Right'></e-column>
                <e-column field='ShippedDate' headerText='Shipped Date' width='130' format="yMd" textAlign='Right'></e-column>
            </e-columns>
        </ejs-grid>
    </div>

     <div id="description">
        <p>
            Grid multiple selection can be achieved with help of checkbox in each row. To render checkbox in each grid row, you need
            to define column type as <code>checkbox</code> using
            <code><a target="_blank" class="code"
        href="https://ej2.syncfusion.com/vue/documentation/api/grid/columnModel/#type">
        columns->type
        </a></code> property.</p>
        <p>Selection can be persisted on all the operations using
            <code><a target="_blank" class="code"
        href="https://ej2.syncfusion.com/vue/documentation/api/grid/selectionSettingsModel/#persistselection">
        selectionSettings-> persistSelection
        </a></code> property. For persisting selection on the Grid, any one of the column should be defined as
            a primary key using
            <code><a target="_blank" class="code"
        href="https://ej2.syncfusion.com/vue/documentation/api/grid/columnModel/#isprimarykey">
        columns->isPrimaryKey
        </a></code> property.
        </p>

        <p>
            In this demo, Grid multiple selection has been enabled with selection persistance. You can also delete multiple records,
            by clicking the toolbar’s <code>Delete</code> button after selecting the checkboxes.
        </p>
        <p>
            More information on the checkbox selection configuration can be found in this
            <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/grid/selection/check-box-selection">
        documentation section</a>.
        </p>
        <p>
            Looking for the full Vue Data Grid component overview, features, pricing, and documentation? Visit our
            <a target="_blank" href="https://www.syncfusion.com/vue-components/vue-data-grid">
                Vue Data Grid component</a> page.
        </p>
  
    </div>

</div>
</template>
<script lang="ts">
import { GridComponent, ColumnDirective, ColumnsDirective, Page, Edit, Toolbar, Sort, Filter } from "@syncfusion/ej2-vue-grids";
import { orderDetails } from "./data-source";

export default {
  components: {
    'ejs-grid': GridComponent,
    'e-column': ColumnDirective,
    'e-columns': ColumnsDirective
  }, 
  data: () => {
    return {
      data: orderDetails.slice(0),
      filterSettings: { type: 'Excel' },
      selectOptions: { persistSelection: true },
      toolbar: ['Delete'],
      editSettings: { allowDeleting: true},
    };
  },
  provide: {
      grid: [Page, Edit, Toolbar, Sort, Filter]
  }
}
</script>
