// syncfusionejs2_trial/Samples/Vue/public/source/chart/date-time.vue
<template>
  <div class="control-section">
    <div align='center'>
      <ejs-chart style='display:block' :theme='theme' align='center' id='chartcontainer' :title='title' :tooltip='tooltip'
        :primaryXAxis='primaryXAxis' :primaryYAxis='primaryYAxis' :chartArea='chartArea' :width='width'>
        <e-series-collection>
          <e-series :dataSource='seriesData' type='Line' xName='Period' yName='MaxTemp' name='Warmest' width=2
            :marker='marker' opacity=1> </e-series>
          <e-series :dataSource='seriesData' type='Line' xName='Period' yName='MinTemp' name='Coldest' width=2
            :marker='marker1' opacity=1> </e-series>
        </e-series-collection>
      </ejs-chart>
    </div>
    <div id="action-description">
      <p>
        This sample shows the date-time axis in a chart with a weather report for the year 2016.
      </p>
    </div>
    <div id="description">
      <p>
        The date-time axis uses a date-time scale and displays date-time values as the axis labels. To use a date-time
        axis, set the <code>ValueType</code> in axis to <b>DateTime</b>.
      </p>
      <p>
        <code>Tooltip</code> is enabled in this example. To see the tooltip in action, hover over or tap on the chart.
      </p>
      <p style="font-weight: 500"><b>Injecting Module</b></p>
      <p>
        Chart component features are segregated into individual feature-wise modules. To use DateTime axis, we need to
        inject
        <code>DateTime</code> module using <code> provide: { chart: [ DateTime ] },</code> method.
      </p>
      <p>
        More information on the DateTime axis can be found in this
        <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/chart/date-time-axis/"
          aria-label="Navigate to the documentation for DateTime Axis in Vue Chart component">documentation
          section</a>.
      </p>
    </div>
  </div>

</template>
<style scoped>

</style>
<script>
import { Browser } from '@syncfusion/ej2-base';
import { ChartComponent, SeriesDirective, SeriesCollectionDirective, LineSeries, Legend, DateTime, DataLabel, Highlight, Tooltip } from "@syncfusion/ej2-vue-charts";

import { loadChartTheme } from "./theme-color";
let theme = loadChartTheme();

export default {
  components: {
    'ejs-chart': ChartComponent,
    'e-series-collection': SeriesCollectionDirective,
    'e-series': SeriesDirective
  },
  data: function () {
    return {
      theme: theme,
      seriesData: [
        { Period: new Date(2016, 3, 1), MaxTemp: 6.3, MinTemp: -5.3 },
        { Period: new Date(2016, 4, 1), MaxTemp: 13.3, MinTemp: 1.0 },
        { Period: new Date(2016, 5, 1), MaxTemp: 18.0, MinTemp: 6.9 },
        { Period: new Date(2016, 6, 1), MaxTemp: 19.8, MinTemp: 9.4 },
        { Period: new Date(2016, 7, 1), MaxTemp: 18.1, MinTemp: 7.6 },
        { Period: new Date(2016, 8, 1), MaxTemp: 13.1, MinTemp: 2.6 },
        { Period: new Date(2016, 9, 1), MaxTemp: 4.1, MinTemp: -4.9 }
      ],
      //Initializing Primary X Axis
      primaryXAxis: {
        valueType: 'DateTime',
        labelFormat: 'MMM d',
        edgeLabelPlacement: 'Shift',
        majorGridLines: { width: 0 }
      },

      //Initializing Primary Y Axis
      primaryYAxis:
      {
        edgeLabelPlacement: 'Shift',
        minimum: -20,
        maximum: 30,
        interval: 10,
        labelFormat: '{value}°C',
        lineStyle: { width: 0 },
        majorTickLines: { width: 0 },
        minorTickLines: { width: 0 }
      },
      chartArea: {
        border: {
          width: 0
        }
      },

      tooltip: {
        enable: true,
        showNearestTooltip: true
      },

      marker: {
        visible: true,
        height: 8, width: 8,
        isFilled: true,
        shape: 'Pentagon',
        dataLabel: { visible: true, position: 'Top' }
      },

      marker1: {
        visible: true, height: 8, width: 8, shape: 'Diamond', isFilled: true,
        dataLabel: { visible: true, position: 'Top' }
      },

      width: Browser.isDevice ? '100%' : '75%',
      title: "Alaska Weather Statistics - 2016"
    };
  },
  provide: {
    chart: [LineSeries, Legend, DateTime, DataLabel, Highlight, Tooltip]
  },
  methods: {
  },

};
</script>

// syncfusionejs2_trial/Samples/React/src/chart/datetime.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.DateTimeAxis = exports.data2 = exports.data1 = void 0;
/**
 * Sample for DateTime axis
 */
var React = require("react");
var ej2_react_charts_1 = require("@syncfusion/ej2-react-charts");
var sample_base_1 = require("../common/sample-base");
var ej2_base_1 = require("@syncfusion/ej2-base");
exports.data1 = [
    { x: new Date(2016, 3, 1), y: 6.3 },
    { x: new Date(2016, 4, 1), y: 13.3 }, { x: new Date(2016, 5, 1), y: 18.0 },
    { x: new Date(2016, 6, 1), y: 19.8 }, { x: new Date(2016, 7, 1), y: 18.1 },
    { x: new Date(2016, 8, 1), y: 13.1 }, { x: new Date(2016, 9, 1), y: 4.1 }
];
exports.data2 = [
    { x: new Date(2016, 3, 1), y: -5.3 },
    { x: new Date(2016, 4, 1), y: 1.0 }, { x: new Date(2016, 5, 1), y: 6.9 },
    { x: new Date(2016, 6, 1), y: 9.4 }, { x: new Date(2016, 7, 1), y: 7.6 },
    { x: new Date(2016, 8, 1), y: 2.6 }, { x: new Date(2016, 9, 1), y: -4.9 }
];
var SAMPLE_CSS = "\n    .control-fluid {\n\t\tpadding: 0px !important;\n    }";
var DateTimeAxis = /** @class */ (function (_super) {
    __extends(DateTimeAxis, _super);
    function DateTimeAxis() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    DateTimeAxis.prototype.render = function () {
        return (React.createElement("div", { className: 'control-pane' },
            React.createElement("style", null, SAMPLE_CSS),
            React.createElement("div", { className: 'control-section' },
                React.createElement(ej2_react_charts_1.ChartComponent, { id: 'charts', style: { textAlign: "center" }, primaryXAxis: {
                        valueType: 'DateTime',
                        labelFormat: 'MMM',
                        edgeLabelPlacement: 'Shift',
                        majorGridLines: { width: 0 }
                    }, load: this.load.bind(this), primaryYAxis: {
                        minimum: -20,
                        maximum: 30,
                        interval: 10,
                        edgeLabelPlacement: 'Shift',
                        labelFormat: '{value}°C',
                        lineStyle: { width: 0 },
                        majorTickLines: { width: 0 },
                        minorTickLines: { width: 0 }
                    }, chartArea: { border: { width: 0 } }, width: ej2_base_1.Browser.isDevice ? '100%' : '75%', title: 'Alaska Weather Statistics - 2016', loaded: this.onChartLoad.bind(this) },
                    React.createElement(ej2_react_charts_1.Inject, { services: [ej2_react_charts_1.LineSeries, ej2_react_charts_1.DateTime, ej2_react_charts_1.Legend, ej2_react_charts_1.DataLabel] }),
                    React.createElement(ej2_react_charts_1.SeriesCollectionDirective, null,
                        React.createElement(ej2_react_charts_1.SeriesDirective, { dataSource: exports.data1, xName: 'x', yName: 'y', name: 'Warmest', type: 'Line', marker: {
                                visible: true, height: 10, width: 10, shape: 'Pentagon',
                                dataLabel: { visible: true, position: 'Top' }
                            }, width: 2 }),
                        React.createElement(ej2_react_charts_1.SeriesDirective, { dataSource: exports.data2, xName: 'x', yName: 'y', name: 'Coldest', type: 'Line', marker: {
                                visible: true, height: 10, width: 10, shape: 'Pentagon',
                                dataLabel: { visible: true, position: 'Top' }
                            }, width: 2 }))),
                React.createElement("div", { style: { float: 'right', marginRight: '10px' } },
                    "Source: \u00A0",
                    React.createElement("a", { href: "http://www.yr.no/place/USA/Alaska/Hatcher_Pass/statistics.html", target: "_blank", "aria-label": "Navigate to the documentation for yr" }, "www.yr.no"))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null, "This sample demonstrates the rendering of date time axis in the chart with weather statistics analysis of Alaska for a year.")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null,
                    "DateTime data is used in this sample and data values are represented using dataLabel. Date time axis uses date time scale and displays the date time values as axis labels. To render dateTime axis, set ",
                    React.createElement("code", null, "valueType"),
                    " in axis to ",
                    React.createElement("code", null, "DateTime"),
                    ". Format for the axis label will be calculated based on intervalType of axis or we can set the format through labelFormat property in axis."),
                React.createElement("p", null,
                    React.createElement("b", null, "Injecting Module")),
                React.createElement("p", null,
                    "Chart component features are segregated into individual feature-wise modules. To use DateTime axis, we need to inject",
                    React.createElement("code", null, "DateTime"),
                    " module into ",
                    React.createElement("code", null, "services"),
                    "."),
                React.createElement("p", null,
                    "More information on the DateTime axis can be found in this \u00A0",
                    React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/chart/date-time-axis/#datetime-axis", "aria-label": "Navigate to the documentation for Date Time Axis in React Chart component" }, "documentation section"),
                    "."))));
    };
    DateTimeAxis.prototype.onChartLoad = function (args) {
        var chart = document.getElementById('charts');
        chart.setAttribute('title', '');
    };
    ;
    DateTimeAxis.prototype.load = function (args) {
        var selectedTheme = location.hash.split('/')[1];
        selectedTheme = selectedTheme ? selectedTheme : 'Fluent2';
        args.chart.theme = (selectedTheme.charAt(0).toUpperCase() + selectedTheme.slice(1)).
            replace(/-dark/i, "Dark").replace(/contrast/i, 'Contrast').replace(/-highContrast/i, 'HighContrast');
    };
    ;
    return DateTimeAxis;
}(sample_base_1.SampleBase));
exports.DateTimeAxis = DateTimeAxis;
