// syncfusionejs2_trial/Samples/Vue/source/chart/marker-chart.vue
<template>
  <div class="control-section">
    <div align='center'>
      <ejs-chart style='display:block' :theme='theme' align='center' id='chartcontainer' :title='title'
        :primaryXAxis='primaryXAxis' :primaryYAxis='primaryYAxis' :chartArea='chartArea' :width='width'
        :tooltip='tooltip' :legendSettings='legendSettings'>
        <e-series-collection>
          <e-series :dataSource='seriesData' type='Line' xName='Country' yName='FBUser_07' name='2007' width=2
            :marker='marker'> </e-series>
          <e-series :dataSource='seriesData' type='Line' xName='Country' yName='FBUser_08' name='2008' width=2
            :marker='marker1'> </e-series>
          <e-series :dataSource='seriesData' type='Line' xName='Country' yName='FBUser_09' name='2009' width=2
            :marker='marker2'> </e-series>
        </e-series-collection>
      </ejs-chart>
    </div>
    <div id="action-description">
      <p>
        This sample illustrates Facebook users in a chart for different countries over several years. 
        In a line-based series, data points can be annotated using symbols.
      </p>
    </div>
    <div id="description">
      <p>
        Each data point in a series can be represented by a symbol as a marker. 
        You can customize the shape, size, and color of the symbol through <code>marker</code> properties.
      </p>
      <p>
        <code>Tooltip</code> is enabled in this example. To see the tooltip in action, hover the mouse over a
        point or tap a point in touch enabled devices.
      </p>
      <p>
        More information on the marker can be found in this
        <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/chart/data-markers/#marker" aria-label="Navigate to the documentation for Data Markers in Vue Chart component">documentation
          section</a>.
      </p>
    </div>
  </div>
</template>
<style scoped>

</style>
<script>
import { Browser } from '@syncfusion/ej2-base';
import { ChartComponent, SeriesDirective, SeriesCollectionDirective, LineSeries, Category, Legend, Tooltip, Highlight } from "@syncfusion/ej2-vue-charts";

import { loadChartTheme } from "./theme-color";
let theme = loadChartTheme();

export default {
  components: {
    'ejs-chart': ChartComponent,
    'e-series-collection': SeriesCollectionDirective,
    'e-series': SeriesDirective
  },
  data: function () {
    return {
      theme: theme,
      seriesData: [
        { Country: "World Wide", FBUser_07: 12, FBUser_08: 22, FBUser_09: 38.3, TooltipMappingName: "World Wide" },
        { Country: "Europe", FBUser_07: 9.9, FBUser_08: 26, FBUser_09: 45.2, TooltipMappingName: "Europe" },
        { Country: "Asia Pacific", FBUser_07: 6.4, FBUser_08: 9.6, FBUser_09: 18.2, TooltipMappingName: "Asia Pacific" },
        { Country: "Latin America", FBUser_07: 4.4, FBUser_08: 28, FBUser_09: 46.7, TooltipMappingName: "Latin America" },
        { Country: "Middle East Africa", FBUser_07: 30, FBUser_08: 45.7, FBUser_09: 61.5, TooltipMappingName: "Middle East Africa" },
        { Country: "North America", FBUser_07: 25.3, FBUser_08: 35.9, FBUser_09: 64, TooltipMappingName: "North America" },
      ],
      //Initializing Primary X Axis
      primaryXAxis: {
        valueType: 'Category',
        labelRotation: Browser.isDevice ? -45 : 0,
        interval: 1, labelIntersectAction: Browser.isDevice ? 'None' : 'Rotate45',
        majorGridLines: { width: 0 }, majorTickLines: { width: 0 }
      },
      //Initializing Primary Y Axis
      primaryYAxis:
      {
        rangePadding: 'None',
        labelFormat: '{value}%', minimum: 0,
        lineStyle: { width: 0 },
        maximum: 75, interval: 15,
        majorTickLines: { width: 0 }
      },
      chartArea: {
        border: {
          width: 0
        }
      },
      width: Browser.isDevice ? '100%' : "75%",
      marker: {
        visible: true, width: 8, height: 8,
        isFilled: true,
        shape: 'Diamond', dataLabel: { name: 'TooltipMappingName' }
      },
      marker1: {
        visible: true, width: 8, height: 8,
        isFilled: true,
        shape: 'Pentagon', dataLabel: { name: 'TooltipMappingName' }
      },
      marker2: {
        visible: true,
        width: 8, height: 8,
        shape: 'Triangle',
        isFilled: true,
        dataLabel: { name: 'TooltipMappingName' }
      },
      tooltip: {
        enable: true,
        header: '',
        format: '<b>${point.x}</b> <br> ${series.name} : <b>${point.y}</b>', enableHighlight: true, showNearestTooltip: true
      },
      legendSettings: { visible: true, enableHighlight: true },

      title: "FB Penetration of Internet Audience"
    };
  },
  provide: {
    chart: [LineSeries, Legend, Category, Tooltip, Highlight]
  },
  methods: {
    load: function (args) {
     loadChartTheme(args);

    }
  },

};
</script>

// syncfusionejs2_trial/Samples/Angular/source/chart/marker-chart.component.ts
import { Component, ViewEncapsulation } from '@angular/core';
import { ILoadedEventArgs, ChartTheme, ChartAllModule } from '@syncfusion/ej2-angular-charts';
import { Browser } from '@syncfusion/ej2-base';
import { SBDescriptionComponent } from '../common/dp.component';
import { SBActionDescriptionComponent } from '../common/adp.component';
import { loadChartTheme } from './theme-color';

/**
 * Sample for Chart Symbols
 */
@Component({
    selector: 'control-content',
    templateUrl: 'marker-chart.html',
    styleUrls: ['chart.style.css'],
    encapsulation: ViewEncapsulation.None,
    standalone: true,
    imports: [SBActionDescriptionComponent, ChartAllModule, SBDescriptionComponent]
})
export class MarkerChartComponent {

    public data: Object[] = [
        {  y: 12, x: 'World Wide' },
        { y: 9.9, x: 'Europe' },
        { y: 4.4, x: 'Asia Pacific' },
        { y: 6.4, x: 'Latin America' },
        { y: 30, x: 'Middle East Africa' },
        { y: 25.3, x: 'North America' }];
    public data1: Object[] = [
        { y: 22, x: 'World Wide' },
        { y: 26, x: 'Europe' },
        {  y: 9.3, x: 'Asia Pacific' },
        {  y: 28, x: 'Latin America' },
        {  y: 45.7, x: 'Middle East Africa' },
        { y: 35.9, x: 'North America' }];
    public data2: Object[] = [
        {  y: 38.3, x: 'World Wide' },
        {  y: 45.2, x: 'Europe' },
        {  y: 18.2, x: 'Asia Pacific' },
        {  y: 46.7, x: 'Latin America' },
        {  y: 61.5, x: 'Middle East Africa' },
        {  y: 64, x: 'North America' }];
    //Initializing Primary X Axis
    public primaryXAxis: Object = {
         valueType: 'Category',
        interval: 1, labelIntersectAction: Browser.isDevice ? 'None' : 'Trim', 
        majorGridLines: { width: 0 }, majorTickLines: {width : 0},
        minorTickLines: {width: 0}, labelRotation: Browser.isDevice ? -45 : 0
    };
    //Initializing Primary Y Axis
    public primaryYAxis: Object = {
        title: 'Penetration',
        rangePadding: 'None',
        labelFormat: '{value}%', minimum: 0,
        lineStyle: { width: 0 },
        maximum: 75, interval: 15
    };
    public legend: Object = {
        visible: true,
        enableHighlight : true
    };
    //Initializing Marker
    public marker1: Object = {
        visible: true, width: 8, height: 8,
        shape: 'Diamond', dataLabel: { name: 'x' }, isFilled: true
    };
    public marker2: Object = {
        visible: true, width: 8, height: 8,
        shape: 'Pentagon', dataLabel: { name: 'x' }, isFilled: true
    };
    public marker3: Object = {
        visible: true,
        width: 8, height: 8,
        shape: 'Triangle',
        dataLabel: { name: 'x' }, isFilled: true
    };
    public tooltip: Object = {
        enable: true, header:"" ,format:"<b>${point.x}</b> <br> ${series.name} : <b>${point.y}</b>", showNearestTooltip: true, enableHighlight: true
    };
    public chartArea: Object = {
        border: {
            width: 0
        }
    };

    public width: string = Browser.isDevice ? '100%' : '75%';
    // custom code start
    public load(args: ILoadedEventArgs): void {
        loadChartTheme(args);
    };
    // custom code end
    public title: string = 'FB Penetration of Internet Audience';
    constructor() {
        //code
    };

}
