// syncfusionejs2_trial/Samples/Vue/source/gantt/toolbar-template.vue
<template>
    <div>
        <div class="control-section">
            <div class="content-wrapper">
                <ejs-gantt ref='gantt' id="ToolbarTemplate" :dataSource="data" :taskFields="taskFields"
                    :toolbar="toolbar" :allowSelection="true" :allowFiltering="true" :height="height" :rowHeight="46"
                    :taskbarHeight="25" :treeColumnIndex="1" :highlightWeekends="true" :columns="columns"
                    :labelSettings="labelSettings" :projectStartDate="projectStartDate" :projectEndDate="projectEndDate"
                    :splitterSettings="splitterSettings" v-on:toolbarClick="toolbarClick">
                </ejs-gantt>
            </div>
        </div>

        <div id="action-description">
            <p>This sample explains the way of rendering built-in and custom toolbar items at the same time.</p>
        </div>

        <div id="description">
            <p>Custom toolbar items can be added by defining the toolbar as a collection of ItemModels.
                Actions for this customized toolbar items are defined in the <a target="_blank"
                    href="https://ej2.syncfusion.com/vue/documentation/api/gantt#toolbarclick">toolbarClick</a> event.
            </p>
            <p>In this sample, the custom toolbar element <code>Quick Filter</code> and <code>Clear Filter</code> is
                rendered
                along with predefined toolbar items ExpandAll and CollapseAll.
                While clicking the <code>Quick Filter</code> toolbar item, the filtering occurs for
                <code>Task Name</code>column.Filtered column can be cleared using <code>Clear Filter</code> toolbar
                item.
            </p>
            <p style="font-weight: 500">Injecting Module:</p>
            <p>
                Gantt component features are segregated into individual feature-wise modules. To use selection, filter, toolbar and
                markers features, inject the <code>Selection</code>, <code>Filter</code>, <code>Toolbar</code> and
                <code>DayMarkers</code> modules using the <code>provide</code> section.
            </p>
            <p>More information on the Essential<sup>®</sup> Vue Gantt Chart can be found in this <a target="_blank"
                href="https://ej2.syncfusion.com/vue/documentation/gantt/toolbar">documentation section</a>.</p>
        </div>
    </div>
</template>
<script>
import { GanttComponent, Selection, Toolbar, DayMarkers, Filter } from "@syncfusion/ej2-vue-gantt";
import { projectNewData } from './data-source';

export default {
    components: {
        'ejs-gantt': GanttComponent
    },
    data: function () {
        return {
            data: projectNewData,
            taskFields: {
                id: 'TaskID',
                name: 'TaskName',
                startDate: 'StartDate',
                endDate: 'EndDate',
                duration: 'Duration',
                progress: 'Progress',
                dependency: 'Predecessor',
                parentID: 'ParentId'
            },
            toolbar: ['ExpandAll', 'CollapseAll', { text: 'Quick Filter', tooltipText: 'Quick Filter', id: 'Quick Filter', prefixIcon: 'e-quickfilter' }, { text: 'Clear Filter', tooltipText: 'Clear Filter', id: 'Clear Filter' }],
            height: '650px',
            columns: [
                { field: 'TaskID', width: 100 },
                { field: 'TaskName', width: 280 },
                { field: 'StartDate' },
                { field: 'EndDate' },
                { field: 'Duration' },
                { field: 'Predecessor', width: 190 },
                { field: 'Progress' },
            ],
            labelSettings: {
                leftLabel: 'TaskName',
            },
            splitterSettings: {
                columnIndex: 2
            },
            projectStartDate: new Date('03/26/2025'),
            projectEndDate: new Date('07/20/2025')
        };
    },
    provide: {
        gantt: [Selection, Toolbar, DayMarkers, Filter]
    },
    methods: {
        toolbarClick: function (args) {
            if (args.item.text === 'Quick Filter') {
                this.$refs.gantt.filterByColumn('TaskName', 'startswith', 'Identify');
            }
            if (args.item.text === 'Clear Filter') {
                this.$refs.gantt.clearFiltering();
            }
        }
    }
}
</script>

<style scoped>
#ToolbarTemplate .e-quickfilter::before {
    content: "\e7ee";
    font-size: 16px;
    font-family: "e-icons"
}

.fabric #ToolbarTemplate ::v-deep .e-quickfilter::before,
.highcontrast #ToolbarTemplate ::v-deep .e-quickfilter::before {
    content: '\e21c';
    font-size: 16px;
    font-family: "e-icons"
}

.bootstrap #ToolbarTemplate ::v-deep .e-quickfilter::before {
    content: '\e946';
    font-size: 16px;
    font-family: "e-icons"
}

.bootstrap4 #ToolbarTemplate ::v-deep .e-quickfilter::before {
    content: '\e714';
    font-size: 16px;
    font-family: "e-icons"
}

.tailwind #ToolbarTemplate ::v-deep .e-quickfilter::before,
.tailwind3 #ToolbarTemplate ::v-deep .e-quickfilter::before,
.tailwind3-dark #ToolbarTemplate ::v-deep .e-quickfilter::before {
    content: '\e7f7';
    font-size: 16px;
    font-family: "e-icons"
}

.fluent #ToolbarTemplate ::v-deep .e-quickfilter::before,
.fluent2 #ToolbarTemplate ::v-deep .e-quickfilter::before,
.fluent2-dark #ToolbarTemplate ::v-deep .e-quickfilter::before,
.fluent2-highcontrast #ToolbarTemplate ::v-deep .e-quickfilter::before,
.bootstrap5_3 #ToolbarTemplate ::v-deep .e-quickfilter::before,
.bootstrap5_3-dark-lite #ToolbarTemplate ::v-deep .e-quickfilter::before,
.bootstrap5_3-dark #ToolbarTemplate ::v-deep .e-quickfilter::before,
.bootstrap5_3-lite #ToolbarTemplate ::v-deep .e-quickfilter::before,
.material3-dark #ToolbarTemplate ::v-deep .e-quickfilter::before,
.material3 #ToolbarTemplate ::v-deep .e-quickfilter::before {
    content: '\e7f7';
    font-size: 16px;
    font-family: "e-icons"
}
</style>

// syncfusionejs2_trial/Samples/React/src/gantt/toolbar-template.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.ToolbarTemplate = void 0;
var React = require("react");
var ej2_react_gantt_1 = require("@syncfusion/ej2-react-gantt");
var data_1 = require("./data");
var sample_base_1 = require("../common/sample-base");
require("./toolbar-template.css");
var ToolbarTemplate = /** @class */ (function (_super) {
    __extends(ToolbarTemplate, _super);
    function ToolbarTemplate() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        _this.taskFields = {
            id: 'TaskID',
            name: 'TaskName',
            startDate: 'StartDate',
            endDate: 'EndDate',
            duration: 'Duration',
            progress: 'Progress',
            dependency: 'Predecessor',
            parentID: 'ParentId'
        };
        _this.toolbar = ['ExpandAll', 'CollapseAll', { text: 'Quick Filter', tooltipText: 'Quick Filter', id: 'Quick Filter', prefixIcon: 'e-quickfilter' }, { text: 'Clear Filter', tooltipText: 'Clear Filter', id: 'Clear Filter' }];
        _this.splitterSettings = {
            columnIndex: 2
        };
        _this.labelSettings = {
            leftLabel: 'TaskName'
        };
        _this.projectStartDate = new Date('03/26/2025');
        _this.projectEndDate = new Date('07/20/2025');
        return _this;
    }
    ToolbarTemplate.prototype.toolbarClick = function (args) {
        if (args.item.text === 'Quick Filter') {
            this.ganttInstance.filterByColumn('TaskName', 'startswith', 'Identify');
        }
        if (args.item.text === 'Clear Filter') {
            this.ganttInstance.clearFiltering();
        }
    };
    ToolbarTemplate.prototype.render = function () {
        var _this = this;
        return (React.createElement("div", { className: 'control-pane' },
            React.createElement("div", { className: 'control-section' },
                React.createElement(ej2_react_gantt_1.GanttComponent, { id: 'ToolbarTemplate', ref: function (gantt) { return _this.ganttInstance = gantt; }, dataSource: data_1.projectNewData, highlightWeekends: true, allowFiltering: true, treeColumnIndex: 1, splitterSettings: this.splitterSettings, toolbar: this.toolbar, toolbarClick: this.toolbarClick.bind(this), taskFields: this.taskFields, labelSettings: this.labelSettings, height: '650px', taskbarHeight: 25, rowHeight: 46, projectStartDate: this.projectStartDate, projectEndDate: this.projectEndDate },
                    React.createElement(ej2_react_gantt_1.ColumnsDirective, null,
                        React.createElement(ej2_react_gantt_1.ColumnDirective, { field: 'TaskID', width: '100' }),
                        React.createElement(ej2_react_gantt_1.ColumnDirective, { field: 'TaskName', width: '250' }),
                        React.createElement(ej2_react_gantt_1.ColumnDirective, { field: 'StartDate' }),
                        React.createElement(ej2_react_gantt_1.ColumnDirective, { field: 'EndDate' }),
                        React.createElement(ej2_react_gantt_1.ColumnDirective, { field: 'Duration' }),
                        React.createElement(ej2_react_gantt_1.ColumnDirective, { field: 'Predecessor', width: 190 }),
                        React.createElement(ej2_react_gantt_1.ColumnDirective, { field: 'Progress' })),
                    React.createElement(ej2_react_gantt_1.Inject, { services: [ej2_react_gantt_1.Selection, ej2_react_gantt_1.DayMarkers, ej2_react_gantt_1.Filter, ej2_react_gantt_1.Toolbar] }))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null, "This sample explains the way of rendering built-in and custom toolbar items at the same time.")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null,
                    "Custom toolbar items can be added by defining the toolbar as a collection of ItemModels. Actions for this customized toolbar items are defined in the ",
                    React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/api/gantt/index-default#toolbarclick" }, "toolbarClick"),
                    " event."),
                React.createElement("p", null,
                    "In this sample, the custom toolbar element ",
                    React.createElement("code", null, "Quick Filter"),
                    " and ",
                    React.createElement("code", null, "Clear Filter"),
                    " is rendered along with predefined toolbar items ExpandAll and CollapseAll. While clicking the ",
                    React.createElement("code", null, "Quick Filter"),
                    " toolbar item, the filtering occurs for ",
                    React.createElement("code", null, "Task Name"),
                    "column.Filtered column can be cleared using ",
                    React.createElement("code", null, "Clear Filter"),
                    " toolbar item."),
                React.createElement("p", null,
                    "Gantt component features are segregated into individual feature-wise modules.To use selection, filter, toolbar and marker features, we need to inject the",
                    React.createElement("code", null, "Selection"),
                    " , ",
                    React.createElement("code", null, "Filter"),
                    " , ",
                    React.createElement("code", null, "Toolbar"),
                    " and ",
                    React.createElement("code", null, "DayMarkers"),
                    " into the ",
                    React.createElement("code", null, "Inject Services"),
                    " section."),
                React.createElement("br", null),
                React.createElement("p", null,
                    "More information on the Essential",
                    React.createElement("sup", null, "\u00AE"),
                    " React Gantt Chart can be found in this ",
                    React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/gantt/tool-bar" }, "documentation section"),
                    "."))));
    };
    return ToolbarTemplate;
}(sample_base_1.SampleBase));
exports.ToolbarTemplate = ToolbarTemplate;
