// syncfusionejs2_trial/Samples/React/src/stock-chart/datetime-category.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.DatetimeCategoryAxis = void 0;
/**
 * Sample for Stock Chart with Default
 */
var React = require("react");
var ej2_react_charts_1 = require("@syncfusion/ej2-react-charts");
var ej2_react_charts_2 = require("@syncfusion/ej2-react-charts");
var sample_base_1 = require("../common/sample-base");
var stock_data_1 = require("./stock-data");
var DatetimeCategoryAxis = /** @class */ (function (_super) {
    __extends(DatetimeCategoryAxis, _super);
    function DatetimeCategoryAxis() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    DatetimeCategoryAxis.prototype.render = function () {
        return (React.createElement("div", { className: 'control-pane' },
            React.createElement("div", { className: 'control-section' },
                React.createElement(ej2_react_charts_1.StockChartComponent, { id: 'stockchartdefault', primaryXAxis: {
                        majorGridLines: { width: 0 },
                        crosshairTooltip: { enable: true },
                        valueType: 'DateTimeCategory'
                    }, primaryYAxis: {
                        lineStyle: { width: 0 },
                        majorTickLines: { width: 0 }
                    }, chartArea: { border: { width: 0 } }, tooltip: { enable: true, header: 'AAPL Stock Price', format: '${point.x}: <b>${point.y}</b>' }, crosshair: { enable: true }, load: this.load.bind(this), title: 'AAPL Stock Price' },
                    React.createElement(ej2_react_charts_1.Inject, { services: [ej2_react_charts_1.DateTimeCategory, ej2_react_charts_1.AreaSeries, ej2_react_charts_1.CandleSeries, ej2_react_charts_1.HiloOpenCloseSeries, ej2_react_charts_1.HiloSeries, ej2_react_charts_1.LineSeries, ej2_react_charts_1.SplineSeries,
                            ej2_react_charts_2.AccumulationDistributionIndicator, ej2_react_charts_2.AtrIndicator, ej2_react_charts_2.BollingerBands, ej2_react_charts_2.EmaIndicator, ej2_react_charts_2.MomentumIndicator,
                            ej2_react_charts_2.MacdIndicator, ej2_react_charts_2.RsiIndicator, ej2_react_charts_2.SmaIndicator, ej2_react_charts_2.StochasticIndicator, ej2_react_charts_1.Trendlines, ej2_react_charts_2.TmaIndicator, ej2_react_charts_1.RangeTooltip, ej2_react_charts_1.Tooltip, ej2_react_charts_1.Crosshair, ej2_react_charts_2.Export] }),
                    React.createElement(ej2_react_charts_1.StockChartSeriesCollectionDirective, null,
                        React.createElement(ej2_react_charts_1.StockChartSeriesDirective, { dataSource: stock_data_1.datetimeCategoryData, type: 'Spline' })))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null,
                    "This sample demonstrates the AAPL stock price using the ",
                    React.createElement("code", null, "DateTimeCategory"),
                    " axis type in the stock chart to display the minimum number of labels without any overlap on various business days.")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null,
                    "In this example, you can see how to render and configure a stock chart to visualize stock data using the ",
                    React.createElement("code", null, "DateTimeCategory"),
                    " axis type. Use series ",
                    React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/stock-chart/series-types", "aria-label": "Navigate to the type property reference for React Stock Chart series" }, "type"),
                    " as ",
                    React.createElement("code", null, "Spline"),
                    " to render a spline series."),
                React.createElement("p", null,
                    React.createElement("code", null, "Tooltip"),
                    " is enabled in this example. To see the tooltip in action, hover the chart or tap on it in touch enabled devices."),
                React.createElement("p", null,
                    "More information about axis types can be found in this",
                    React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/stock-chart/axis-types", "aria-label": "Navigate to the documentation for axis types in React Stock Chart component" }, "documentation section"),
                    "."),
                React.createElement("p", null,
                    React.createElement("b", null, "Injecting Module")),
                React.createElement("p", null,
                    "The stock chart component features are segregated into individual feature-wise modules. To use datetime category axis, inject the ",
                    React.createElement("code", null, "DateTimeCategory"),
                    " module using the ",
                    React.createElement("code", null, "StockChart.Inject(DateTimeCategory)"),
                    " method. To use the SplineSeries, inject the ",
                    React.createElement("code", null, "SplineSeries"),
                    " module using the ",
                    React.createElement("code", null, "StockChart.Inject(SplineSeries)"),
                    " method."))));
    };
    DatetimeCategoryAxis.prototype.tooltipRender = function (args) {
        if (args.text.split('<br/>')[4]) {
            var target = parseFloat(args.text.split('<br/>')[4].split('<b>')[1].split('</b>')[0]);
            var value = (target / 100000000).toFixed(1) + 'B';
            args.text = args.text.replace(args.text.split('<br/>')[4].split('<b>')[1].split('</b>')[0], value);
        }
    };
    ;
    DatetimeCategoryAxis.prototype.load = function (args) {
        var selectedTheme = location.hash.split('/')[1];
        selectedTheme = selectedTheme ? selectedTheme : 'Fluent2';
        args.stockChart.theme = (selectedTheme.charAt(0).toUpperCase() + selectedTheme.slice(1)).
            replace(/-dark/i, "Dark").replace(/contrast/i, 'Contrast').replace(/-highContrast/i, 'HighContrast');
    };
    return DatetimeCategoryAxis;
}(sample_base_1.SampleBase));
exports.DatetimeCategoryAxis = DatetimeCategoryAxis;

// syncfusionejs2_trial/Samples/Vue/public/source/stock-chart/datetime-category.vue
<template>
    <div class="control-section">
        <div>
            <ejs-stockchart style="display:block" id="stockchartcontainerdefault" :primaryXAxis="primaryXAxis"
                :primaryYAxis="primaryYAxis" :chartArea="chartArea" :tooltip="tooltip" :crosshair="crosshair" :title="title" 
                :theme="theme">
                <e-stockchart-series-collection>
                     <e-stockchart-series :dataSource="seriesData" type="Spline"></e-stockchart-series>
                </e-stockchart-series-collection>
            </ejs-stockchart>
        </div>
  
        <div id="action-description">
            <p>This sample demonstrates the AAPL stock price using the <code>DateTimeCategory</code> axis type in the stock chart to display the minimum number of labels without any overlap on various business days.</p>
        </div>
        <div id="description">
            <p>
                In this example, you can see how to render and configure a stock chart to visualize stock data using the <code>DateTimeCategory</code> axis type. Use series <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/api/chart/series/#type" aria-label="Navigate to the type property reference for Vue Stock Chart component">type</a> as <code>Spline</code> to render a spline series.
            </p>
            <p>
                <code>Tooltip</code> is enabled in this example. To see the tooltip in action, hover the chart or tap on it in touch enabled devices.
            </p>
            
            <p style="font-weight: 500"><b>Injecting Module</b></p>
            <p>
                The stock chart component features are segregated into individual feature-wise modules. To use datetime category
                axis and spline, inject the
                <code>DateTimeCategory</code> and <code>SplineSeries</code> module using
                <code> provide: { stockchart: [ DateTimeCategory, SplineSeries] },</code> method.
            </p>
            <p>
                More information about axis type can be found in this
                <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/stock-chart/axis-types" aria-label="Navigate to the documentation for axis types in Vue Stock Chart component">documentation
                    section</a>.
            </p>
  
        </div>
    </div>
  </template>
  <script>
  import { Browser } from "@syncfusion/ej2-base";
  import { datetimeCategoryData } from "./stock-data";
  import {
    StockChartComponent,
    StockChartSeriesCollectionDirective,
    StockChartSeriesDirective,
    DateTimeCategory,
    CandleSeries,
    Tooltip,
    Crosshair,
    RangeTooltip,
    LineSeries,
    SplineSeries,
    HiloOpenCloseSeries,
    HiloSeries,
    RangeAreaSeries,
    Trendlines,
    EmaIndicator,
    RsiIndicator,
    BollingerBands,
    TmaIndicator,
    MomentumIndicator,
    SmaIndicator,
    AtrIndicator,
    AccumulationDistributionIndicator,
    MacdIndicator,
    StochasticIndicator,
    Export
  } from "@syncfusion/ej2-vue-charts";
  import { loadStockChartTheme } from './theme-color';
  
  let theme = loadStockChartTheme();
  
  export default {
    components: {
        'ejs-stockchart': StockChartComponent,
        'e-stockchart-series-collection': StockChartSeriesCollectionDirective,
        'e-stockchart-series': StockChartSeriesDirective
    },
    data: function () {
        return {
            seriesData: datetimeCategoryData,
            theme: theme,
            //Initializing Primary X Axis
            primaryXAxis: {
                majorGridLines: { width: 0 },
                crosshairTooltip: { enable: true },
                valueType: 'DateTimeCategory',
                edgeLabelPlacement: 'Shift'
            },
  
            //Initializing Primary Y Axis
            primaryYAxis: {
                lineStyle: { width: 0 },
            majorTickLines: { width: 0 }
            },
            crosshair: {
                enable: true,
            },
            title: 'AAPL Stock Price',
            chartArea: {
                border: {
                    width: 0
                }
            },
            tooltip: { enable: true, header: 'AAPL Stock Price', format: '${point.x}: <b>${point.y}</b>' },
        };
    },
    provide: {
        stockChart: [
        DateTimeCategory,
            Tooltip,
            Crosshair,
            RangeTooltip,
            LineSeries,
            SplineSeries,
            CandleSeries,
            HiloOpenCloseSeries,
            HiloSeries,
            RangeAreaSeries,
            Trendlines,
            EmaIndicator,
            RsiIndicator,
            BollingerBands,
            TmaIndicator,
            MomentumIndicator,
            SmaIndicator,
            AtrIndicator,
            AccumulationDistributionIndicator,
            MacdIndicator,
            StochasticIndicator,
            Export
        ]
    },
    methods: {
    }
  };
  </script>
