// syncfusionejs2_trial/Samples/Vue/public/source/range-slider/events.vue
<template>
  <div class="slider-events">
    <div class="col-lg-8 control-section">
      <div class="content_wrapper">
        <div class="sliderwrap">
          <!-- Slider element -->
          <ejs-slider
            id="minrange"
            ref="minslider"
            :value="value"
            :min="min"
            :max="max"
            :type="type"
            :ticks="ticks"
            :tooltip="tooltip"
            :created="onCreated"
            :change="onChange"
            :changed="onChanged"
          ></ejs-slider>
        </div>
      </div>
    </div>

    <div id="slider_event" class="col-lg-4 property-section">
      <table id="property" title="Event Trace">
        <tr>
          <td>
            <div class="eventarea" style="height: 245px;overflow: auto">
              <!-- Event log element -->
              <span class="EventLog" id="EventLog" style="word-break: normal;"></span>
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <div class="evtbtn" style="padding-top:10px;padding-bottom: 10px">
              <!-- clear button element -->
              <button
                id="clear"
                type="button"
                class="e-control e-btn e-primary"
                value="Clear"
                v-on:click="onClear"
              >Clear</button>
            </div>
          </td>
        </tr>
      </table>
    </div>

    <div id="action-description">
      <p>
        This sample demonstrates the events that have been triggered on the Slider operations with the help of event trace panel.
        Drag the thumb over the bar between min and max to know the event details.
      </p>
    </div>

    <div id="description">
      <p>
        Slider component triggers the event based on its actions. The events can be used as an extension point to perform custom
        operations.
      </p>
      <p>In this demo, Slider performs following actions which can be traced by event trace panel:</p>
      <ul>
        <li><a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/api/slider/#change">created</a> - Triggers when Slider is created.</li>
        <li><a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/api/slider/#change">change</a> - Triggers when the Slider value is changed.</li>
        <li><a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/api/slider/#changed">changed</a> - Triggers when the Slider action is completed with change in Slider value.</li>
      </ul>
      <p>
        For more information, refer to the
        <a
          target="_blank"
          href="https://ej2.syncfusion.com/vue/documentation/api/slider/#events"
        >events</a> API from the documentation.
      </p>
    </div>
  </div>
</template>

<style>
.slider-events .property-section {
  margin-top: 20px;
}
.slider-events .content_wrapper {
  padding-top: 50px;
  width: 55%;
  margin: 0 auto;
  min-width: 185px;
}

.slider-events .sliderwrap {
  margin-top: 40px;
}

.e-bigger .slider-events .content_wrapper {
  width: 80%;
}

.slider-events .userselect {
  -webkit-user-select: none;
  /* Safari 3.1+ */
  -moz-user-select: none;
  /* Firefox 2+ */
  -ms-user-select: none;
  /* IE 10+ */
  user-select: none;
  /* Standard syntax */
}

.slider-events #EventLog b {
  color: #27642a;
}

.slider-events hr {
  margin-top: 6px;
  margin-bottom: 6px;
}

.slider-events #slider_event .property-panel-table div {
  margin-top: -4px;
  padding-bottom: 0px;
}

.slider-events #slider_event.property-section {
  margin-bottom: -19px;
}
</style>

<script>
import { SliderComponent } from "@syncfusion/ej2-vue-inputs";
import { ButtonComponent } from "@syncfusion/ej2-vue-buttons";
import { isNullOrUndefined } from "@syncfusion/ej2-base";

export default {
  data: function() {
    return {
      value: 30,
      min: 0,
      max: 100,
      type: "MinRange",
      ticks: {
        placement: "Both",
        largeStep: 20,
        smallStep: 5,
        showSmallTicks: true
      },
      tooltip: { isVisible: true, placement: "Before", showOn: "Focus" }
    };
  },
  components: { 
    'ejs-slider': SliderComponent,
    'ejs-button': ButtonComponent
  },
  methods: {
    onCreated: function() {
      this.appendElement("Slider control has been <b>created</b><hr>");
    },
    onChange: function(args) {
      this.appendElement(
        "Slider value is <b>changing</b> from " +
          args.previousValue +
          "  to  " +
          args.value +
          "<hr>"
      );
    },
    onChanged: function(args) {
      this.appendElement(
        "Slider value has been <b>changed</b> from " +
          args.previousValue +
          "  to  " +
          args.value +
          "<hr>"
      );
    },
    appendElement: function appendElement(html) {
      var span = document.createElement("span");
      span.innerHTML = html;
      var log = document.getElementById("EventLog");
      log.insertBefore(span, log.firstChild);
    },
    onClear: function() {
      document.getElementById("EventLog").innerHTML = "";
    },
    onScroll: function() {
      if (
        !isNullOrUndefined(document.getElementById("minrange")) &&
        this.$refs.minslider
      ) {
        this.$refs.minslider.ej2Instances.refreshTooltip(this.$refs.minslider.ej2Instances.tooltipTarget);
      }
    }
  },
  mounted: function() {
    if (document.getElementById("right-pane")) {
      document
        .getElementById("right-pane")
        .addEventListener("scroll", this.onScroll.bind(this));
    }
  }
};
</script>

// syncfusionejs2_trial/Samples/React/src/range-slider/events.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.Events = void 0;
var React = require("react");
var ej2_react_inputs_1 = require("@syncfusion/ej2-react-inputs");
var sample_base_1 = require("../common/sample-base");
var property_pane_1 = require("../common/property-pane");
var ej2_base_1 = require("@syncfusion/ej2-base");
var slidercss = "\n.content-wrapper {\n    width: 52%;\n    margin: 0 auto;\n    min-width: 185px;\n}\n\n.sliderwrap {\n    margin-top: 60px;\n}\n\n.userselect {\n    -webkit-user-select: none;\n    /* Safari 3.1+ */\n    -moz-user-select: none;\n    /* Firefox 2+ */\n    -ms-user-select: none;\n    /* IE 10+ */\n    user-select: none;\n    /* Standard syntax */\n}\n\n#EventLog b {\n    color: #388e3c;\n}\n\nhr {\n    margin-top: 6px;\n    margin-bottom: 6px;\n}\n\n";
var Events = /** @class */ (function (_super) {
    __extends(Events, _super);
    function Events() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        _this.defaultTooltip = { isVisible: true, placement: 'Before', showOn: 'Focus' };
        _this.defaultTicks = { placement: 'Both', largeStep: 20, smallStep: 5, showSmallTicks: true };
        return _this;
    }
    //Handler for create event trace
    Events.prototype.onCreated = function () {
        this.appendElement('Slider control has been <b>created</b><hr>');
    };
    //Handler for change event trace
    Events.prototype.onChange = function (args) {
        this.appendElement('Slider value is <b>changing</b> from ' + args.previousValue + '  to  ' + args.value + '<hr>');
    };
    //Handler for changed event trace
    Events.prototype.onChanged = function (args) {
        this.appendElement('Slider value has been <b>changed</b> from ' + args.previousValue + '  to  ' + args.value + '<hr>');
    };
    //Display event log
    Events.prototype.appendElement = function (html) {
        var span = document.createElement('span');
        span.innerHTML = html;
        var log = document.getElementById('EventLog');
        log.insertBefore(span, log.firstChild);
    };
    // Clears the event log details
    Events.prototype.onclick = function () {
        document.getElementById('EventLog').innerHTML = '';
    };
    Events.prototype.refreshTooltip = function (e) {
        if (this.defaultObj) {
            this.defaultObj.refreshTooltip(this.defaultObj.tooltipTarget);
        }
    };
    Events.prototype.render = function () {
        var _this = this;
        if (!(0, ej2_base_1.isNullOrUndefined)(document.getElementById('right-pane'))) {
            document.getElementById('right-pane').addEventListener('scroll', this.refreshTooltip.bind(this));
        }
        return (React.createElement("div", { className: 'control-pane' },
            React.createElement("style", null, slidercss),
            React.createElement("div", { className: 'control-section' },
                React.createElement("div", { className: 'col-lg-8' },
                    React.createElement("div", { className: "content-wrapper" },
                        React.createElement("div", { className: 'sliderwrap' },
                            React.createElement(ej2_react_inputs_1.SliderComponent, { id: 'minrange', value: 30, type: 'MinRange', tooltip: this.defaultTooltip, ticks: this.defaultTicks, ref: function (slider) { _this.defaultObj = slider; }, changed: this.onChanged.bind(this), created: this.onCreated.bind(this), change: this.onChange.bind(this) })))),
                React.createElement("div", { id: "slider_event", className: "col-lg-4 property-section" },
                    React.createElement(property_pane_1.PropertyPane, { title: 'Properties' },
                        React.createElement("table", { id: "property", title: "Event Trace", className: 'property-panel-table', style: { width: '100%' } },
                            React.createElement("tbody", null,
                                React.createElement("tr", null,
                                    React.createElement("td", null,
                                        React.createElement("div", { className: "eventarea", style: { height: '245px', overflow: 'auto' } },
                                            React.createElement("span", { className: "EventLog", id: "EventLog", style: { wordBreak: 'normal' } })))),
                                React.createElement("tr", null,
                                    React.createElement("td", null,
                                        React.createElement("div", { className: "evtbtn", style: { paddingBottom: '10px' } },
                                            React.createElement("input", { id: "clear", type: "button", className: "btn btn-default", value: "Clear", onClick: this.onclick }))))))))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null, "This sample demonstrates the events that have been triggered on the Slider operations with the help of Event Trace panel. Drag the thumb over the bar between min and max to know the event details.")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null, "Slider component triggers event based on its actions. The events can be used as an extension point to perform custom operations."),
                React.createElement("p", null, "In this demo, Slider performs following action like created, change, changed Which can be traced by event trace panel."),
                React.createElement("ul", null,
                    React.createElement("li", null,
                        React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/api/slider/#change" }, "created"),
                        " - Triggers when Slider is created."),
                    React.createElement("li", null,
                        React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/api/slider/#change" }, "change"),
                        " - Triggers when the Slider value is changed."),
                    React.createElement("li", null,
                        React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/api/slider/#changed" }, "changed"),
                        " - Triggers when the Slider action is completed with change in Slider value.")),
                React.createElement("p", null,
                    "For more information, we can refer the",
                    React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/api/slider/#events" }, "events"),
                    " API from the documentation."))));
    };
    return Events;
}(sample_base_1.SampleBase));
exports.Events = Events;
