// syncfusionejs2_trial/Samples/Angular/source/tooltip/tooltip-menu.component.ts
/**
 * Tooltip template sample
 */

import { Component, ViewChild, ViewChildren, ViewEncapsulation, Inject } from '@angular/core';
import { TooltipComponent, TooltipEventArgs, TooltipModule } from '@syncfusion/ej2-angular-popups';
import { ListViewComponent, ListViewModule } from '@syncfusion/ej2-angular-lists';
import { closest } from '@syncfusion/ej2-base';
import { SBDescriptionComponent } from '../common/dp.component';
import { ToolbarModule } from '@syncfusion/ej2-angular-navigations';
import { SBActionDescriptionComponent } from '../common/adp.component';
@Component({
    selector: 'control-content',
    templateUrl: 'tooltip-menu.html',
    styleUrls: ['tooltip-menu.css'],
    encapsulation: ViewEncapsulation.None,
    standalone: true,
    imports: [SBActionDescriptionComponent, TooltipModule, ToolbarModule, ListViewModule, SBDescriptionComponent]
})

export class TooltipMenuComponent {
    @ViewChild('tooltip')
    public tooltip: TooltipComponent;
    @ViewChild('listview')
    public listview: ListViewComponent;
    public fields = {
        text: 'Name',
        iconCss: 'icon'
    }

    public data: any;

    public data1: any = [{
        Name: 'WI-FI',
        id: '1',
        icon: 'wifi'
    },
    {
        Name: 'Bluetooth',
        id: '2',
        icon: 'bluetooth'
    },
    {
        Name: 'SIM cards',
        id: '3',
        icon: 'sim'
    }
    ];
    public data2: any = [{
        Name: 'Display',
        icon: 'display'
    },
    {
        Name: 'Sound',
        icon: 'sound'
    },
    {
        Name: 'Battery',
        icon: 'battery'
    },
    {
        Name: 'Users',
        icon: 'user'
    }
    ];
    public data3: any = [{
        Name: 'Location',
        icon: 'location'
    },
    {
        Name: 'Security',
        icon: 'security'
    },
    {
        Name: 'Language',
        icon: 'language'
    }
    ]
    public created() {
        if (document.getElementById('right-pane')) {
            document.getElementById('right-pane').addEventListener('click', this.onClick.bind(this));
            document.getElementById('right-pane').addEventListener('scroll', this.onScroll.bind(this));
        }
    }
    public onClick(args: any) {
        let targetEle: any;
        if (args) {
            targetEle = closest(args.target, '.e-toolbar-item');
        }
        if (!targetEle) {
            if (this.tooltip && document.getElementsByClassName('e-tooltip-wrap').length > 0) {
                this.tooltip.close();
            }
        }
    }
    public onScroll() {
        if (document.getElementsByClassName('e-tooltip-wrap').length > 0) {
            this.tooltip.close();
        }
    }
    public onBeforeRender(args: any) {
        let data: any = [{
            title: 'Wireless & networks',
            data: this.data1
        },
        {
            title: 'Device',
            data: this.data2
        },
        {
            title: 'Personal',
            data: this.data3
        }
        ];

        for (let i = 0; i < data.length; i++) {
            if (data[i].title === args.target.parentElement.getAttribute('title')) {
                this.data = data[i].data;
            }
        }
    }
}

// syncfusionejs2_trial/Samples/React/src/tooltip/tooltip-menu.js
"use strict";
/**
 * Loading tooltip menu sample
 */
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.TooltipMenu = void 0;
var ej2_react_lists_1 = require("@syncfusion/ej2-react-lists");
var ej2_react_navigations_1 = require("@syncfusion/ej2-react-navigations");
var ej2_react_popups_1 = require("@syncfusion/ej2-react-popups");
var ej2_base_1 = require("@syncfusion/ej2-base");
var React = require("react");
var sample_base_1 = require("../common/sample-base");
require("./tooltip-menu.css");
var TooltipMenu = /** @class */ (function (_super) {
    __extends(TooltipMenu, _super);
    function TooltipMenu() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        _this.fields = { text: "Name", iconCss: "icon" };
        _this.animationSettings = { effect: "None", duration: 0, delay: 0 };
        _this.data1 = [
            { Name: "WI-FI", id: "1", icon: "wifi" },
            { Name: "Bluetooth", id: "2", icon: "bluetooth" },
            { Name: "SIM cards", id: "3", icon: "sim" }
        ];
        _this.data2 = [
            { Name: "Display", icon: "display" },
            { Name: "Sound", icon: "sound" },
            { Name: "Battery", icon: "battery" },
            { Name: "Users", icon: "user" }
        ];
        _this.data3 = [
            { Name: "Location", icon: "location" },
            { Name: "Security", icon: "security" },
            { Name: "Language", icon: "language" }
        ];
        _this.data = [_this.data1, _this.data2, _this.data3];
        return _this;
    }
    TooltipMenu.prototype.tooltipTemplate = function () {
        return (React.createElement(ej2_react_lists_1.ListViewComponent, { id: "tooltipMenu-list", dataSource: this.listData, fields: this.fields, showIcon: true }));
    };
    TooltipMenu.prototype.onClick = function (args) {
        var targetEle;
        if (args) {
            targetEle = (0, ej2_base_1.closest)(args.target, '.e-toolbar-item');
        }
        if (!targetEle) {
            if (document.getElementsByClassName("e-tooltip-wrap").length > 0 && this.tooltip) {
                this.tooltip.close(this.animationSettings);
            }
        }
    };
    TooltipMenu.prototype.onScroll = function () {
        if (document.getElementsByClassName("e-tooltip-wrap").length > 0 && this.tooltip) {
            this.tooltip.close(this.animationSettings);
        }
    };
    TooltipMenu.prototype.onBeforeRender = function (args) {
        var data = [{ title: "Wireless & networks" }, { title: "Device" }, { title: "Personal" }];
        for (var i = 0; i < data.length; i++) {
            if (data[i].title === args.target.parentElement.getAttribute("title")) {
                if (document.getElementsByClassName("e-tooltip-wrap").length > 0) {
                    this.tooltip.close(this.animationSettings);
                }
                this.listData = this.data[i];
            }
        }
    };
    TooltipMenu.prototype.created = function () {
        if (document.getElementById("right-pane")) {
            document.getElementById("right-pane").addEventListener("click", this.onClick.bind(this));
            document.getElementById("right-pane").addEventListener("scroll", this.onScroll.bind(this));
        }
    };
    TooltipMenu.prototype.render = function () {
        var _this = this;
        return (React.createElement("div", { className: "control-pane" },
            React.createElement("div", { className: "control-section" },
                React.createElement("div", { className: "col-lg-12 control-section" },
                    React.createElement(ej2_react_popups_1.TooltipComponent, { created: this.created.bind(this), ref: function (t) { return (_this.tooltip = t); }, opensOn: "Click", cssClass: "e-tooltip-menu-settings", beforeRender: this.onBeforeRender.bind(this), target: "#toolbar-menu button", width: 170, tabIndex: 0, id: "tooltip-menu", content: this.tooltipTemplate.bind(this) },
                        React.createElement("div", { className: "toolbarContainer" },
                            React.createElement(ej2_react_navigations_1.ToolbarComponent, { id: "toolbar-menu" },
                                React.createElement(ej2_react_navigations_1.ItemsDirective, null,
                                    React.createElement(ej2_react_navigations_1.ItemDirective, { prefixIcon: "e-copy-icon tb-icons", tooltipText: "Wireless & networks", text: "Wireless & networks", overflow: "Hide" }),
                                    React.createElement(ej2_react_navigations_1.ItemDirective, { prefixIcon: "e-copy-icon tb-icons", tooltipText: "Device", text: "Device", overflow: "Hide" }),
                                    React.createElement(ej2_react_navigations_1.ItemDirective, { prefixIcon: "e-copy-icon tb-icons", tooltipText: "Personal", text: "Personal", overflow: "Hide" }))))))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null, "In this demo, the Tooltip has been customized to show the list of menu items.")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null,
                    "Tooltip has been integrated with Listview component to display the Tooltip menu. With the help of ",
                    React.createElement("a", { href: "https://ej2.syncfusion.com/react/documentation/api/tooltip/#beforerender" }, "beforeRender"),
                    " event, dataSource for ListView changed and its instance assigned to ",
                    React.createElement("a", { href: "https://ej2.syncfusion.com/react/documentation/api/tooltip/#content" }, "content"),
                    " of Tooltip to appear like menu. On clicking the Toolbar items, the corresponding Tooltip menu will be opened."))));
    };
    return TooltipMenu;
}(sample_base_1.SampleBase));
exports.TooltipMenu = TooltipMenu;
