// syncfusionejs2_trial/Samples/React/src/treegrid/columnformatting.tsx
import * as ReactDOM from 'react-dom';
import * as React from 'react';
import { TreeGridComponent, ColumnsDirective, ColumnDirective, Inject, Page, Column } from '@syncfusion/ej2-react-treegrid';
import { DropDownListComponent, ChangeEventArgs } from '@syncfusion/ej2-react-dropdowns';
import { DateFormatOptions } from '@syncfusion/ej2-base';
import { formatData } from './data';
import { SampleBase } from '../common/sample-base';
import { PropertyPane } from '../common/property-pane';


export class ColumnFormat extends SampleBase<{}, {}> {

  public treegridObj: TreeGridComponent;
  public dropdownObj: DropDownListComponent;
  public dropdownObj2: DropDownListComponent;
  public format: any = { type:'dateTime',format:'M/d/yyyy'};

  private columnNames: { [key: string]: Object }[] = [
    { id: 'price', name: 'Price' },
    { id: 'orderDate', name: 'Order Date' }
  ];

  private priceFormat: { [key: string]: Object }[] = [
    { id: 'n2', format: 'n2' },
    { id: 'n3', format: 'n3' },
    { id: 'c2', format: 'c2' },
    { id: 'c3', format: 'c3' },
    { id: 'p2', format: 'p2' },
    { id: 'p3', format: 'p3' }
  ];

  private dateFormat: { [key: string]: Object }[] = [
    { id: 'M/d/yyyy', format: 'Short Date' },
    { id: 'dddd, MMMM dd, yyyy', format: 'Long Date' },
    { id: 'MMMM, yyyy', format: 'Month/Year' },
    { id: 'MMMM, dd', format: 'Month/Day' }
  ];

  private change(args: ChangeEventArgs): void {
    let columnName: string = args.value.toString();
    if (columnName === 'price') {
      this.dropdownObj2.dataSource = this.priceFormat;
      let priceColumn: Column = this.treegridObj.getColumnByField('price');
      this.dropdownObj2.value = priceColumn.format.toString();
    }
    if (columnName === 'orderDate') {
      this.dropdownObj2.dataSource = this.dateFormat;
      let format: any = this.treegridObj.getColumnByField('orderDate').format;
      this.dropdownObj2.value = format.format;
    }
  }

  private change2(args: ChangeEventArgs): void {
    let formatval: any = args.value;
    let columnName: string = this.dropdownObj.value.toString();
    if (columnName === 'price') {
      this.treegridObj.getColumnByField(columnName).format = formatval;
    }
    if (columnName === 'orderDate') {
      this.treegridObj.getColumnByField(columnName).format = { format : formatval, type: 'date' };
    }
    this.treegridObj.refreshColumns();
  }

  render() {
    return (
      <div className='control-pane'>
        <div className='control-section'>
          <div className = 'col-lg-9'>
            <TreeGridComponent dataSource={formatData} treeColumnIndex={1} childMapping='subtasks' height='350' allowPaging={true} 
              ref={treegrid=> this.treegridObj = treegrid} pageSettings={{ pageCount: 5 }}>
              <ColumnsDirective>
                <ColumnDirective field='orderID' headerText='Order ID' width='110' textAlign='Right'></ColumnDirective>
                <ColumnDirective field='orderName' headerText='Order Name' width='200'></ColumnDirective>
                <ColumnDirective field='orderDate' headerText='Order Date' width='190' type='date' format={this.format} textAlign='Right' />
                <ColumnDirective field='price' headerText='Price' width='120' format='c2' textAlign='Right' type='number' />
              </ColumnsDirective>
            <Inject services={[Page]} />
          </TreeGridComponent>
        </div>
        <div className='col-lg-3 property-section' style={{paddingLeft:'5px'}}>
          <PropertyPane title='Properties'>
              <table id='property' title='Properties' className='property-panel-table' style={{ width: '100%' }}>
                <tbody>
                  <tr style={{ height: '50px' }}>
                    <td>
                      <div style={{ paddingTop: '7px' }}> Column </div>
                    </td>
                    <td style={{ width: '70%', paddingRight: '10px' }}>
                      <div>
                        <DropDownListComponent width="145px" id="columns" change={this.change.bind(this)}
                          dataSource={this.columnNames} fields={{ text: 'name', value: 'id' }} value="price"
                          ref={dropdown => this.dropdownObj = dropdown} />
                      </div>
                    </td>
                  </tr>
                  <tr style={{ height: '50px' }}>
                    <td>
                      <div> Format </div>
                    </td>
                    <td style={{ width: '70%', paddingRight: '10px' }}>
                      <div>
                        <DropDownListComponent width="145px" id="colformat" change={this.change2.bind(this)}
                          dataSource={this.priceFormat} fields={{ text: 'format', value: 'id' }} value="c2"
                          ref={dropdown => this.dropdownObj2 = dropdown} />
                      </div>
                    </td>
                  </tr>
                </tbody>
              </table>
          </PropertyPane>
        </div>
      </div>
      <div id="action-description">
          <p>This sample demonstrates the way of displaying the content of Tree Grid columns
              based on the specified format. In this sample, format of columns can be changed dynamically through property panel.
          </p>
      </div>
      <div id="description">
        <p>Format is the process of customizing the particular column data/values based on specific culture. The Tree Grid uses
              Internalization library to format number and date values.
            The format can be specified by using <code>format</code> property of columns.</p>
            <p>In this demo, select the column and format from the property panel to format the corresponding column values.</p>
            <p>
                More information about Column Formatting can be found in this <a target="_blank" href="https://ej2.syncfusion.com/react/documentation/treegrid/columns/columns">documentation</a> section.
            </p>
            <p>
              Looking for the full React Tree Grid component overview, features, pricing, and documentation? Visit our <a target="_blank" href="https://www.syncfusion.com/react-components/react-tree-grid">React Tree Grid component</a> page.
            </p>
      </div>
    </div>
    )
  }
}

// syncfusionejs2_trial/Samples/Vue/public/source/tree-grid/columnformatting.vue
<template>
    <div class="control-section">
      <div class="col-md-9 control-section">
          <ejs-treegrid ref='treegrid' :dataSource='data' :height='350' childMapping='subtasks' :treeColumnIndex='1' :allowPaging='true' :pageSettings='pageSettings'>
            <e-columns>
                <e-column field='orderID' headerText='Order ID' width='70' textAlign='Right'></e-column>
                <e-column field='orderName' headerText='Order Name' width='150'></e-column>
                <e-column field='orderDate' headerText='Order Date' width='140' :format="format" textAlign='Right'></e-column>
                <e-column field='price' headerText='Price' width='100' format='c2' textAlign='Right'></e-column>
            </e-columns>
        </ejs-treegrid>
      </div>
      <div>
        <div class="col-md-3 property-section columnformatting-section">
            <table id="property" title="Properties" style="width: 100%">
                <br/><br/>
                <tr style="height: 50px">
                    <td>
                        <div>Column</div>
                    </td>
                    <td style="width: 70%; padding-left: 7%; padding-right:10px;">
                        <ejs-dropdownlist width='140px' ref='columns' id='columns' :dataSource='columnNames' value='price' :fields='colfields' :change="onColChange"></ejs-dropdownlist>                      
                    </td>
                </tr>
                <tr style="height: 50px">
                    <td>
                        <div> Format</div>
                    </td>
                    <td style="width: 70%; padding-left: 7%; padding-right:10px;">
                        <ejs-dropdownlist ref='format' width='140px' id='format' :dataSource='priceFormat' value='c2' :fields='ddlfields' :change="onChange"></ejs-dropdownlist>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div id="action-description">
    <p>This sample demonstrates the way of displaying the content of Tree Grid columns based on the specified format. In this sample, format of columns can be changed dynamically through property panel.
    </p>
</div>
<div id="description">
    <p>Format is the process of customizing the particular column data/values based on specific culture. The Tree Grid uses Internalization library to format number and date values. 
            The format can be specified by using <code>
            format</code> property of columns.</p>
            <p>In this demo, select the column and format from the property panel to format the corresponding column values.</p>
            <p>
                More information about Column Formatting can be found in this <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/treegrid/columns/columns#format">documentation section</a>.
            </p>
            <p>
                Looking for the full Vue Tree Grid component overview, features, pricing, and documentation? Visit our <a target="_blank" href="https://www.syncfusion.com/vue-components/vue-tree-grid">Vue Tree Grid component</a> page.
            </p>
</div>
</div>
</template>
<style>
        @media (min-with:990 && max-width:1300){
          .property-panel-section{
            padding-left: 0px;
          }
          .columnformatting-section{
            padding-left: 0px !important;
          }
        }
        
</style>

<script lang="ts">
import { TreeGridComponent, ColumnDirective, ColumnsDirective, Page, Filter, Column } from "@syncfusion/ej2-vue-treegrid";
import { DropDownListComponent, ChangeEventArgs } from "@syncfusion/ej2-vue-dropdowns";
import { sampleData, formatData } from "./data-source";
import { DateFormatOptions } from "@syncfusion/ej2-base";

export default {
  components: {
    'ejs-treegrid': TreeGridComponent,
    'e-column': ColumnDirective,
    'e-columns': ColumnsDirective,
    'ejs-dropdownlist': DropDownListComponent
  },  
  data: () => {
    return {
      data: formatData,
      pageSettings: { pageSize: 10 },
      format: { format: 'M/d/yyyy', type: 'date'},
      columnNames: [
        { id: 'price', name: 'Price' },
        { id: 'orderDate', name: 'Order Date' }
    ],
      priceFormat: [
        { id: 'n2', name: 'n2' },
        { id: 'n3', name: 'n3' },
        { id: 'c2', name: 'c2' },
        { id: 'c3', name: 'c3' },
        { id: 'p2', name: 'p2' },
        { id: 'p3', name: 'p3' }
    ],
      dateFormat: [
        { id: 'M/d/yyyy', name: 'Short Date' },
        { id: 'dddd, MMMM dd, yyyy', name: 'Long Date' },
        { id: 'MMMM, yyyy', name: 'Month/Year' },
        { id: 'MMMM, dd', name: 'Month/Day' }
    ],
    colfields: {text: 'name', value: 'id'},
    ddlfields: {text: 'name', value: 'id'}
    };
  },
  provide: {
      treegrid: [ Page, Filter ]
    },
   methods:{
       onColChange: function(e: ChangeEventArgs): void {
         let columnName = e.value;
            let format;
            if (columnName === 'price') {
                ((this as any).$refs.format).ej2Instances.dataSource = (this as any).priceFormat;
                format = (((this as any).$refs.treegrid).getColumnByField(columnName) as Column).format;
                ((this as any).$refs.format).ej2Instances.value = format;
            }
            if (columnName === 'orderDate') {
               ((this as any).$refs.format).ej2Instances.dataSource = (this as any).dateFormat;
                format = ((((this as any).$refs.treegrid).getColumnByField(columnName) as Column).format as DateFormatOptions).format;
                ((this as any).$refs.format).ej2Instances.value = format;
            }
    },
    onChange: function(e: ChangeEventArgs): void {
            let formatval: string = <string>e.value;
            let columnName = ((this as any).$refs.columns).ej2Instances.value;
            if (columnName === 'price') {
                (((this as any).$refs.treegrid).getColumnByField(columnName) as Column).format = formatval;
            }
            if (columnName === 'orderDate') {
                (((this as any).$refs.treegrid).getColumnByField(columnName) as Column).format = { format: formatval, type: 'date' };
            }
            ((this as any).$refs.treegrid).ej2Instances.refreshColumns();
    }
  }

}
</script>
