// syncfusionejs2_trial/Samples/React/src/treegrid/sortingapi.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.SortingAPI = void 0;
var React = require("react");
var ej2_react_treegrid_1 = require("@syncfusion/ej2-react-treegrid");
var ej2_react_dropdowns_1 = require("@syncfusion/ej2-react-dropdowns");
var ej2_react_buttons_1 = require("@syncfusion/ej2-react-buttons");
var data_1 = require("./data");
var sample_base_1 = require("../common/sample-base");
var property_pane_1 = require("../common/property-pane");
var SAMPLE_CSS = "\n@media (min-with:990 && max-width:1300){\n .property-panel-section{\n   padding-left:0px;\n }\n}";
var SortingAPI = /** @class */ (function (_super) {
    __extends(SortingAPI, _super);
    function SortingAPI() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        _this.columnsName = [
            { id: 'taskID', name: 'Task ID' },
            { id: 'taskName', name: 'Task Name' },
            { id: 'duration', name: 'Duration' },
            { id: 'progress', name: 'Progress' }
        ];
        _this.direction = [
            { id: 'Ascending', name: 'Ascending' },
            { id: 'Descending', name: 'Descending' }
        ];
        return _this;
    }
    SortingAPI.prototype.btnClick = function () {
        var columnName = this.columnName.value;
        var sortType = this.sortDirection.value;
        this.treegridObj.sortByColumn(columnName, sortType, false);
    };
    SortingAPI.prototype.btnClick2 = function () {
        this.treegridObj.clearSorting();
    };
    SortingAPI.prototype.render = function () {
        var _this = this;
        return (React.createElement("div", { className: 'control-pane' },
            React.createElement("div", { className: 'control-section' },
                React.createElement("div", { className: 'col-md-9' },
                    React.createElement(ej2_react_treegrid_1.TreeGridComponent, { dataSource: data_1.sampleData, treeColumnIndex: 1, childMapping: 'subtasks', height: '410', ref: function (treegrid) { return _this.treegridObj = treegrid; }, allowSorting: true },
                        React.createElement(ej2_react_treegrid_1.ColumnsDirective, null,
                            React.createElement(ej2_react_treegrid_1.ColumnDirective, { field: 'taskID', headerText: 'Task ID', width: '80', textAlign: 'Right' }),
                            React.createElement(ej2_react_treegrid_1.ColumnDirective, { field: 'taskName', headerText: 'Task Name', width: '160' }),
                            React.createElement(ej2_react_treegrid_1.ColumnDirective, { field: 'duration', headerText: 'Duration', width: '90', textAlign: 'Right' }),
                            React.createElement(ej2_react_treegrid_1.ColumnDirective, { field: 'progress', headerText: 'Progress', width: '90', textAlign: 'Right' })),
                        React.createElement(ej2_react_treegrid_1.Inject, { services: [ej2_react_treegrid_1.Sort] }))),
                React.createElement("div", { className: 'col-md-3 property-section' },
                    React.createElement("style", null, SAMPLE_CSS),
                    React.createElement(property_pane_1.PropertyPane, { title: 'Properties' },
                        React.createElement("table", { id: 'property', title: 'Properties', className: 'property-panel-table', style: { width: '100%' } },
                            React.createElement("tbody", null,
                                React.createElement("tr", null,
                                    React.createElement("td", null,
                                        React.createElement("div", null, " Column ")),
                                    React.createElement("td", { style: { width: '80%', paddingRight: '10px' } },
                                        React.createElement("div", { style: { paddingLeft: '8px' } },
                                            React.createElement(ej2_react_dropdowns_1.DropDownListComponent, { width: "146px", id: "columns", ref: function (columnname) { return _this.columnName = columnname; }, dataSource: this.columnsName, fields: { text: 'name', value: 'id' }, value: "taskID" })))),
                                React.createElement("tr", null,
                                    React.createElement("td", null,
                                        React.createElement("div", null, " Direction ")),
                                    React.createElement("td", { style: { width: '80%', paddingRight: '10px' } },
                                        React.createElement("div", { style: { paddingLeft: '8px' } },
                                            React.createElement(ej2_react_dropdowns_1.DropDownListComponent, { width: "146px", id: "direction", ref: function (sortdirection) { return _this.sortDirection = sortdirection; }, dataSource: this.direction, fields: { text: 'name', value: 'id' }, value: "Ascending" })))),
                                React.createElement("tr", null,
                                    React.createElement("td", { colSpan: 2, style: { paddingTop: '10%', paddingLeft: '10px' } },
                                        React.createElement(ej2_react_buttons_1.ButtonComponent, { style: { marginRight: '10px' }, onClick: this.btnClick.bind(this) }, "Sort"),
                                        React.createElement(ej2_react_buttons_1.ButtonComponent, { onClick: this.btnClick2.bind(this) }, "Clear")))))))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null, "Sorting feature enables us to order the data in a particular direction. It can be enabled by setting the allowSorting as true.")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null,
                    "Sorting feature enables us to order the data in a particular direction. It can be enabled by setting the ",
                    React.createElement("code", null, "allowSorting"),
                    " as true."),
                React.createElement("p", { className: "e-treegrid", style: { border: 'none' } },
                    "To sort a Tree Grid column simply click the column header. The icons ",
                    React.createElement("span", { className: "e-icons e-icon-ascending" }),
                    "(ascending) and ",
                    React.createElement("span", { className: "e-icons e-icon-descending" }),
                    "(descending) specifies the sort direction of a column."),
                React.createElement("p", null,
                    "By default, multi-sorting is enabled in Tree Grid, to sort multiple column hold ",
                    React.createElement("strong", null, "CTRL"),
                    " key and click the column header. To clear sort for a column, hold ",
                    React.createElement("strong", null, "SHIFT"),
                    " key and click the column header."),
                React.createElement("p", null, "While using Tree Grid in a touch device, you have an option for multi sorting in single tap on the Tree Grid header. By tapping on the Tree Grid header, it will show the toggle button in small popup with sort icon. Now tap the button to enable the multi-sorting in single tap."),
                React.createElement("p", null, "In this demo, select the column and direction from the properties panel then click the Sort button. Use the Clear button to remove sort for the selected column."),
                React.createElement("p", null, "Injecting Module:"),
                React.createElement("p", null,
                    "Tree Grid features are segregated into individual feature-wise modules. To use sorting feature, we need to inject",
                    React.createElement("code", null, "Sort"),
                    " module into the ",
                    React.createElement("code", null, "services"),
                    "."),
                React.createElement("p", null,
                    "More information on the sorting feature configuration can be found in this ",
                    React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/treegrid/sorting" }, "documentation section"),
                    "."),
                React.createElement("p", null,
                    "Looking for the full React Tree Grid component overview, features, pricing, and documentation? Visit our ",
                    React.createElement("a", { target: "_blank", href: "https://www.syncfusion.com/react-components/react-tree-grid" }, "React Tree Grid component"),
                    " page."))));
    };
    return SortingAPI;
}(sample_base_1.SampleBase));
exports.SortingAPI = SortingAPI;

// syncfusionejs2_trial/Samples/Vue/public/source/tree-grid/sorting-api.vue
<template>
    <div class="control-section">
      <div class="col-md-9 control-section">
          <ejs-treegrid ref='treegrid' :dataSource='data' childMapping='subtasks' :treeColumnIndex='1' :allowSorting='true' height='380'>
            <e-columns>
                <e-column field='taskID' headerText='Task ID' width='90' textAlign='Right'></e-column>
                <e-column field='taskName' headerText='Task Name' width='190'></e-column>
                <e-column field='startDate' headerText='Start Date' width='100' format="yMd" textAlign='Right'></e-column>
                <e-column field='duration' headerText='Duration' width='90' textAlign='Right'></e-column>
            </e-columns>
        </ejs-treegrid>
      </div>
      <div>
        <div class="col-md-3 property-section sorting-api">
             <table id="property" title="Properties" style="width: 100%">
        <tr>
            <td>
                <div>Column</div>
            </td>
            <td class='table-data' style="width: 70%;padding-right: 10px;padding-left:10px">
                <div id='columnddl'>
                     <ejs-dropdownlist ref='columns' width='147px' id='columns' :dataSource='columnsName' value='taskID' :fields='ddlfields'></ejs-dropdownlist>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div>Direction</div>
            </td>
            <td class='table-data' style="width: 70%;padding-right: 10px;padding-left:10px">
                <div>
                    <ejs-dropdownlist ref='direction' width='147px' id='direction' :dataSource='direction' value='Ascending' :fields='ddlfields'></ejs-dropdownlist>
                </div>
            </td>
        </tr>
        <tr>
        <td colSpan="2" style="padding-top: 10%; padding-left: 10px;">
                    <ejs-button class="btn btn-default" ref='sort' v-on:click="sort" style="margin-right:15px">Sort</ejs-button>
                    <ejs-button ref='clear' v-on:click="clear">Clear</ejs-button>
            </td>
        </tr>
    </table>
            
        </div>
    </div>

<div id="action-description">
    <p>
        Sorting feature enables us to order the data in a particular direction. It can be enabled 
        by setting the allowSorting as true.
    </p>
</div>

<div id="description">
    <p>
        Sorting feature enables us to order the data in a particular direction. It can be enabled by setting the <code>allowSorting</code> as true.
    </p>
    <p class="e-treegrid" style="border:none">To sort a Tree Grid column simply click the column header. The icons <span class="e-icons e-icon-ascending"></span>(ascending)
        and <span class="e-icons e-icon-descending"></span>(descending) specifies the sort direction of a column.</p>
    <p>By default, multi-sorting is enabled in Tree Grid, to sort multiple column hold <strong>CTRL</strong> key and click the column
        header. To clear sort for a column, hold <strong>SHIFT</strong> key and click the column header.</p>
    <p>
        While using Tree Grid in a touch device, you have an option for multi sorting in single tap on the Tree Grid header. By tapping on
        the Tree Grid header, it will show the toggle button in small popup with sort icon. Now tap the button to enable the multi-sorting
        in single tap.
    </p>
    <p>In this demo, select the column and direction from the properties panel then click the Sort button. Use the Clear button
        to remove sort for the selected column.
    </p>

    <p style="font-weight: 500">Injecting Module:</p>
    <p>
        Tree Grid features are segregated into individual feature-wise modules. To use sorting feature, we need to inject <code>Sort</code>
        module into the <code>provide</code> section.
    </p>
    <p>
        More information on the sorting feature configuration can be found in this <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/treegrid/sorting">documentation section</a>.
    </p>
    <p>
        Looking for the full Vue Tree Grid component overview, features, pricing, and documentation? Visit our <a target="_blank" href="https://www.syncfusion.com/vue-components/vue-tree-grid">Vue Tree Grid component</a> page.
    </p>
</div>

  </div>
  </template>
  <script lang="ts">
import { TreeGridComponent, ColumnsDirective, ColumnDirective, Sort, Column } from "@syncfusion/ej2-vue-treegrid";
import { SortDirection } from "@syncfusion/ej2-vue-grids";
import { ChangeEventArgs, DropDownListComponent } from "@syncfusion/ej2-vue-dropdowns";
import { sampleData } from "./data-source";
import { ButtonComponent, ClickEventArgs } from '@syncfusion/ej2-vue-buttons';

export default {
  components: {
    'ejs-treegrid': TreeGridComponent,
    'e-columns': ColumnsDirective,
    'e-column': ColumnDirective,
    'ejs-button': ButtonComponent,
    'ejs-dropdownlist': DropDownListComponent,
  },
  data: () => {
    return {
      data: sampleData,
      columnsName: [
        { id: 'taskID', name: 'Task ID' },
        { id: 'taskName', name: 'Task Name' },
        { id: 'startDate', name: 'Start Date' },
        { id: 'duration', name: 'Duration' }
    ],
      direction: [
        { id: 'Ascending', name: 'Ascending' },
        { id: 'Descending', name: 'Descending' }
    ],
    ddlfields: {text: 'name', value: 'id'}
    };
  },
  provide: {
      treegrid: [ Sort ]
    },
   methods:{
       sort: function(e: ClickEventArgs): void {
        let columnName = ((this as any).$refs.columns).ej2Instances.value;
        let sortType = ((this as any).$refs.direction).ej2Instances.value;
        ((this as any).$refs.treegrid).sortByColumn(columnName, <SortDirection>sortType, false);
    },
       clear: function(e: ChangeEventArgs): void {       
        ((this as any).$refs.treegrid).clearSorting();
    }
  }
};
</script>

<style>
#sort {
    padding-top: 0px !important;
}

@media (min-width: 990px) and (max-width: 1300px) {
    .property-panel-section,
    .sorting-api {
        padding-left: 0px;
      }
     .table-data {
        padding-left:0% !important;
     }

}
</style>
