// syncfusionejs2_trial/Samples/React/src/dashboard-layout/dynamic.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.DynamicWidget = void 0;
var React = require("react");
var sample_base_1 = require("../common/sample-base");
var ej2_react_layouts_1 = require("@syncfusion/ej2-react-layouts");
var ej2_react_buttons_1 = require("@syncfusion/ej2-react-buttons");
var ej2_react_popups_1 = require("@syncfusion/ej2-react-popups");
var ej2_react_charts_1 = require("@syncfusion/ej2-react-charts");
require("./dynamic.css");
var DynamicWidget = /** @class */ (function (_super) {
    __extends(DynamicWidget, _super);
    function DynamicWidget(props) {
        var _this = _super.call(this, props) || this;
        _this.count = 4;
        _this.cellSpacing = [10, 10];
        _this.state = {
            hideDialog: false
        };
        return _this;
    }
    DynamicWidget.prototype.btnClick = function () {
        if (this.btnobj.element.classList.contains('e-active')) {
            this.dashboardObj.allowDragging = true;
            this.dashboardObj.allowResizing = true;
            this.btnobj.content = "Save";
            this.btnobj.iconCss = 'save';
            document.getElementById('dialogBtn').style.display = 'block';
        }
        else {
            this.dashboardObj.allowDragging = false;
            this.dashboardObj.allowResizing = false;
            this.btnobj.content = "Edit";
            this.btnobj.iconCss = 'edit';
            document.getElementById('dialogBtn').style.display = 'none';
        }
    };
    DynamicWidget.prototype.onPanelResize = function (args) {
        if (args.element && args.element.querySelector('.e-panel-container .e-panel-content div div')) {
            var chartObj = (args.element.querySelector('.e-panel-container .e-panel-content div div')).ej2_instances[0];
            chartObj.height = '95%';
            chartObj.width = '100%';
            chartObj.refresh();
        }
    };
    DynamicWidget.prototype.content = function (data) {
        return (React.createElement("div", { id: "dialogcontent" },
            React.createElement("div", null,
                React.createElement("div", { id: "linetemplate" },
                    React.createElement("p", { className: "dialog-text" }, "Linechart (1x1) ")),
                React.createElement("div", { id: "pietemplate" },
                    React.createElement("p", { className: "dialog-text" }, "Piechart (1x1) ")),
                React.createElement("div", { id: "splinetemplate" },
                    React.createElement("p", { className: "dialog-text" }, "Splinechart (2x1) ")))));
    };
    DynamicWidget.prototype.onAdd = function () {
        var proxy = this;
        var panel = [{
                "id": this.count.toString() + "_layout", "sizeX": 2, "sizeY": 2, "row": 0, "col": 0,
                header: "<div>Panel" + this.count.toString() + "</div>", content: "<div></div>"
            }];
        this.count = this.count + 1;
        proxy.dashboardObj.addPanel(panel[0]);
    };
    DynamicWidget.prototype.splineTemplate = function () {
        var splineData1 = [
            { x: new Date(2002, 0, 1), y: 2.2 }, { x: new Date(2003, 0, 1), y: 3.4 },
            { x: new Date(2004, 0, 1), y: 2.8 }, { x: new Date(2005, 0, 1), y: 1.6 },
            { x: new Date(2006, 0, 1), y: 2.3 }, { x: new Date(2007, 0, 1), y: 2.5 },
            { x: new Date(2008, 0, 1), y: 2.9 }, { x: new Date(2009, 0, 1), y: 3.8 },
            { x: new Date(2010, 0, 1), y: 1.4 }, { x: new Date(2011, 0, 1), y: 3.1 }
        ];
        var splineData2 = [
            { x: new Date(2002, 0, 1), y: 2 }, { x: new Date(2003, 0, 1), y: 1.7 },
            { x: new Date(2004, 0, 1), y: 1.8 }, { x: new Date(2005, 0, 1), y: 2.1 },
            { x: new Date(2006, 0, 1), y: 2.3 }, { x: new Date(2007, 0, 1), y: 1.7 },
            { x: new Date(2008, 0, 1), y: 1.5 }, { x: new Date(2009, 0, 1), y: 2.8 },
            { x: new Date(2010, 0, 1), y: 1.5 }, { x: new Date(2011, 0, 1), y: 2.3 }
        ];
        return (React.createElement("div", { className: "template" },
            React.createElement(ej2_react_charts_1.ChartComponent, { style: { "height": "100%", "width": "100%", textAlign: "center" }, primaryXAxis: {
                    valueType: 'DateTime',
                    labelFormat: 'MMM',
                    majorGridLines: { width: 0 },
                    intervalType: 'Months',
                    edgeLabelPlacement: 'Shift'
                }, primaryYAxis: {
                    labelFormat: '{value}%',
                    lineStyle: { width: 0 },
                    maximum: 4, interval: 1,
                    majorTickLines: { width: 0 },
                    minorTickLines: { width: 0 }
                }, load: this.load.bind(this), chartArea: { border: { width: 0 } } },
                React.createElement(ej2_react_charts_1.Inject, { services: [ej2_react_charts_1.SplineAreaSeries, ej2_react_charts_1.DateTime, ej2_react_charts_1.Legend] }),
                React.createElement(ej2_react_charts_1.SeriesCollectionDirective, null,
                    React.createElement(ej2_react_charts_1.SeriesDirective, { dataSource: splineData1, xName: 'x', yName: 'y', name: 'Jan', opacity: 0.5, type: 'SplineArea', width: 2, fill: 'rgb(239, 183, 202)' }),
                    React.createElement(ej2_react_charts_1.SeriesDirective, { dataSource: splineData2, xName: 'x', yName: 'y', name: 'Feb', opacity: 0.5, type: 'SplineArea', width: 2, fill: 'rgb(0, 189, 174)' })))));
    };
    DynamicWidget.prototype.lineTemplate = function () {
        var data1 = [{ x: 'Jan', y: 46 }, { x: 'Feb', y: 27 }, { x: 'Mar', y: 26 }];
        var data2 = [{ x: 'Jan', y: 37 }, { x: 'Feb', y: 23 }, { x: 'Mar', y: 18 }];
        var data3 = [{ x: 'Jan', y: 38 }, { x: 'Feb', y: 17 }, { x: 'Mar', y: 26 }];
        return (React.createElement("div", { className: "template" },
            React.createElement(ej2_react_charts_1.ChartComponent, { style: { "height": "100%", "width": "100%" }, load: this.load.bind(this), primaryXAxis: { valueType: 'Category', interval: 1, majorGridLines: { width: 0 } }, primaryYAxis: {
                    majorGridLines: { width: 0 },
                    majorTickLines: { width: 0 }, lineStyle: { width: 0 }, labelStyle: { color: 'transparent' }
                }, chartArea: { border: { width: 0 } }, tooltip: { enable: true } },
                React.createElement(ej2_react_charts_1.Inject, { services: [ej2_react_charts_1.ColumnSeries, ej2_react_charts_1.Legend, ej2_react_charts_1.Tooltip, ej2_react_charts_1.Category, ej2_react_charts_1.DataLabel] }),
                React.createElement(ej2_react_charts_1.SeriesCollectionDirective, null,
                    React.createElement(ej2_react_charts_1.SeriesDirective, { dataSource: data1, xName: 'x', yName: 'y', name: 'Jan', type: 'Column', marker: { dataLabel: { visible: false } }, fill: '#00bdae' }),
                    React.createElement(ej2_react_charts_1.SeriesDirective, { dataSource: data2, xName: 'x', yName: 'y', name: 'Feb', type: 'Column', marker: { dataLabel: { visible: false } }, fill: '#e56691' }),
                    React.createElement(ej2_react_charts_1.SeriesDirective, { dataSource: data3, xName: 'x', yName: 'y', name: 'Mar', type: 'Column', marker: { dataLabel: { visible: false } }, fill: '#357cd2' })))));
    };
    DynamicWidget.prototype.pieTemplate = function () {
        var pieData = [
            { "x": "Jan", y: 12.5, text: "January" },
            { "x": "Feb", y: 25, text: "February" },
            { "x": "Mar", y: 50, text: "March" },
        ];
        var piePalette = ["#00bdaed1", "#357cd2bf", "#e56691e8"];
        return (React.createElement("div", { className: "template" },
            React.createElement(ej2_react_charts_1.AccumulationChartComponent, { style: { "height": "100%", "width": "100%" }, legendSettings: { visible: false }, enableSmartLabels: true, enableAnimation: true, center: { x: '50%', y: '50%' }, load: this.Pieload.bind(this), tooltip: { enable: true, header: '<b>${point.x}</b>', format: 'Composition : <b>${point.y}%</b>' } },
                React.createElement(ej2_react_charts_1.Inject, { services: [ej2_react_charts_1.AccumulationLegend, ej2_react_charts_1.PieSeries, ej2_react_charts_1.AccumulationTooltip, ej2_react_charts_1.AccumulationDataLabel] }),
                React.createElement(ej2_react_charts_1.AccumulationSeriesCollectionDirective, null,
                    React.createElement(ej2_react_charts_1.AccumulationSeriesDirective, { dataSource: pieData, name: 'Earnings', xName: 'x', yName: 'y', dataLabel: { visible: true, position: 'Inside', name: 'value', font: { fontWeight: '600' } }, radius: '100%', innerRadius: "40%", palettes: ['#00bdae', '#357cd2', '#e56691'] })))));
    };
    DynamicWidget.prototype.render = function () {
        var _this = this;
        return (React.createElement("div", null,
            React.createElement("div", { id: 'edit_target', className: "control-section" },
                React.createElement("div", null,
                    React.createElement("div", { style: { "width": "100%", "marginBottom": "10px", "marginTop": "10px", "height": "30px" } },
                        React.createElement(ej2_react_buttons_1.ButtonComponent, { id: "togglebtn", cssClass: 'e-outline e-flat e-primary', ref: function (scope) { _this.btnobj = scope; }, iconCss: 'edit', isToggle: true, onClick: this.btnClick.bind(this), style: { "float": "right", "width": "75px" } }, "Edit")),
                    React.createElement("div", { style: { "padding": "5px", "marginBottom": "5px", "textAlign": "end" } },
                        React.createElement("div", { id: "dialogBtn", className: "add-widget-button e-control e-btn e-lib", onClick: this.dlgClick.bind(this) }, "Add New Widget"))),
                React.createElement(ej2_react_layouts_1.DashboardLayoutComponent, { id: "edit_dashboard", columns: 2, cellSpacing: this.cellSpacing, ref: function (scope) { _this.dashboardObj = scope; }, resizeStop: this.onPanelResize.bind(this), allowResizing: false, allowDragging: false },
                    React.createElement(ej2_react_layouts_1.PanelsDirective, null,
                        React.createElement(ej2_react_layouts_1.PanelDirective, { sizeX: 1, sizeY: 1, row: 0, col: 0, content: this.lineTemplate.bind(this), header: "<div>Line Chart</div>" }),
                        React.createElement(ej2_react_layouts_1.PanelDirective, { sizeX: 1, sizeY: 1, row: 0, col: 1, content: this.pieTemplate.bind(this), header: "<div>Pie Chart</div>" }),
                        React.createElement(ej2_react_layouts_1.PanelDirective, { sizeX: 2, sizeY: 1, row: 1, col: 0, content: this.splineTemplate.bind(this), header: "<div>Spline Chart</div>" })))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null,
                    "The following sample demonstrates a editable dashboard layout. Initially the DashboardLayout component doesn't allow to ",
                    React.createElement("a", { href: "https://ej2.syncfusion.com/react/documentation/api/dashboard-layout#allowdragging", target: "_blank" }, "drag"),
                    ",",
                    React.createElement("a", { href: "https://ej2.syncfusion.com/react/documentation/api/dashboard-layout#allowresizing", target: "_blank" }, "resize"),
                    " or reorder the panels. After clicking the edit button, the layout becomes editable which allows to drag and reorder the panels as per the requirement and also you can add new panels to the layout with predefined templates by clicking the add new button and reorder them by dragging and placing in the required position. Drag and resizing of the panles are not applicable in mobile resolution.")),
            React.createElement("div", { id: "description" }, "The following sample demonstrates about using the dashboard layout as an editable layout."),
            React.createElement(ej2_react_popups_1.DialogComponent, { id: "listdialog", width: "500px", height: "260px", visible: false, header: "Add a widget", showCloseIcon: true, animationSettings: { effect: 'Zoom' }, isModal: true, target: '#edit_target', ref: function (scope) { _this.dialogObj = scope; }, content: this.content })));
    };
    DynamicWidget.prototype.dlgClick = function () {
        var _this = this;
        this.dialogObj.visible = true;
        document.getElementById('linetemplate').onclick = function () {
            var countValue = _this.count.toString();
            var panel = [{
                    'id': '_layout' + countValue, 'sizeX': 1, 'sizeY': 1, 'row': 0, 'col': 0,
                    header: '<div>Line Chart</div>', content: _this.lineTemplate.bind(_this)
                }];
            _this.count = _this.count + 1;
            _this.dashboardObj.addPanel(panel[0]);
            _this.dialogObj.visible = false;
            setTimeout(function () {
                document.getElementById("_layout" + countValue).querySelector(".e-control.e-chart").ej2_instances[0].refresh();
            }, 20);
        };
        document.getElementById('pietemplate').onclick = function () {
            var countValue = _this.count.toString();
            var panel = [{
                    'id': '_layout' + countValue, 'sizeX': 1, 'sizeY': 1, 'row': 0, 'col': 0,
                    header: '<div>Pie Chart</div>', content: _this.pieTemplate.bind(_this)
                }];
            _this.count = _this.count + 1;
            _this.dashboardObj.addPanel(panel[0]);
            _this.dialogObj.visible = false;
            setTimeout(function () {
                document.getElementById("_layout" + countValue).querySelector(".e-control.e-accumulationchart").ej2_instances[0].refresh();
            }, 20);
        };
        document.getElementById('splinetemplate').onclick = function () {
            var countValue = _this.count.toString();
            var panel = [{
                    'id': '_layout' + countValue, 'sizeX': 2, 'sizeY': 1, 'row': 0, 'col': 0,
                    header: '<div>Spline Chart</div>', content: _this.splineTemplate.bind(_this)
                }];
            _this.count = _this.count + 1;
            _this.dashboardObj.addPanel(panel[0]);
            _this.dialogObj.visible = false;
            setTimeout(function () {
                document.getElementById("_layout" + countValue).querySelector(".e-control.e-chart").ej2_instances[0].refresh();
            }, 20);
        };
    };
    DynamicWidget.prototype.load = function (args) {
        var selectedTheme = location.hash.split('/')[1];
        selectedTheme = selectedTheme ? selectedTheme : 'Material';
        args.chart.theme = (selectedTheme.charAt(0).toUpperCase() + selectedTheme.slice(1)).replace(/-dark/i, "Dark");
    };
    ;
    DynamicWidget.prototype.Pieload = function (args) {
        var selectedTheme = location.hash.split('/')[1];
        selectedTheme = selectedTheme ? selectedTheme : 'Material';
        args.accumulation.theme = (selectedTheme.charAt(0).toUpperCase() + selectedTheme.slice(1)).replace(/-dark/i, "Dark");
    };
    return DynamicWidget;
}(sample_base_1.SampleBase));
exports.DynamicWidget = DynamicWidget;

// syncfusionejs2_trial/Samples/Vue/source/dashboard-layout/dynamic.vue
<template>
<div>
    <div class="control-section dashboard-dynamic">
      <div>
           <div style="width:100%;height: 30px;margin-bottom:5px">
            <ejs-button style="float:right;width:75px;" id="toggleBtn" ref="toggleBtn" :iconCss='iconCss' cssClass="e-outline e-flat e-primary" isToggle=true v-on:click='toggleClick'>Edit</ejs-button>
        </div>
        <div style="padding:5px;text-align: end;">
            <div class="add-widget-button e-control e-btn e-lib" id="dialogBtn" v-on:click="dialogButtonClick($event)">
                Add New Widget
            </div>
        </div>
    </div>
    <ejs-dashboardlayout ref="DashbordInstance" :columns="2" id='edit_dashboard' :allowResizing="false" :allowDragging="false" :cellSpacing="spacing" :resizeStop="onPanelResize">
         <e-panels>
                <e-panel :row="0" :col="0" :sizeX="1" :sizeY="1" header="<div>Line Chart</div>" :content="line"></e-panel>
                <e-panel :row="0" :col="1" :sizeX="1" :sizeY="1" header="<div>Pie Chart</div>" :content="pie"></e-panel>
                <e-panel :row="1" :col="0" :sizeX="2" :sizeY="1" header="<div>Spline Chart</div>" :content="spline"></e-panel>
            </e-panels>
    </ejs-dashboardlayout>   
 <ejs-dialog :header='header' ref="dialogObj" :content='contenttemplateVue'  :showCloseIcon='showCloseIcon' :target='target' :width='width' :visible='false' :isModal='true'></ejs-dialog>
</div>
<div id="action-description">
    <p>
        The following sample demonstrates a editable dashboard layout. Initially the DashboardLayout component doesn't
        allow to <a href="https://ej2.syncfusion.com/vue/documentation/api/dashboard-layout#allowdragging" target="_blank">drag</a>, 
        <a href="https://ej2.syncfusion.com/vue/documentation/api/dashboard-layout#allowresizing" target="_blank">resize</a> or reorder the panels. After clicking the edit button, 
        the layout becomes editable which allows to drag and reorder the
        panels as per the requirement and also you can add new panels to the layout with predefined templates by
        clicking the add new button and reorder them by dragging and placing in the required position. Drag and resizing
        of the panles are not applicable in mobile resolution.
    </p>
</div>

<div id="description">
    <p>
        The following sample demonstrates about using the dashboard layout as an editable layout.
    </p>
</div>
</div>
</template>

<script>
import { createApp } from "vue";
import { DashboardLayoutComponent, PanelsDirective, PanelDirective } from "@syncfusion/ej2-vue-layouts";
import lineTemplate from "./linetemplate.vue";
import pieTemplate from "./pietemplate.vue";
import splineTemplate from "./splinetemplate.vue";
import { ButtonComponent } from "@syncfusion/ej2-vue-buttons";
import { DialogComponent } from '@syncfusion/ej2-vue-popups';

export default {
    components: {
      'ejs-dashboardlayout': DashboardLayoutComponent,
      'e-panel': PanelDirective,
      'e-panels': PanelsDirective,
      'ejs-button': ButtonComponent,
      'ejs-dialog': DialogComponent
    },
    data: function() {
        return {
          spacing: [10,10],
          iconCss: 'edit',
          header:'Add a Content',
          target:'.control-section',
          width:'43%',
          showCloseIcon: true,
          contenttemplateVue:'<div id="dialogcontent"><div><div id="linetemplate"><p class="dialog-text">Linechart (1x1) </p></div><div id="pietemplate"><p class="dialog-text">Piechart (1x1) </p></div><div id="splinetemplate"><p class="dialog-text">Splinechart (2x1) </p></div></div></div></div>',
          spline: function () {
                return { template : createApp({}).component('splineTemplate', splineTemplate) }
            },
          pie: function () {
                return { template : createApp({}).component('pieTemplate', pieTemplate) }
            },
          line: function () {
                return { template : createApp({}).component('lineTemplate', lineTemplate) }
            },
        };
    },
    methods: {
         toggleClick: function() {
              if (this.$refs.toggleBtn.$el.textContent == 'Edit') { 
                    this.$refs.DashbordInstance.$el.allowResizing = true;
                    this.$refs.DashbordInstance.$el.allowDragging = true;
                    this.$refs.toggleBtn.$el.textContent = 'Save';
                    this.iconCss = "save";
                    document.getElementById('dialogBtn').style.display = 'block';
            } else {
                this.$refs.DashbordInstance.$el.allowResizing = false;
                this.$refs.DashbordInstance.$el.allowDragging = false;
                this.$refs.toggleBtn.$el.textContent = 'Edit';
                this.iconCss = "edit";
                document.getElementById('dialogBtn').style.display = 'none';
            }
        },
        onPanelResize: function(args) {
            var dashboardObject = this.$refs.DashbordInstance;
        if (dashboardObject && args.element && args.element.querySelector('.e-panel-container .e-panel-content div')) {
            var chartObj = (args.element.querySelector('.e-panel-container .e-panel-content div.e-control')).ej2_instances[0];
            chartObj.height = '95%';
            chartObj.width = '100%';
            chartObj.refresh();
        }
        },
        dialogButtonClick: function() {
              this.$refs.dialogObj.show();
              var proxy = this;
              this.$refs.dialogObj.$el.querySelector('#linetemplate').onclick = function () {
                   var panel = {
                       sizeX: 1,
                       sizeY: 1,
                       header: '<div>Line Chart</div>',
                       row: 0,
                       col:0,
                       content: proxy.line
                   }
                   proxy.$refs.DashbordInstance.addPanel(panel);
                   proxy.$refs.dialogObj.hide();
               }
               this.$refs.dialogObj.$el.querySelector('#pietemplate').onclick = function () {
                   var panel = {
                       sizeX: 1,
                       sizeY: 1,
                       header: '<div>Pie Chart</div>',
                       row: 0,
                       col:0,
                       content: proxy.pie
                   }
                   proxy.$refs.DashbordInstance.addPanel(panel);
                   proxy.$refs.dialogObj.hide();
               }
               this.$refs.dialogObj.$el.querySelector('#splinetemplate').onclick = function () {
                   var panel = {
                       sizeX: 2,
                       sizeY: 1,
                       header: '<div>Spline Chart</div>',
                       row: 0,
                       col:0,
                       content: proxy.spline
                   }
                   proxy.$refs.DashbordInstance.addPanel(panel);
                   proxy.$refs.dialogObj.hide();
               }
        } 
    },
}
</script>

<style>

.dashboard-dynamic #dialogBtn {
    display: none;
}

.dashboard-dynamic .dialog-text {
    height: 35px;
    border: 1px solid #80808029;
    vertical-align: middle;
    line-height: 35px;
    border-radius: 4px;
    padding-left: 12px;
    margin-bottom: 5%;
    cursor: pointer;
}

@media (max-width: 650px) {
    .dashboard-dynamic #togglebtn{
        width: 90px !important;
    }
}

.dashboard-dynamic .add-widget-button {
    padding: 10px;
    text-align: center;
    margin-bottom: 10px;
    cursor: pointer;
    font-size: 15px;
}

body.fluent.e-bigger button#toggleBtn,  body.fluent-dark.e-bigger button#toggleBtn{
     width : 100px !important;
     margin: -8px;
    }
    
.dashboard-dynamic #edit_dashboard.e-dashboardlayout.e-control .e-panel:hover span {
    display: block;
}

.dashboard-dynamic #edit_dashboard.e-dashboardlayout.e-control .e-panel .e-panel-container .e-panel-header {
    border-bottom: 2px solid #e6e9ed !important;
    height: 35px;
    padding: 0 15px 0 15px;
    line-height: 35px;
}


.dashboard-dynamic #edit_dashboard .e-panel-content {
    height: calc(100% - 37px) !important;
    overflow: hidden;
    width:100%;
}

.dashboard-dynamic #edit_dashboard.e-dashboardlayout.e-control .e-panel,
.dashboard-dynamic #edit_dashboard.e-dashboardlayout.e-control .e-panel:hover,
.dashboard-dynamic #edit_dashboard.e-dashboardlayout.e-control .e-panel:active {
    border: 1px solid #bbb;
}

.dashboard-dynamic .e-dialog .e-dlg-header-content {
    border-bottom: none;
    padding: 18px 18px 18px 20px;
}

.dashboard-dynamic .edit::before {
        content: '\e501';
        font-family: 'e-sb-icons';
        /* color: #e3165b; */
        margin-left: -7px;
        vertical-align: middle;
    }

.dashboard-dynamic .save::before {
    content: '\e500';
    font-family: 'e-sb-icons';
    /* color: #e3165b; */
    margin-left: -7px;
    vertical-align: middle;
}


/* custom code start*/
@font-face {
    font-family: 'e-sb-icons';
    src: url(data:application/x-font-ttf;charset=utf-8;base64,AAEAAAAKAIAAAwAgT1MvMjttR/MAAAEoAAAAVmNtYXDlEOVaAAABjAAAADhnbHlmAM1kuQAAAcwAAAD8aGVhZBRipc8AAADQAAAANmhoZWEIUQQEAAAArAAAACRobXR4DAAAAAAAAYAAAAAMbG9jYQA6AH4AAAHEAAAACG1heHABEQA4AAABCAAAACBuYW1lWD3y/QAAAsgAAAIlcG9zdNvk7cwAAATwAAAANQABAAAEAAAAAFwEAAAAAAAD9AABAAAAAAAAAAAAAAAAAAAAAwABAAAAAQAApr5cCV8PPPUACwQAAAAAANioMG8AAAAA2KgwbwAAAAAD9AP0AAAACAACAAAAAAAAAAEAAAADACwABAAAAAAAAgAAAAoACgAAAP8AAAAAAAAAAQQAAZAABQAAAokCzAAAAI8CiQLMAAAB6wAyAQgAAAIABQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUGZFZABA5QDlAQQAAAAAXAQAAAAAAAABAAAAAAAABAAAAAQAAAAEAAAAAAAAAgAAAAMAAAAUAAMAAQAAABQABAAkAAAABAAEAAEAAOUB//8AAOUA//8AAAABAAQAAAABAAIAAAAAADoAfgAEAAAAAAP0A/MAAwALABkAIwAAAREhEQEVMzUzFSE1IxEhETMVMxEjESERIxEjERUhESM1IzUhAx79xAEeR0j+m0gB9I9HR/02SEcD6EdI/KcBcf7iAR4CPI+P19f+4gEeSPzuAWb+mgNa/KZHA1lIRwAAAAMAAAAAA/QD9AADAAgAKwAACQEnCQEDJQEnNwcXPwc1Lw8PBgLH/ko2Abb9uT4BGQJC2m0/2z8HBgUFAwMCAQIEBQcICQoLDA0NDw8PEA0NDQwLCwsCkf5KNgG2/l7+5z4CQ9puP9s/CgsLCwwNDQ0QDw8PDQ0MCwoJCAcFBAIBAQEDAwUFBgAAABIA3gABAAAAAAAAAAEAAAABAAAAAAABAAcAAQABAAAAAAACAAcACAABAAAAAAADAAcADwABAAAAAAAEAAcAFgABAAAAAAAFAAsAHQABAAAAAAAGAAcAKAABAAAAAAAKACwALwABAAAAAAALABIAWwADAAEECQAAAAIAbQADAAEECQABAA4AbwADAAEECQACAA4AfQADAAEECQADAA4AiwADAAEECQAEAA4AmQADAAEECQAFABYApwADAAEECQAGAA4AvQADAAEECQAKAFgAywADAAEECQALACQBIyBlai1pY29uUmVndWxhcmVqLWljb25lai1pY29uVmVyc2lvbiAxLjBlai1pY29uRm9udCBnZW5lcmF0ZWQgdXNpbmcgU3luY2Z1c2lvbiBNZXRybyBTdHVkaW93d3cuc3luY2Z1c2lvbi5jb20AIABlAGoALQBpAGMAbwBuAFIAZQBnAHUAbABhAHIAZQBqAC0AaQBjAG8AbgBlAGoALQBpAGMAbwBuAFYAZQByAHMAaQBvAG4AIAAxAC4AMABlAGoALQBpAGMAbwBuAEYAbwBuAHQAIABnAGUAbgBlAHIAYQB0AGUAZAAgAHUAcwBpAG4AZwAgAFMAeQBuAGMAZgB1AHMAaQBvAG4AIABNAGUAdAByAG8AIABTAHQAdQBkAGkAbwB3AHcAdwAuAHMAeQBuAGMAZgB1AHMAaQBvAG4ALgBjAG8AbQAAAAACAAAAAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMBAgEDAQQABHNhdmUEZWRpdAAAAAAA) format('truetype');
    font-weight: normal;
    font-style: normal;
}

[class^="sf-icon-"],
[class*=" sf-icon-"] {
    font-family: 'e-sb-icons' !important;
    speak: none;
    font-size: 55px;
    font-style: normal;
    font-weight: normal;
    font-variant: normal;
    text-transform: none;
    line-height: 1;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}

.dashboard-dynamic #edit_dashboard{
    display: block;
}
/* highcontrast style */

body.highcontrast .dashboard-dynamic #edit_dashboard.e-dashboardlayout.e-control .e-panel {
    background: #000;
}

body.highcontrast .dashboard-dynamic #edit_dashboard.e-dashboardlayout.e-control .e-panel .e-panel-container .e-panel-header {
    color: rgba(255, 255, 255, 0.54);
}

.fabric #togglebtn,
.fabric-dark #togglebtn,
.highcontrast #togglebtn {
    padding:0 13px;
}

.bootstrap5-dark .dialog-text,
.highcontrast .dialog-text,
.tailwind-dark .dialog-text,
.fabric-dark .dialog-text,
.bootstrap-dark .dialog-text {
    border: 1px solid #FFFFFF;
}

.e-bigger.material3 #togglebtn.e-btn .e-btn-icon.e-icon-left,
.e-bigger.material3-dark #togglebtn.e-btn .e-btn-icon.e-icon-left,
.e-bigger.bootstrap5 #togglebtn.e-btn .e-btn-icon.e-icon-left,
.e-bigger.tailwind #togglebtn.e-btn .e-btn-icon.e-icon-left,
.e-bigger.tailwind-dark #togglebtn.e-btn .e-btn-icon.e-icon-left {
    margin-left: -0.2em;
    width: 1em;
}

.e-bigger.highcontrast #togglebtn.e-btn .e-btn-icon.e-icon-left {
    margin-left: -0.5em;
    width: 1em;
}

</style>
