// syncfusionejs2_trial/Samples/Angular/source/ribbon/gallery.component.ts
import { Component, ViewChild, ViewEncapsulation, Inject } from '@angular/core';
import { Ribbon, FileMenuSettingsModel, RibbonButtonSettingsModel, RibbonSplitButtonSettingsModel, RibbonDropDownSettingsModel, RibbonItemSize, RibbonCheckBoxSettingsModel, LauncherClickEventArgs, DisplayMode, FileMenuEventArgs, RibbonGallerySettingsModel, GallerySelectEventArgs } from '@syncfusion/ej2-ribbon';
import { MenuItemModel } from "@syncfusion/ej2-navigations";
import { SelectEventArgs as SelectListEventArgs } from "@syncfusion/ej2-lists";
import { ToastComponent, ToastAllModule } from '@syncfusion/ej2-angular-notifications';
import { ItemModel } from '@syncfusion/ej2-angular-splitbuttons';
import { SBDescriptionComponent } from '../common/dp.component';
import { SBActionDescriptionComponent } from '../common/adp.component';
import { ListViewAllModule } from '@syncfusion/ej2-angular-lists';
import { RibbonAllModule } from '@syncfusion/ej2-angular-ribbon';

@Component({
    selector: 'control-content',
    templateUrl: 'gallery.html',
    styleUrls: ['gallery.component.css'],
    encapsulation: ViewEncapsulation.None,
    standalone: true,
    imports: [RibbonAllModule, ToastAllModule, ListViewAllModule, SBActionDescriptionComponent, SBDescriptionComponent]
})
export class RibbonGalleryComponent {
  @ViewChild('toast') toastObj: ToastComponent;
  @ViewChild('galleryRibbon')
  public ribbonObj: Ribbon;

  constructor(@Inject('sourceFiles') private sourceFiles: any) {
    sourceFiles.files = ['gallery.component.css'];
  }

  public pasteOptions: ItemModel[] = [{ text: "Keep Source Format" }, { text: "Merge Format" }, { text: "Keep Text Only" }];
  public findOptions: ItemModel[] = [{ text: "Find", iconCss: "e-icons e-search" }, { text: "Advanced Find", iconCss: "e-icons e-search" }, { text: "Go to", iconCss: "e-icons e-arrow-right" }];
  public selectOptions: ItemModel[] = [{ text: "Select All" }, { text: "Select Objects" }];
  public dictateOptions: ItemModel[] = [{ text: "Chinese" }, { text: "English" }, { text: "German" }, { text: "French" }];
  public tableOptions: ItemModel[] = [{ text: "Insert Table" }, { text: "Draw Table" }, { text: "Convert Table" }, { text: "Excel SpreadSheet" }];
  public shapeOptions: ItemModel[] = [{ text: "Lines" }, { text: "Rectangles" }, { text: "Basic Arrows" }, { text: "Basic Shapes" }, { text: "FlowChart" }];
  public headerOptions: ItemModel[] = [{ text: "Insert Header" }, { text: "Edit Header" }, { text: "Remove Header" }];
  public footerOptions: ItemModel[] = [{ text: "Insert Footer" }, { text: "Edit Footer" }, { text: "Remove Footer" }];
  public pageOptions: ItemModel[] = [{ text: "Insert Top of page" }, { text: "Insert Bottom of page" }, { text: "Format Page Number" }];
  public linkOptions: ItemModel[] = [{ text: "Insert Link", iconCss: "e-icons e-link" }, { text: "Recent Links", iconCss: "e-icons e-clock" }, { text: "Bookmarks", iconCss: "e-icons e-bookmark" }];

  public pasteSettings: RibbonSplitButtonSettingsModel = { iconCss: 'e-icons e-paste', items: this.pasteOptions, content: 'Paste', select: (args) => { this.updateContent("Paste -> " + args.item.text); }, click: () => { this.updateContent("Paste"); } };
  public tableSettings: RibbonDropDownSettingsModel = { iconCss: "e-icons e-table", content: "Table", items: this.tableOptions, select: (args) => { this.updateContent("Table -> " + args.item.text); } };
  public pictureSettings: RibbonDropDownSettingsModel = { iconCss: "e-icons e-image", content: "Picture", target:'#gallery-pictureList' };
  public shapeSettings: RibbonDropDownSettingsModel = { iconCss: "sf-icon-shapes", content: "Shapes", items: this.shapeOptions, select: (args) => { this.updateContent("Shapes -> " + args.item.text); } };
  public headerSettings: RibbonDropDownSettingsModel = { iconCss: "e-icons e-header", content: "Header", items: this.headerOptions, select: (args) => { this.updateContent("Header -> " + args.item.text); } };
  public footerSettings: RibbonDropDownSettingsModel = { iconCss: "e-icons e-footer", content: "Footer", items: this.footerOptions, select: (args) => { this.updateContent("Footer -> " + args.item.text); } };
  public pageSettings: RibbonDropDownSettingsModel = { iconCss: "e-icons e-page-numbering", content: "Page Number", items: this.pageOptions, select: (args) => { this.updateContent("Page Number -> " + args.item.text); } };
  public linkSettings: RibbonDropDownSettingsModel = { iconCss: "e-icons e-link", content: "Link", items: this.linkOptions, select: (args) => { this.updateContent("Link -> " + args.item.text); } };
  public dictateSettings: RibbonSplitButtonSettingsModel = { iconCss: "sf-icon-dictate", content: "Dictate", items: this.dictateOptions, select: (args) => { this.updateContent("Dictate -> " + args.item.text); }, click: () => { this.updateContent("Dictate"); } };

  public gallerySettings: RibbonGallerySettingsModel = {
      select: (args: GallerySelectEventArgs) => {
        this.updateContent("Gallery -> " + args.currentItem.content);
      },
      popupWidth: '544px',
      itemCount: 3,
      groups: [{
        itemWidth: '100',
        itemHeight: '40',
        header: 'Title and Headings',
        items: [
            {
                content: 'Heading 1',
                cssClass: 'heading_1'
            },
            {
                content: 'Heading 2',
                cssClass: 'heading_2'
            }, {
                content: 'Heading 3',
                cssClass: 'heading_3'
            }, {
                content: 'Heading 4',
                cssClass: 'heading_4'
            }, {
                content: 'Title',
                cssClass: 'title'
            }, {
                content: 'Total',
                cssClass: 'total'
            }
        ]
      }, {
          itemWidth: '100',
          itemHeight: '40',
          header: 'Data and Model',
          items: [
              {
                  content: 'Calculation',
                  cssClass: 'calculation'
              },
              {
                  content: 'Check Cell',
                  cssClass: 'check-cell'
              }, {
                  content: 'Hyperlink',
                  cssClass: 'hyperlink'
              }, {
                  content: 'Input',
                  cssClass: 'input'
              }, {
                  content: 'Linked Cell',
                  cssClass: 'linked-cell'
              }, {
                  content: 'Note',
                  cssClass: 'note'
              }
          ]
      }, {
          itemWidth: '100',
          itemHeight: '40',
          header: 'Good, Bad and Neutral',
          items: [{
                  content: 'Normal',
                  cssClass: 'normal'
              }, {
                  content: 'Bad',
                  cssClass: 'bad'
              }, {
                  content: 'Good',
                  cssClass: 'good'
              }, {
                  content: 'Neutral',
                  cssClass: 'neutral'
              }
          ]
      }]
  };

  public cutButton: RibbonButtonSettingsModel = { iconCss: "e-icons e-cut", content: "Cut", clicked: () => { this.updateContent("Cut"); this.enablePaste(); } };
  public copyButton: RibbonButtonSettingsModel = { iconCss: "e-icons e-copy", content: "Copy", clicked: () => { this.updateContent("Copy"); this.enablePaste(); } };
  public formatButton: RibbonButtonSettingsModel = { iconCss: "e-icons e-format-painter", content: "Format Painter", clicked: () => { this.updateContent("Format Painter"); } };
  public boldButton: RibbonButtonSettingsModel = { iconCss: "e-icons e-bold", content: "Bold", isToggle: true, clicked: () => { this.updateContent("Bold"); } };
  public italicButton: RibbonButtonSettingsModel = { iconCss: "e-icons e-italic", content: "Italic", isToggle: true, clicked: () => { this.updateContent("Italic"); } };
  public underlineButton: RibbonButtonSettingsModel = { iconCss: "e-icons e-underline", content: "Underline", isToggle: true, clicked: () => { this.updateContent("Underline"); } };
  public strikethroughButton: RibbonButtonSettingsModel = { iconCss: "e-icons e-strikethrough", content: "Strikethrough", isToggle: true, clicked: () => { this.updateContent("Strikethrough"); } };
  public changecaseButton: RibbonButtonSettingsModel = { iconCss: "e-icons e-change-case", content: "Change Case", isToggle: true, clicked: () => { this.updateContent("Change Case"); } };
  public modelButton: RibbonButtonSettingsModel = { iconCss: "sf-icon-3d-model", content: "3D Models", clicked: () => { this.updateContent("3D Models"); } };
  public smartButton: RibbonButtonSettingsModel = { iconCss: "sf-icon-smart-art", content: "Smart Art", clicked: () => { this.updateContent("Smart Art"); } };
  public chartButton: RibbonButtonSettingsModel = { iconCss: "sf-icon-chart", content: "Chart", clicked: () => { this.updateContent("Chart"); } };
  public screenshotButton: RibbonButtonSettingsModel = { iconCss: "sf-icon-screenshot", content: "Screenshot", clicked: () => { this.updateContent("Screenshot"); } };
  public commentButton: RibbonButtonSettingsModel = { iconCss: "e-icons e-comment-add", content: "New Comment", clicked: () => { this.updateContent("New Comment"); } };
  public readButton: RibbonButtonSettingsModel = { iconCss: "sf-icon-read", content: "Read Mode", clicked: () => { this.updateContent("Read Mode"); } };
  public printButton: RibbonButtonSettingsModel = { iconCss: "e-icons e-print", content: "Print Layout", clicked: () => { this.updateContent("Print Layout"); } };
  public zoominButton: RibbonButtonSettingsModel = { iconCss: "e-icons e-zoom-in", content: "Zoom In", clicked: () => { this.updateContent("Zoom In"); } };
  public zoomoutButton: RibbonButtonSettingsModel = { iconCss: "e-icons e-zoom-out", content: "Zoom Out", clicked: () => { this.updateContent("Zoom Out"); } };
  public webButton: RibbonButtonSettingsModel = { iconCss: "sf-icon-web-layout", content: "Web Layout", clicked: () => { this.updateContent("Web Layout"); } };
  public darkButton: RibbonButtonSettingsModel = { iconCss: "sf-icon-mode", content: "Dark Mode", clicked: () => { this.updateContent("Dark Mode"); } };
  public editorButton: RibbonButtonSettingsModel = { iconCss: "sf-icon-editor", content: "Editor", clicked: () => { this.updateContent("Editor"); } };
  public reuseButton: RibbonButtonSettingsModel = { iconCss: "sf-icon-reuse", content: "Reuse Files", clicked: () => { this.updateContent("Reuse Files"); } };

  public ruler: RibbonCheckBoxSettingsModel = { label: "Ruler", checked: false, change: () => { this.updateContent("Ruler"); } };
  public grid: RibbonCheckBoxSettingsModel = { label: "Gridlines", checked: false, change: () => { this.updateContent("Gridlines"); } };
  public navigation: RibbonCheckBoxSettingsModel = { label: "Navigation Pane", checked: false, change: () => { this.updateContent("Navigation Pane"); } };

  public fileOptions: MenuItemModel[] = [{ text: "New", iconCss: "e-icons e-file-new", id: "new" },
  { text: "Open", iconCss: "e-icons e-folder-open", id: "Open" },
  { text: "Rename", iconCss: "e-icons e-rename", id: "rename" },
  {
    text: "Save as", iconCss: "e-icons e-save", id: "save",
    items: [
      { text: "Microsoft Word (.docx)", iconCss: "sf-icon-word", id: "newword" },
      { text: "Microsoft Word 97-2003(.doc)", iconCss: "sf-icon-word", id: "oldword" },
      { text: "Download as PDF", iconCss: "e-icons e-export-pdf", id: "pdf" }]
  }]

  public fileSettings: FileMenuSettingsModel = {
    menuItems: this.fileOptions,
    visible: true,
    select: (args: FileMenuEventArgs) => {
      if (args.item.id === "newword" || args.item.id === "oldword" || args.item.id === "pdf") {
        this.updateContent("File -> Save as -> " + args.item.text);
      }
      else {
        this.updateContent("File -> " + args.item.text);
      }
    }
  };

  public largeSize: RibbonItemSize = RibbonItemSize.Large;
  public smallSize: RibbonItemSize = RibbonItemSize.Small;

  public colorPickerDisplayMode: DisplayMode = DisplayMode.Simplified | DisplayMode.Classic;
  public Overflow: DisplayMode = DisplayMode.Overflow;

  public position = { X: 'Right' };
  public animation = { show: { effect: 'FadeIn' }, hide: { effect: 'FadeOut' } };

  public pasteDisabled: boolean = true;
  
  public enablePaste() {
    if (!this.pasteDisabled) { return; }
    this.ribbonObj.enableItem('pastebtn');
    this.pasteDisabled = false;
  }

  public pictureList: Object = [
    { text: 'This Device' },
    { text: 'Stock Images' },
    { text: 'Online Images' }];

  public listItem (args: SelectListEventArgs) {
    this.updateContent( "Pictures -> " + args.text)
  }
  
  public updateContent(args: string) {
    this.toastObj.show({ content: "Last clicked item is " + args });
  }

  public launchClick(args: LauncherClickEventArgs) {
    if (args.groupId == "clipboard") {
      this.updateContent("Clipboard Launcher Icon");
    }
    else if (args.groupId == "illustration") {
      this.updateContent("Illustration Launcher Icon");
    }
    else if (args.groupId == "header_footer") {
      this.updateContent("Header & Footer Launcher Icon");
    }
  }
}

// syncfusionejs2_trial/Samples/React/src/ribbon/gallery.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.Gallery = void 0;
var React = require("react");
var ej2_react_ribbon_1 = require("@syncfusion/ej2-react-ribbon");
var ej2_react_ribbon_2 = require("@syncfusion/ej2-react-ribbon");
var ej2_react_notifications_1 = require("@syncfusion/ej2-react-notifications");
var ej2_react_lists_1 = require("@syncfusion/ej2-react-lists");
var sample_base_1 = require("../common/sample-base");
require("./gallery.css");
var Gallery = /** @class */ (function (_super) {
    __extends(Gallery, _super);
    function Gallery() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        _this.gallerySelect = function (args) {
            _this.updateContent("Gallery -> " + args.currentItem.content);
        };
        _this.gallerySettings = ({
            select: _this.gallerySelect,
            popupWidth: '544px',
            itemCount: 3,
            groups: [{
                    itemWidth: '100',
                    itemHeight: '40',
                    header: 'Title and Headings',
                    items: [
                        {
                            content: 'Heading 1',
                            cssClass: 'heading_1'
                        },
                        {
                            content: 'Heading 2',
                            cssClass: 'heading_2'
                        }, {
                            content: 'Heading 3',
                            cssClass: 'heading_3'
                        }, {
                            content: 'Heading 4',
                            cssClass: 'heading_4'
                        }, {
                            content: 'Title',
                            cssClass: 'title'
                        }, {
                            content: 'Total',
                            cssClass: 'total'
                        }
                    ]
                }, {
                    itemWidth: '100',
                    itemHeight: '40',
                    header: 'Data and Model',
                    items: [
                        {
                            content: 'Calculation',
                            cssClass: 'calculation'
                        },
                        {
                            content: 'Check Cell',
                            cssClass: 'check-cell'
                        }, {
                            content: 'Hyperlink',
                            cssClass: 'hyperlink'
                        }, {
                            content: 'Input',
                            cssClass: 'input'
                        }, {
                            content: 'Linked Cell',
                            cssClass: 'linked-cell'
                        }, {
                            content: 'Note',
                            cssClass: 'note'
                        }
                    ]
                }, {
                    itemWidth: '100',
                    itemHeight: '40',
                    header: 'Good, Bad and Neutral',
                    items: [{
                            content: 'Normal',
                            cssClass: 'normal'
                        }, {
                            content: 'Bad',
                            cssClass: 'bad'
                        }, {
                            content: 'Good',
                            cssClass: 'good'
                        }, {
                            content: 'Neutral',
                            cssClass: 'neutral'
                        }
                    ]
                }]
        });
        _this.pasteOptions = [{ text: "Keep Source Format" }, { text: "Merge Format" }, { text: "Keep Text Only" }];
        _this.tableOptions = [{ text: "Insert Table" }, { text: "Draw Table" }, { text: "Convert Table" }, { text: "Excel SpreadSheet" }];
        _this.shapeOptions = [{ text: "Lines" }, { text: "Rectangles" }, { text: "Basic Arrows" }, { text: "Basic Shapes" }, { text: "FlowChart" }];
        _this.headerOptions = [{ text: "Insert Header" }, { text: "Edit Header" }, { text: "Remove Header" }];
        _this.footerOptions = [{ text: "Insert Footer" }, { text: "Edit Footer" }, { text: "Remove Footer" }];
        _this.pageOptions = [{ text: "Insert Top of page" }, { text: "Insert Bottom of page" }, { text: "Format Page Number" }];
        _this.linkOptions = [{ text: "Insert Link", iconCss: "e-icons e-link" }, { text: "Recent Links", iconCss: "e-icons e-clock" }, { text: "Bookmarks", iconCss: "e-icons e-bookmark" }];
        _this.dictateOptions = [{ text: "Chinese" }, { text: "English" }, { text: "German" }, { text: "French" }];
        _this.fontSize = ["8", "9", "10", "11", "12", "14", "16", "18", "20", "22", "24", "26", "28", "36", "48", "72", "96"];
        _this.fontStyle = ["Algerian", "Arial", "Calibri", "Cambria", "Cambria Math", "Courier New", "Candara", "Georgia", "Impact", "Segoe Print", "Segoe Script", "Segoe UI", "Symbol", "Times New Roman", "Verdana", "Windings"];
        _this.fileOptions = [{ text: "New", iconCss: "e-icons e-file-new", id: "new" },
            { text: "Open", iconCss: "e-icons e-folder-open", id: "Open" },
            { text: "Rename", iconCss: "e-icons e-rename", id: "rename" },
            {
                text: "Save as", iconCss: "e-icons e-save", id: "save",
                items: [
                    { text: "Microsoft Word (.docx)", iconCss: "sf-icon-word", id: "newword" },
                    { text: "Microsoft Word 97-2003(.doc)", iconCss: "sf-icon-word", id: "oldword" },
                    { text: "Download as PDF", iconCss: "e-icons e-export-pdf", id: "pdf" }
                ]
            }];
        _this.isPasteDisabled = true;
        _this.enablePaste = function () {
            if (!_this.isPasteDisabled) {
                return;
            }
            _this.ribbonObj.enableItem('pastebtn');
            _this.isPasteDisabled = false;
        };
        _this.updateContent = function (args) {
            _this.toastInstance.show({ content: "Last clicked item is " + args });
        };
        _this.fileSelect = function (args) {
            if (args.item.id === "newword" || args.item.id === "oldword" || args.item.id === "pdf") {
                _this.updateContent("File -> Save as -> " + args.item.text);
            }
            else {
                _this.updateContent("File -> " + args.item.text);
            }
        };
        _this.launchClick = function (args) {
            if (args.groupId == "clipboard") {
                _this.updateContent("Clipboard Launcher Icon");
            }
            else if (args.groupId == "illustration") {
                _this.updateContent("Illustration Launcher Icon");
            }
            else if (args.groupId == "header_footer") {
                _this.updateContent("Header & Footer Launcher Icon");
            }
        };
        return _this;
    }
    Gallery.prototype.render = function () {
        var _this = this;
        return (React.createElement("div", { className: 'control-pane' },
            React.createElement("div", { className: 'col-lg-12 control-section ribbon-gallery-section' },
                React.createElement("div", { className: 'control ribbon-sample' },
                    React.createElement("div", { id: "gallery-ribbonContainer", className: 'ribbon-gallery-container' },
                        React.createElement(ej2_react_ribbon_1.RibbonComponent, { id: 'gallery-ribbon', cssClass: 'ribbonGallery', ref: function (ribbonDefault) { _this.ribbonObj = ribbonDefault; }, fileMenu: { visible: true, menuItems: this.fileOptions, select: this.fileSelect }, launcherIconClick: this.launchClick },
                            React.createElement(ej2_react_ribbon_1.RibbonTabsDirective, null,
                                React.createElement(ej2_react_ribbon_1.RibbonTabDirective, { header: 'Home' },
                                    React.createElement(ej2_react_ribbon_1.RibbonGroupsDirective, null,
                                        React.createElement(ej2_react_ribbon_1.RibbonGroupDirective, { header: "Clipboard", id: 'clipboard', groupIconCss: "e-icons e-paste", showLauncherIcon: true },
                                            React.createElement(ej2_react_ribbon_1.RibbonCollectionsDirective, null,
                                                React.createElement(ej2_react_ribbon_1.RibbonCollectionDirective, null,
                                                    React.createElement(ej2_react_ribbon_2.RibbonItemsDirective, null,
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "SplitButton", disabled: true, id: "pastebtn", allowedSizes: ej2_react_ribbon_2.RibbonItemSize.Large, splitButtonSettings: { iconCss: "e-icons e-paste", items: this.pasteOptions, content: "Paste", select: function (args) { this.updateContent("Paste -> " + args.item.text); }, click: function () { this.updateContent("Paste"); } } }))),
                                                React.createElement(ej2_react_ribbon_1.RibbonCollectionDirective, null,
                                                    React.createElement(ej2_react_ribbon_2.RibbonItemsDirective, null,
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "Button", buttonSettings: { iconCss: "e-icons e-cut", content: "Cut", clicked: function () { this.updateContent("Cut"); this.enablePaste(); } } }),
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "Button", buttonSettings: { iconCss: "e-icons e-copy", content: "Copy", clicked: function () { this.updateContent("Copy"); this.enablePaste(); } } }),
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "Button", buttonSettings: { iconCss: "e-icons e-format-painter", content: "Format Painter", clicked: function () { this.updateContent("Format Painter"); } } }))))),
                                        React.createElement(ej2_react_ribbon_1.RibbonGroupDirective, { header: "Gallery", id: 'gallery', groupIconCss: "e-icons e-paste", showLauncherIcon: true },
                                            React.createElement(ej2_react_ribbon_1.RibbonCollectionsDirective, null,
                                                React.createElement(ej2_react_ribbon_1.RibbonCollectionDirective, null,
                                                    React.createElement(ej2_react_ribbon_2.RibbonItemsDirective, null,
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "Gallery", allowedSizes: ej2_react_ribbon_2.RibbonItemSize.Large, gallerySettings: this.gallerySettings }))))),
                                        React.createElement(ej2_react_ribbon_1.RibbonGroupDirective, { header: "Voice", groupIconCss: "sf-icon-dictate", isCollapsible: false },
                                            React.createElement(ej2_react_ribbon_1.RibbonCollectionsDirective, null,
                                                React.createElement(ej2_react_ribbon_1.RibbonCollectionDirective, null,
                                                    React.createElement(ej2_react_ribbon_2.RibbonItemsDirective, null,
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "SplitButton", allowedSizes: ej2_react_ribbon_2.RibbonItemSize.Large, splitButtonSettings: { iconCss: "sf-icon-dictate", items: this.dictateOptions, content: "Dictate", select: function (args) { this.updateContent("Dictate -> " + args.item.text); }, click: function () { this.updateContent("Dictate"); } } }))))),
                                        React.createElement(ej2_react_ribbon_1.RibbonGroupDirective, { header: "Editor", groupIconCss: "sf-icon-editor", isCollapsible: false },
                                            React.createElement(ej2_react_ribbon_1.RibbonCollectionsDirective, null,
                                                React.createElement(ej2_react_ribbon_1.RibbonCollectionDirective, null,
                                                    React.createElement(ej2_react_ribbon_2.RibbonItemsDirective, null,
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "Button", allowedSizes: ej2_react_ribbon_2.RibbonItemSize.Large, buttonSettings: { iconCss: "sf-icon-editor", content: "Editor", clicked: function () { this.updateContent("Editor"); } } }))))),
                                        React.createElement(ej2_react_ribbon_1.RibbonGroupDirective, { header: "Reuse Files", groupIconCss: "sf-icon-reuse", isCollapsible: false },
                                            React.createElement(ej2_react_ribbon_1.RibbonCollectionsDirective, null,
                                                React.createElement(ej2_react_ribbon_1.RibbonCollectionDirective, null,
                                                    React.createElement(ej2_react_ribbon_2.RibbonItemsDirective, null,
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "Button", disabled: true, allowedSizes: ej2_react_ribbon_2.RibbonItemSize.Large, buttonSettings: { iconCss: "sf-icon-reuse", content: "Reuse Files", clicked: function () { this.updateContent("Reuse Files"); } } }))))))),
                                React.createElement(ej2_react_ribbon_1.RibbonTabDirective, { header: 'Insert' },
                                    React.createElement(ej2_react_ribbon_1.RibbonGroupsDirective, null,
                                        React.createElement(ej2_react_ribbon_1.RibbonGroupDirective, { header: "Tables", isCollapsible: false },
                                            React.createElement(ej2_react_ribbon_1.RibbonCollectionsDirective, null,
                                                React.createElement(ej2_react_ribbon_1.RibbonCollectionDirective, null,
                                                    React.createElement(ej2_react_ribbon_2.RibbonItemsDirective, null,
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "DropDown", allowedSizes: ej2_react_ribbon_2.RibbonItemSize.Large, dropDownSettings: { iconCss: "e-icons e-table", items: this.tableOptions, content: "Table", select: function (args) { this.updateContent("Table -> " + args.item.text); } } }))))),
                                        React.createElement(ej2_react_ribbon_1.RibbonGroupDirective, { header: "Illustration", overflowHeader: "Illustrations", id: "illustration", groupIconCss: "e-icons e-image", enableGroupOverflow: true, orientation: "Row" },
                                            React.createElement(ej2_react_ribbon_1.RibbonCollectionsDirective, null,
                                                React.createElement(ej2_react_ribbon_1.RibbonCollectionDirective, null,
                                                    React.createElement(ej2_react_ribbon_2.RibbonItemsDirective, null,
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { id: 'pictureddl', type: "DropDown", dropDownSettings: { iconCss: "e-icons e-image", content: "Pictures", target: '#gallery-pictureList' } }),
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "DropDown", dropDownSettings: { iconCss: "sf-icon-shapes", items: this.shapeOptions, content: "Shapes", select: function (args) { this.updateContent("Shapes -> " + args.item.text); } } }),
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "Button", buttonSettings: { iconCss: "sf-icon-3d-model", content: "3D Models", clicked: function () { this.updateContent("3D Models"); } } }),
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "Button", buttonSettings: { iconCss: "sf-icon-smart-art", content: "Smart Art", clicked: function () { this.updateContent("Smart Art"); } } }),
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "Button", buttonSettings: { iconCss: "sf-icon-chart", content: "Charts", clicked: function () { this.updateContent("Chart"); } } }),
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "Button", buttonSettings: { iconCss: "sf-icon-screenshot", content: "Screenshot", clicked: function () { this.updateContent("Screenshot"); } } }))))),
                                        React.createElement(ej2_react_ribbon_1.RibbonGroupDirective, { header: "Header & Footer", id: "header_footer", groupIconCss: "e-icons e-table", orientation: "Column", showLauncherIcon: true },
                                            React.createElement(ej2_react_ribbon_1.RibbonCollectionsDirective, null,
                                                React.createElement(ej2_react_ribbon_1.RibbonCollectionDirective, null,
                                                    React.createElement(ej2_react_ribbon_2.RibbonItemsDirective, null,
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "DropDown", dropDownSettings: { iconCss: "e-icons e-header", items: this.headerOptions, content: "Header", select: function (args) { this.updateContent("Header -> " + args.item.text); } } }),
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "DropDown", dropDownSettings: { iconCss: "e-icons e-footer", items: this.footerOptions, content: "Footer", select: function (args) { this.updateContent("Footer -> " + args.item.text); } } }),
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "DropDown", dropDownSettings: { iconCss: "e-icons e-page-numbering", items: this.pageOptions, content: "Page Numbering", select: function (args) { this.updateContent("Page Numbering -> " + args.item.text); } } }))))),
                                        React.createElement(ej2_react_ribbon_1.RibbonGroupDirective, { header: "Comments", isCollapsible: false },
                                            React.createElement(ej2_react_ribbon_1.RibbonCollectionsDirective, null,
                                                React.createElement(ej2_react_ribbon_1.RibbonCollectionDirective, null,
                                                    React.createElement(ej2_react_ribbon_2.RibbonItemsDirective, null,
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "Button", allowedSizes: ej2_react_ribbon_2.RibbonItemSize.Large, buttonSettings: { iconCss: "e-icons e-comment-add", content: "New Comment", clicked: function () { this.updateContent("New Comment"); } } }))))),
                                        React.createElement(ej2_react_ribbon_1.RibbonGroupDirective, { header: "Links", groupIconCss: "e-icons e-link", isCollapsible: false },
                                            React.createElement(ej2_react_ribbon_1.RibbonCollectionsDirective, null,
                                                React.createElement(ej2_react_ribbon_1.RibbonCollectionDirective, null,
                                                    React.createElement(ej2_react_ribbon_2.RibbonItemsDirective, null,
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "DropDown", allowedSizes: ej2_react_ribbon_2.RibbonItemSize.Large, dropDownSettings: { iconCss: "e-icons e-link", items: this.linkOptions, content: "Link", select: function (args) { this.updateContent("Link -> " + args.item.text); } } }))))))),
                                React.createElement(ej2_react_ribbon_1.RibbonTabDirective, { header: 'View' },
                                    React.createElement(ej2_react_ribbon_1.RibbonGroupsDirective, null,
                                        React.createElement(ej2_react_ribbon_1.RibbonGroupDirective, { header: "Views", groupIconCss: 'e-icons e-print', orientation: 'Row' },
                                            React.createElement(ej2_react_ribbon_1.RibbonCollectionsDirective, null,
                                                React.createElement(ej2_react_ribbon_1.RibbonCollectionDirective, null,
                                                    React.createElement(ej2_react_ribbon_2.RibbonItemsDirective, null,
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "Button", buttonSettings: { iconCss: "sf-icon-read", content: "Read Mode", clicked: function () { this.updateContent("Read Mode"); } } }),
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "Button", buttonSettings: { iconCss: "e-icons e-print", content: "Print Layout", clicked: function () { this.updateContent("Print Layout"); } } }),
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "Button", buttonSettings: { iconCss: "sf-icon-web-layout", content: "Web Layout", clicked: function () { this.updateContent("Web Layout"); } } }))))),
                                        React.createElement(ej2_react_ribbon_1.RibbonGroupDirective, { header: "Zoom", groupIconCss: "e-icons e-zoom-to-fit", orientation: "Row" },
                                            React.createElement(ej2_react_ribbon_1.RibbonCollectionsDirective, null,
                                                React.createElement(ej2_react_ribbon_1.RibbonCollectionDirective, null,
                                                    React.createElement(ej2_react_ribbon_2.RibbonItemsDirective, null,
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "Button", buttonSettings: { iconCss: "e-icons e-zoom-in", content: "Zoom in", clicked: function () { this.updateContent("Zoom in"); } } }),
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "Button", buttonSettings: { iconCss: "e-icons e-zoom-out", content: "Zoom out", clicked: function () { this.updateContent("Zoom out"); } } }))))),
                                        React.createElement(ej2_react_ribbon_1.RibbonGroupDirective, { header: "Show", isCollapsible: true },
                                            React.createElement(ej2_react_ribbon_1.RibbonCollectionsDirective, null,
                                                React.createElement(ej2_react_ribbon_1.RibbonCollectionDirective, null,
                                                    React.createElement(ej2_react_ribbon_2.RibbonItemsDirective, null,
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "CheckBox", checkBoxSettings: { label: "Ruler", checked: false, change: function () { this.updateContent("Ruler"); } } }),
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "CheckBox", checkBoxSettings: { label: "Gridlines", checked: false, change: function () { this.updateContent("Gridlines"); } } }),
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "CheckBox", checkBoxSettings: { label: "Navigation Pane", checked: true, change: function () { this.updateContent("Navigation Pane"); } } }))))),
                                        React.createElement(ej2_react_ribbon_1.RibbonGroupDirective, { header: "Dark Mode", isCollapsible: false },
                                            React.createElement(ej2_react_ribbon_1.RibbonCollectionsDirective, null,
                                                React.createElement(ej2_react_ribbon_1.RibbonCollectionDirective, null,
                                                    React.createElement(ej2_react_ribbon_2.RibbonItemsDirective, null,
                                                        React.createElement(ej2_react_ribbon_2.RibbonItemDirective, { type: "Button", buttonSettings: { iconCss: "sf-icon-mode", content: "Dark Mode", clicked: function () { this.this.updateContent("Dark Mode"); } } })))))))),
                            React.createElement(ej2_react_ribbon_2.Inject, { services: [ej2_react_ribbon_2.RibbonFileMenu, ej2_react_ribbon_2.RibbonColorPicker, ej2_react_ribbon_2.RibbonGallery] })),
                        React.createElement("div", { id: "gallery-ribbonPlaceHolder" },
                            React.createElement("div", { className: "content1" }),
                            React.createElement("div", { className: "content2" }),
                            React.createElement("div", { className: "content3" }),
                            React.createElement("div", { className: "content4" }),
                            React.createElement(ej2_react_notifications_1.ToastComponent, { id: 'toast', ref: function (toast) { return _this.toastInstance = toast; }, position: { X: 'Right' }, width: 'auto', height: 25, timeOut: 2000, cssClass: 'e-toast-info', showCloseButton: true, target: "#gallery-ribbonPlaceHolder", newestOnTop: true, animation: { show: { effect: 'FadeIn' }, hide: { effect: 'FadeOut' } } })),
                        React.createElement(ej2_react_lists_1.ListViewComponent, { id: 'gallery-pictureList', dataSource: ['This Device', 'Stock Images', 'Online Images'], showHeader: true, headerTitle: "Insert Picture From", select: function (args) { this.updateContent("Picture -> " + args.text); } })))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null, "This sample showcases the functionality of the Ribbon Gallery item.")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null,
                    "The Ribbon Gallery item enables to perform specific actions by displaying a collection of related items, including icons, content, or images. In this sample, the gallery item is added to showcase a collection of items with content using ",
                    React.createElement("code", null, "gallerySettings"),
                    " property with the defined type as ",
                    React.createElement("code", null, "RibbonItemType.Gallery"),
                    ". Each collection can be grouped using ",
                    React.createElement("code", null, "groups"),
                    " property with defined group name using ",
                    React.createElement("code", null, "header"),
                    " property. Each item's content is added using ",
                    React.createElement("code", null, "content"),
                    " property, and its customization using ",
                    React.createElement("code", null, "itemWidth"),
                    ", ",
                    React.createElement("code", null, "itemHeight"),
                    ", and ",
                    React.createElement("code", null, "cssClass"),
                    " properties."))));
    };
    return Gallery;
}(sample_base_1.SampleBase));
exports.Gallery = Gallery;
