// syncfusionejs2_trial/Samples/React/src/progress-bar/semi-circular.tsx
/**
 * Sample for semi circular progress bar
 */
import * as ReactDOM from 'react-dom';
import * as React from "react";
import {
    ProgressBarComponent, ProgressBarAnnotationsDirective, ProgressBarAnnotationDirective, Inject,
    ProgressAnnotation, ProgressTheme, ILoadedEventArgs
} from '@syncfusion/ej2-react-progressbar';
import { Browser } from '@syncfusion/ej2-base';
import { ButtonComponent } from '@syncfusion/ej2-react-buttons';
import { EmitType } from '@syncfusion/ej2-base';
import { SampleBase } from '../common/sample-base';
import { loadProgressBarTheme } from './theme-colors';


const SAMPLE_CSS = `
    .control-fluid {
         padding: 0px !important;
     }
     #control-container {
         padding: 0px !important;
     }
     .annotaion-pro {
             font-family: Roboto-Regular;
             font-size: 20px;
             color: #1B1C1A;
             letter-spacing: 0.01px;
         }
         .progress-bar-parent {
             margin-top: 8%;
             text-align: center;
         }
         .progress-text {
             display: inline-flex;
             margin: auto;
         }
         .progress-text-align {
             font-family: Roboto-Regular;
             font-size: 12px;
             color: #3D3E3C;
             letter-spacing: 0;
             margin: auto;
         }

         #control-container {
             padding: 0px !important;
         }

         .progress-container-align {
             text-align: center;
         }

         .reload-btn {
             text-align: center;
         }

         #reLoad {
             border-radius: 4px;
             text-transform: capitalize;
             margin-top: 3%;
         }

     `;

export class ProgressBarSemiCircular extends SampleBase<{}, {}> {
    private annotationColors: string[] = ['#e91e63', '#0078D6', '#317ab9', '#007bff', '#4F46E5', '#FFD939', '#9A9A9A', '#22D3EE', '#0D6EFD', '#6750A4', '#D0BCFF', '#0F6CBD', '#1AEBFF', '#115EA3', '#6366F1'];
    private content1: string = '<div id="point1" style="font-size:24px;font-weight:bold;color:#0078D6;fill:#0078D6"><span>100%</span></div>';
    private content2: string = '<div id="point1" style="font-size:24px;font-weight:bold;color:#0078D6;fill:#0078D6"><span>100%</span></div>';
    private content3: string = '<div id="point1" style="font-size:24px;font-weight:bold;color:#0078D6;fill:#0078D6"><span>100%</span></div>';
    private content4: string = '<div id="point1" style="font-size:24px;font-weight:bold;color:#0078D6;fill:#0078D6"><span>100%</span></div>';
    private thickness: number = 5;
    private inverseSemiProgress: ProgressBarComponent;
    private verticalProgress: ProgressBarComponent;
    private semiProgress: ProgressBarComponent;
    private verticalOppose: ProgressBarComponent;

    private onclick(): void {
        this.inverseSemiProgress.refresh();
        this.verticalProgress.refresh();
        this.verticalOppose.refresh();
        this.semiProgress.refresh();
    }

    private annotationElementContent(color: string, controlID: string): string {
        let content: string;
        switch (controlID) {
            case 'angle-container':
                content = '100%';
                break;
            case 'vertical-container':
                content = '100%';
                break;
            case 'vsemi-container':
                content = '100%';
                break;
            case 'semi-container':
                content = '100%';
                break;
        }
        return ('<div id="point1" style="font-size:24px;font-weight:bold;color: ' + color + ' "><span>' + content + '</span></div>');
    }

    private progressLoad: EmitType<ILoadedEventArgs> = (args: ILoadedEventArgs) => {
        let selectedTheme: string = loadProgressBarTheme(args);
        switch (selectedTheme) {
            case 'Material':
                args.progressBar.annotations[0].content = this.annotationElementContent(this.annotationColors[0], args.progressBar.element.id);
                break;
            case 'Fabric':
                args.progressBar.annotations[0].content = this.annotationElementContent(this.annotationColors[1], args.progressBar.element.id);
                break;
            case 'Bootstrap':
                args.progressBar.annotations[0].content = this.annotationElementContent(this.annotationColors[2], args.progressBar.element.id);
                break;
            case 'Bootstrap4':
                args.progressBar.annotations[0].content = this.annotationElementContent(this.annotationColors[3], args.progressBar.element.id);
                break;
            case 'Tailwind':
            case 'Tailwind3':
                args.progressBar.annotations[0].content = this.annotationElementContent(this.annotationColors[4], args.progressBar.element.id);
                break;
            case 'BootstrapDark':
            case 'FabricDark':
            case 'MaterialDark':
                args.progressBar.annotations[0].content = this.annotationElementContent(this.annotationColors[6], args.progressBar.element.id);
                break;
            case 'Bootstrap5':
            case 'Bootstrap5Dark':
            case 'fluent':
            case 'FluentDark':
                args.progressBar.annotations[0].content = this.annotationElementContent(this.annotationColors[8], args.progressBar.element.id);
                break;
            case 'TailwindDark':
                args.progressBar.annotations[0].content = this.annotationElementContent(this.annotationColors[7], args.progressBar.element.id);
                break;
            case 'Tailwind3Dark':
                args.progressBar.annotations[0].content = this.annotationElementContent(this.annotationColors[14], args.progressBar.element.id);
                break;
            case 'Material3':
                args.progressBar.annotations[0].content = this.annotationElementContent(this.annotationColors[9], args.progressBar.element.id);
                break;
            case 'Material3Dark':
                args.progressBar.annotations[0].content = this.annotationElementContent(this.annotationColors[10], args.progressBar.element.id);
                break;
            case "Fluent2":
                args.progressBar.annotations[0].content = this.annotationElementContent(this.annotationColors[11], args.progressBar.element.id);
                break;
            case "Fluent2HighContrast":
                args.progressBar.annotations[0].content = this.annotationElementContent(this.annotationColors[12], args.progressBar.element.id);
                break;
            case "Fluent2Dark":
                args.progressBar.annotations[0].content = this.annotationElementContent(this.annotationColors[13], args.progressBar.element.id);
                break;
            default:
                args.progressBar.annotations[0].content = this.annotationElementContent(this.annotationColors[5], args.progressBar.element.id);
                break;
        }
    }

    render() {
        return (
            <div className='control-pane'>
                <style>
                    {SAMPLE_CSS}
                </style>
                <div className="control-section progress-bar-parent">
                    <div className="row">
                        <div className="col-lg-3 col-md-3 col-3 progress-container">
                            <div className="progress-container-align">
                                <ProgressBarComponent id="angle-container" ref={progress1 => this.inverseSemiProgress = progress1}
                                    type='Circular'
                                    startAngle={240}
                                    endAngle={120}
                                    width='160px'
                                    height='160px'
                                    minimum={0}
                                    maximum={100}
                                    value={100}
                                    cornerRadius='Round'
                                    trackThickness={this.thickness}
                                    progressThickness={this.thickness}
                                    animation={{
                                        enable: true,
                                        duration: 2000,
                                        delay: 0,
                                    }}
                                    load={this.progressLoad.bind(this)}
                                >
                                    <Inject services={[ProgressAnnotation]} />
                                    <ProgressBarAnnotationsDirective>
                                        <ProgressBarAnnotationDirective content={this.content1}>

                                        </ProgressBarAnnotationDirective>
                                    </ProgressBarAnnotationsDirective>
                                </ProgressBarComponent>
                            </div>
                        </div>
                        <div className="col-lg-3 col-md-3 col-3 progress-container">
                            <div className="progress-container-align">
                                <ProgressBarComponent id="vertical-container" ref={progress2 => this.verticalProgress = progress2}
                                    type='Circular'
                                    startAngle={180}
                                    endAngle={0}
                                    width='160px'
                                    height='160px'
                                    minimum={0}
                                    maximum={100}
                                    value={100}
                                    cornerRadius='Round'
                                    trackThickness={this.thickness}
                                    progressThickness={this.thickness}
                                    load={this.progressLoad.bind(this)}
                                    animation={{
                                        enable: true,
                                        duration: 2000,
                                        delay: 0,
                                    }}
                                >
                                    <Inject services={[ProgressAnnotation]} />
                                    <ProgressBarAnnotationsDirective>
                                        <ProgressBarAnnotationDirective content={this.content2}>

                                        </ProgressBarAnnotationDirective>
                                    </ProgressBarAnnotationsDirective>
                                </ProgressBarComponent>
                            </div>
                        </div>
                        <div className="col-lg-3 col-md-3 col-3 progress-container">
                            <div className="progress-container-align">
                                <ProgressBarComponent id="vsemi-container" ref={progress3 => this.verticalOppose = progress3}
                                    type='Circular'
                                    startAngle={0}
                                    endAngle={180}
                                    width='160px'
                                    height='160px'
                                    minimum={0}
                                    maximum={100}
                                    value={100}
                                    cornerRadius='Round'
                                    trackThickness={this.thickness}
                                    progressThickness={this.thickness}
                                    load={this.progressLoad.bind(this)}
                                    animation={{
                                        enable: true,
                                        duration: 2000,
                                        delay: 0,
                                    }}
                                >
                                    <Inject services={[ProgressAnnotation]} />
                                    <ProgressBarAnnotationsDirective>
                                        <ProgressBarAnnotationDirective content={this.content3}>

                                        </ProgressBarAnnotationDirective>
                                    </ProgressBarAnnotationsDirective>
                                </ProgressBarComponent>
                            </div>
                        </div>
                        <div className="col-lg-3 col-md-3 col-3 progress-container">
                            <div className="progress-container-align">
                                <ProgressBarComponent id="semi-container" ref={progress4 => this.semiProgress = progress4}
                                    type='Circular'
                                    startAngle={270}
                                    endAngle={90}
                                    width='160px'
                                    height='160px'
                                    minimum={0}
                                    maximum={100}
                                    value={100}
                                    cornerRadius='Round'
                                    trackThickness={this.thickness}
                                    progressThickness={this.thickness}
                                    load={this.progressLoad.bind(this)}
                                    animation={{
                                        enable: true,
                                        duration: 2000,
                                        delay: 0,
                                    }}
                                >
                                    <Inject services={[ProgressAnnotation]} />
                                    <ProgressBarAnnotationsDirective>
                                        <ProgressBarAnnotationDirective content={this.content4}>

                                        </ProgressBarAnnotationDirective>
                                    </ProgressBarAnnotationsDirective>
                                </ProgressBarComponent>
                            </div>
                        </div>
                    </div>
                    <div className="row">
                        <div className="col-lg-12 col-md-12 col-12 reload-btn">
                            <button onClick={this.onclick.bind(this)} id="reLoad" className="e-control e-btn e-lib e-outline e-primary">Reload</button>
                        </div>
                    </div>
                </div>
                <div id="action-description">
                    <p>
                    This sample illustrates a circular progress bar with start and end angle customized.
                </p>
                </div>
                <div id="description">
                    <p>This demo for Essential<sup>®</sup> JS2 Progress Bar control shows the customizing options for angle in circular progress bar.</p>
                </div>
            </div>
        )
    }
}

// syncfusionejs2_trial/Samples/Vue/public/source/progress-bar/semi-circular.vue
<template>
  <div class="control-section progress-bar-parent">
    <div class="row">
        <div class="col-lg-3 col-md-3 col-3 progress-container">
          <div class="col-lg-3 col-md-3 col-3 progress-container">
          <div id="angle-container">
           <ejs-progressbar
            ref="angle"
            id="angle-progress"
            type='Circular'
            :startAngle='startAngle1'
            :endAngle='endAngle1'
            :minimum='minimum'
            width='160px'
            height='160px'
            :maximum='maximum'
            :value='value1'
            cornerRadius='Round'
            :trackThickness='trackThickness'
            :progressThickness='progressThickness'
            :animation="animation"
            :load='load'
            >
            <e-progressbar-annotations>
              <e-progressbar-annotation
               :content="content1"
              ></e-progressbar-annotation>
            </e-progressbar-annotations>
            </ejs-progressbar>
            </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-3 col-3 progress-container">
            <div class="progress-container-align">
             <div id="vertical-container">
            <ejs-progressbar
            ref="vertical"
            id="vertical-progress"
            type='Circular'
            :startAngle='startAngle2'
            :endAngle='endAngle2'
            :minimum='minimum'
            width='160px'
            height='160px'
            :maximum='maximum'
            :value='value2'
            cornerRadius='Round'
            :trackThickness='trackThickness'
            :progressThickness='progressThickness'
            :animation="animation"
            :load='load'
            >
            <e-progressbar-annotations>
              <e-progressbar-annotation
               :content="content2"
              ></e-progressbar-annotation>
            </e-progressbar-annotations>
            </ejs-progressbar>
            </div>
            </div>
           </div>
           <div class="col-lg-3 col-md-3 col-3 progress-container">
             <div class="progress-container-align">
                <div id="vsemi-container">
            <ejs-progressbar
            ref="vsemi"
            id="vsemi-progress"
            type='Circular'
            :startAngle='startAngle3'
            :endAngle='endAngle3'
            :minimum='minimum'
            width='160px'
            height='160px'
            :maximum='maximum'
            :value='value3'
            cornerRadius='Round'
            :trackThickness='trackThickness'
            :progressThickness='progressThickness'
            :animation="animation"
            :load='load'
            >
            <e-progressbar-annotations>
              <e-progressbar-annotation
                :content="content3"
              ></e-progressbar-annotation>
            </e-progressbar-annotations>
            </ejs-progressbar>  
            </div>
          </div>
        </div>
        <div class="col-lg-3 col-md-3 col-3 progress-container">
          <div class="progress-container-align">
             <div id="semi-container">
           <ejs-progressbar
            ref="semi"
            id="semi-progress"
            type='Circular'
            :startAngle='startAngle4'
            :endAngle='endAngle4'
            :minimum='minimum'
            width='160px'
            height='160px'
            :maximum='maximum'
            :value='value4'
            cornerRadius='Round'
            :trackThickness='trackThickness'
            :progressThickness='progressThickness'
            :animation="animation"
            :load='load'
            >
             <e-progressbar-annotations>
              <e-progressbar-annotation
                :content="content4"
              ></e-progressbar-annotation>
            </e-progressbar-annotations>
            </ejs-progressbar>  
             </div>
          </div>
       </div>
     </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-12 reload-btn">
            <button id="reLoad" class="e-control e-btn e-lib e-outline e-primary" @click="onclick">Reload</button>
        </div>
    </div>
 <div id="action-description">
      <p>This sample illustrates a circular progress bar with start and end angle customized.</p>
    </div>
    <div id="description">
      <p> This demo for Essential JS2 Progress Bar control shows the customizing options for angle in circular progress bar. Annotation is enabled in the sample to represent the progress value with animation.</p>
    </div>
  </div>
</template>
<style scoped>
  #control-container {
        padding: 0px !important;
    }
    .annotaion-pro {
            font-family: Roboto-Regular;
            font-size: 20px;
            color: #1B1C1A;
            letter-spacing: 0.01px;
        }
        .progress-bar-parent {
            margin-top: 8%;
            text-align: center;
        }
        .progress-text {
            display: inline-flex;
            margin: auto;
        }
        .progress-text-align {
            font-family: Roboto-Regular;
            font-size: 12px;
            color: #3D3E3C;
            letter-spacing: 0;
            margin: auto;
        }

        #control-container {
            padding: 0px !important;
        }

        .progress-container-align {
            text-align: center;
        }

        .reload-btn {
            text-align: center;
             margin-top:6%;
        }

        #reLoad {
            border-radius: 4px;
            text-transform: capitalize;
        }

</style>
<script>
import {
  ProgressBarComponent,
  ProgressAnnotation,
  ProgressBarAnnotationsDirective,
  ProgressBarAnnotationDirective
} from "@syncfusion/ej2-vue-progressbar";
import { loadProgressBarTheme } from "./theme-color";
 function annotationElementContent(color, controlID) {
        let content;
        switch (controlID) {
            case 'angle-container':
                content = '100%';
                break;
            case 'vertical-container':
                content = '100%';
                break;
            case 'semi-container':
                content = '100%';
                break;
            case 'vsemi-container':
                content = '100%';
                break;
        }
        return ('<div id="point1" style="font-size:24px;font-weight:bold;color: ' + color + ' "><span>' + content + '</span></div>');
    }
    let annotationColors = ['#e91e63', '#0078D6', '#317ab9', '#007bff', '#4F46E5', '#FFD939', '#9A9A9A', '#22D3EE', '#0D6EFD', '#6750A4', '#D0BCFF', '#0F6CBD', '#1AEBFF', '#115EA3', '#6366F1'];

export default {
  components: {
    'ejs-progressbar': ProgressBarComponent,
    'e-progressbar-annotations':  ProgressBarAnnotationsDirective,
    'e-progressbar-annotation':  ProgressBarAnnotationDirective
  },
  data: function() {
    return {
      startAngle1:240,
      endAngle1:120,
      value1:100,
      startAngle2:180,
      endAngle2:0,
      value2:100,
      startAngle3:0,
      endAngle3:180,
      value3:100,
      startAngle4:270,
      endAngle4:90,
      value4:100,
      minimum:0,
      maximum:100,
      trackThickness:5,
      progressThickness:5,
      cornerRadius: 'Round',
       animation: {
        enable: true,
        duration: 2000,
        delay: 0
      },
      angle1:310,
      angle2:340,
      angle3:330,
      content1: '<div id="point1" style="font-size:35px;font-weight:bold;color:#0078D6;fill:#0078D6"><span>100%</span></div>',
      content2: '<div id="point1" style="font-size:35px;font-weight:bold;color:#0078D6;fill:#0078D6"><span>100%</span></div>',
      content3: '<div id="point1" style="font-size:35px;font-weight:bold;color:#0078D6;fill:#0078D6"><span>100%</span></div>',
      content4: '<div id="point1" style="font-size:35px;font-weight:bold;color:#0078D6;fill:#0078D6"><span>100%</span></div>',
     };
  },
  provide: {
    progressbar: [ProgressAnnotation]
  },
  methods: {
     onclick: function() {
      this.$refs.angle.ej2Instances.refresh();
      this.$refs.vertical.ej2Instances.refresh();
       this.$refs.vsemi.ej2Instances.refresh();
      this.$refs.semi.ej2Instances.refresh();
     },
     load: function(args) {
        loadProgressBarTheme(args);
        switch (args.progressBar.theme) {
            case 'Material':
                args.progressBar.annotations[0].content = annotationElementContent(annotationColors[0], args.progressBar.element.id);
                break;
            case 'Fabric':
                args.progressBar.annotations[0].content = annotationElementContent(annotationColors[1], args.progressBar.element.id);
                break;
            case 'Bootstrap':
                args.progressBar.annotations[0].content = annotationElementContent(annotationColors[2], args.progressBar.element.id);
                break;
            case 'Bootstrap4':
                args.progressBar.annotations[0].content = annotationElementContent(annotationColors[3], args.progressBar.element.id);
                break;
            case 'Tailwind':
            case 'Tailwind3':
                args.progressBar.annotations[0].content = annotationElementContent(annotationColors[4], args.progressBar.element.id);
                break;
            case 'BootstrapDark':
            case 'FabricDark':
            case 'MaterialDark':
                args.progressBar.annotations[0].content = annotationElementContent(annotationColors[6], args.progressBar.element.id);
                break;
            case 'Bootstrap5':
            case 'Bootstrap5Dark':
            case 'Fluent':
            case 'FluentDark':
                args.progressBar.annotations[0].content = annotationElementContent(annotationColors[8], args.progressBar.element.id);
                break;
            case 'Tailwind3Dark':
                args.progressBar.annotations[0].content = annotationElementContent(annotationColors[14], args.progressBar.element.id);
                break;
            case 'TailwindDark':
                args.progressBar.annotations[0].content = annotationElementContent(annotationColors[7], args.progressBar.element.id);
                break;
            case 'Material3':
                args.progressBar.annotations[0].content = annotationElementContent(annotationColors[9], args.progressBar.element.id);
                break;
            case 'Material3Dark':
                args.progressBar.annotations[0].content = annotationElementContent(annotationColors[10], args.progressBar.element.id);
                break;
            case "Fluent2":
                args.progressBar.annotations[0].content = annotationElementContent(annotationColors[11], args.progressBar.element.id);
                break;
            case "Fluent2Dark":
                args.progressBar.annotations[0].content = annotationElementContent(annotationColors[13], args.progressBar.element.id);
                break;
            case "Fluent2HighContrast":
                args.progressBar.annotations[0].content = annotationElementContent(annotationColors[12], args.progressBar.element.id);
                break;
            default:
                args.progressBar.annotations[0].content = annotationElementContent(annotationColors[5], args.progressBar.element.id);
                break;
          }
      }
  }
}
</script>
