// syncfusionejs2_trial/Samples/Vue/src/maps/sales-map.vue
<template>
  <main><div>
     <div class="control-section">
          <ejs-maps
            id="container"
            :load="load"
            :titleSettings="titleSettings"
            :zoomSettings="zoomSettings"
            :useGroupingSeparator="useGroupingSeparator"
            :tooltipDisplayMode='tooltipDisplayMode'
            format="n"
          >
            <e-layers>
              <e-layer
                :shapeData="shapeData"
                :dataSource="dataSource"
                :shapeSettings="shapeSettings"
                :markerClusterSettings="markerClusterSettings"
                :markerSettings="markerSettings"
              ></e-layer>
            </e-layers>
          </ejs-maps>
          <div style="float: right; margin-right: 10px;">
            Source:
            <a
              href="http://www.citymayors.com/statistics/largest-cities-population-125.html"
              target="_blank"
              >www.citymayors.com</a
            >
          </div>
        </div>
    </div>
    <section id="action-description" aria-label="Description of Maps sample">
      <p>
        This sample illustrates the sales details of the products and users location by rendering the markers. Marker clustering is also enabled in this sample.
      </p>
    </section>
    <section id="description" aria-label="Description of the Maps features demonstrated in this sample">
      <p>
        In this example, you can see how to render cluster for more number of markers if it is at the exact latitude and longitude values. On clicking the cluster, it will gets expanded. 
      </p>
      <p>
      Tooltip is enabled in this example. To see the tooltip in action, click the mouse over the marker or tap a marker in touch-enabled devices.
      </p>
      <p style="font-weight: 500">Injecting Module</p>
      <p>
     Maps component features are segregated into individual feature-wise modules. To use a marker and cluster, inject the <code>Marker</code> module using the <code>Maps.Inject(Marker)</code> method.
      </p>
    </section>
    </main>
</template>
<script>
import Vue from "vue";
import {
  MapsComponent,
  LayersDirective,
  LayerDirective,
  Marker,
  MapsTooltip,
  Zoom
} from "@syncfusion/ej2-vue-maps";
import { salesmapdata } from "../maps/map-data/marker-location";
import { worldMap } from '../maps/map-data/world-map';

export default {
  components: {
    'ejs-maps': MapsComponent,
    'e-layers': LayersDirective,
    'e-layer': LayerDirective
  },
  data: function() {
    return {
      useGroupingSeparator: true,
      zoomSettings: {
        enable: true,
                  mouseWheelZoom: false,
            pinchZooming: false
      },
      titleSettings: {
        text: 'Sales details of products in various countries',
        textStyle: {
          size: "16px",
          fontFamily: 'Segoe UI'
        }
      },
      shapeData: worldMap,
      dataSource: salesmapdata,
      shapeSettings: {
        fill: "#C3E6ED",
      },
      tooltipDisplayMode: 'Click',
       markerClusterSettings: {
            allowClustering: true,
            allowClusterExpand: true,
            shape: 'Image',
            height: 40,
            width: 40,
            labelStyle : { color: 'white'},
            imageUrl: 'src/maps/images/cluster.svg'
        },
      markerSettings: [
        {
           visible: true,
            dataSource: salesmapdata,
            shape: 'Image',
            imageUrl: 'src/maps/images/ballon.png',
            tooltipSettings: {
                format:  '<b>Name</b> : ${name}<br><b>Product</b> : ${product}<br><b>Total value</b> : ${worth}',
                visible: true,
                valuePath: 'area',
                textStyle: {
                    fontFamily: 'Segoe UI'
                }
            },
            height: 15,
            width: 15,
            animationDuration: 0
        }
      ]
    };
  },
  provide: {
    maps: [Marker, MapsTooltip, Zoom]
  },
  /* custom code start */
  methods: {
    load: function(args) {
      let selectedTheme = location.hash.split("/")[1];
      selectedTheme = selectedTheme ? selectedTheme : "Material";
      args.maps.theme =
        (selectedTheme.charAt(0).toUpperCase() +
            selectedTheme.slice(1)).replace(/-dark/i, 'Dark').replace(/-high/i, 'High').replace(/contrast/i, 'Contrast').replace(/5.3/i, '5');
    }
  }
  /* custom code end */
};
</script>

// syncfusionejs2_trial/Samples/Angular/source/maps/sales-map.component.ts
/**
 * Zoom Marker Sample
 */
import { Component, ViewEncapsulation, Inject, ViewChild } from '@angular/core';
import { MapsTheme, Maps, Marker, MapsTooltip, ILoadEventArgs, Zoom, MapsModule } from '@syncfusion/ej2-angular-maps';
import { salesMap } from './marker-location';
import { SBDescriptionComponent } from '../common/dp.component';
import { SBActionDescriptionComponent } from '../common/adp.component';
Maps.Inject(Marker, MapsTooltip, Zoom);
declare var require: any;
let worlMap: object[] = require('./world-map.json');
let population: object[] = require('./sales-map.json');
@Component({
    selector: 'control-content',
    templateUrl: 'sales-map.html',
    encapsulation: ViewEncapsulation.None,
    standalone: true,
    imports: [SBActionDescriptionComponent, MapsModule, SBDescriptionComponent]
})
export class MapsSalesMapComponent {
  @ViewChild('maps')
  public maps: Maps;
  // custom code start
  public load = (args: ILoadEventArgs) => {
    let theme: string = location.hash.split('/')[1];
    theme = theme ? theme : 'Material';
    args.maps.theme = <MapsTheme>(theme.charAt(0).toUpperCase() +
    theme.slice(1)).replace(/-dark/i, 'Dark').replace(/contrast/i, 'Contrast').replace(/-high/i, 'High').replace(/5.3/i, '5');
  }
  // custom code end
  public zoomSettings: object = {
    enable: true,
    mouseWheelZoom: false,
    pinchZooming: false
  };
  public titleSettings: object = {
    text: 'Sales details of products in various countries',
    titleStyle: { size: '16px' }
  };
  public layers: object[] = [{
    shapeData: worlMap,
    dataSource: population,
    shapeSettings: {
      fill: '#C1DFF5'
    },
    markerClusterSettings: {
        allowClustering: true,
        allowClusterExpand: true,
        shape: 'Image',
        height: 40,
        width: 40,
        labelStyle: { color: 'white' },
        imageUrl: 'https://ej2.syncfusion.com/angular/demos/assets/maps/images/cluster.svg'
    },
    markerSettings: [{
      dataSource: salesMap,
      visible: true,
      animationDuration: 0,
      height: 15,
      width: 15,
      shape: 'Image',
      imageUrl: 'https://ej2.syncfusion.com/demos/src/maps/images/ballon.png',
      tooltipSettings: {
        format: '<b>Name</b> : ${name}<br><b>Product</b> : ${product}<br><b>Total value</b> : ${worth}',
        visible: true,
        valuePath: 'name',
      }
    }]
  }];
  // custom code start
  constructor(@Inject('sourceFiles') private sourceFiles: any) {
    sourceFiles.files = ['sales-map.json', 'world-map.json'];
  };
  // custom code end
}
