// syncfusionejs2_trial/Samples/React/src/sankey/print-export.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
Object.defineProperty(exports, "__esModule", { value: true });
/** Print & Export sample for Sankey */
var React = require("react");
var ej2_react_charts_1 = require("@syncfusion/ej2-react-charts");
var ej2_react_dropdowns_1 = require("@syncfusion/ej2-react-dropdowns");
var theme_color_1 = require("./theme-color");
var base_1 = require("@syncfusion/ej2/base");
var SAMPLE_CSS = "\n  .control-fluid { padding: 0 !important; }\n  #sankey-print-export { text-align: center; }\n  .e-export-icon::before { content: '\\e728'; }\n  .e-print-icon::before  { content: '\\e75d'; }\n  .e-view.tailwind .e-print-icon::before,\n  .e-view.tailwind-dark .e-print-icon::before,\n  .e-view.tailwind3 .e-print-icon::before,\n  .e-view.tailwind3-dark .e-print-icon::before { content: '\\e75d'; }\n  .e-view.tailwind3 .e-export-icon::before,\n  .e-view.tailwind3-dark .e-export-icon::before { content: '\\e7bf'; }\n  .e-view.fluent .e-export-icon::before,\n  .e-view.fluent-dark .e-export-icon::before,\n  .e-view.fluent2 .e-export-icon::before,\n  .e-view.fluent2-dark .e-export-icon::before,\n  .e-view.fluent2-highcontrast .e-export-icon::before,\n  .e-view.material3 .e-export-icon::before,\n  .e-view.material3-dark .e-export-icon::before,\n  .e-view.bootstrap5_3 .e-export-icon::before,\n  .e-view.bootstrap5_3-dark .e-export-icon::before { content: '\\e72e'; }\n  .e-view.fluent .e-print-icon::before,\n  .e-view.fluent-dark .e-print-icon::before,\n  .e-view.fluent2 .e-print-icon::before,\n  .e-view.fluent2-dark .e-print-icon::before,\n  .e-view.fluent2-highcontrast .e-print-icon::before,\n  .e-view.material3 .e-print-icon::before,\n  .e-view.material3-dark .e-print-icon::before,\n  .e-view.bootstrap5_3 .e-print-icon::before,\n  .e-view.bootstrap5_3-dark .e-print-icon::before { content: '\\e75d'; }\n\n  .chart-toolbar {\n    display: flex;\n    justify-content: flex-end;\n    align-items: center;\n    gap: 10px;\n    padding: 6px 0;\n  }\n  .toolbar-btn {\n    display: inline-flex;\n    align-items: center;\n    gap: 6px;\n    border-radius: 4px;\n    font-weight: 600;\n    letter-spacing: .3px;\n    padding: 6px 14px;\n    cursor: pointer;\n    border: 1px solid transparent;\n    outline: none;\n    transition: all 0.2s ease;\n  }\n  .toolbar-btn--print {\n    background-color: #FFFFFF !important;\n    color: #000000DE !important;\n    border: 1px solid #D1D5DB !important;\n  }\n  .toolbar-btn--print:hover { background-color: #F3F4F6 !important; }\n  .toolbar-btn--print:focus,\n  .toolbar-btn--print:focus-visible {\n    outline: 2px solid #E3165B;\n    outline-offset: 2px;\n  }\n  .toolbar-btn--export {\n    background-color: #E3165B !important;\n    color: #FFFFFF !important;\n    border: 1px solid #E3165B !important;\n  }\n  .toolbar-btn--export:hover { background-color: #C4134F !important; }\n  .toolbar-btn--export:focus,\n  .toolbar-btn--export:focus-visible {\n    outline: 2px solid #E3165B;\n    outline-offset: 2px;\n  }\n\n  .chart-shell {\n    display: flex;\n    flex-direction: row;\n    align-items: stretch;\n    width: 100%;\n    overflow: hidden;\n    border: 1px solid #E5E7EB;\n    border-radius: 4px;\n  }\n  .chart-shell.mobile-panel-open .export-panel {\n    flex: 0 0 100% !important;\n    width: 100% !important;\n    border-left: none !important;\n    box-shadow: none !important;\n  }\n  .chart-host {\n    flex: 1 1 auto;\n    min-width: 0;\n    transition: flex-basis .25s ease-out;\n  }\n\n  .export-panel {\n    flex: 0 0 0px;\n    overflow: hidden;\n    background: transparent;\n    border-left: 0px solid #E5E7EB;\n    transition: flex-basis .25s ease-out, border-left .25s ease-out;\n    display: flex;\n    flex-direction: column;\n    box-sizing: border-box;\n  }\n  .with-panel .export-panel {\n    flex: 0 0 300px;\n    border-left: 1px solid #E5E7EB;\n    box-shadow: -2px 0 8px rgba(0,0,0,.07);\n    overflow: visible;\n  }\n\n  .panel-header {\n    display: flex;\n    align-items: center;\n    justify-content: space-between;\n    padding: 14px 16px 10px 16px;\n    border-bottom: 1px solid #E5E7EB;\n    white-space: nowrap;\n  }\n  .panel-header-left { display: flex; align-items: center; gap: 8px; }\n  .panel-header-icon { font-size: 16px; }\n  .panel-title { font-size: 15px; font-weight: 600; }\n  .panel-close {\n    background: transparent;\n    border: none;\n    cursor: pointer;\n    padding: 2px 4px;\n    color: #6B7280;\n    font-size: 16px;\n    display: flex;\n    align-items: center;\n    outline: none;\n    transition: all 0.2s ease;\n  }\n  .panel-close:hover { color: #111827; }\n  .panel-close:focus,\n  .panel-close:focus-visible {\n    outline: 2px solid #E3165B;\n    outline-offset: 2px;\n  }\n\n  .panel-body {\n    display: flex;\n    flex-direction: column;\n    gap: 8px;\n    padding: 16px 16px 0 16px;\n    white-space: nowrap;\n  }\n  .panel-label { font-size: 12px; margin-bottom: 2px; }\n\n  .panel-input {\n    width: 100%;\n    box-sizing: border-box;\n    border: none !important;\n    border-bottom: 1px solid #9CA3AF !important;\n    border-radius: 0 !important;\n    outline: none !important;\n    padding: 4px 0 6px 0;\n    background: transparent;\n    font-size: 14px;\n    color: inherit;\n  }\n  .panel-input:focus { border-bottom: 2px solid #E3165B !important; }\n\n  .export-panel .e-ddl.e-input-group,\n  .export-panel .e-ddl.e-input-group.e-control-wrapper {\n    border: none !important;\n    border-bottom: 1px solid #9CA3AF !important;\n    border-radius: 0 !important;\n    box-shadow: none !important;\n    background: transparent !important;\n  }\n  .export-panel .e-ddl.e-input-group:focus-within,\n  .export-panel .e-ddl.e-input-group.e-control-wrapper:focus-within {\n    border-bottom: 2px solid #E3165B !important;\n  }\n  .export-panel .e-input-group::before,\n  .export-panel .e-input-group::after { display: none !important; }\n\n  .panel-footer {\n    display: flex;\n    justify-content: space-between;\n    gap: 10px;\n    padding-top: 20px;\n    border-top: 0px !important\n  }\n  .panel-action-btn {\n    flex: 1;\n    background: transparent !important;\n    border: none !important;\n    font-weight: 600;\n    font-size: 15px;\n    letter-spacing: .5px;\n    padding: 6px 0;\n    cursor: pointer;\n    border-radius: 0;\n    outline: none;\n    transition: all 0.2s ease;\n  }\n  .panel-action-btn:focus,\n  .panel-action-btn:focus-visible {\n    outline: 2px solid #E3165B;\n    outline-offset: 2px;\n  }\n  .btn-text {\n    padding: 0;\n    display: inline;\n    line-height: 20px; \n  }\n  .panel-action-btn--export { color: #E3165B !important; }\n  .panel-action-btn--export:hover { color: #C4134F !important; }\n  .panel-action-btn--cancel { color: #6B7280 !important; }\n  .panel-action-btn--cancel:hover { color: #111827 !important; }\n";
var nodes = [
    { id: 'Books' },
    { id: 'Clothing' },
    { id: 'Electronics' },
    { id: 'Furniture' },
    { id: 'Jewelry' },
    { id: 'Toys' },
    { id: 'Air' },
    { id: 'Ground' },
    { id: 'Sea' },
    { id: 'Asia' },
    { id: 'Europe' },
    { id: 'North America' },
    { id: 'South America' },
    { id: 'Delayed' },
    { id: 'Delivered' },
    { id: 'In Transit' }
];
var links = [
    { sourceId: 'Books', targetId: 'Air', value: 18 },
    { sourceId: 'Books', targetId: 'Ground', value: 12 },
    { sourceId: 'Clothing', targetId: 'Air', value: 25 },
    { sourceId: 'Clothing', targetId: 'Ground', value: 15 },
    { sourceId: 'Clothing', targetId: 'Sea', value: 20 },
    { sourceId: 'Electronics', targetId: 'Air', value: 35 },
    { sourceId: 'Electronics', targetId: 'Ground', value: 22 },
    { sourceId: 'Electronics', targetId: 'Sea', value: 18 },
    { sourceId: 'Furniture', targetId: 'Ground', value: 28 },
    { sourceId: 'Furniture', targetId: 'Sea', value: 25 },
    { sourceId: 'Jewelry', targetId: 'Air', value: 12 },
    { sourceId: 'Jewelry', targetId: 'Ground', value: 8 },
    { sourceId: 'Toys', targetId: 'Ground', value: 15 },
    { sourceId: 'Toys', targetId: 'Sea', value: 22 },
    { sourceId: 'Air', targetId: 'Asia', value: 40 },
    { sourceId: 'Air', targetId: 'Europe', value: 30 },
    { sourceId: 'Air', targetId: 'North America', value: 20 },
    { sourceId: 'Ground', targetId: 'Europe', value: 35 },
    { sourceId: 'Ground', targetId: 'North America', value: 30 },
    { sourceId: 'Ground', targetId: 'South America', value: 15 },
    { sourceId: 'Ground', targetId: 'Asia', value: 20 },
    { sourceId: 'Sea', targetId: 'Asia', value: 25 },
    { sourceId: 'Sea', targetId: 'Europe', value: 15 },
    { sourceId: 'Sea', targetId: 'North America', value: 30 },
    { sourceId: 'Sea', targetId: 'South America', value: 15 },
    { sourceId: 'Asia', targetId: 'Delayed', value: 35 },
    { sourceId: 'Asia', targetId: 'Delivered', value: 40 },
    { sourceId: 'Asia', targetId: 'In Transit', value: 10 },
    { sourceId: 'Europe', targetId: 'Delivered', value: 65 },
    { sourceId: 'Europe', targetId: 'In Transit', value: 15 },
    { sourceId: 'North America', targetId: 'Delivered', value: 50 },
    { sourceId: 'North America', targetId: 'In Transit', value: 30 },
    { sourceId: 'South America', targetId: 'Delayed', value: 10 },
    { sourceId: 'South America', targetId: 'In Transit', value: 20 }
];
var PrintExport = /** @class */ (function (_super) {
    __extends(PrintExport, _super);
    function PrintExport(props) {
        var _this = _super.call(this, props) || this;
        _this.sankeyRef = React.createRef();
        _this.formatRef = React.createRef();
        _this.fileName = 'Sankey';
        _this.chartShellRef = React.createRef();
        _this.chartHostRef = React.createRef();
        _this.exportPanelRef = React.createRef();
        _this.fileNameInputRef = React.createRef();
        _this.resizeObserver = null;
        _this.originalSvgWidth = null;
        _this.refreshChart = function () {
            var _a;
            var sankey = _this.sankeyRef.current;
            if (!sankey)
                return;
            var animation = sankey.animation;
            if (animation) {
                animation.enable = false;
            }
            (_a = sankey.refresh) === null || _a === void 0 ? void 0 : _a.call(sankey);
            if (animation) {
                animation.enable = true;
            }
        };
        _this.handlePanelKeydown = function (event) {
            if (event.key === 'Escape') {
                event.preventDefault();
                _this.setState({ isPanelOpen: false });
            }
        };
        _this.load = function (args) {
            (0, theme_color_1.loadSankeyChartTheme)(args);
        };
        _this.onLoaded = function () {
            var element = document.getElementById('sankey-print-export');
            if (element)
                element.setAttribute('title', '');
            setTimeout(function () { return _this.resizeSankeySvg(); }, 0);
        };
        _this.getSankeySvg = function () {
            var _a;
            var byId = document.getElementById('sankey-print-export_svg');
            if (byId instanceof SVGSVGElement)
                return byId;
            var root = (_a = _this.sankeyRef.current) === null || _a === void 0 ? void 0 : _a.element;
            if (root) {
                var inside = root.querySelector('svg');
                if (inside instanceof SVGSVGElement)
                    return inside;
            }
            var bySelector = document.querySelector('svg#sankey-print-export_svg');
            if (bySelector instanceof SVGSVGElement)
                return bySelector;
            return null;
        };
        _this.resizeSankeySvg = function () {
            var svg = _this.getSankeySvg();
            var host = _this.chartHostRef.current;
            if (!svg || !host)
                return;
            var newWidth = host.offsetWidth;
            if (!newWidth)
                return;
            var heightAttribute = svg.getAttribute('height');
            var svgHeight = heightAttribute
                ? Math.max(1, parseFloat(heightAttribute))
                : Math.max(1, svg.getBoundingClientRect().height);
            svg.setAttribute('width', String(newWidth));
            svg.setAttribute('viewBox', "0 0 ".concat(newWidth, " ").concat(svgHeight));
            svg.setAttribute('preserveAspectRatio', 'xMidYMid meet');
            var sankeyHost = document.getElementById('sankey-print-export');
            if (sankeyHost)
                sankeyHost.style.width = "".concat(newWidth, "px");
        };
        _this.handleExport = function () {
            var _a;
            var type = (((_a = _this.formatRef.current) === null || _a === void 0 ? void 0 : _a.value) || 'JPEG');
            var name = (_this.fileName || 'Sankey').trim();
            var doExport = function () {
                var _a, _b;
                var el = (_a = _this.sankeyRef.current) === null || _a === void 0 ? void 0 : _a.element;
                var rect = el === null || el === void 0 ? void 0 : el.getBoundingClientRect();
                var scale = Math.max(2, Math.min(3, window.devicePixelRatio || 1));
                var exportW = rect ? Math.round(rect.width * scale) : undefined;
                var exportH = rect ? Math.round(rect.height * scale) : undefined;
                (_b = _this.sankeyRef.current) === null || _b === void 0 ? void 0 : _b.export(type, name);
            };
            if (base_1.Browser.isDevice && _this.state.isPanelOpen) {
                _this.setState({ isPanelOpen: false }, function () {
                    requestAnimationFrame(function () {
                        _this.resizeSankeySvg();
                        doExport();
                    });
                });
                return;
            }
            _this.resizeSankeySvg();
            doExport();
            _this.setState({ isPanelOpen: false });
        };
        _this.handlePrint = function () {
            var _a;
            (_a = _this.sankeyRef.current) === null || _a === void 0 ? void 0 : _a.print();
        };
        _this.openPanel = function () { return _this.setState({ isPanelOpen: true }); };
        _this.closePanel = function () { return _this.setState({ isPanelOpen: false }); };
        _this.state = { isPanelOpen: false };
        return _this;
    }
    PrintExport.prototype.componentDidMount = function () {
        var _this = this;
        if (this.chartHostRef.current && 'ResizeObserver' in window) {
            this.resizeObserver = new ResizeObserver(function () { return _this.resizeSankeySvg(); });
            this.resizeObserver.observe(this.chartHostRef.current);
        }
    };
    PrintExport.prototype.componentWillUnmount = function () {
        if (this.resizeObserver && this.chartHostRef.current) {
            this.resizeObserver.unobserve(this.chartHostRef.current);
        }
        this.resizeObserver = null;
        document.removeEventListener('keydown', this.handlePanelKeydown);
    };
    PrintExport.prototype.componentDidUpdate = function (prevProps, prevState) {
        var _this = this;
        var panel = this.exportPanelRef.current;
        if (!panel)
            return;
        if (this.state.isPanelOpen) {
            panel.removeAttribute('inert');
            document.addEventListener('keydown', this.handlePanelKeydown);
            requestAnimationFrame(function () {
                var _a;
                (_a = _this.fileNameInputRef.current) === null || _a === void 0 ? void 0 : _a.focus();
            });
            setTimeout(function () {
                _this.resizeSankeySvg();
                _this.refreshChart();
            }, 250);
        }
        else {
            panel.setAttribute('inert', '');
            document.removeEventListener('keydown', this.handlePanelKeydown);
            var exportButton = document.querySelector('.toolbar-btn--export');
            exportButton === null || exportButton === void 0 ? void 0 : exportButton.focus();
            setTimeout(function () {
                _this.resizeSankeySvg();
                _this.refreshChart();
            }, 250);
        }
    };
    PrintExport.prototype.render = function () {
        var _this = this;
        var isPanelOpen = this.state.isPanelOpen;
        return (React.createElement("div", { className: "control-pane" },
            React.createElement("style", null, SAMPLE_CSS),
            React.createElement("div", { className: "chart-toolbar", role: "toolbar", "aria-label": "Chart actions" },
                React.createElement("button", { className: "toolbar-btn toolbar-btn--print", onClick: this.handlePrint, onKeyDown: function (e) {
                        if (e.key === 'Enter') {
                            e.preventDefault();
                            _this.handlePrint();
                        }
                    } },
                    React.createElement("span", { className: "e-icons e-print-icon" }),
                    React.createElement("span", { className: "btn-text" }, "PRINT")),
                React.createElement("button", { className: "toolbar-btn toolbar-btn--export", onClick: this.openPanel, onKeyDown: function (e) {
                        if (e.key === 'Enter') {
                            e.preventDefault();
                            _this.openPanel();
                        }
                    } },
                    React.createElement("span", { className: "e-icons e-export-icon" }),
                    React.createElement("span", { className: "btn-text" }, "EXPORT"))),
            React.createElement("div", { id: "chartShell", ref: this.chartShellRef, className: "chart-shell ".concat(isPanelOpen ? 'with-panel' : '', " ").concat(base_1.Browser.isDevice && isPanelOpen ? 'mobile-panel-open' : '') },
                React.createElement("div", { id: "chartHost", ref: this.chartHostRef, className: "chart-host", style: { display: base_1.Browser.isDevice && isPanelOpen ? 'none' : undefined } },
                    React.createElement(ej2_react_charts_1.SankeyComponent, { id: "sankey-print-export", ref: this.sankeyRef, width: "95%", height: "450", title: "Supply Chain Management", subTitle: "Source: OECD\u2011ITF Global Freight Data", enableRtl: false, orientation: "Horizontal", background: "transparent", margin: { left: 20, right: 20, top: 20, bottom: 20 }, border: { color: '#E0E0E0', width: 0 }, linkStyle: { opacity: 0.4, curvature: 0.5, colorType: 'Source' }, labelSettings: { visible: base_1.Browser.isDevice ? false : true }, tooltip: {
                            enable: true,
                            nodeTemplate: '${name}: ${value}k shipments',
                            linkTemplate: base_1.Browser.isDevice ? '${start.name}: ${start.out}k → <br/> ${target.name}: ${target.in}k shipments' : '${start.name}: ${start.out}k → ${target.name}: ${target.in}k shipments'
                        }, legendSettings: { visible: true }, load: this.load, loaded: this.onLoaded },
                        React.createElement(ej2_react_charts_1.Inject, { services: [ej2_react_charts_1.SankeyTooltip, ej2_react_charts_1.SankeyLegend, ej2_react_charts_1.SankeyHighlight, ej2_react_charts_1.SankeyExport] }),
                        React.createElement(ej2_react_charts_1.SankeyNodesCollectionDirective, null, nodes.map(function (node) { return React.createElement(ej2_react_charts_1.SankeyNodeDirective, { key: node.id, id: node.id, color: (node).color }); })),
                        React.createElement(ej2_react_charts_1.SankeyLinksCollectionDirective, null, links.map(function (link, i) { return React.createElement(ej2_react_charts_1.SankeyLinkDirective, __assign({ key: "".concat(link.sourceId, "-").concat(link.targetId, "-").concat(i) }, link)); })))),
                React.createElement("aside", { id: "exportPanel", ref: this.exportPanelRef, className: "export-panel", "aria-hidden": !isPanelOpen },
                    React.createElement("div", { className: "panel-header" },
                        React.createElement("span", { className: "panel-header-left" },
                            React.createElement("span", { className: "e-icons e-export-icon panel-header-icon" }),
                            React.createElement("span", { className: "panel-title" }, "Export")),
                        React.createElement("button", { className: "panel-close", "aria-label": "Close export panel", onClick: this.closePanel, onKeyDown: function (e) {
                                if (e.key === 'Enter') {
                                    e.preventDefault();
                                    _this.closePanel();
                                }
                            } },
                            React.createElement("span", { className: "e-icons e-close" }))),
                    React.createElement("div", { className: "panel-body" },
                        React.createElement("label", { className: "panel-label", htmlFor: "expFileName" }, "File Name:"),
                        React.createElement("input", { id: "expFileName", ref: this.fileNameInputRef, className: "panel-input", type: "text", defaultValue: this.fileName, placeholder: "Input Text", onChange: function (element) { _this.fileName = element.target.value; }, onKeyDown: function (e) {
                                if (e.key === 'Escape') {
                                    e.preventDefault();
                                    _this.closePanel();
                                }
                            } }),
                        React.createElement("label", { className: "panel-label", htmlFor: "fileTypeDropdown" }, "File Type:"),
                        React.createElement(ej2_react_dropdowns_1.DropDownListComponent, { id: "fileTypeDropdown", ref: this.formatRef, dataSource: ['JPEG', 'PNG', 'SVG', 'PDF'], value: 'JPEG', width: '100%' }),
                        React.createElement("div", { className: "panel-footer", style: { background: 'transparent' } },
                            React.createElement("button", { className: "panel-action-btn panel-action-btn--export", onClick: this.handleExport, onKeyDown: function (e) {
                                    if (e.key === 'Enter') {
                                        e.preventDefault();
                                        _this.handleExport();
                                    }
                                } }, "EXPORT"),
                            React.createElement("button", { className: "panel-action-btn panel-action-btn--cancel", onClick: this.closePanel, onKeyDown: function (e) {
                                    if (e.key === 'Enter') {
                                        e.preventDefault();
                                        _this.closePanel();
                                    }
                                } }, "CANCEL"))))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null, "Explore supply chain flows with a Sankey chart using illustrative values in thousand shipments (k). It maps product categories to transport modes, world regions, and delivery status. Use built\u2011in print and export options (JPEG, PNG, SVG, PDF) to share or download the chart.")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null, "This Sankey visualizes shipments (k) from product categories through Air, Ground, and Sea to regions and final status (Delivered, Delayed, In Transit). Hover or tap nodes and links to see precise shipment counts."),
                React.createElement("p", null,
                    React.createElement("strong", null, "Key features:")),
                React.createElement("ul", null,
                    React.createElement("li", null, "End\u2011to\u2011end flow from category \u2192 mode \u2192 region \u2192 status"),
                    React.createElement("li", null, "Export to JPEG, PNG, SVG, or PDF, and print directly"),
                    React.createElement("li", null, "Interactive tooltips showing values in thousand shipments")))));
    };
    return PrintExport;
}(React.Component));
exports.default = PrintExport;

// syncfusionejs2_trial/Samples/Vue/source/sankey/print-export.vue
<template>
  <div class="control-pane">
    <div class="control-section">
      <div class="chart-toolbar" role="toolbar" aria-label="Chart actions">
        <button id="btnPrint" class="toolbar-btn toolbar-btn--print" @click="printChart" @keydown.enter="printChart">
          <span class="e-icons e-print-icon"></span>
          <span class="btn-text">PRINT</span>
        </button>
        <button id="btnExport" class="toolbar-btn toolbar-btn--export" @click="openPanel" @keydown.enter="openPanel">
          <span class="e-icons e-export-icon"></span>
          <span class="btn-text">EXPORT</span>
        </button>
      </div>

      <div class="chart-shell" ref="chartShell"
        :class="{ 'with-panel': isPanelOpen, 'mobile-panel-open': isMobile && isPanelOpen }">
        <div class="chart-host" ref="chartHost" v-show="!isMobile || !isPanelOpen">
          <ejs-sankey ref="sankey" id="sankey-print-export" :width="width" :height="height" background="transparent"
            title="Supply Chain Management" subTitle="Source: OECD-ITF Global Freight Data" :load="load"
            :linkStyle="linkStyle" :labelSettings="labelSettings" :legendSettings="legendSettings" :tooltip="tooltip">
            <e-sankey-nodes>
              <!-- Product Categories -->
              <e-sankey-node id="Books" />
              <e-sankey-node id="Clothing" />
              <e-sankey-node id="Electronics" />
              <e-sankey-node id="Furniture" />
              <e-sankey-node id="Jewelry" />
              <e-sankey-node id="Toys" />

              <!-- Transport Modes -->
              <e-sankey-node id="Air" />
              <e-sankey-node id="Ground" />
              <e-sankey-node id="Sea" />

              <!-- Regions -->
              <e-sankey-node id="Asia" />
              <e-sankey-node id="Europe" />
              <e-sankey-node id="North America" />
              <e-sankey-node id="South America" />

              <!-- Delivery Status -->
              <e-sankey-node id="Delayed" />
              <e-sankey-node id="Delivered" />
              <e-sankey-node id="In Transit" />
            </e-sankey-nodes>

            <e-sankey-links>
              <!-- Category → Transport Mode -->
              <e-sankey-link source-id="Books" target-id="Air" :value="18" />
              <e-sankey-link source-id="Books" target-id="Ground" :value="12" />

              <e-sankey-link source-id="Clothing" target-id="Air" :value="25" />
              <e-sankey-link source-id="Clothing" target-id="Ground" :value="15" />
              <e-sankey-link source-id="Clothing" target-id="Sea" :value="20" />

              <e-sankey-link source-id="Electronics" target-id="Air" :value="35" />
              <e-sankey-link source-id="Electronics" target-id="Ground" :value="22" />
              <e-sankey-link source-id="Electronics" target-id="Sea" :value="18" />

              <e-sankey-link source-id="Furniture" target-id="Ground" :value="28" />
              <e-sankey-link source-id="Furniture" target-id="Sea" :value="25" />

              <e-sankey-link source-id="Jewelry" target-id="Air" :value="12" />
              <e-sankey-link source-id="Jewelry" target-id="Ground" :value="8" />

              <e-sankey-link source-id="Toys" target-id="Ground" :value="15" />
              <e-sankey-link source-id="Toys" target-id="Sea" :value="22" />

              <!-- Transport Mode → Region -->
              <e-sankey-link source-id="Air" target-id="Asia" :value="40" />
              <e-sankey-link source-id="Air" target-id="Europe" :value="30" />
              <e-sankey-link source-id="Air" target-id="North America" :value="20" />

              <e-sankey-link source-id="Ground" target-id="Asia" :value="20" />
              <e-sankey-link source-id="Ground" target-id="Europe" :value="35" />
              <e-sankey-link source-id="Ground" target-id="North America" :value="30" />
              <e-sankey-link source-id="Ground" target-id="South America" :value="15" />

              <e-sankey-link source-id="Sea" target-id="Asia" :value="25" />
              <e-sankey-link source-id="Sea" target-id="Europe" :value="15" />
              <e-sankey-link source-id="Sea" target-id="North America" :value="30" />
              <e-sankey-link source-id="Sea" target-id="South America" :value="15" />

              <!-- Region → Delivery Status -->
              <e-sankey-link source-id="Asia" target-id="Delayed" :value="35" />
              <e-sankey-link source-id="Asia" target-id="Delivered" :value="40" />
              <e-sankey-link source-id="Asia" target-id="In Transit" :value="10" />

              <e-sankey-link source-id="Europe" target-id="Delivered" :value="65" />
              <e-sankey-link source-id="Europe" target-id="In Transit" :value="15" />

              <e-sankey-link source-id="North America" target-id="Delivered" :value="50" />
              <e-sankey-link source-id="North America" target-id="In Transit" :value="30" />

              <e-sankey-link source-id="South America" target-id="Delayed" :value="10" />
              <e-sankey-link source-id="South America" target-id="In Transit" :value="20" />
            </e-sankey-links>
          </ejs-sankey>
        </div>

        <aside id="exportPanel" class="export-panel" :aria-hidden="!isPanelOpen" :class="{ open: isPanelOpen }">
          <div class="panel-header">
            <span class="panel-header-left">
              <span class="e-icons e-export-icon panel-header-icon"></span>
              <span class="panel-title">Export</span>
            </span>
            <button id="btnClosePanel" class="panel-close" aria-label="Close export panel" @click="closePanel"
              @keydown.enter="closePanel">
              <span class="e-icons e-close"></span>
            </button>
          </div>
          <div class="panel-body">
            <label class="panel-label" for="expFileName">File Name:</label>
            <input id="expFileName" class="panel-input" type="text" v-model.trim="fileName" placeholder="Input Text"
              @keydown.escape="closePanel" />

            <label class="panel-label" for="fileTypeDropdown">File Type:</label>
            <ejs-dropdownlist ref="exportType" id="fileTypeDropdown" :dataSource="exportTypes" :value="exportTypes[0]"
              :width="'100%'"></ejs-dropdownlist>

            <div class="panel-footer" style="background: transparent">
              <button id="btnDoExport" class="panel-action-btn panel-action-btn--export" @click="exportChart"
                @keydown.enter="exportChart">EXPORT</button>
              <button id="btnCancelExport" class="panel-action-btn panel-action-btn--cancel" @click="closePanel"
                @keydown.enter="closePanel">CANCEL</button>
            </div>
          </div>
        </aside>
      </div>
    </div>

    <div id="action-description">
      <p>
        Explore supply chain flows with a Sankey chart using illustrative values in thousand
        shipments (k). It maps product categories to transport modes, world regions, and delivery status.
        Use built‑in print and export options (JPEG, PNG, SVG, PDF) to share or download the chart.
      </p>
    </div>

    <div id="description">
      <p>
        This Sankey visualizes shipments (k) from product categories through Air, Ground, and Sea to regions and
        final status (Delivered, Delayed, In Transit).
        Hover or tap nodes and links to see precise shipment counts.
      </p>
      <p><strong>Key features:</strong></p>
      <ul>
        <li>End‑to‑end flow from category → mode → region → status</li>
        <li>Export to JPEG, PNG, SVG, or PDF, and print directly</li>
        <li>Interactive tooltips showing values in thousand shipments</li>
      </ul>
    </div>
  </div>
</template>

<script>
import {
  SankeyComponent,
  SankeyLegend,
  SankeyTooltip,
  SankeyExport,
  SankeyNodesCollectionDirective,
  SankeyNodeDirective,
  SankeyLinksCollectionDirective,
  SankeyLinkDirective,
} from "@syncfusion/ej2-vue-charts";
import { ButtonComponent } from "@syncfusion/ej2-vue-buttons";
import { loadSankeyChartTheme } from './theme-color';
import { DropDownListComponent } from "@syncfusion/ej2-vue-dropdowns";
import { Browser } from "@syncfusion/ej2-base";

export default {
  name: "SankeyPrintExport",

  components: {
    "ejs-sankey": SankeyComponent,
    "ejs-button": ButtonComponent,
    "ejs-dropdownlist": DropDownListComponent,
    "e-sankey-nodes": SankeyNodesCollectionDirective,
    "e-sankey-node": SankeyNodeDirective,
    "e-sankey-links": SankeyLinksCollectionDirective,
    "e-sankey-link": SankeyLinkDirective,
  },

  provide: {
    sankey: [SankeyLegend, SankeyTooltip, SankeyExport],
  },

  data() {
    return {
      width: "100%",
      height: "450px",
      linkStyle: { opacity: 0.4, curvature: 0.5, colorType: "Source" },
      labelSettings: {
        visible: Browser.isDevice ? false : true
      },
      legendSettings: {
        visible: Browser.isDevice ? false : true,
        position: 'Bottom'
      },
      tooltip: {
        enable: true,
        nodeTemplate: '${name}: ${value}k shipments',
        linkTemplate: '${start.name}: ${start.out}k → ${target.name}: ${target.in}k shipments'
      },
      exportTypes: ["JPEG", "PNG", "SVG", "PDF"],
      fileName: "Sankey",
      isPanelOpen: false,
      isMobile: Browser.isDevice,
    };
  },

  computed: {
  },

  methods: {
    load(args) {
      loadSankeyChartTheme(args);
    },

    togglePanel(open) {
      this.isPanelOpen = open;
      if (!open) {
        // Move focus back to Export button when closing panel
        const btnExport = document.getElementById('btnExport');
        if (btnExport) {
          btnExport.focus();
        }
        // Remove keyboard event listener when closing
        document.removeEventListener('keydown', this.handlePanelKeydown);
      } else {
        // Add keyboard event listener when opening
        document.addEventListener('keydown', this.handlePanelKeydown);
        // Focus filename input after panel opens
        this.$nextTick(() => {
          const fileNameInput = document.getElementById('expFileName');
          if (fileNameInput) {
            fileNameInput.focus();
          }
        });
      }
      if (this.isMobile) {
        this.$refs.chartHost.style.display = open ? 'none' : '';
      }
      setTimeout(() => {
        this.refreshChart();
      }, 250);
    },

    handlePanelKeydown(event) {
      // Close panel on Escape key
      if (event.key === 'Escape') {
        event.preventDefault();
        this.closePanel();
      }
    },

    refreshChart() {
      const sankey = this.$refs.sankey.ej2Instances;
      const animation = sankey.animation;
      animation.enable = false;
      sankey.refresh();
      animation.enable = true;
    },

    openPanel() {
      this.togglePanel(true);
    },

    closePanel() {
      this.togglePanel(false);
    },

    exportChart() {
      const type =
        this.$refs.exportType?.ej2Instances?.value || this.exportTypes[0] || "PNG";
      const name = (this.fileName || "Sankey").trim();
      this.$refs.sankey.ej2Instances.export(type, name);
      this.togglePanel(false);
    },

    printChart() {
      this.$refs.sankey.ej2Instances.print();
    }
  },


};
</script>

<style>
.control-section {
  overflow: visible !important;
}

.chart-toolbar {
  display: flex;
  justify-content: flex-end;
  align-items: center;
  gap: 10px;
  padding: 6px 0 6px 0;
}

.toolbar-btn {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  border-radius: 4px;
  font-weight: 600;
  letter-spacing: 0.3px;
  padding: 6px 14px;
  cursor: pointer;
  transition: all 0.2s ease;
  outline: none;
}

.toolbar-btn:focus {
  outline: 2px solid #e3165b;
  outline-offset: 2px;
}

.toolbar-btn--print {
  background-color: #ffffff !important;
  color: #000000de !important;
  border: 1px solid #d1d5db !important;
}

.toolbar-btn--print:hover {
  background-color: #f3f4f6 !important;
}

.toolbar-btn--print:focus {
  background-color: #f3f4f6 !important;
  box-shadow: inset 0 0 0 2px #e3165b;
}

.toolbar-btn--export {
  background-color: #e3165b !important;
  color: #ffffff !important;
  border: 1px solid #e3165b !important;
}

.toolbar-btn--export:hover {
  background-color: #c4134f !important;
}

.toolbar-btn--export:focus {
  background-color: #c4134f !important;
  outline: 2px solid #e3165b;
  outline-offset: 2px;
}

.chart-shell {
  display: flex;
  flex-direction: row;
  align-items: stretch;
  width: 100%;
  overflow: hidden;
  border: 1px solid #e5e7eb;
  border-radius: 4px;
}

.chart-shell.mobile-panel-open .export-panel {
  flex: 0 0 100% !important;
  width: 100% !important;
  border-left: none !important;
  box-shadow: none !important;
}

.chart-host {
  flex: 1 1 auto;
  min-width: 0;
  transition: flex-basis 0.25s ease-out;
}

.export-panel {
  flex: 0 0 0px;
  overflow: hidden;
  background: transparent;
  border-left: 0px solid #e5e7eb;
  transition: flex-basis 0.25s ease-out, border-left 0.25s ease-out;
  display: flex;
  flex-direction: column;
  box-sizing: border-box;
}

.with-panel .export-panel {
  flex: 0 0 300px;
  border-left: 1px solid #e5e7eb;
  overflow: visible;
}

.panel-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 14px 16px 10px 16px;
  border-bottom: 1px solid #e5e7eb;
  white-space: nowrap;
}

.panel-header-left {
  display: flex;
  align-items: center;
  gap: 8px;
}

.panel-header-icon {
  font-size: 16px;
}

.panel-title {
  font-size: 15px;
  font-weight: 600;
}

.panel-close {
  background: transparent;
  border: none;
  cursor: pointer;
  padding: 2px 4px;
  color: #6b7280;
  font-size: 16px;
  display: flex;
  align-items: center;
  border-radius: 2px;
  outline: none;
  transition: all 0.2s ease;
}

.panel-close:hover {
  color: #111827;
}

.panel-close:focus {
  outline: 2px solid #e3165b;
  outline-offset: 1px;
}

.panel-body {
  display: flex;
  flex-direction: column;
  gap: 8px;
  padding: 16px 16px 0 16px;
  white-space: nowrap;
}

.panel-label {
  font-size: 14px;
  margin-bottom: 2px;
}

.panel-input {
  width: 100%;
  box-sizing: border-box;
  border: none !important;
  border-radius: 0 !important;
  border-bottom: 1px solid #9ca3af !important;
  outline: none !important;
  padding: 4px 0 6px 0;
  background: transparent;
  font-size: 14px;
  color: inherit;
  transition: border-color 0.2s ease;
}

.panel-input:focus {
  border-bottom: 2px solid #e3165b !important;
  box-shadow: 0 1px 0 #e3165b;
}

.export-panel .e-ddl.e-input-group,
.export-panel .e-ddl.e-input-group.e-control-wrapper {
  border: none !important;
  border-radius: 0 !important;
  box-shadow: none !important;
  background: transparent !important;
}

.export-panel .e-ddl.e-input-group:focus-within,
.export-panel .e-ddl.e-input-group.e-control-wrapper:focus-within {
  box-shadow: none !important;
}

.export-panel .e-input-group::before,
.export-panel .e-input-group::after {
  display: none !important;
}

.panel-footer {
  display: flex;
  justify-content: space-between;
  gap: 10px;
  padding-top: 20px;
}

.panel-action-btn {
  flex: 1;
  background: transparent !important;
  border: none !important;
  font-size: 15px;
  letter-spacing: 0.5px;
  padding: 6px 0;
  cursor: pointer;
  border-radius: 2px;
  outline: none;
  transition: all 0.2s ease;
  position: relative;
}

.panel-action-btn:focus {
  outline: 2px solid #e3165b;
  outline-offset: 2px;
}

.panel-action-btn--export {
  color: #e3165b !important;
}

.panel-action-btn--export:hover {
  color: #c4134f !important;
}

.panel-action-btn--cancel {
  color: #6b7280 !important;
}

.panel-action-btn--cancel:hover {
  color: #111827 !important;
}

.e-print-icon::before {
  content: "\e75d";
}

.e-view.tailwind .e-print-icon::before,
.e-view.tailwind3 .e-print-icon::before,
.e-view.bootstrap5 .e-print-icon::before,
.e-view.bootstrap5-dark .e-print-icon::before,
.e-view.tailwind-dark .e-print-icon::before,
.e-view.tailwind3-dark .e-print-icon::before {
  content: "\e75d";
}

.e-view.fabric .e-print-icon::before,
.e-view.fabric-dark .e-print-icon::before {
  content: "\e7df";
}

.e-view.bootstrap .e-print-icon::before {
  content: "\ebd2";
}

.e-view.bootstrap4 .e-print-icon::before {
  content: "\e743";
}

.e-view.highcontrast .e-print-icon::before {
  content: "\ebf9";
}

.e-view.fluent .e-print-icon::before,
.e-view.fluent-dark .e-print-icon::before,
.e-view.fluent2 .e-print-icon::before,
.e-view.fluent2-dark .e-print-icon::before,
.e-view.fluent2-highcontrast .e-print-icon::before,
.e-view.material3 .e-print-icon::before,
.e-view.material3-dark .e-print-icon::before,
.e-view.bootstrap5\.3 .e-print-icon::before,
.e-view.bootstrap5\.3-dark .e-print-icon::before {
  content: "\e75d";
}

.e-export-icon::before {
  content: "\e72e";
}

.e-view.tailwind .e-export-icon::before,
.e-view.tailwind3 .e-export-icon::before,
.e-view.tailwind-dark .e-export-icon::before,
.e-view.tailwind3-dark .e-export-icon::before {
  content: "\e7bf";
}

.e-view.fluent .e-export-icon::before,
.e-view.fluent-dark .e-export-icon::before,
.e-view.fluent2 .e-export-icon::before,
.e-view.fluent2-dark .e-export-icon::before,
.e-view.fluent2-highcontrast .e-export-icon::before,
.e-view.material3 .e-export-icon::before,
.e-view.material3-dark .e-export-icon::before,
.e-view.bootstrap5 .e-export-icon::before,
.e-view.bootstrap5-dark .e-export-icon::before,
.e-view.bootstrap5\.3 .e-export-icon::before,
.e-view.bootstrap5\.3-dark .e-export-icon::before {
  content: "\e72e" !important;
}

@media print {
  @page {
    size: A4 landscape;
    margin: 0;
  }

  .chart-toolbar,
  .export-panel,
  #action-description,
  #description {
    display: none !important;
  }

  #sankey-print-export,
  #sankey-print-export_svg,
  svg {
    transform: scale(0.97);
    transform-origin: top left;
  }
}
</style>

<style scoped>
#sankey-print-export {
  text-align: center;
}

.property-section {
  padding: 12px 16px;
}

.property-text {
  font-size: 13px;
  font-weight: 400;
}

.btn-row {
  display: flex;
  gap: 8px;
}
</style>
