// syncfusionejs2_trial/Samples/React/src/treemap/rtl.tsx
/**
 * Drilldown sample for treemap
 */
import * as React from "react";
import * as ReactDOM from "react-dom";
import {
	TreeMapComponent, LevelsDirective, LevelDirective, Inject, TreeMapTooltip, TreeMapAjax,
	ILoadedEventArgs, TreeMapTheme, IDrillStartEventArgs, ITreeMapTooltipRenderEventArgs, Alignment
} from '@syncfusion/ej2-react-treemap';
import { DropDownListComponent } from '@syncfusion/ej2-react-dropdowns';
import { CheckBoxComponent, ChangeEventArgs } from "@syncfusion/ej2-react-buttons";
import { PropertyPane } from '../common/property-pane';
import { SampleBase } from '../common/sample-base';
import * as data from './treemap-data/rtl-data.json';
let datasource: any = data as any;
const SAMPLE_CSS = `
    .control-fluid {
		padding: 0px !important;
		}`;

export class RTL extends SampleBase<{}, {}> {
	private treemapInstance: TreeMapComponent;
	private prevTime: Date;
    private curTime: Date;
    
    public load(args: ILoadedEventArgs): void {
		// custom code start
		let theme: string = location.hash.split('/')[1];
		theme = theme ? theme : 'Material';
		args.treemap.theme = ((theme.charAt(0).toUpperCase() +
		theme.slice(1)).replace(/-dark/i, 'Dark').replace(/-high/i, 'High').replace(/contrast/i, 'Contrast').replace(/5.3/i, '5')) as TreeMapTheme;
		// custom code end
    }
    
	render() {
		return (
            <main><div className='control-pane'>
				<style>
					{SAMPLE_CSS}
				</style>
				<div className='control-section'>
				  <TreeMapComponent load={this.load.bind(this)} id='treemap-container' ref={m => this.treemapInstance = m}
						palette={['#5B244D', '#6F3953', ' #87525A', '#A26F63', '#BA896B', '#D5A574', '#F1C37D']}
						titleSettings={{			//To config title for treemap
							text: 'List of countries by unemployment rate',
							textStyle: { size: '15px' }
						}}
						enableDrillDown={true}
						format={"n"}
						useGroupingSeparator={true}
						enableRtl={true}
						renderDirection = 'TopRightBottomLeft'
						dataSource={datasource.rtl}
						weightValuePath='Size'
						tooltipSettings={{			// To config tooltip for treemap
							visible: true,
							format: '${Size} : ${Name}'
						}}
						leafItemSettings={{         // To config leafitem customization for treemap
							labelPath: 'Name',
							showLabels: true							
						}}>
						<Inject services={[TreeMapTooltip]} />
						<LevelsDirective>
							<LevelDirective groupPath= 'Continent' border={{ color: 'black', width: 0.5 }} headerAlignment='Far'/>
							<LevelDirective groupPath='Country'  border={{ color: 'black', width: 0.5 }} headerAlignment='Center' />							
						</LevelsDirective>
					</TreeMapComponent>
				</div>
				<div style={{ float: 'right', marginRight: '10px' }}>Source:
       <a href="https://www.indexmundi.com/facts/visualizations/treemap#SL.UEM.TOTL.ZS:SL.UEM.TOTL.ZS" target="_blank">www.indexmundi.com</a>
				</div>
			</div>
				<section id="action-description" aria-label="Description of TreeMap sample">
					<p>
					This sample orders the countries based on the unemployment rate, by rendering the TreeMap
					in right to left (RTL) direction.
            </p>
				</section>
				<section id="description" aria-label="Description of the TreeMap features demonstrated in this sample">
					<p>
						In this example, you can see how to render a TreeMap from right to left direction.
        		The tooltip is enabled in this example. To see the tooltip in action,
        		hover the mouse over an item or tap an item in touch-enabled devices.
					</p>
				</section>
			</main>
		)
	}
}

// syncfusionejs2_trial/Samples/Angular/source/treemap/rtl.component.ts
import { Component, ViewEncapsulation, ViewChild, Inject } from '@angular/core';
import { TreeMap, TreeMapTooltip, IDrillStartEventArgs, ITreeMapTooltipRenderEventArgs, TreeMapModule } from '@syncfusion/ej2-angular-treemap';
import { RTLData } from './rtl-data';
import { ILoadEventArgs, TreeMapTheme, Alignment, RenderingMode } from '@syncfusion/ej2-angular-treemap';
import { CheckBox, ChangeEventArgs as CheckBoxChangeEvents } from '@syncfusion/ej2-buttons';
import { DropDownList } from '@syncfusion/ej2-dropdowns';
import { EmitType } from '@syncfusion/ej2-base';
import { SBDescriptionComponent } from '../common/dp.component';
import { SBActionDescriptionComponent } from '../common/adp.component';
TreeMap.Inject(TreeMapTooltip);

/**
 * Default sample
 */
@Component({
    selector: 'control-content',
    templateUrl: 'rtl.html',
    encapsulation: ViewEncapsulation.None,
    standalone: true,
    imports: [TreeMapModule, SBActionDescriptionComponent, SBDescriptionComponent]
})
export class TreemapRTLComponent {
    @ViewChild('treemap')
    public treemap: TreeMap;
    public load = (args: ILoadEventArgs) => {
        let theme: string = location.hash.split('/')[1];
        theme = theme ? theme : 'Material';
        args.treemap.theme = <TreeMapTheme>(theme.charAt(0).toUpperCase() +
        theme.slice(1)).replace(/-dark/i, 'Dark').replace(/contrast/i, 'Contrast').replace(/-high/i, 'High').replace(/5.3/i, '5');
    }
    tooltipRendering = (args: ITreeMapTooltipRenderEventArgs) => {
        //tslint:disable-next-line
        if (args.item['groupIndex'] !== 2 ) {
            args.cancel = true;
        }
    }
        public palette: string[] = ['#5B244D', '#6F3953', ' #87525A', '#A26F63', '#BA896B', '#D5A574', '#F1C37D'];
        public titleSettings: object = {
            text: 'List of countries by unemployment rate',
            textStyle: { size: '15px'}
        };
        public dataSource: object[] = RTLData;
        public weightValuePath: string = 'Size';
        public tooltipSettings: object = {
            visible: true,
            format: '${Name} : ${Size}'
        };
        public leafItemSettings: object = {
            labelPath: 'Name',
            showLabels: true            
        };
        border: object = {
            color: 'black',
            width: 0.5
        };

        ngAfterViewInit(): void {  }
        constructor(@Inject('sourceFiles') private sourceFiles: any) {
            sourceFiles.files = ['rtl-data.ts' ];
        };
};
