// syncfusionejs2_trial/Samples/Vue/public/source/maps/zooming.vue

<template>
<main><div id="maps-zoom-sample">
<div class="col-lg-8 control-section">
<ejs-maps ref="maps" id='mapszooming' :zoomSettings='zoomSettings' :load='load'>
    <e-layers>
        <e-layer :shapeData='shapeData' :shapePropertyPath='shapePropertyPath' :animationDuration='animationDuration' :shapeDataPath='shapeDataPath' :dataSource='dataSource' :shapeSettings='shapeSettings'></e-layer>
    </e-layers>
</ejs-maps>    
    <div id="height_slider"></div>        
    </div>

    <div class="col-lg-4 property-section">
        <table role="none" id="property" title="Properties" style="width: 100%;">
        <colgroup>
            <col span="1" style="width: 50%;">
            <col span="1" style="width: 50%;">
       </colgroup>
       <tbody>
                <tr style="height: 50px">
                    <td>
                        <div  class="text">Zooming</div>
                    </td>
                    <td>
                    <div  class="text" style="margin-top: 3px;  margin-left: 10px;">
                        <input type="checkbox" checked id="zoom"  v-on:change='changeZoom' />
                   </div>
                    </td>
                </tr>
                <tr style="height: 50px">
                    <td>
                        <div  class="text">Panning</div>
                    </td>
                    <td>
                   <div  class="text" style="margin-top: 3px;  margin-left: 10px;">
                        <input type="checkbox" checked id="panning"  v-on:change='changePan' />
                   </div>
                    </td>
                </tr>
                <tr style="height: 50px">
                    <td>
                        <div style="width: 93%;"  class="text">Mouse wheel zoom</div>
                    </td>
                    <td>
                    <div  class="text" style="margin-top: 3px;  margin-left: 10px;">
                        <input type="checkbox" checked id="mousewheel" v-on:change='changeMousewheel'/>
                    </div>
                    </td>
                </tr>
                <tr style="height: 50px">
                        <td>
                            <div  class="text">Pinch zoom</div>
                        </td>
                        <td>
                        <div  class="text" style="margin-top: 3px;  margin-left: 10px;">
                            <input type="checkbox" checked id="pinch"  v-on:change='changePinch' />
                         </div>
                        </td>
                </tr>
                <tr style="height: 50px">
                    <td>
                        <div  class="text" style="width: 89%;">Single click zoom</div>
                    </td>
                    <td>
                     <div  class="text" style="margin-top: 3px;  margin-left: 10px;" >
                        <input type="checkbox" id="singletap" v-on:change='changeSingletap' />
                      </div>
                    </td>
                </tr>
                <tr style="height: 50px">
                    <td>
                        <div  class="text" style="width: 93%;">Double click zoom</div>
                    </td>
                    <td>
                    <div  class="text" style="margin-top: 3px;  margin-left: 10px;">
                        <input type="checkbox" id="doubletap" v-on:change='changeDoubletap' />
                     </div>
                    </td>
                </tr>
                 <tr style="height: 50px">
                    <td>
                        <div  id="animation" style="width: 94%; padding-left: 0px;">Animation duration</div>
                    </td>
                    <td>
                    <div style="padding-top: 5px; margin-left: -10px;">
                        <ejs-slider id='range' :value='value' min=0 max=1000 :step='step' :change='sliderChange' class="slider" style="width: 50%;"></ejs-slider>
                        </div>
                    </td>
                    <td align="center" class="duration" style="width: 10%; text-align: center; padding-top: 10px;">
                        <span id="dur" style="margin-left: -30px;">500ms</span>
                    </td>
                </tr>
                </tbody>
        </table>
    </div>
</div>
    <section id="action-description" aria-label="Description of Maps sample">
            <p>
                This sample depicts the zooming and panning options in the maps. You can customize these options by changing the Zooming, Panning, Mouse wheel zoom, Pinch zoom, Single-click zoom, and Double-click zoom in the Properties panel.
           </p>
        </section>
        <section id="description" aria-label="Description of the Maps features demonstrated in this sample">
            <p>
                In this example, you can see how to zoom and pan the map. The support has been provided for zooming with the toolbar, rectangle zoom, pinch zoom, mouse wheel zoom, single-click, and double-click zoom.Panning can be enabled or disabled using
                the Panning option. When it is disabled, the map will switch to zooming mode.
            </p>
        <br/>
            <p style="font-weight: 500">Injecting Module</p>
            <p>
              Maps component features are segregated into individual feature-wise modules. To use the zooming feature, inject the <code>Zoom</code> module using the <code>Maps.Inject(Zoom)</code> method.
            </p>
            
        </section>
        </main>
</template>

 <style scoped>
     #maps-zoom-sample .slider-content-wrapper {
        width: 40%;
        margin: 0 auto;
        min-width: 185px;
    }

    #maps-zoom-sample .slider-userselect {
        -webkit-user-select: none;
        /* Safari 3.1+ */
        -moz-user-select: none;
        /* Firefox 2+ */
        -ms-user-select: none;
        /* IE 10+ */
        user-select: none;
        /* Standard syntax */
    }

    #maps-zoom-sample .slider-labeltext {
        text-align: -webkit-left;
        font-weight: 500;
        font-size: 13px;
        padding-bottom: 10px;
    }

    #maps-zoom-sample .slider_container {
        margin-top: 40px;
    }

    #maps-zoom-sample .e-bigger .slider-content-wrapper {
        width: 80%;
    }

    #maps-zoom-sample #height_slider .e-tab-handle::after {
        background-color: #f9920b;
    }

    #maps-zoom-sample #height_slider.e-control.e-slider .e-slider-track {
        height: 8px;
        top: calc(50% - 4px);
        border-radius: 0;
    }
    #maps-zoom-sample .highcontrast #height_slider.e-control.e-slider .e-slider-track {
        height: 10px;
        top: calc(50% - 5px);
        border-radius: 0;
    }
    #maps-zoom-sample .fabric .slider_container .e-slider-hover .e-slider-track, #maps-zoom-sample .fabric .slider_container .e-slider-container:active .e-slider-track,
    #maps-zoom-sample .fabric .slider_container .e-slider-container .e-slider .e-tab-track{
        background-color: #c8c8c8;
    }

    #maps-zoom-sample #gradient_slider.e-control.e-slider .e-range {
        height: 6px;
        top: calc(50% - 3px);
        border-radius: 5px;
        background: linear-gradient(to top left, #f9f9f9 25%, #f9920b 90%);
    }

    #maps-zoom-sample .fabric .slider_container .e-slider-hover .e-slider-track,
    #maps-zoom-sample .fabric .slider_container .e-slider-container:active .e-slider-track,
    #maps-zoom-sample .fabric .slider_container .e-slider-container .e-slider .e-tab-track {
        background-color: #c8c8c8;
    }

    #maps-zoom-sample #gradient_slider.e-control.e-slider .e-slider-track {
        height: 8px;
        top: calc(50% - 4px);
        border-radius: 5px;
    }
    #maps-zoom-sample #control-container {
        padding: 0px !important;
    }
    #maps-zoom-sample #range > * {
        padding: 0px !important;
    }
    div.text {
        padding-left: 0px; padding-top: 0px;
    }
</style>
<style>
.slider .e-slider-track{
    padding-top: 0px;
}
</style>
<script>
import Vue from 'vue';
import { MapsComponent, LayersDirective, LayerDirective, Zoom} from '@syncfusion/ej2-vue-maps';
import { SliderComponent } from "@syncfusion/ej2-vue-inputs";
import { worldMap } from '../maps/map-data/world-map';
import { zoomData } from '../maps/map-data/zooming-datasource';

export default {
    components: {
    'ejs-maps': MapsComponent,
    'e-layers': LayersDirective,
    'e-layer': LayerDirective,
    'ejs-slider': SliderComponent
  },
  data:function(){
      return{
            zoomSettings: {
            enable: true,
            toolbarSettings:{
                buttonSettings: {
                   toolbarItems: ['Zoom', 'ZoomIn', 'ZoomOut', 'Pan', 'Reset']
                }
            },
            pinchZooming: true
        },
        shapeData: worldMap,
        shapePropertyPath: 'continent',
        shapeDataPath: 'continent',
        animationDuration: 500,
        shapeSettings: {
                    autofill: true,
                    colorValuePath: 'color'
        },
        dataSource: zoomData,
        value: 500,
        step: 250
      }
  },
provide: {
    maps: [Zoom]
},
methods:{
    /* custom code start */
   load: function(args) {
      let selectedTheme = location.hash.split("/")[1];
      selectedTheme = selectedTheme ? selectedTheme : "Material";
      args.maps.theme =
        (selectedTheme.charAt(0).toUpperCase() +
            selectedTheme.slice(1)).replace(/-dark/i, 'Dark').replace(/-high/i, 'High').replace(/contrast/i, 'Contrast').replace(/5.3/i, '5');
    },
    /* custom code end */
    // Code for Property Panel
    changeZoom:function(args){
        let element = (document.getElementById('zoom'));
        this.$refs.maps.ej2Instances.zoomSettings.enable = element.checked;
        this.$refs.maps.ej2Instances.refresh();
    },
    changePan:function(args){
        let element = (document.getElementById('panning'));
        this.$refs.maps.ej2Instances.zoomSettings.enablePanning = element.checked;
        this.$refs.maps.ej2Instances.refresh();
    },
    changeMousewheel:function(args){
        let element = (document.getElementById('mousewheel'));
        this.$refs.maps.ej2Instances.zoomSettings.mouseWheelZoom = element.checked;
        this.$refs.maps.ej2Instances.refresh();
    },
    changePinch:function(args){
        let element = (document.getElementById('pinch'));
        this.$refs.maps.ej2Instances.zoomSettings.pinchZooming = element.checked;
        this.$refs.maps.ej2Instances.refresh();
    },
    changeSingletap:function(args){
        let element = (document.getElementById('singletap'));
        let ele1 = document.getElementById('doubletap');
        this.$refs.maps.ej2Instances.zoomSettings.zoomOnClick = element.checked;
        if (element.checked) {
            ele1.disabled = true;
        } else {
            ele1.disabled = false;
        }
    },
    changeDoubletap:function(args){      
        let element = (document.getElementById('doubletap'));
        this.$refs.maps.ej2Instances.zoomSettings.doubleClickZoom = element.checked;
        let ele1 = document.getElementById('singletap');
        if (element.checked) {
            ele1.disabled = true;
        } else {
            ele1.disabled = false;
        }
    },
    sliderChange:function(args){
        this.$refs.maps.ej2Instances.layers[0].animationDuration = args.value;
        this.$refs.maps.ej2Instances.refresh();
        document.getElementById('dur').innerHTML = args.value.toString() + 'ms';
    }
}
}
</script>

// syncfusionejs2_trial/Samples/React/src/maps/zooming.js
"use strict";
/**
 * Zooming sample
 */
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.ZoomingMaps = void 0;
var React = require("react");
var ej2_react_maps_1 = require("@syncfusion/ej2-react-maps");
var sample_base_1 = require("../common/sample-base");
var property_pane_1 = require("../common/property-pane");
var ej2_react_inputs_1 = require("@syncfusion/ej2-react-inputs");
var data = require("./map-data/zooming-datasource.json");
var worldMap = require("./map-data/world-map.json");
var datasource = data;
var SAMPLE_CSS = "\n    .control-fluid {\n\t\tpadding: 0px !important;\n    }\n    .slider-content-wrapper {\n        width: 40%;\n        margin: 0 auto;\n        min-width: 185px;\n    }\n\n    .slider-userselect {\n        -webkit-user-select: none;\n        /* Safari 3.1+ */\n        -moz-user-select: none;\n        /* Firefox 2+ */\n        -ms-user-select: none;\n        /* IE 10+ */\n        user-select: none;\n        /* Standard syntax */\n    }\n\n    .slider-labeltext {\n        text-align: -webkit-left;\n        font-weight: 500;\n        font-size: 13px;\n        padding-bottom: 10px;\n    }\n\n    .slider_container {\n        margin-top: 40px;\n    }\n\n    .e-bigger .slider-content-wrapper {\n        width: 80%;\n    }\n\n    #height_slider .e-tab-handle::after {\n        background-color: #f9920b;\n    }\n\n    #height_slider.e-control.e-slider .e-slider-track {\n        height: 8px;\n        top: calc(50% - 4px);\n        border-radius: 0;\n    }\n    .highcontrast #height_slider.e-control.e-slider .e-slider-track {\n        height: 10px;\n        top: calc(50% - 5px);\n        border-radius: 0;\n    }\n    .fabric .slider_container .e-slider-hover .e-slider-track, .fabric .slider_container .e-slider-container:active .e-slider-track,\n    .fabric .slider_container .e-slider-container .e-slider .e-tab-track{\n        background-color: #c8c8c8;\n    }\n\n    #gradient_slider.e-control.e-slider .e-range {\n        height: 6px;\n        top: calc(50% - 3px);\n        border-radius: 5px;\n        background: linear-gradient(to top left, #f9f9f9 25%, #f9920b 90%);\n    }\n\n    .fabric .slider_container .e-slider-hover .e-slider-track,\n    .fabric .slider_container .e-slider-container:active .e-slider-track,\n    .fabric .slider_container .e-slider-container .e-slider .e-tab-track {\n        background-color: #c8c8c8;\n    }\n\n    #gradient_slider.e-control.e-slider .e-slider-track {\n        height: 8px;\n        top: calc(50% - 4px);\n        border-radius: 5px;\n    }\n\n    #range > * {\n        padding: 0px !important;\n    }";
var slidercss = "  \n    .content-wrapper {\n        width: 40%;\n        margin: 0 auto;\n        min-width: 100px;\n    }";
var ZoomingMaps = /** @class */ (function (_super) {
    __extends(ZoomingMaps, _super);
    function ZoomingMaps() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    ZoomingMaps.prototype.sliderchange = function (args) {
        this.mapInstance.zoomModule.toolBarZooming(args.value, 'ZoomIn');
    };
    ZoomingMaps.prototype.render = function () {
        var _this = this;
        return (React.createElement("main", null,
            React.createElement("div", { className: 'control-pane' },
                React.createElement("style", null, SAMPLE_CSS),
                React.createElement("div", { className: 'control-section row' },
                    React.createElement("div", { className: 'col-md-8' },
                        React.createElement(ej2_react_maps_1.MapsComponent, { id: "maps", loaded: this.onMapsLoad.bind(this), load: this.load, ref: function (m) { return _this.mapInstance = m; }, zoomSettings: {
                                enable: true,
                                pinchZooming: true,
                                toolbarSettings: {
                                    buttonSettings: {
                                        toolbarItems: ['Zoom', 'ZoomIn', 'ZoomOut', 'Pan', 'Reset']
                                    }
                                }
                            } },
                            React.createElement(ej2_react_maps_1.Inject, { services: [ej2_react_maps_1.Zoom] }),
                            React.createElement(ej2_react_maps_1.LayersDirective, null,
                                React.createElement(ej2_react_maps_1.LayerDirective, { shapeData: worldMap, shapePropertyPath: 'continent', shapeDataPath: 'continent', dataSource: datasource, animationDuration: 500, shapeSettings: {
                                        autofill: true,
                                        colorValuePath: 'color'
                                    } })))),
                    React.createElement("div", { className: 'col-md-4 property-section' },
                        React.createElement(property_pane_1.PropertyPane, { title: 'Properties' },
                            React.createElement("table", { role: 'none', id: 'property', title: 'Properties', className: 'property-panel-table', style: { width: '100%', marginLeft: '-10px' } },
                                React.createElement("tbody", null,
                                    React.createElement("tr", { style: { height: '50px' } },
                                        React.createElement("td", null,
                                            React.createElement("div", null, "Zooming")),
                                        React.createElement("td", { style: { width: '40%' } },
                                            React.createElement("div", { style: { marginTop: "2px" } },
                                                React.createElement("input", { type: "checkbox", onClick: this.zooming.bind(this), defaultChecked: true, id: "zoom", style: { marginLeft: '0px' } })))),
                                    React.createElement("tr", { style: { height: '50px' } },
                                        React.createElement("td", null,
                                            React.createElement("div", null, "Panning")),
                                        React.createElement("td", { style: { width: '40%' } },
                                            React.createElement("div", { style: { marginTop: "2px" } },
                                                React.createElement("input", { type: "checkbox", onClick: this.panning.bind(this), defaultChecked: true, id: "panning", style: { marginLeft: '0px' } })))),
                                    React.createElement("tr", { style: { height: '50px' } },
                                        React.createElement("td", null,
                                            React.createElement("div", null, "Mouse wheel zoom")),
                                        React.createElement("td", { style: { width: '40%' } },
                                            React.createElement("div", { style: { marginTop: "2px" } },
                                                React.createElement("input", { type: "checkbox", onClick: this.mousewheel.bind(this), defaultChecked: true, id: "mousewheel", style: { marginLeft: '0px' } })))),
                                    React.createElement("tr", { style: { height: '50px' } },
                                        React.createElement("td", null,
                                            React.createElement("div", null, "Pinch zoom")),
                                        React.createElement("td", { style: { width: '40%' } },
                                            React.createElement("div", { style: { marginTop: "2px" } },
                                                React.createElement("input", { type: "checkbox", onClick: this.pinching.bind(this), defaultChecked: true, id: "pinch", style: { marginLeft: '0px' } })))),
                                    React.createElement("tr", { style: { height: '50px' } },
                                        React.createElement("td", null,
                                            React.createElement("div", null, "Single click zoom")),
                                        React.createElement("td", { style: { width: '40%' } },
                                            React.createElement("div", { style: { marginTop: "2px" } },
                                                React.createElement("input", { type: "checkbox", onClick: this.singletap.bind(this), id: "singletap", style: { marginLeft: '0px' } })))),
                                    React.createElement("tr", { style: { height: '50px' } },
                                        React.createElement("td", null,
                                            React.createElement("div", null, "Double click zoom")),
                                        React.createElement("td", { style: { width: '40%' } },
                                            React.createElement("div", { style: { marginTop: "2px" } },
                                                React.createElement("input", { type: "checkbox", onClick: this.doubletab.bind(this), id: "doubletap", style: { marginLeft: '0px' } })))),
                                    React.createElement("tr", { style: { height: '50px' } },
                                        React.createElement("td", null,
                                            React.createElement("div", { style: { marginTop: '-15px' } }, "Animation Duration ")),
                                        React.createElement("td", { style: { width: '40%' } },
                                            React.createElement("div", { className: "content-wrapper", style: { paddingLeft: '0px', marginTop: '-20px' } },
                                                React.createElement(ej2_react_inputs_1.SliderComponent, { id: "range", change: this.animationChange.bind(this), ref: function (slider) { return _this.animationElement = slider; }, name: "animationRange", step: 250, value: 500, min: 0, max: 1000, width: '70%' }))),
                                        React.createElement("td", { style: { width: '10%' } },
                                            React.createElement("div", { style: { textAlign: 'center', paddingLeft: '0px', marginTop: '-20px', marginLeft: '-20px' } },
                                                React.createElement("span", { id: 'range1' }, "500ms")))))))))),
            React.createElement("section", { id: "action-description", "aria-label": "Description of Maps sample" },
                React.createElement("p", null, "This sample depicts the zooming and panning options in the maps. You can customize these options by changing the Zooming, Panning, Mouse wheel zoom, Pinch zoom, Single-click zoom, and Double-click zoom in the Properties panel.")),
            React.createElement("section", { id: "description", "aria-label": "Description of the Maps features demonstrated in this sample" },
                React.createElement("p", null, "In this example, you can see how to zoom and pan the map. The support has been provided for zooming with the toolbar, rectangle zoom, pinch zoom, mouse wheel zoom, single-click, and double-click zoom.Panning can be enabled or disabled using the Panning option. When it is disabled, the map will switch to zooming mode."),
                React.createElement("br", null),
                React.createElement("p", { style: { fontWeight: 500 } }, "Injecting Module"),
                React.createElement("p", null,
                    "Maps component features are segregated into individual feature-wise modules. To use the zooming feature, inject the ",
                    React.createElement("code", null, "zoom"),
                    " module using the Maps.Inject(zoom) method."))));
    };
    ZoomingMaps.prototype.onMapsLoad = function (args) {
        var maps = document.getElementById('maps');
        maps.setAttribute('title', '');
    };
    ;
    ZoomingMaps.prototype.load = function (args) {
        // custom code start
        var selectedTheme = location.hash.split('/')[1];
        selectedTheme = selectedTheme ? selectedTheme : 'Material';
        args.maps.theme = ((selectedTheme.charAt(0).toUpperCase() +
            selectedTheme.slice(1)).replace(/-dark/i, 'Dark').replace(/-high/i, 'High').replace(/contrast/i, 'Contrast').replace(/5.3/i, '5'));
        // custom code end
    };
    ;
    ZoomingMaps.prototype.mousewheel = function () {
        var element = (document.getElementById('mousewheel'));
        this.mapInstance.zoomSettings.mouseWheelZoom = element.checked;
        this.mapInstance.refresh();
    };
    ZoomingMaps.prototype.pinching = function () {
        var element = (document.getElementById('pinch'));
        this.mapInstance.zoomSettings.pinchZooming = element.checked;
        this.mapInstance.refresh();
    };
    ZoomingMaps.prototype.zooming = function () {
        var element = (document.getElementById('zoom'));
        this.mapInstance.zoomSettings.enable = element.checked;
        this.mapInstance.refresh();
    };
    ZoomingMaps.prototype.panning = function () {
        var element = (document.getElementById('panning'));
        this.mapInstance.zoomSettings.enablePanning = element.checked;
        this.mapInstance.refresh();
    };
    ZoomingMaps.prototype.doubletab = function () {
        var element = (document.getElementById('doubletap'));
        this.mapInstance.zoomSettings.doubleClickZoom = element.checked;
        var ele1 = document.getElementById('singletap');
        if (element.checked) {
            ele1.disabled = true;
        }
        else {
            ele1.disabled = false;
        }
        this.mapInstance.refresh();
    };
    ZoomingMaps.prototype.singletap = function () {
        var element = (document.getElementById('singletap'));
        var ele1 = document.getElementById('doubletap');
        this.mapInstance.zoomSettings.zoomOnClick = element.checked;
        if (element.checked) {
            ele1.disabled = true;
        }
        else {
            ele1.disabled = false;
        }
        this.mapInstance.refresh();
    };
    ZoomingMaps.prototype.animationChange = function () {
        this.mapInstance.layers[0].animationDuration = parseInt(this.animationElement.value.toString(), 10);
        this.mapInstance.refresh();
        document.getElementById('range1').innerHTML = (parseInt(this.animationElement.value.toString(), 10)) + 'ms';
    };
    return ZoomingMaps;
}(sample_base_1.SampleBase));
exports.ZoomingMaps = ZoomingMaps;
