// syncfusionejs2_trial/Samples/React/src/sparkline/axis-types.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.Axis = void 0;
/**
 * Axis types samples for sparkline
 */
var React = require("react");
var ej2_react_charts_1 = require("@syncfusion/ej2-react-charts");
var sample_base_1 = require("../common/sample-base");
var SAMPLE_CSS = "\n    .control-fluid {\n\t\tpadding: 0px !important;\n    }";
var tableWidth = { width: '100%' };
var padding10 = { padding: '10px' };
var Axis = /** @class */ (function (_super) {
    __extends(Axis, _super);
    function Axis() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Axis.prototype.load = function (args) {
        var theme = location.hash.split('/')[1];
        theme = theme ? theme : 'Fluent2';
        args.sparkline.theme = (theme.charAt(0).toUpperCase() + theme.slice(1)).replace(/-dark/i, 'Dark').replace(/contrast/i, 'Contrast').replace(/-highContrast/i, 'HighContrast');
    };
    Axis.prototype.render = function () {
        return (React.createElement("div", { className: 'control-pane' },
            React.createElement("style", null, SAMPLE_CSS),
            React.createElement("div", { className: 'control-section' },
                React.createElement("div", { id: "spark-container", className: "row" },
                    React.createElement("div", { className: "cols-sample-area" },
                        React.createElement("table", { style: tableWidth },
                            React.createElement("tbody", null,
                                React.createElement("tr", null,
                                    React.createElement("td", { style: { "textAlign": "center", "fontSize": "14px", "fontWeight": "600", "fontFamily": "Roboto" } },
                                        React.createElement("div", null, "Mean working hours for a month"),
                                        React.createElement("div", null,
                                            React.createElement("i", null, "(DateTime axis)"))),
                                    React.createElement("td", { style: padding10 },
                                        React.createElement(ej2_react_charts_1.SparklineComponent, { load: this.load.bind(this), id: 'spark1-container', height: '100px', width: '170px', lineWidth: 1, type: 'Column', valueType: 'DateTime', fill: '#3C78EF', tooltipSettings: {
                                                visible: true, format: '${xDate} : ${yval}hrs',
                                            }, dataSource: [
                                                { xDate: new Date(2018, 0, 1), x: 0, yval: 4 },
                                                { xDate: new Date(2018, 0, 2), x: 1, yval: 4.5 },
                                                { xDate: new Date(2018, 0, 3), x: 2, yval: 8 },
                                                { xDate: new Date(2018, 0, 4), x: 3, yval: 7 },
                                                { xDate: new Date(2018, 0, 5), x: 4, yval: 6 },
                                                { xDate: new Date(2018, 0, 8), x: 5, yval: 8 },
                                                { xDate: new Date(2018, 0, 9), x: 6, yval: 8 },
                                                { xDate: new Date(2018, 0, 10), x: 7, yval: 6.5 },
                                                { xDate: new Date(2018, 0, 11), x: 8, yval: 4 },
                                                { xDate: new Date(2018, 0, 12), x: 9, yval: 5.5 },
                                                { xDate: new Date(2018, 0, 15), x: 10, yval: 8 },
                                                { xDate: new Date(2018, 0, 16), x: 11, yval: 6 },
                                                { xDate: new Date(2018, 0, 17), x: 12, yval: 6.5 },
                                                { xDate: new Date(2018, 0, 18), x: 13, yval: 7.5 },
                                                { xDate: new Date(2018, 0, 19), x: 14, yval: 7.5 },
                                                { xDate: new Date(2018, 0, 22), x: 15, yval: 4 },
                                                { xDate: new Date(2018, 0, 23), x: 16, yval: 8 },
                                                { xDate: new Date(2018, 0, 24), x: 17, yval: 6 },
                                                { xDate: new Date(2018, 0, 25), x: 18, yval: 7.5 },
                                                { xDate: new Date(2018, 0, 26), x: 19, yval: 4.5 },
                                                { xDate: new Date(2018, 0, 29), x: 20, yval: 6 },
                                                { xDate: new Date(2018, 0, 30), x: 21, yval: 5 },
                                                { xDate: new Date(2018, 0, 31), x: 22, yval: 7 }
                                            ], xName: 'xDate', yName: 'yval' },
                                            React.createElement(ej2_react_charts_1.Inject, { services: [ej2_react_charts_1.SparklineTooltip] })))),
                                React.createElement("tr", null,
                                    React.createElement("td", { style: { "textAlign": "center", "fontSize": "14px", "fontWeight": "600", "fontFamily": "Roboto" } },
                                        React.createElement("div", null, "Percentage of the students in a class"),
                                        React.createElement("div", null,
                                            React.createElement("i", null, "(Category axis)"))),
                                    React.createElement("td", { style: padding10 },
                                        React.createElement(ej2_react_charts_1.SparklineComponent, { load: this.load.bind(this), id: 'spark2-container', height: '100px', width: '170px', lineWidth: 1, type: 'Column', valueType: 'Category', fill: '#3C78EF', tooltipSettings: {
                                                visible: true, format: '${xval} : ${yval}%',
                                            }, dataSource: [
                                                { x: 0, xval: 'Robert', yval: 60 },
                                                { x: 1, xval: 'Andrew', yval: 65 },
                                                { x: 2, xval: 'Suyama', yval: 70 },
                                                { x: 3, xval: 'Michael', yval: 80 },
                                                { x: 4, xval: 'Janet', yval: 55 },
                                                { x: 5, xval: 'Davolio', yval: 90 },
                                                { x: 6, xval: 'Fuller', yval: 75 },
                                                { x: 7, xval: 'Nancy', yval: 85 },
                                                { x: 8, xval: 'Margaret', yval: 77 },
                                                { x: 9, xval: 'Steven', yval: 68 },
                                                { x: 10, xval: 'Laura', yval: 96 },
                                                { x: 11, xval: 'Elizabeth', yval: 57 }
                                            ], xName: 'xval', yName: 'yval' },
                                            React.createElement(ej2_react_charts_1.Inject, { services: [ej2_react_charts_1.SparklineTooltip] })))),
                                React.createElement("tr", null,
                                    React.createElement("td", { style: { "textAlign": "center", "fontSize": "14px", "fontWeight": "600", "fontFamily": "Roboto" } },
                                        React.createElement("div", null, "Expenditure details of various trips"),
                                        React.createElement("div", null,
                                            React.createElement("i", null, "(Numeric axis)"))),
                                    React.createElement("td", { style: padding10 },
                                        React.createElement(ej2_react_charts_1.SparklineComponent, { load: this.load.bind(this), id: 'spark3-container', height: '100px', width: '170px', lineWidth: 1, type: 'Column', valueType: 'Numeric', fill: '#3C78EF', tooltipSettings: {
                                                visible: true, format: '${x} : $${yval}',
                                            }, dataSource: [
                                                { x: 1, xval: 2010, yval: 190 },
                                                { x: 2, xval: 2011, yval: 165 },
                                                { x: 3, xval: 2012, yval: 158 },
                                                { x: 4, xval: 2013, yval: 175 },
                                                { x: 5, xval: 2014, yval: 200 },
                                                { x: 6, xval: 2015, yval: 180 },
                                                { x: 7, xval: 2016, yval: 210 }
                                            ], xName: 'x', yName: 'yval' },
                                            React.createElement(ej2_react_charts_1.Inject, { services: [ej2_react_charts_1.SparklineTooltip] }))))))))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null, "This sample depicts the various types of axis value types available in sparkline.")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null, "In this example, you can see the sparklines with various axis value types such as date-time, category, and numeric. Tooltip is enabled in this example. To see the tooltip in action, hover the mouse over the data points or tap on a data point in touch enabled devices."))));
    };
    return Axis;
}(sample_base_1.SampleBase));
exports.Axis = Axis;

// syncfusionejs2_trial/Samples/Vue/public/source/sparkline/axis-types.vue
<template>
<div>
<div class="control-section">
    <div id="spark-container" class="row">
        <div class="cols-sample-area">
            <table style="width:100%;">
                <tr>
                    <td align="center">
                        <div>Mean working hours for a month</div>
                        <div><i>(DateTime axis)</i></div>
                    </td>
                    <td style="padding: 10px;">
                        <ejs-sparkline id='datetime' :load='load' style="width:170px; height:100px" :height='height' :width='width' :lineWidth='lineWidth' :type='type' :valueType='valueType' :fill='fill' :dataSource='dataSource' :tooltipSettings='tooltipSettings' xName='xDate' yName='yval'></ejs-sparkline>                        
                    </td>
                </tr>
                <tr>
                    <td align="center">
                        <div>Percentage of the students in a class</div>
                        <div><i>(Category axis)</i></div>
                    </td>
                    <td style="padding: 10px;">
                        <ejs-sparkline id='category' :load='load' style="width:170px; height:100px" :height='height' :width='width' :lineWidth='lineWidth' :type='type' :valueType='valueType2' :fill='fill2' :dataSource='dataSource2' :tooltipSettings='tooltipSettings2' xName='xval' yName='yval'></ejs-sparkline>                        
                    </td>
                </tr>
                <tr>
                    <td align="center">
                        <div>Expenditure details of various trips</div>
                        <div><i>(Numeric axis)</i></div>
                        </td>
                    <td style="padding: 10px;">
                        <ejs-sparkline id='numeric' :load='load' style="width:170px; height:100px" :height='height' :width='width' :lineWidth='lineWidth' :type='type' :valueType='valueType3' :fill='fill3' :dataSource='dataSource3' :tooltipSettings='tooltipSettings3' xName='x' yName='yval'></ejs-sparkline>                        
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
<div id="action-description">
    <p>
        This sample depicts the various types of axis value types available in sparkline.
    </p>
</div>
<div id="description">
    <p>
        In this example, you can see the sparklines with various axis value types such as date-time, category, and numeric. Tooltip is enabled in this example. To see the tooltip in action, hover the mouse over the data points or tap on a data point in touch enabled devices.
	</p>
</div>
</div>
</template>
<style scoped>
    td{
        font-family: "Roboto", "Segoe UI", "GeezaPro", "DejaVu Serif", "sans-serif";
        font-size: 14px;
        font-weight: 500;
    }
</style>
<script>
import { SparklineComponent, SparklineTooltip } from "@syncfusion/ej2-vue-charts";
import { data, data2 } from "./axistypes";
import { loadSparkLineTheme } from "./theme-color";
export default {
components: {
    'ejs-sparkline': SparklineComponent
},
data:function(){
return{
        height: '100px',
        width: '170px',
        lineWidth: 1,
        fill: '#3C78EF',
        type: 'Column',
        valueType: 'DateTime',
        dataSource: data,
        tooltipSettings: {
            visible: true,
            format: '${xDate} : ${yval}hrs'
        },
        fill2: '#3C78EF',
        valueType2: 'Category',
        dataSource2: data2,
        tooltipSettings2: {
            visible: true,
            format: '${xval} : ${yval}%'
        },
        fill3: '#3C78EF',
        valueType3: 'Numeric',
        dataSource3: [
             { x: 1, xval: 2010, yval: 190 },
            { x: 2, xval: 2011, yval: 165 },
            { x: 3, xval: 2012, yval: 158 },
            { x: 4, xval: 2013, yval: 175 },
            { x: 5, xval: 2014, yval: 200 },
            { x: 6, xval: 2015, yval: 180 },
            { x: 7, xval: 2016, yval: 210 }
        ],
        tooltipSettings3: {
            visible: true,
            format: '${x} : $${yval}'
        }
}
},
provide:{
    sparkline:[SparklineTooltip]
},
/* custom code start */
methods:{
    load:function(args){
      loadSparkLineTheme(args);
    }
}
/* custom code end */
}
</script>
