// syncfusionejs2_trial/Samples/Angular/source/maps/seat-selection.component.ts
/**
 * Seat Selection sample
 */
import { Component, ViewEncapsulation, Inject, ViewChild } from '@angular/core';
import { MapsTheme, Maps, ISelectionEventArgs, Selection, ILoadEventArgs, MapsModule } from '@syncfusion/ej2-angular-maps';
import { SBDescriptionComponent } from '../common/dp.component';
import { SBActionDescriptionComponent } from '../common/adp.component';
Maps.Inject(Selection);
interface SeatInfo {
    seatno?: number;
    fill?: string;
}
declare var require: any;
let seat_selection: object[] = require('./seat-data.json');
@Component({
    selector: 'control-content',
    templateUrl: 'seat-selection.html',
    encapsulation: ViewEncapsulation.None,
    standalone: true,
    imports: [SBActionDescriptionComponent, MapsModule, SBDescriptionComponent]
})
export class MapsSeatSelectionComponent {
    @ViewChild('maps')
    public maps: Maps;
    public zoomSettings: object = {
        enable: false
    };
    public seatInfo: HTMLDivElement;
    // custom code start
    public load = (args: ILoadEventArgs) => {
        let theme: string = location.hash.split('/')[1];
        theme = theme ? theme : 'Material';
        args.maps.theme = <MapsTheme>(theme.charAt(0).toUpperCase() +
        theme.slice(1)).replace(/-dark/i, 'Dark').replace(/contrast/i, 'Contrast').replace(/-high/i, 'High').replace(/5.3/i, '5');
    }
    // custom code end
    public itemSelection = (args: ISelectionEventArgs) => {
        if ((args.shapeData as SeatInfo).fill === 'Orange') {
            args.fill = 'Orange';
            document.getElementById(args.target).setAttribute('class', 'ShapeselectionMapStyle');
            return;
        }
        args.fill = 'green';
        let seat: number = (args.shapeData as SeatInfo).seatno;
        let connector: string = ' ';
        if (this.seatInfo.innerHTML === '') {
            this.seatInfo.innerHTML = '<span id="seat-info">Seats Selected -</span>';
        } else {
            connector = ', ';
        }
        let seatString: string = '<span class="seats">' + connector + seat + '</span>';
        let seatString1: string = ' ' + seat + '</span><span class="seats">,'; // 15</span><span class="seats">,
        let lastString: string = '<span id="seat-info">Seats Selected -</span><span class="seats"> ' + seat + '</span>';
        if (this.seatInfo.innerHTML.indexOf(seatString) === -1 && this.seatInfo.innerHTML.indexOf(seatString1) === -1 &&
            this.seatInfo.innerHTML.indexOf(lastString) === -1) {
            this.seatInfo.innerHTML += '<span class="seats">' + connector + seat + '</span>';
        } else {
            this.seatInfo.innerHTML = this.seatInfo.innerHTML.replace(seatString, '');
            this.seatInfo.innerHTML = this.seatInfo.innerHTML.replace(seatString1, '');
            if (this.seatInfo.innerHTML === lastString) {
                this.seatInfo.innerHTML = '';
            }
        }
    };

    public layers: object[] = [
        {
            geometryType: 'Normal',
            shapeData: seat_selection,
            shapeSettings: {
                colorValuePath: 'fill'
            },
            selectionSettings: {
                enable: true,
                opacity: 1,
                enableMultiSelect: true,
                fill : 'green'
            }
        }
    ];
    ngAfterViewInit() {
        this.seatInfo = <HTMLDivElement>document.getElementById('selectedseats');
        document.getElementById('clear-btn').onclick = () => {
            if (this.seatInfo.innerHTML === '') { return; }
            let seats: any[] = this.seatInfo.innerText.split('-')[1].trim().split(',').map(num => Number(num.trim()));
            for (let i: number = 0, length: number = seats.length; i < length; i++) {
                this.maps.shapeSelection(0, 'seatno', seats[i], false);
            }
            this.seatInfo.innerHTML = '';
        };
    }
    // custom code start
    constructor(@Inject('sourceFiles') private sourceFiles: any) {
        sourceFiles.files = [ 'seat-data.json'];
    };
    // custom code end

}

// syncfusionejs2_trial/Samples/Vue/source/maps/seat-selection.vue
<template>
<main><div>
<div class="col-lg-9 control-section">
        <div style="width:200px;margin:auto;padding-bottom:20px">
            <img src="src/maps/images/bus-icon.png" alt="Bus icon" style="width:25px;height:25px;float:left">
            <div style="padding-left:30px;font-size:20px;font-weight:400; font-family: Segoe UI;">Bus seat selection</div>
        </div>        
        <div style="border: 3px solid darkgray;width:200px;display:block;margin:auto;border-radius:5px">
            <img src="src/maps/images/wheel.png" alt="Steering wheel icon" style="width:30px;height:30px;margin-left:18%;margin-top:10px">
<ejs-maps ref="maps" id='maps' :load='load' :projectionType='projectionType' :itemSelection='itemSelection' :height='height' :zoomSettings='zoomSettings'>
    <e-layers>
        <e-layer :geometryType='geometryType' :shapeData='shapeData'  :selectionSettings='selectionSettings' :shapeSettings='shapeSettings'></e-layer>
    </e-layers>
</ejs-maps>           
        </div>
    </div>

    <div class="col-lg-3 property-section">
        <br/>
        <table role="none" id="property" title="Seat Selection" style="width: 100%;font-weight:400 !important">
            <br/>
            <tbody>
                <tr style="height: 30px">
                    <td>
                        <div style="height:0;width:15px;padding-bottom:5px;background-color:gray;border-radius:25%"></div>

                        <div id="available" style="margin-top: -25px;margin-left: 15px">Available</div>
                    </td>
                </tr>
                <tr style="height: 30px">
                    <td>
                        <div style="height:0;width:15px;padding-bottom:5px;background-color:Green;border-radius:25%"></div>

                        <div id="selected" style="margin-top: -25px;margin-left: 15px">Selected</div>
                    </td>
                </tr>
                <tr style="height: 30px">
                    <td>
                        <div style="height:0;width:15px;padding-bottom:5px;background-color:Orange;border-radius:25%"></div>

                        <div id="booked" style="margin-top: -25px;margin-left: 15px">Booked</div>
                    </td>
                </tr>
            </tbody>
        </table>
        </div>
        <div id="seat-parent">
            <span id='clear-btn' v-on:click="clickClear" >Clear Selection</span><br/><br/>
            <div id="selectedseats"></div>
        </div>
</div>
<section id="action-description" aria-label="Description of Maps sample">
                <p>
                    This sample visualizes a seating chart, in which the seats can be selected similarly to bus seat booking. Available, booked, and selected seats will be displayed in different colors.
                </p>	
</section>
<section id="description" aria-label="Description of the Maps features demonstrated in this sample">
            <p>
              In this example, you can see how to render the normal geometry type shapes on the map. Selection is enabled in this sample. You can use the <code>fill</code>, <code>width</code>, and <code>color</code> properties in the <code>selectionSettings</code> to customize the appearance of the shapes after selection.
            </p>
        <br/>
            <p style="font-weight: 500">Injecting Module</p>
            <p>
             Maps component features are segregated into individual feature-wise modules. To use the selection, inject the <code>Selection</code> module using the <code>Maps.Inject(Selection)</code> method.
            </p>       
        </section>
        </main>
</template>
<style scoped>
            #control-container {
                padding: 0px !important;
            }
            #seat-parent {
                text-align: center;
                cursor: pointer
            }
            #selectedseats {
                padding: 10px;                
            }
            #selectedseats, #seat-info {             
                font-size: 14px;
            }
            #clear-btn {
                padding: 10px;
                border: 2px solid rgb(241, 235, 247);
                border-radius: 8px;
                background: rgb(246, 245, 248);
                color: black;
                font-size: 14px;
            }
            .seats {
                padding-top: 15px;
                font-weight: bold;                
            }
            #property div{
                padding-left: 10px;
                padding-top: 10px;
            }
</style>
<script>
import { MapsComponent, LayersDirective, LayerDirective, Selection } from '@syncfusion/ej2-vue-maps';
import { seatData } from '../maps/map-data/seat';

export default {
  components: {
    'ejs-maps': MapsComponent,
    'e-layers': LayersDirective,
    'e-layer': LayerDirective
  },
  data:function(){
      return{
        projectionType: 'Equirectangular',
        height: '400',
        zoomSettings: {
            enable: false
        },
        geometryType: 'Normal',
        shapeData: seatData,
        shapeSettings: {
                    colorValuePath: 'fill'
        },
        selectionSettings: {
                    enable: true,
                    opacity: 1,
                    enableMultiSelect: true
        }
      }
  },
  provide:{
      maps:[Selection]
  },
methods:{
    /* custom code start */
   load: function(args) {
      let selectedTheme = location.hash.split("/")[1];
      selectedTheme = selectedTheme ? selectedTheme : "Material";
      args.maps.theme =
        (selectedTheme.charAt(0).toUpperCase() +
            selectedTheme.slice(1)).replace(/-dark/i, 'Dark').replace(/-high/i, 'High').replace(/contrast/i, 'Contrast').replace(/5.3/i, '5');
    },
    /* custom code end */
    itemSelection:function(args){
        let seatInfo = document.getElementById('selectedseats');
          if ((args.shapeData).fill === 'Orange') {
                args.fill = 'Orange !important';
                document.getElementById(args.target).setAttribute('class', 'ShapeselectionMapStyle');
                return;
            }
            args.fill = 'green';
            let seat = (args.shapeData).seatno;
            let connector = ' ';
            if (seatInfo.innerHTML === '') {
                seatInfo.innerHTML = '<span id="seat-info">Seats Selected -</span>';
            } else {
                connector = ', ';
            }
            let seatString = '<span class="seats">' + connector + seat + '</span>';
            let seatString1 = ' ' + seat + '</span><span class="seats">,';
            let lastString = '<span id="seat-info">Seats Selected -</span><span class="seats"> ' + seat + '</span>';
            if (seatInfo.innerHTML.indexOf(seatString) === -1 && seatInfo.innerHTML.indexOf(seatString1) === -1 &&
                seatInfo.innerHTML.indexOf(lastString) === -1) {
                seatInfo.innerHTML += '<span class="seats">' + connector + seat + '</span>';
            } else {
                seatInfo.innerHTML = seatInfo.innerHTML.replace(seatString, '');
                seatInfo.innerHTML = seatInfo.innerHTML.replace(seatString1, '');
                if (seatInfo.innerHTML === lastString) {
                    seatInfo.innerHTML = '';
                }
            }
    },
    clickClear:function(args){
        let seatInfo = document.getElementById('selectedseats');
        if (seatInfo.innerHTML === '') {
            return;
        }
        let seats = seatInfo.innerText.split('-')[1].trim().split(',').map(num => Number(num.trim()));
        for (let i = 0, length = seats.length; i < length; i++) {
            this.$refs.maps.ej2Instances.shapeSelection(0, 'seatno', seats[i], false);
        }
        seatInfo.innerHTML = '';
    }
}
}
</script>
