// syncfusionejs2_trial/Samples/Vue/public/source/mention/disabled-items.vue
<template>
<div>
	<div class="col-lg-12 control-section">
	    <div id="mention-disabled">
		<table>
		    <tr>
			<td>
			    <label id="disabled-size">Compose your content</label>
			    <div id="disabledMention" placeholder = "Type @ and tag user"></div>
			    <ejs-mention id='disabled' :target='target' mentionChar='@' :dataSource='data' :fields='mentionfields' allowSpaces='true' :itemTemplate="'iTemplate'" :displayTemplate="'dTemplate'" noRecordsTemplate="No item related to the search" popupWidth="250px" popupHeight="200px">
				<template v-slot:iTemplate="{ data }">
			                <div class="disabled_listItems">
			                    <img class="mentionEmpImage" :src="data.Eimg" alt="employee" />
			                    <div class="mention-text">
				                    <span class="person">{{ data.Name }}</span>
				                    <span class="email">{{ data.EmailId }}</span>
			                    </div>
			                </div>
		                </template>
				<template v-slot:dTemplate="{data}">{{data.Name}}</template>
			    </ejs-mention>
			</td>
		    </tr>
		</table>
	    </div>
	</div>

    <div id="action-description">
        <p>This sample showcases the disabled items of the Mention component. Type the <code>@</code> character in the editable element and you will notice that the disabled items are greyed out and cannot be selected.</p>
    </div>
    <div id="description">
        <p>The Mention provides options for individual items to be in either an enabled or disabled state for specific scenarios. Once an item is disabled, it cannot be select a particular item. To configure the disabled item columns, use the <b>fields.disabled</b> property.</p>
    </div>
</div>
</template>

<script>
import { MentionComponent } from "@syncfusion/ej2-vue-dropdowns";
import data from './dataSource.json';

export default {
        components: {
            'ejs-mention': MentionComponent
        },
        data: function() {
        return {
          mentionfields: { text: 'Name', disabled: 'State' },
          data: data['emailData2'],
          target: "#disabledMention",
        };
    }
}
</script>

<style scoped>

    #mention-disabled #disabledMention {
        min-height: 100px;
        border: 1px solid #D7D7D7;
        width: 600px;
        padding: 8px;
        font-size: 14px;
        border-radius: 4px;
    }
    #mention-disabled {
        margin: 0 auto;
        width: 600px;
    }
    .disabled_listItems {
	padding-left: 12px;
	vertical-align: middle;
	width: 80%;
        display: flex;
        align-items: center;
    }
     #disabledMention_popup .e-dropdownbase .e-list-item {
    	line-height: 25px;
    	text-indent: 8px;
      }
      #disabledMention_popup .mentionEmpImage {
	  width: 40px;
          height: 40px;
          border-radius: 50%;
          margin-right: 10px;
       }
    #disabledMention_popup .mention-text {
        display: flex;
        flex-direction: column; /* Name and email appear in separate lines */
    }
    #disabledMention_popup .person {
	font-size: 16px;
        font-weight: 500;
	}
    #disabledMention_popup .email {
	font-size: 14px;
    }
    div#disabledMention[placeholder]:empty:before {
        content: attr(placeholder);
        color: #555;
    }
    #mention-disabled #disabled-size{
        font-size: 15px;
	font-weight: 600;
    }
    @media screen and (max-width: 1010px) {
        #mention-disabled #disabledMention,
        #mention-disabled, #mention-disabled table {
            width: 100%;
        }
    }
    
</style>

// syncfusionejs2_trial/Samples/React/src/mention/disabled-items.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.DisabledItems = void 0;
var React = require("react");
var ej2_react_dropdowns_1 = require("@syncfusion/ej2-react-dropdowns");
var sample_base_1 = require("../common/sample-base");
require("./disabled-items.css");
var data = require("./dataSource.json");
var DisabledItems = /** @class */ (function (_super) {
    __extends(DisabledItems, _super);
    function DisabledItems() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        _this.temp = 'emailData2';
        _this.emailData = data[_this.temp];
        _this.disabledTarget = '#disabledMention';
        _this.disabledFields = { text: 'Name', disabled: 'State' };
        return _this;
    }
    DisabledItems.prototype.itemTemplate = function (data) {
        return (React.createElement("div", { className: "disabled_listItems" },
            React.createElement("img", { className: "mentionEmpImage", src: "src/mention/Employees/" + data['Eimg'] + ".png", alt: "employee" }),
            React.createElement("span", { className: "person" }, data.Name),
            React.createElement("span", { className: "email" }, data.EmailId)));
    };
    DisabledItems.prototype.displayTemplate = function (data) {
        return (React.createElement(React.Fragment, null, data.Name));
    };
    DisabledItems.prototype.render = function () {
        return (React.createElement("div", { className: 'control-pane' },
            React.createElement("div", { className: 'control-section' },
                React.createElement("div", { className: "content-wrapper" },
                    React.createElement("div", { id: 'mention_disabled' },
                        React.createElement("table", null,
                            React.createElement("tbody", null,
                                React.createElement("tr", null,
                                    React.createElement("td", null,
                                        React.createElement("label", { className: "disabled-size" }, "Compose your content"),
                                        React.createElement("div", { id: "disabledMention", placeholder: "Type @ and tag user" }))))),
                        React.createElement(ej2_react_dropdowns_1.MentionComponent, { dataSource: this.emailData, target: this.disabledTarget, fields: this.disabledFields, itemTemplate: this.itemTemplate, displayTemplate: this.displayTemplate, noRecordsTemplate: "No item related to the search", popupWidth: 250, popupHeight: 200 })))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null,
                    "This sample showcases the disabled items of the Mention component. Type the ",
                    React.createElement("code", null, "@"),
                    " character in the editable element and you will notice that the disabled items are greyed out and cannot be selected.")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null,
                    "The Mention provides options for individual items to be in either an enabled or disabled state for specific scenarios. Once an item is disabled, it cannot be select a particular item. To configure the disabled item columns, use the ",
                    React.createElement("b", null, "fields.disabled"),
                    " property."))));
    };
    return DisabledItems;
}(sample_base_1.SampleBase));
exports.DisabledItems = DisabledItems;
