// syncfusionejs2_trial/Samples/React/src/barcode/default-functionality.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.Default = void 0;
var React = require("react");
var ej2_react_dropdowns_1 = require("@syncfusion/ej2-react-dropdowns");
var ej2_react_inputs_1 = require("@syncfusion/ej2-react-inputs");
var ej2_react_barcode_generator_1 = require("@syncfusion/ej2-react-barcode-generator");
var sample_base_1 = require("../common/sample-base");
var ej2_react_inputs_2 = require("@syncfusion/ej2-react-inputs");
var ej2_inputs_1 = require("@syncfusion/ej2-inputs");
var ej2_react_buttons_1 = require("@syncfusion/ej2-react-buttons");
var canShowError = false;
var customFn = function (args) {
    if (canShowError) {
        return false;
    }
    return true;
};
var options = {
    rules: {
        'textbox_0': { minLength: [customFn, 'Invalid input'] },
    }
};
var Default = /** @class */ (function (_super) {
    __extends(Default, _super);
    function Default() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Default.prototype.rendereComplete = function () {
        var div = document.getElementsByClassName('sb-property-border')[0];
        this.formObject = new ej2_inputs_1.FormValidator('#form1', options);
        var input = document.getElementById("textbox_0");
        input.addEventListener('keydown', function (e) {
            if (e.key === 'Enter') {
                e.preventDefault();
            }
        });
        if (div)
            div.style.left = '63%';
    };
    //public canShowError: boolean = false;
    Default.prototype.render = function () {
        var _this = this;
        return (React.createElement("div", { className: "control-pane" },
            React.createElement("style", null, sample_css),
            React.createElement("div", { className: "col-lg-8 control-section", style: { width: "64%" } },
                React.createElement("div", { className: "content-wrapper", style: { width: "100%", height: "590px" } },
                    React.createElement("div", { className: 'center' },
                        React.createElement("div", { className: 'centercontrol' },
                            React.createElement(ej2_react_barcode_generator_1.BarcodeGeneratorComponent, { id: "barcode", ref: function (barcode) { return (barcodeInstance = barcode); }, width: "200px", invalid: function (arg) {
                                    canShowError = true;
                                    _this.formObject.validate();
                                }, height: "150px", mode: 'SVG', type: 'Codabar', value: '123456789' }))),
                    React.createElement("div", { className: 'allowedText' },
                        React.createElement("span", { style: { fontWeight: 600 } }, " Allowed Input characters :"),
                        " support 16 letters: 0-9, -, $, :, /, ., + and start/stop characters A-D'"))),
            React.createElement("div", { className: "col-lg-4 property-section", style: { paddingRight: "0px", minWidth: "36%" } },
                React.createElement("div", { className: "property-panel-header" }, "Appearance"),
                React.createElement("div", { id: "propertypanel" },
                    React.createElement("div", { className: "property-section-content" },
                        React.createElement("div", { className: "row sb-child-row" },
                            React.createElement("div", { className: "col-xs-2 top left" }, "Value"),
                            React.createElement("div", { className: "col-xs-10 left" },
                                React.createElement("form", { id: "form1", method: "post" },
                                    React.createElement("div", { id: 'barcodevaluediv' },
                                        React.createElement(ej2_react_inputs_1.TextBoxComponent, { ref: function (value) { return (barcodeValueInstance = value); }, value: '123456789', id: 'textbox_0', change: valueOnChange })))))),
                    React.createElement("div", { className: "row sb-child-row" },
                        React.createElement("div", null,
                            React.createElement("div", { className: "col-xs-2 top left" }, "Width"),
                            React.createElement("div", { className: "col-xs-4 left" },
                                React.createElement(ej2_react_inputs_2.NumericTextBoxComponent
                                //ref={widthRef => (portWidthNum = widthRef)}
                                , { 
                                    //ref={widthRef => (portWidthNum = widthRef)}
                                    id: "width", width: 100, enabled: true, format: "###.##", value: 200, step: 2, min: 150, max: 250, change: barcodewidthChange })),
                            React.createElement("div", { className: "col-xs-2 top left" }, "Height"),
                            React.createElement("div", { className: "col-xs-4 left" },
                                React.createElement(ej2_react_inputs_2.NumericTextBoxComponent
                                //ref={widthRef => (portWidthNum = widthRef)}
                                , { 
                                    //ref={widthRef => (portWidthNum = widthRef)}
                                    id: "width", width: 100, enabled: true, format: "###.##", value: 150, step: 2, min: 100, max: 200, change: barcodeheightChange })))),
                    React.createElement("div", { className: "row sb-child-row", style: { marginTop: "20px" } },
                        React.createElement("div", { className: "col-xs-6 left" },
                            React.createElement("div", { className: "col-xs-12 left" },
                                React.createElement(ej2_react_buttons_1.CheckBoxComponent, { id: "textVisibility", checked: true, change: textVisibility }),
                                React.createElement("div", { style: { display: "inline-block", verticalAlign: "middle", paddingLeft: "4px" } }, "Text Visibility"))),
                        React.createElement("div", { className: "col-xs-6 left" },
                            React.createElement("div", { className: "col-xs-12 left" },
                                React.createElement(ej2_react_buttons_1.CheckBoxComponent, { id: "svgMode", checked: true, change: modeChange }),
                                React.createElement("div", { style: { display: "inline-block", verticalAlign: "middle", paddingLeft: "4px" } }, "SVG Mode")))),
                    React.createElement("div", { className: "row sb-child-row" },
                        React.createElement("div", { style: { marginTop: "5px" } },
                            React.createElement("div", { className: "col-xs-3 top left" }, "BG Color"),
                            React.createElement("div", { className: "col-xs-3 left" },
                                React.createElement(ej2_react_inputs_2.ColorPickerComponent, { id: "bgcolor", value: "#000", change: barCodeColorChange })),
                            React.createElement("div", { className: "col-xs-3 top left" }, "Fore Color"),
                            React.createElement("div", { className: "col-xs-3 left" },
                                React.createElement(ej2_react_inputs_2.ColorPickerComponent, { id: "forecolor", value: "#000", change: foreColorChange })))),
                    React.createElement("div", { className: "property-panel-header" }, "Margin"),
                    React.createElement("div", { className: "row sb-child-row" },
                        React.createElement("div", { className: "col-xs-2 top left" }, "Left"),
                        React.createElement("div", { className: "col-xs-4 left" },
                            React.createElement(ej2_react_inputs_2.NumericTextBoxComponent, { id: "marginLeft", enabled: true, format: "###.##", value: 10, step: 1, min: -10, max: 30, change: barcodeMarginLeft })),
                        React.createElement("div", { className: "col-xs-2 top left" }, "Right"),
                        React.createElement("div", { className: "col-xs-4 left" },
                            React.createElement(ej2_react_inputs_2.NumericTextBoxComponent, { id: "marginRight", enabled: true, format: "###.##", value: 10, step: 1, min: -10, max: 30, change: barcodeMarginRight }))),
                    React.createElement("div", { className: "row sb-child-row" },
                        React.createElement("div", { className: "col-xs-2 top left" }, "Top"),
                        React.createElement("div", { className: "col-xs-4 left" },
                            React.createElement("div", { style: { paddingBottom: '8px' } },
                                React.createElement(ej2_react_inputs_2.NumericTextBoxComponent, { id: "marginbottom", enabled: true, format: "###.##", value: 10, step: 1, min: -10, max: 30, change: barcodeMarginTop }))),
                        React.createElement("div", { className: "col-xs-2 top left" }, "Bottom"),
                        React.createElement("div", { className: "col-xs-4 left" },
                            React.createElement(ej2_react_inputs_2.NumericTextBoxComponent, { id: "marginBottom", enabled: true, format: "###.##", value: 10, step: 1, min: -10, max: 30, change: barcodeMarginBottom })))),
                React.createElement("div", { className: "property-panel-header" }, " Text Properties"),
                React.createElement("div", { className: "row sb-child-row" },
                    React.createElement("div", { className: "col-xs-2 top left" }, "Top"),
                    React.createElement("div", { className: "col-xs-4 left" },
                        React.createElement(ej2_react_inputs_2.NumericTextBoxComponent, { id: "TextmarginTop", enabled: true, format: "###.##", value: 0, step: 1, min: -10, max: 20, change: TextmarginTopChange })),
                    React.createElement("div", { className: "col-xs-2 top left" }, "Bottom"),
                    React.createElement("div", { className: "col-xs-4 left" },
                        React.createElement(ej2_react_inputs_2.NumericTextBoxComponent, { id: "TextmarginTop", enabled: true, format: "###.##", value: 0, step: 1, min: -10, max: 20, change: TextmarginBottomChangeChange }))),
                React.createElement("div", { className: "row sb-child-row" },
                    React.createElement("div", { className: "col-xs-3 top left" }, "Position"),
                    React.createElement("div", { className: "col-xs-9" },
                        React.createElement(ej2_react_dropdowns_1.DropDownListComponent, { id: "position", popupWidth: 150, width: "100%", value: 'Bottom', index: 0, dataSource: positionList, change: updatePosition, ref: function (fontfamily) { return (position = fontfamily); } }))),
                React.createElement("div", { className: "row sb-child-row" },
                    React.createElement("div", { className: "col-xs-3 top left" }, "Alignment"),
                    React.createElement("div", { className: "col-xs-9" },
                        React.createElement(ej2_react_dropdowns_1.DropDownListComponent, { id: "position", popupWidth: 150, width: "100%", value: 'Center', index: 0, dataSource: alignmentValue, change: updateAlignment, ref: function (fontfamily) { return (alignment = fontfamily); } }))),
                React.createElement("div", { className: "row sb-child-row" },
                    React.createElement("div", { className: "col-xs-3 top left" }, "Display Text"),
                    React.createElement("div", { className: "col-xs-9" },
                        React.createElement(ej2_react_inputs_1.TextBoxComponent, { ref: function (value) { return (barcodetextInstance = value); }, value: '123456789', change: textOnChange }))),
                React.createElement("div", { className: "row sb-child-row" },
                    React.createElement("div", { className: "col-xs-6 top barcode-panel-left" },
                        React.createElement(ej2_react_buttons_1.ButtonComponent, { id: "downloadBtn1", onClick: function () {
                                barcodeInstance.exportImage("Barcode", "PNG");
                            } }, "Download")))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null, "This sample visualizes a barcode that is designed to be accurately read even when printed with dot matrix printers. This type of barcode is widely used in applications that require serial numbers, such as blood bank management, slips for door-to door delivery services, and member cards.")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null, "This sample shows a codabar with a character set of 16 letters with four start and stop characters. The `type` property can be used to set the barcode type as `Codabar`."),
                React.createElement("br", null))));
    };
    return Default;
}(sample_base_1.SampleBase));
exports.Default = Default;
var sample_css = " \n.column-style {\n  display: table;\n  height: 35px;\n  padding-right: 4px;\n  padding-left: 0px;\n  width: calc((100% - 12px) / 3);\n}\n\n.row {\n  margin-left: 0px;\n  margin-right: 0px;\n}\n\n.row-header {\n  font-size: 15px;\n  font-weight: 500;\n}\n\n.labelstyle {\n  padding-top: 10px;\n  float: left;\n  padding-right: 10px\n}\n\n.propertystyle {\n  padding-top: 22px;\n  font-weight: 600;\n  font-size: 15px;\n}\n\n.sb-child-row {\n  margin-top: 8px;\n}\n\n.center {\n  margin-left: 14px;\n  margin-right: 17px;\n  margin-top: 14px;\n  min-width: 280px;\n  width: auto;\n  border: 2px solid lightgray;\n  min-height: 40%;\n  padding-top: 35px;\n}\n\n.col-lg-4-property-section {\n  width: 36%;\n}\n\n.rightProperty {\n  margin-top: 10px;\n  width: 16.66666667%;\n  float: left;\n  position: relative;\n  min-height: 1px;\n  padding-right: 15px;\n  padding-left: 15px;\n}\n\n.textProperty {\n  width: 81%;\n  padding-left: 0px;\n  padding-right: 0;\n  float: left;\n  position: relative;\n  min-height: 1px;\n}\n\n.sb-mobile-prop-pane .svgTextClass {\n  width: 40px;\n  padding-left: 24px;\n}\n\n.svgTextClass {\n  width: 100px;\n  float: left;\n  position: relative;\n  min-height: 1px;\n  padding-right: 15px;\n  padding-left: 15px;\n}\n\n\n\n.sb-mobile-prop-pane .rightProperty {\n  padding-left: 2px;\n}\n\n.sb-mobile-prop-pane .textPropertyClass {\n  padding-left: 30px;\n}\n\n.sb-mobile-prop-pane .textProperty {\n  padding-left: 30px;\n  width: 77%\n}\n\n.textPropertyClass {\n  width: 83.33333333%;\n  float: left;\n  padding-left: 0px;\n  position: relative;\n  min-height: 1px;\n  padding-right: 15px;\n}\n\n.allowedText {\n  margin-left: 14px;\n  margin-right: 17px;\n  margin-top: 14px;\n  width: auto;\n  height: auto;\n}\n\n.errorMessage {\n  margin-left: 14px;\n  margin-right: 17px;\n  margin-top: 14px;\n  width: auto;\n  height: auto;\n}\n\n.errorMessage {\n  margin-left: 14px;\n  margin-right: 17px;\n  margin-top: 14px;\n  width: auto;\n  height: auto;\n}\n\n\n.top {\n  margin-top: 10px;\n}\n\n.left {\n  padding-left :0px;\n}\n\n.centercontrol {\n  margin: auto;\n  width: 200px;\n  height: 150px;\n}\n\n#password-info {\n  position: absolute;\n  margin-top: 30px;\n}\n.sb-child-row {\n  margin-top: 8px;\n}\n\n\n.sb-property-border sb-prop-md-4{\n  left: 64%\n}\n\n.property-panel-header {\n  padding-top: 15px;\n  padding-bottom: 15px;\n}\n\n\n.row-header {\n  font-size: 13px;\n  font-weight: 500;\n  padding-left: 10px\n}\n\n\n.center {\n  margin-left: 14px;\n  margin-right: 17px;\n  margin-top: 14px;\n  min-width: 280px;\n  width: auto;\n  border: 2px solid lightgray;\n  min-height: 40%;\n  padding-top: 35px;\n}\n";
var barcodeInstance;
var position;
var alignment;
var barcodeValueInstance;
var barcodetextInstance;
function valueOnChange(args) {
    var divElement = document.getElementById('barcodevaluediv');
    divElement.children[0].className = 'e-input-group e-control-wrapper';
    barcodeValueInstance.cssClass = 'e-input-group e-control-wrapper';
    barcodeValueInstance.dataBind();
    barcodeInstance.value = args.value.toString();
    barcodetextInstance.value = args.value.toString();
}
var positionList = [
    { type: 'Bottom', text: 'Bottom' },
    { type: 'Top', text: 'Top' },
];
var alignmentValue = [
    { type: 'Left', text: 'Left' },
    { type: 'Right', text: 'Right' },
    { type: 'Center', text: 'Center' },
];
function barcodewidthChange(args) {
    barcodeInstance.width = args.value.toString();
}
function barcodeheightChange(args) {
    barcodeInstance.height = args.value.toString();
}
function textVisibility(args) {
    barcodeInstance.displayText.visibility = args.checked;
}
function modeChange(args) {
    barcodeInstance.mode = args.checked ? 'SVG' : 'Canvas';
}
function barCodeColorChange(args) {
    barcodeInstance.backgroundColor = args.currentValue.hex;
}
function foreColorChange(args) {
    barcodeInstance.foreColor = args.currentValue.hex;
}
function barcodeMarginLeft(args) {
    barcodeInstance.margin.left = args.value;
}
function barcodeMarginRight(args) {
    barcodeInstance.margin.right = args.value;
}
function barcodeMarginTop(args) {
    barcodeInstance.margin.top = args.value;
}
function barcodeMarginBottom(args) {
    barcodeInstance.margin.bottom = args.value;
}
function TextmarginTopChange(args) {
    barcodeInstance.displayText.margin.top = args.value;
}
function TextmarginBottomChangeChange(args) {
    barcodeInstance.displayText.margin.bottom = args.value;
}
function updatePosition(value) {
    var positionValue = value.value;
    barcodeInstance.displayText.position = (positionValue);
}
function updateAlignment(value) {
    var alignnValue = value.value;
    barcodeInstance.displayText.alignment = (alignnValue);
}
function textOnChange(args) {
    barcodeInstance.displayText.text = args.value.toString();
}

// syncfusionejs2_trial/Samples/Vue/public/source/barcode/default-functionality.vue
<template>
  <div class="control-section">
    <div class="col-lg-8 control-section" style="width: 64%">
      <div
        class="barcodecenter"
        style="margin-left: 14px ;Margin-right:17px;padding-left: 16%;padding-bottom: 7%; margin-top:14px;min-width: 280px ;width: auto; border: 2px solid lightgray;min-height: 40%;padding-top: 35px;"
      >
        <div class="centercontrol" style=" margin: auto; width: 50%;height: 50%;">
          <ejs-barcodegenerator
            id="barcode"
            ref="barcodeControl"
            :width="width"
            :height="height"
            :type="type"
            :value="value"
            :mode="mode"
          ></ejs-barcodegenerator>
        </div>
      </div>
    </div>
    <div
      class="col-lg-4 property-section"
      style="width: 36%;padding-right: 0px;
padding-left: 18px;"
    >
      <div class="property-panel-header">Appearance</div>
      <div id="propertypanel" class="e-remove-selection"></div>
      <div class="property-section-content">
        <div class="row sb-child-row">
          <div class="col-xs-2 top barcode-panel-left"> Value </div>
          <div class="col-xs-10 barcode-panel-left">
            <div id="barcodevaluediv">
              <ejs-textbox id="textbox" value="11223344" :change="textboxchange"></ejs-textbox>
            </div>
          </div>
        </div>
        <div class="row sb-child-row">
          <div>
            <div class="col-xs-2 top barcode-panel-left"> Width </div>
            <div class="col-xs-4 barcode-panel-left" >
              <ejs-numerictextbox
                ref="widthObj"
                id="width"
                format="###.##"
                :value="200"
                :step="2"
                :min="150"
                :max="250"
                :change="widthchange"
              ></ejs-numerictextbox>
            </div>
          </div>
          <div>
            <div class="col-xs-2 top barcode-panel-left"> Height </div>
            <div class="col-xs-4 barcode-panel-left" >
              <ejs-numerictextbox
                ref="heightObj"
                id="height"
                format="###.##"
                value="150"
                :step="2"
                :min="100"
                :max="200"
                :change="heightchange"
              ></ejs-numerictextbox>
            </div>
          </div>
        </div>

        <div class="row sb-child-row" style="padding-top: 10px">
          <div class="col-xs-6 barcode-panel-left">
            <div class="col-xs-2 barcode-panel-left">
              <ejs-checkbox id="textVisibility" :checked="true" :change="textVisibilitychange"></ejs-checkbox>
            </div>
            <div class="col-xs-10 barcode-panel-left">Text Visibility</div>
          </div>
          <div class="col-xs-6 barcode-panel-left">
            <div class="col-xs-2 barcode-panel-left" >
              <ejs-checkbox id="svgMode" :checked="true" :change="svgModechange"></ejs-checkbox>
            </div>
            <div class="col-xs-10 barcode-panel-left">SVG Mode</div>
          </div>
        </div>

        <div class="row sb-child-row">
          <div style="padding-top: 10px;">
            <div class="col-xs-3 barcode-panel-left" style="padding-top: 5px;">BG Color</div>
            <div class="col-xs-3 barcode-panel-left" >
              <ejs-colorpicker
                ref="bgColor"
                id="bgColor"
                :value="bgcolorvalue"
                :change="bgColorchange"
              ></ejs-colorpicker>
            </div>
            <div class="col-xs-3 barcode-panel-left" style="padding-top: 5px;">Fore Color</div>
            <div class="col-xs-3 barcode-panel-left">
              <ejs-colorpicker
                ref="foreColor"
                id="foreColor"
                :value="fontcolorvalue"
                :change="foreColorchange"
              ></ejs-colorpicker>
            </div>
          </div>
        </div>

        <div class="property-panel-header">Margin</div>
        <div class="row sb-child-row">
          <div class="col-xs-2 top barcode-panel-left">Left</div>
          <div class="col-xs-4 barcode-panel-left">
            <ejs-numerictextbox
              id="marginLeft"
              format="###.##"
              value="10"
              :step="1"
              :min="-10"
              :max="30"
              :change="MarginLeftchange"
            ></ejs-numerictextbox>
          </div>
          <div class="col-xs-2 top barcode-panel-left" >Right</div>
          <div class="col-xs-4 barcode-panel-left">
            <ejs-numerictextbox
              id="MarginRight"
              format="###.##"
              value="10"
              :step="1"
              :min="-10"
              :max="30"
              :change="MarginRightchange"
            ></ejs-numerictextbox>
          </div>
        </div>
        <div class="row sb-child-row">
          <div class="col-xs-2 top barcode-panel-left">Top</div>
          <div class="col-xs-4 barcode-panel-left" >
            <div style="padding-bottom: 8px">
              <ejs-numerictextbox
                id="marginTop"
                format="###.##"
                value="10"
                :step="1"
                :min="-10"
                :max="30"
                :change="MarginTopchange"
              ></ejs-numerictextbox>
            </div>
          </div>
          <div class="col-xs-2 top barcode-panel-left" >Bottom</div>
          <div class="col-xs-4 barcode-panel-left">
            <ejs-numerictextbox
              id="MarginBottom"
              format="###.##"
              value="10"
              :step="1"
              :min="-10"
              :max="30"
              :change="MarginBottomchange"
            ></ejs-numerictextbox>
          </div>

          <div class="property-panel-header">Text Properties</div>
          <div class="row sb-child-row">
            <div class="col-xs-2 top barcode-panel-left" >Top</div>
            <div class="col-xs-4 barcode-panel-left">
              <ejs-numerictextbox
                id="TextmarginTop"
                format="###.##"
                value="0"
                :step="1"
                :min="-10"
                :max="20"
                :change="TextMarginTopchange"
              ></ejs-numerictextbox>
            </div>
            <div class="col-xs-2 top barcode-panel-left" >Bottom</div>
            <div class="col-xs-4 barcode-panel-left">
              <ejs-numerictextbox
                id="TextMarginBottom"
                format="###.##"
                value="0"
                :step="1"
                :min="-10"
                :max="20"
                :change="TextMarginBottomchange"
              ></ejs-numerictextbox>
            </div>
          </div>

          <div class="row sb-child-row">
            <div class="col-xs-3 top barcode-panel-left"> Position </div>
            <div class="col-xs-9 ">
              <ejs-dropdownlist
                ref="textPosition"
                id="textPosition"
                :dataSource="textPositiondataSource"
                :fields="ftextPositionfields"
                :popupWidth="150"
                :width="textPositionwidth"
                value="Bottom"
                :index="0"
                :change="textPositionchange"
              />
            </div>
          </div>

          <div class="row sb-child-row">
            <div class="col-xs-3 top barcode-panel-left">Alignment</div>
            <div class="col-xs-9 ">
                <ejs-dropdownlist
                  ref="textAlignment"
                  id="textAlignment"
                  :dataSource="textAlignmentdataSource"
                  :fields="ftextPositionfields"
                  :popupWidth="150"
                  :width="textPositionwidth"
                  value="Center"
                  :index="0"
                  :change="textAlignmentchange"
                />
            </div>
          </div>
          <div class="row sb-child-row">
            <div class="col-xs-3 top barcode-panel-left">Display Text</div>
            <div class="col-xs-9">
              <ejs-textbox id="displayText" value="11223344" :change="displayTextchange"></ejs-textbox>
            </div>
          </div>
          <div class="row sb-child-row">
            <div class="col-xs-6 top barcode-panel-left">
                <ejs-button id="downloadButton" :onClick="onDownloadbuttonClick">Download</ejs-button>
            </div>
        </div>
        </div>
      </div>
    </div>
    <div id="action-description">
      <p>This sample visualizes the processing of an order placed using credit card with built-in flow shapes.</p>
    </div>
    <div id="description">
      <p>
        This example shows how to create a simple flow chart using the diagram control. The
        <code>nodes</code> property can be used to define different stages of a process. To define the flow between different stages, the
        <code>connectors</code> property can be used. The
        <code>getNodeDefaults</code> and
        <code>getConnectorDefaults</code> properties define the default behavior of shapes and connectors.
      </p>

      <p>
        To easily build flow diagrams, few shapes are predefined and added to symbol palette. You can drag-and-drop predefined shapes into the drawing area. The
        <code>symbols</code> property allows you to add predefined symbols to the palette.
      </p>

      <p>In this example, undo and redo support is enabled.</p>
      <p style="font-weight: 500">Injecting Module</p>
      <p>
        The diagram component’s features are segregated into individual feature-wise modules. To enable undo and redo support, inject
        <code>UndoRedo</code> module using
        <code>provide: { diagram: [UndoRedo] }</code> method.
      </p>
      <br>
    </div>
  </div>
</template>
<style>
.row {
  margin-left: 0px;
  margin-right: 0px;
}
.top {
  margin-top: 10px;
}
.column-style {
  display: table;
  height: 35px;
  padding-right: 4px;
  padding-left: 0px;
  width: calc((100% - 12px) / 3);
}

.row {
  margin-left: 0px;
  margin-right: 0px;
}

.row-header {
  font-size: 15px;
  font-weight: 500;
}

.labelstyle {
  padding-top: 10px;
  float: left;
  padding-right: 10px;
}

.propertystyle {
  padding-top: 22px;
  font-weight: 600;
  font-size: 15px;
}

.sb-child-row {
  margin-top: 8px;
}

.barcodecenter {
  margin-left: 14px;
  margin-right: 17px;
  margin-top: 14px;
  min-width: 280px;
  width: auto;
  border: 2px solid lightgray;
  min-height: 40%;
  padding-top: 35px;
}

.col-lg-4-property-section {
  width: 36%;
}

.rightProperty {
  margin-top: 10px;
  width: 16.66666667%;
  float: left;
  position: relative;
  min-height: 1px;
  padding-right: 15px;
  padding-left: 15px;
}

.textProperty {
  width: 81%;
  padding-left: 0px;
  padding-right: 0;
  float: left;
  position: relative;
  min-height: 1px;
}

.sb-mobile-prop-pane .svgTextClass {
  width: 40px;
  padding-left: 24px;
}

.svgTextClass {
  width: 100px;
  float: left;
  position: relative;
  min-height: 1px;
  padding-right: 15px;
  padding-left: 15px;
}

.sb-mobile-prop-pane .rightProperty {
  padding-left: 2px;
}

.sb-mobile-prop-pane .textPropertyClass {
  padding-left: 30px;
}

.sb-mobile-prop-pane .textProperty {
  padding-left: 30px;
  width: 77%;
}

.textPropertyClass {
  width: 83.33333333%;
  float: left;
  padding-left: 0px;
  position: relative;
  min-height: 1px;
  padding-right: 15px;
}

.allowedText {
  margin-left: 14px;
  margin-right: 17px;
  margin-top: 14px;
  width: auto;
  height: auto;
}

.errorMessage {
  margin-left: 14px;
  margin-right: 17px;
  margin-top: 14px;
  width: auto;
  height: auto;
}

.errorMessage {
  margin-left: 14px;
  margin-right: 17px;
  margin-top: 14px;
  width: auto;
  height: auto;
}

.top {
  margin-top: 10px;
}

.barcode-panel-left {
  padding-left: 0px;
}

.centercontrol {
  margin: auto;
  height: 150px;
  width: 200px;
}

</style>


<script>
import { CheckBoxComponent, ButtonComponent } from "@syncfusion/ej2-vue-buttons";
import { BarcodeGeneratorComponent } from "@syncfusion/ej2-vue-barcode-generator";
import {
  NumericTextBoxComponent,
  TextBoxComponent,
  ColorPickerComponent,
  FormValidator
} from "@syncfusion/ej2-vue-inputs";
import { DropDownListComponent } from "@syncfusion/ej2-vue-dropdowns";

let isMobile;
let barCodeInstance;
let textPositiondataSourceValue = [
  { type: "Bottom", text: "Bottom" },
  { type: "Top", text: "Top" }
];

let textAlignmentdataSourceValue = [
  { type: "Center", text: "Center" },
  { type: "Left", text: "Left" },
  { type: "Right", text: "Right" }
];

export default {
  components: {
    'ejs-numerictextbox': NumericTextBoxComponent,
    'ejs-barcodegenerator': BarcodeGeneratorComponent,
    'ejs-checkbox': CheckBoxComponent,
    'ejs-colorpicker': ColorPickerComponent,
    'ejs-textbox': TextBoxComponent,
    'ejs-dropdownlist': DropDownListComponent,
    'ejs-button': ButtonComponent
  },
  data: function() {
    return {
      width: "200px",
      height: "150px",
      mode: "SVG",
      type: "Codabar",
      value: "123456789",
      bgcolorvalue: "#fff",
      fontcolorvalue: "#000",
      textPositionwidth: "100%",
      ftextPositionfields: { value: "type", text: "text" },
      textPositiondataSource: textPositiondataSourceValue,
      textAlignmentdataSource: textAlignmentdataSourceValue,
      textboxchange: arg => {
        barCodeInstance.value = arg.value;
      },
      widthchange: arg => {
        barCodeInstance.width = arg.value;
      },
      heightchange: arg => {
        barCodeInstance.height = arg.value;
      },
      textVisibilitychange: arg => {
        barCodeInstance.displayText.visibility = arg.checked;
      },
      svgModechange: arg => {
        barCodeInstance.mode = arg.checked ? "SVG" : "Canvas";
      },
      bgColorchange: arg => {
        barCodeInstance.backgroundColor = arg.currentValue.hex;
      },
      foreColorchange: arg => {
        barCodeInstance.foreColor = arg.currentValue.hex;
      },
      MarginLeftchange: arg => {
        barCodeInstance.margin.left = arg.value;
      },
      MarginRightchange: arg => {
        barCodeInstance.margin.right = arg.value;
      },
      MarginTopchange: arg => {
        barCodeInstance.margin.top = arg.value;
      },
      MarginBottomchange: arg => {
        barCodeInstance.margin.bottom = arg.value;
      },
      TextMarginTopchange: arg => {
        barCodeInstance.displayText.margin.top = arg.value;
      },
      TextMarginBottomchange: arg => {
        barCodeInstance.displayText.margin.bottom = arg.value;
      },
      textPositionchange: arg => {
        barCodeInstance.displayText.position = arg.value;
      },
      textAlignmentchange: arg => {
        barCodeInstance.displayText.alignment = arg.value;
      },
      displayTextchange: arg => {
        barCodeInstance.displayText.text = arg.value.toString();
      },
      onDownloadbuttonClick: arg=>{
        barCodeInstance.exportImage("Barcode", "PNG");
      },
      created: args => {
        addEvents();
      }
    };
  },
  mounted: function() {
    barCodeInstance = this.$refs.barcodeControl.ej2Instances;
    let input = document.getElementById("textbox");
    input.addEventListener('keydown', (e) => {
        if (e.key === 'Enter') {
          e.preventDefault()
        }
    });
  }
};
</script>
