// syncfusionejs2_trial/Samples/React/src/block-editor/pasteSettings.jsx
import * as React from 'react';
import { BlockEditorComponent } from '@syncfusion/ej2-react-blockeditor';
import { DropDownListComponent } from '@syncfusion/ej2-react-dropdowns';
import { TextBoxComponent } from '@syncfusion/ej2-react-inputs';
import { SampleBase } from '../common/sample-base';
import './pasteSettings.css';
import * as data from './blockData.json';
export class PasteSettings extends SampleBase {
    blockEditorRef = React.createRef();
    formatOptionRef = React.createRef();
    deniedTagsRef = React.createRef();
    pasteSettings = {
        deniedTags: ['script', 'iframe'],
        plainText: false,
        keepFormat: true,
        allowedStyles: []
    };
    formatData = [
        { Id: 'plainText', Format: 'Plain Text' },
        { Id: 'keepFormat', Format: 'Keep Format' }
    ];
    fields = { text: 'Format', value: 'Id' };
    height = '200px';
    value = 'keepFormat';
    formatChange = () => {
        if (!this.blockEditorRef.current) {
            return;
        }
        const newPasteSettings = { ...this.pasteSettings };
        if (this.formatOptionRef.current?.value === 'plainText') {
            newPasteSettings.plainText = true;
            newPasteSettings.keepFormat = false;
        }
        else if (this.formatOptionRef.current?.value === 'keepFormat') {
            newPasteSettings.plainText = false;
            newPasteSettings.keepFormat = true;
        }
        this.pasteSettings = newPasteSettings;
        this.blockEditorRef.current.dataBind();
    };
    deniedTagChange = () => {
        if (!this.deniedTagsRef.current?.value)
            return;
        this.onPasteCleanupSettingsChange(this.deniedTagsRef.current.value);
    };
    onPasteCleanupSettingsChange = (value) => {
        if (!this.blockEditorRef.current) {
            return;
        }
        if (value) {
            const arrayValue = value.split(',').map(item => item.trim().replace(/^['"]|['"]$/g, ''));
            this.pasteSettings.deniedTags = arrayValue.filter(prop => prop !== '');
            this.blockEditorRef.current.dataBind();
        }
    };
    render() {
        return (<div className='control-pane'>
                <div className="col-lg-8 control-section">
                    <div className="blockeditor-paste">
                        <BlockEditorComponent ref={this.blockEditorRef} id='block-editor' height="600px" blocks={data["blockDataPaste"]} pasteCleanupSettings={this.pasteSettings}/>
                    </div>
                </div>
                <div className="col-lg-4 property-section">
                    <div className="property-panel-header">
                        <div id="property" title="Properties" className="property-panel-table">
                            <table id="property" title="Properties">
                                <tbody>
                                    <tr>
                                        <td>
                                            <div>Format Option</div>
                                        </td>
                                        <td>
                                            <div>
                                                <DropDownListComponent id='formatOption' ref={this.formatOptionRef} dataSource={this.formatData} change={this.formatChange} value={this.value} fields={this.fields} popupHeight={this.height}/>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div>Denied Tags</div>
                                        </td>
                                        <td>
                                            <div>
                                                <TextBoxComponent ref={this.deniedTagsRef} cssClass="e-input" placeholder="'img[!href]', 'h1'" blur={this.deniedTagChange}/>
                                            </div>
                                        </td>
                                    </tr>
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <div id="action-description">
                    <p>
                        This sample demonstrates the Block Editor <code>pasteCleanupSettings</code> property allows you to define various options to control how content is pasted into the editor.
                    </p>
                </div>

                <div id="description">
                    <p>The following settings are available to cleanup the content in pasteCleanup settings property:</p>
                    <ul>
                        <li>Select any option in <code>Format Option</code> drop down list for the paste content.</li>
                        <ul>
                            <li>Select the <code>Plain Text</code> option to paste the content as plain text.</li>
                            <li>Select the <code>Keep Format</code> option to keep the same format in the copied content.</li>
                        </ul>
                        <li>Fill the <code>denied tags</code> text box to ignore the tags when pasting HTML content.</li>
                        <ul>
                            <li><code>['a[!href]']</code> - paste the content by filtering anchor tags that don’t have the 'href' attribute.</li>
                            <li><code>['a[href, target]']</code> - paste the content by filtering anchor tags that have the 'href' and 'target' attributes</li>
                        </ul>
                    </ul>
                </div>
            </div>);
    }
}

// syncfusionejs2_trial/Samples/Angular/source/block-editor/pasteSettings.component.ts
import { Component, ViewChild, ViewEncapsulation } from '@angular/core';
import { BlockEditor, BlockEditorModule, BlockModel, PasteCleanupSettingsModel } from '@syncfusion/ej2-angular-blockeditor';
import { DropDownListComponent, FieldSettingsModel, DropDownListModule } from '@syncfusion/ej2-angular-dropdowns';
import { TextBoxComponent, TextBoxModule } from '@syncfusion/ej2-angular-inputs';
import { isNullOrUndefined } from '@syncfusion/ej2-base';
import blockData from './blockData.json';

@Component({
    selector: 'app-root',
    templateUrl: 'pasteSettings.html',
    styleUrls: ['pasteSettings.component.css'],
    encapsulation: ViewEncapsulation.None,
    standalone: true,
    imports: [BlockEditorModule, DropDownListModule, TextBoxModule]
})
export class BlockEditorPasteSettingsComponent {

    @ViewChild('pasteBlockEditor')
    public blockEditorObj: BlockEditor;

    @ViewChild('formatOption')
    public formatObj?: DropDownListComponent;

    @ViewChild('deniedTags')
    public deniedTags?: TextBoxComponent;


    public blockDataPaste: BlockModel[] = blockData.blockDataPaste as BlockModel[];

    public pasteSettings: PasteCleanupSettingsModel = {
        deniedTags: ['script', 'iframe'],
        plainText: false,
        keepFormat: true,
        allowedStyles: []
    };

    public formatData: { [key: string]: Object }[] = [
        { Id: 'plainText', Format: 'Plain Text' },
        { Id: 'keepFormat', Format: 'Keep Format' }
    ];

    public fields: FieldSettingsModel = { text: 'Format', value: 'Id' };
    public height: string = '200px';
    public value: string = 'keepFormat';

    // Toggle paste behavior based on dropdown selection
    public formatChange(): void {
        if (!this.blockEditorObj) {
            console.warn('BlockEditorComponent is not available yet.');
            return;
        }
        if (this.formatObj?.value === 'plainText') {
            this.blockEditorObj.pasteCleanupSettings.plainText = true;
            this.blockEditorObj.pasteCleanupSettings.keepFormat = false;
        } else if (this.formatObj?.value === 'keepFormat') {
            this.blockEditorObj.pasteCleanupSettings.plainText = false;
            this.blockEditorObj.pasteCleanupSettings.keepFormat = true;
        }
        this.blockEditorObj.dataBind();
    }

    // update denied tags properties from a comma-separated textbox
    public deniedTagChange(): void {
        if (!this.deniedTags?.value) return;
        this.onPasteCleanupSettingsChange(this.deniedTags.value);
    }


    // Update the specified paste settings property with parsed array value and rebind the editor
    public onPasteCleanupSettingsChange(value: any): void {
        if (!this.blockEditorObj) {
            console.warn('BlockEditorComponent is not available yet.');
            return;
        }
        if (!isNullOrUndefined(value)) {
            const arrayValue = value.split(',').map((item: string) => item.trim().replace(/^['"]|['"]$/g, ''));
            this.blockEditorObj.pasteCleanupSettings.deniedTags = arrayValue.filter((prop: string) => prop !== '');
            this.blockEditorObj.dataBind();
        }
    }
}
