// syncfusionejs2_trial/Samples/React/src/dialog/template.jsx
import * as React from 'react';
import { DialogComponent } from '@syncfusion/ej2-react-popups';
import { SanitizeHtmlHelper } from '@syncfusion/ej2-base';
import { SampleBase } from '../common/sample-base';
import './template.css';
export class Template extends SampleBase {
    dialogInstance;
    proxy;
    buttonRef;
    buttonElement;
    constructor(props) {
        super(props);
        this.state = {
            hideDialog: true
        };
        this.buttonElement = null;
        this.buttonRef = element => {
            this.buttonElement = element;
        };
    }
    header() {
        return (<div>
            <span className="e-avatar template-image e-avatar-xsmall e-avatar-circle"></span>
            <div id="dlg-template" title="Nancy" className="e-icon-settings">Nancy</div>
        </div>);
    }
    footerTemplate() {
        return (<div>
                <input id="inVal" className="e-input" type="text" placeholder="Enter your message here!"/>
                <button id="sendButton" className="e-control e-btn e-primary" data-ripple="true">Send</button>
            </div>);
    }
    content() {
        return (<div className="dialogContent">
                <span className="dialogText">Greetings Nancy! When will you share me the source files of the project?</span>
            </div>);
    }
    buttonClick() {
        this.setState({ hideDialog: true });
    }
    dialogClose() {
        this.setState({ hideDialog: false });
        this.buttonElement.style.display = 'inline-block';
    }
    dialogOpen() {
        this.setState({ hideDialog: true });
        this.buttonElement.style.display = 'none';
    }
    updateTextValue() {
        let enteredVal = document.getElementById('inVal');
        let dialogTextElement = document.getElementsByClassName('dialogText')[0];
        if (enteredVal.value !== '') {
            dialogTextElement.innerHTML = SanitizeHtmlHelper.sanitize(enteredVal.value);
        }
        enteredVal.value = '';
    }
    rendereComplete() {
        this.proxy = this;
        this.dialogInstance.target = document.getElementById('target');
        document.getElementById('sendButton').onkeydown = (e) => {
            if (e.keyCode === 13) {
                this.updateTextValue();
            }
        };
        document.getElementById('inVal').onkeydown = (e) => {
            if (e.keyCode === 13) {
                this.updateTextValue();
            }
        };
        document.getElementById('sendButton').onclick = () => {
            this.updateTextValue();
        };
    }
    render() {
        return (<div className='control-pane'>
        <div className='control-section row'>
            <div id='target' className='col-lg-12 target-element'>
            <button className="e-control e-btn dlgbtn dlgbtn-position" ref={this.buttonRef} onClick={this.buttonClick.bind(this)}>Open</button>
            <DialogComponent header={this.header} footerTemplate={this.footerTemplate} content={this.content} showCloseIcon={true} ref={dialog => this.dialogInstance = dialog} target='#target' width={'437px'} open={this.dialogOpen.bind(this)} close={this.dialogClose.bind(this)} height={'255px'} visible={this.state.hideDialog}></DialogComponent>
            </div>
        </div>
        <div id="action-description">
        <p>
            This example demonstrates the template functionalities of the dialog component. The dialog's header and footer is configured with HTML template. 
            The typed content will be replaced every time when clicking the "send" button.
        </p>
        </div>
        <div id="description">
        <p>
            The dialog component displays HTML template content on the header and footer. The user can set any HTML element as header and footer with the usage of content and footer template properties.
        </p>
        <p>
            More information on the modal behavior of Dialog can be found in
            the <a target="_blank" href="https://ej2.syncfusion.com/react/documentation/dialog/template/">
            documentation section</a>.
        </p>
        </div>
      </div>);
    }
}

// syncfusionejs2_trial/Samples/Vue/public/source/dialog/template.vue
<template>
  <div>
     <div class="col-lg-12 control-section dialog-template">
        <ejs-button id='dlgbtn' v-if="ShowBtn" v-on:click="BtnClick">Open</ejs-button>
        <ejs-dialog :header="'headerTemplate'" ref="dialogObj" :footerTemplate="'footerTemplate'" :content="'contentTemplate'" :height='height' :animationSettings='animationSettings' :showCloseIcon='showCloseIcon' :target='target' :width='width' :open="dialogOpen"
            :close="dialogClose">
            <template v-slot:headerTemplate>
            <span id="container">
                <div class="e-avatar template-image e-avatar-xsmall e-avatar-circle"></div>
                <div id="dlg-template" title="Nancy" class="e-icon-settings"> Nancy </div>
            </span>
            </template>
            <template v-slot:footerTemplate>
            <div id="container">
                <input id="inVal" class="e-input" type="text" placeholder="Enter your message here!"/>
                <button id="sendButton" class="e-control e-btn e-primary sendButton" data-ripple="true">Send</button>
            </div>
            </template>
            <template v-slot:contentTemplate>
            <div id="container">
                <div class="dialogContent">
                <span class="dialogText">Greetings Nancy! When will you share me the source files of the project?</span></div>
            </div>
            </template>
        </ejs-dialog>
    </div>
    <div id="action-description">
        <p>
            This example demonstrates the template functionalities of the dialog component. The dialog's header and footer is configured with HTML template. The typed content will be replaced every time when clicking the "send" button.
        </p>
    </div>
    <div id="description">
        <p>
            The dialog component displays HTML template content on the header and footer. The user can set any HTML element as header and footer with the usage of content and footer template properties.
        </p>
    </div>
  </div>
</template>

<script>
import { DialogComponent } from '@syncfusion/ej2-vue-popups';
import { ButtonComponent } from '@syncfusion/ej2-vue-buttons';
import { detach, isNullOrUndefined, SanitizeHtmlHelper } from '@syncfusion/ej2-base';

export default {
    components: {
      'ejs-dialog': DialogComponent,
      'ejs-button': ButtonComponent
    },
    data: function() {
        return {
            proxy: this,
            showCloseIcon: true,
            height: '75%',
            target: '.control-section',
            animationSettings:  { effect: 'None' },
            width:  '435px',
            ShowBtn: false            
        }
    },
    methods: {
        dialogClose: function() {
            this.ShowBtn = true;
        },    
        BtnClick: function() {
            this.$refs.dialogObj.show();
        },
        dialogOpen: function() {
            this.ShowBtn = false;
            document.getElementById('sendButton').keypress = (e) => {
                if (e.keyCode === 13) { this.updateTextValue(); }
            };    
            document.getElementById('inVal').onkeydown = (e) => {
                if (e.keyCode === 13) { this.updateTextValue(); }
            };    
            document.getElementById('sendButton').onclick = () => {
                this.updateTextValue();
            };
        },
        changePosition: function(event) {
            this.$refs.dialogObj.position = { X: event.value.split(" ")[0], Y: event.value.split(" ")[1] };
            document.getElementById('posvalue').innerHTML = 'Position: {X: "' + event.value.split(" ")[0] + '", Y: "' + event.value.split(" ")[1] + '"}'
            var txt = event.target.parentElement.querySelector('.e-label').innerText.split(" ");
            document.getElementById('posvalue').innerHTML = 'Position: { X: "' + txt[0] + '", Y: "' + txt[1] + '" }';
        },
        updateTextValue: function() {
            var enteredVal = document.getElementById('inVal');
            var dialogTextElement = document.getElementsByClassName('dialogText')[0];
            if (!isNullOrUndefined(document.getElementsByClassName('contentText')[0])) {
                detach(document.getElementsByClassName('contentText')[0]);
            }
            if (enteredVal.value !== '') {
                dialogTextElement.innerHTML = SanitizeHtmlHelper.sanitize(enteredVal.value);
            }
            enteredVal.value = '';
        }
    }
}
</script>

<style>
    .highcontrast .dialog-template .e-dialog .e-dlg-header-content {
        background-color: #ffd939;
    }
    .fabric .dialog-template .e-dialog .e-dlg-header-content {
        background-color: #0078d7;
    }

	.tailwind .dialog-template .e-dialog .e-dlg-header-content,
    .tailwind-dark .dialog-template .e-dialog .e-dlg-header-content,
    .tailwind3 .dialog-template .e-dialog .e-dlg-header-content,
    .tailwind3-dark .dialog-template .e-dialog .e-dlg-header-content,
    .bootstrap5 .dialog-template .e-dialog .e-dlg-header-content,
    .bootstrap5-dark .dialog-template .e-dialog .e-dlg-header-content,
    .material .dialog-template .e-dialog .e-dlg-header-content,
    .material3 .dialog-template .e-dialog .e-dlg-header-content {
        background-color: #3f51b5;
    }
    .bootstrap .dialog-template .e-dialog .e-dlg-header-content {
        background-color: #428bca;
    }
    .bootstrap4 .dialog-template .e-dialog .e-dlg-header-content {
        background-color: #007bff;
    }
    .dialog-template .e-dlg-header-content .e-btn.e-dlg-closeicon-btn {
        top: 5px;
        left: -11px;
    }
    .fluent .dialog-template .e-dlg-header-content .e-btn.e-dlg-closeicon-btn {
        top: 3px;
        left: 0px;
    }
    .e-bigger .dialog-template .e-dialog .e-dlg-header-content .e-btn.e-dlg-closeicon-btn {
        top: 3px;
        left: -11px;
    }
    .bootstrap4 .dialog-template .e-dlg-header-content .e-btn.e-dlg-closeicon-btn,
    .bootstrap4.e-bigger .dialog-template .e-dialog .e-dlg-header-content .e-btn.e-dlg-closeicon-btn {
        top: 8px;
    }

    .dialog-template .e-dialog .e-dlg-header {
        position: relative;
    }
    .dialog-template .e-dialog .e-footer-content {
        padding: 10px 13px 13px;
    }
    .dialog-template .e-dialog .e-dlg-content {
        padding: 0;
    }
    .dialog-template button#sendButton, .dialog-template .highcontrast button#sendButton {
        top: -2px;
        position: relative;
    }

    .dialog-template button#sendbtn, .dialog-template .highcontrast button#sendbtn {
        top: -2px;
    }

    .dialog-template input.e-input {
        width: 62%;
        float: left;
    }
    .dialog-template .e-dialog .e-dlg-header-content {
        padding: 6px;
    }
    .dialog-template .e-open-icon::before {
        content: '\e782';
    }
    .dialog-template img.img2 {
        height: 36px;
        width: 36px;
        border-radius: 50%;
        vertical-align: middle;
    }
    .dialog-template #dlg-template {
        display: inline-block;
        padding: 0px 10px;
        vertical-align: middle;
        height: 40px;
        line-height: 40px;
    }
    .dialog-template input.e-input {
        width: 75%;
        float: left;
    }
    .dialog-template .e-icon-settings.e-icons {
        float: left;
        position: relative;
        left: 14%;
        top: -33px;
    }
    .dialog-template .e-icon-settings.e-icons {
        top: -37px;
    }
    .dialog-template .dialogContent .dialogText {
        font-size: 13px;
        padding: 5%;
        word-wrap: break-word;
        border-radius: 6px;
        text-align: justify;
        font-style: initial;
        display: block;
    }
    .dialog-template .e-dlg-header .e-icon-settings, .dialog-template .e-icon-btn {
        color: #fff;
    }
    .material .dialog-template .e-dialog .e-footer-content, .fabric .dialog-template .e-dialog .e-footer-content {
        border-top: 0.5px solid rgba(0, 0, 0, 0.42);
    }
    .highcontrast .dialog-template .e-dialog .e-footer-content{
        border-top: 0.5px solid #fff;
    }
    .bootstrap4 .dialog-template .e-dialog .e-footer-content{
        border-top: 1px solid #e9ecef;
    }
    .bootstrap5 .dialog-template .e-dialog .e-footer-content {
        border-top: 1px solid #dee2e6;
    }
    .bootstrap5-dark .dialog-template .e-dialog .e-footer-content {
        border-top: 1px solid #444c54;
    }
    .highcontrast .dialog-template .dialogContent .dialogText{
        background-color: #bfbfbf;
    }
    .dialog-template .dialogContent .dialogText, .dialog-template .dialogContent .dialogText  {
        background-color: #f5f5f5;
    }
    .material-dark .dialog-template .dialogContent .dialogText,
    .material3-dark .dialog-template .dialogContent .dialogText,
    .fabric-dark .dialog-template .dialogContent .dialogText,
    .bootstrap-dark .dialog-template .dialogContent .dialogText,
    .bootstrap5-dark .dialog-template .dialogContent .dialogText,
    .tailwind-dark .dialog-template .dialogContent .dialogText,
    .tailwind3-dark .dialog-template .dialogContent .dialogText,
    .fluent-dark .dialog-template .dialogContent .dialogText {
        background-color: rgba(255,255,255,0.20);
        color: #ffff;
    }
    .dialog-template .dialogContent {
        display: block;
        font-size: 15px;
        word-wrap: break-word;
        text-align: center;
        font-style: italic;
        border-radius: 6px;
        padding: 3%;
        position: relative;
        top: 25px;
    }
    .control-wrapper .dialog-template .e-control.e-dialog {
        width: 30%;
    }
    .fabric .dialog-template .e-dialog .e-btn.e-dlg-closeicon-btn:hover span {
        color: #8ECBFF;
    }
    .dialog-template .e-dialog .e-dlg-header-content .e-icon-dlg-close {
        color: #fff;
    }
    .material .dialog-template .e-dialog .e-dlg-header-content .e-btn.e-dlg-closeicon-btn:hover,
    .material .dialog-template .e-dialog .e-dlg-header-content .e-btn.e-dlg-closeicon-btn:focus {
        background-color: rgba(255,255,255, 0.10);
    }
    .bootstrap4 .dialog-template .e-dialog .e-dlg-header-content .e-btn.e-dlg-closeicon-btn:hover,
    .bootstrap4 .dialog-template .e-dialog .e-dlg-header-content .e-btn.e-dlg-closeicon-btn:focus {
        background-color : transparent;
    }

    .tailwind .dialog-template .e-dialog .e-dlg-header-content .e-btn.e-dlg-closeicon-btn:hover,
    .tailwind .dialog-template .e-dialog .e-dlg-header-content .e-btn.e-dlg-closeicon-btn:focus,
    .tailwind-dark .dialog-template .e-dialog .e-dlg-header-content .e-btn.e-dlg-closeicon-btn:hover,
    .tailwind-dark .dialog-template .e-dialog .e-dlg-header-content .e-btn.e-dlg-closeicon-btn:focus,
    .tailwind3 .dialog-template .e-dialog .e-dlg-header-content .e-btn.e-dlg-closeicon-btn:hover,
    .tailwind3 .dialog-template .e-dialog .e-dlg-header-content .e-btn.e-dlg-closeicon-btn:focus,
    .tailwind3-dark .dialog-template .e-dialog .e-dlg-header-content .e-btn.e-dlg-closeicon-btn:hover,
    .tailwind3-dark .dialog-template .e-dialog .e-dlg-header-content .e-btn.e-dlg-closeicon-btn:focus,
    .bootstrap5 .dialog-template .e-dialog .e-dlg-header-content .e-btn.e-dlg-closeicon-btn:hover,
    .bootstrap5 .dialog-template .e-dialog .e-dlg-header-content .e-btn.e-dlg-closeicon-btn:focus,
    .bootstrap5-dark .dialog-template .e-dialog .e-dlg-header-content .e-btn.e-dlg-closeicon-btn:hover,
    .bootstrap5-dark .dialog-template .e-dialog .e-dlg-header-content .e-btn.e-dlg-closeicon-btn:focus,
    .bootstrap5\.3 .dialog-template .e-dialog .e-dlg-header-content .e-btn.e-dlg-closeicon-btn:hover,
    .bootstrap5\.3 .dialog-template .e-dialog .e-dlg-header-content .e-btn.e-dlg-closeicon-btn:focus,
    .bootstrap5\.3-dark .dialog-template .e-dialog .e-dlg-header-content .e-btn.e-dlg-closeicon-btn:hover,
    .bootstrap5\.3-dark .dialog-template .e-dialog .e-dlg-header-content .e-btn.e-dlg-closeicon-btn:focus {
        background-color : transparent;
    }

    .material .dialog-template .e-dialog .e-dlg-header-content .e-btn.e-dlg-closeicon-btn:active .e-icon-dlg-close,
    .material .dialog-template .e-dialog .e-dlg-header-content .e-btn.e-dlg-closeicon-btn:focus .e-icon-dlg-close,
    .material .dialog-template .e-dialog .e-dlg-header-content .e-btn.e-dlg-closeicon-btn:hover .e-icon-dlg-close {
        color: #fff;
    }
    .dialog-template .e-dialog .e-dlg-header-content .e-dlg-header .e-avatar.template-image {
        background-image: url('./images/dialog-img1.png');
        vertical-align: middle;
        display: inline-block;
        width: 36px;
        height: 36px;
    }

    .control-section {
        height: 100%;
        min-height: 350px;
    }
</style>
