// syncfusionejs2_trial/Samples/React/src/chart/column-sorting.tsx
import * as React from 'react';
import { ChartComponent, SeriesCollectionDirective, SeriesDirective, Inject, ColumnSeries, Category, DataLabel, ILoadedEventArgs, IPointRenderEventArgs, IAxisRangeCalculatedEventArgs, ChartTheme, sort } from '@syncfusion/ej2-react-charts';
import { EmitType, Browser } from '@syncfusion/ej2-base';
import { fabricColors, materialColors, bootstrapColors, highContrastColors, fluent2Colors, fluent2DarkColors } from './theme-color';

const SAMPLE_CSS = `
  .control-fluid {
    padding: 0px !important;
  }
`;

const labelRender: EmitType<IPointRenderEventArgs> = (args: IPointRenderEventArgs): void => {
    let selectedTheme: string = location.hash.split('/')[1];
    selectedTheme = selectedTheme ? selectedTheme : 'Fluent2';
    if (selectedTheme && selectedTheme.indexOf('fabric') > -1) {
        args.fill = fabricColors[args.point.index % 10];
    } else if (selectedTheme === 'material') {
        args.fill = materialColors[args.point.index % 10];
    } else if (selectedTheme === 'highcontrast') {
        args.fill = highContrastColors[args.point.index % 10];
    } else if (selectedTheme === 'fluent2') {
        args.fill = fluent2Colors[args.point.index % 10];
    } else if (selectedTheme === 'fluent2-dark') {
        args.fill = fluent2DarkColors[args.point.index % 10];
    } else {
        args.fill = bootstrapColors[args.point.index % 10];
    }
};

let updatedData: Object[] = [
    { x: 'Inida', y: 97.21 },
    { x: 'France', y: 95.21 },
    { x: 'Indonesia', y: 62.74 },
    { x: 'Iceland', y: 61.71 },
    { x: 'United States', y: 57.97 },
    { x: 'Greece', y: 57.51 },
    { x: 'Iran', y: 55.31 },
    { x: 'Canada', y: 48.76 },
    { x: 'Finland', y: 48.50 },
    { x: 'Brazil', y: 45.13 },

];
let updatedData2: Object[] = [
    { x: 'Inida', y: 102.54 },
    { x: 'France', y: 90.76 },
    { x: 'Indonesia', y: 64.61 },
    { x: 'Iceland', y: 70.95 },
    { x: 'United States', y: 61.52 },
    { x: 'Greece', y: 49.03 },
    { x: 'Iran', y: 33.05 },
    { x: 'Canada', y: 59.83 },
    { x: 'Finland', y: 43.13 },
    { x: 'Brazil', y: 55.56 },
];
let updatedData3: Object[] = [
    { x: 'Inida', y: 99.33 },
    { x: 'France', y: 94.50 },
    { x: 'Indonesia', y: 64.86 },
    { x: 'Iceland', y: 77.86 },
    { x: 'United States', y: 62.14 },
    { x: 'Greece', y: 47.73 },
    { x: 'Iran', y: 39.97 },
    { x: 'Canada', y: 66.53 },
    { x: 'Finland', y: 43.15 },
    { x: 'Brazil', y: 50.02 }
];
let updatedData4: Object[] = [
    { x: 'Inida', y: 98.85 },
    { x: 'France', y: 101.11 },
    { x: 'Indonesia', y: 60.72 },
    { x: 'Iceland', y: 71.09 },
    { x: 'United States', y: 60.97 },
    { x: 'Greece', y: 52.07 },
    { x: 'Iran', y: 37.99 },
    { x: 'Canada', y: 58.35 },
    { x: 'Finland', y: 43.41 },
    { x: 'Brazil', y: 58.61 }
];
let updatedData5: Object[] = [
    { x: 'Inida', y: 100.02 },
    { x: 'France', y: 100.55 },
    { x: 'Indonesia', y: 62.84 },
    { x: 'Iceland', y: 89.05 },
    { x: 'United States', y: 59.46 },
    { x: 'Greece', y: 54.04 },
    { x: 'Iran', y: 42.58 },
    { x: 'Canada', y: 59.90 },
    { x: 'Finland', y: 46.18 },
    { x: 'Brazil', y: 65.06 }
];
let updatedData6: Object[] = [
    { x: 'Inida', y: 102.54 },
    { x: 'France', y: 103.56 },
    { x: 'Indonesia', y: 60.23 },
    { x: 'Iceland', y: 94.00 },
    { x: 'United States', y: 59.39 },
    { x: 'Greece', y: 50.11 },
    { x: 'Iran', y: 34.23 },
    { x: 'Canada', y: 60.40 },
    { x: 'Finland', y: 44.73 },
    { x: 'Brazil', y: 50.04 }
];
let updatedData7: Object[] = [
    { x: 'Inida', y: 98.84 },
    { x: 'France', y: 101.95 },
    { x: 'Indonesia', y: 60.86 },
    { x: 'Iceland', y: 89.51 },
    { x: 'United States', y: 58.26 },
    { x: 'Greece', y: 53.20 },
    { x: 'Iran', y: 34.28 },
    { x: 'Canada', y: 57.22 },
    { x: 'Finland', y: 42.99 },
    { x: 'Brazil', y: 51.68 }
];
let updatedData8: Object[] = [
    { x: 'Inida', y: 100.41 },
    { x: 'France', y: 108.54 },
    { x: 'Indonesia', y: 56.44 },
    { x: 'Iceland', y: 107.98 },
    { x: 'United States', y: 57.75 },
    { x: 'Greece', y: 56.34 },
    { x: 'Iran', y: 35.53 },
    { x: 'Canada', y: 57.49 },
    { x: 'Finland', y: 43.32 },
    { x: 'Brazil', y: 64.56 }
];
let updatedData9: Object[] = [
    { x: 'Inida', y: 104.45 },
    { x: 'France', y: 102.07 },
    { x: 'Indonesia', y: 61.19 },
    { x: 'Iceland', y: 97.05 },
    { x: 'United States', y: 59.53 },
    { x: 'Greece', y: 55.61 },
    { x: 'Iran', y: 41.84 },
    { x: 'Canada', y: 64.13 },
    { x: 'Finland', y: 43.69 },
    { x: 'Brazil', y: 64.73 }
];
let updatedData10: Object[] = [
    { x: 'Inida', y: 111.84 },
    { x: 'France', y: 95.53 },
    { x: 'Indonesia', y: 55.15 },
    { x: 'Iceland', y: 85.79 },
    { x: 'United States', y: 59.53 },
    { x: 'Greece', y: 58.93 },
    { x: 'Iran', y: 46.53 },
    { x: 'Canada', y: 59.52 },
    { x: 'Finland', y: 45.67 },
    { x: 'Brazil', y: 67.84 }
];

class UpdateColumnDataSource extends React.Component<{}, {}> {
    private chart: ChartComponent;
    private intervalId: any;
    private yearIndex: number = 2;

    private updateClearInterval = (): void => {
        if (this.intervalId) {
            clearInterval(this.intervalId);
            this.intervalId = null;
        }
    }

    private load = (args: ILoadedEventArgs): void => {
        let selectedTheme: string = location.hash.split('/')[1];
        selectedTheme = selectedTheme ? selectedTheme : 'Fluent2';
        args.chart.theme = (selectedTheme.charAt(0).toUpperCase() +
            selectedTheme.slice(1)).replace(/-dark/i, 'Dark').replace(/contrast/i, 'Contrast').replace(/-highContrast/i, 'HighContrast') as ChartTheme;
        
        this.updateClearInterval();
        this.intervalId = setInterval(() => {
            let container: HTMLElement = document.getElementById('data-sorting-container');
            if (container && container.id === args.chart.element.id) {
                let newData: Object[] = (eval('updatedData' + this.yearIndex) || []).map((item: { x: string; y: number; }) => {
                    return { x: item.x, y: item.y };
                });
                if (this.chart.series.length > 0) {
                    let newSource: Object[] = sort(newData, ['y'], true);
                    this.chart.series[0].setData(newSource, 1400);
                }
                this.yearIndex = this.yearIndex < 10 ? this.yearIndex + 1 : 2;
            } else {
                this.updateClearInterval();
            }
        }, 2000);
    }

    private axisRangeCalculated = (args: IAxisRangeCalculatedEventArgs): void => {
        if (args.axis.name === 'primaryYAxis') {
            if (args.maximum > 120) {
                args.interval = 30;
            } else {
                args.interval = 20;
            }
        }
    }

    render() {
        return (
            <div className='control-pane'>
                <style>{SAMPLE_CSS}</style>
                <div className='control-section row'>
                    <ChartComponent
                        id='data-sorting-container'
                        style={{ textAlign: 'center' }} 
                        ref={chart => this.chart = chart as ChartComponent}
                        primaryXAxis={{
                            valueType: 'Category',
                            majorGridLines: { width: 0 },
                            border: { width: 0 },
                            lineStyle: { width: 0 },
                            majorTickLines: { width: 0 },
                            labelRotation: 90
                        }}
                        primaryYAxis={{
                            interval: 20,
                            title: 'Nitrogen Fertilizer Use (kg/ha)',
                            labelFormat: '{value}',
                            border: { width: 0 },
                            lineStyle: { width: 0 },
                            majorTickLines: { width: 0 }
                        }}
                        chartArea={{ border: { width: 0 } }}
                        title='Nitrogen Fertilizer Use per Hectare of Cropland'
                        pointRender={labelRender}
                        width={Browser.isDevice ? '100%' : '75%'}
                        load={this.load}
                        axisRangeCalculated={this.axisRangeCalculated}
                    >
                        <Inject services={[ColumnSeries, Category, DataLabel]} />
                        <SeriesCollectionDirective>
                            <SeriesDirective
                                dataSource={updatedData}
                                xName='x'
                                yName='y'
                                type='Column'
                                animation={{ enable: true }}
                                marker={{ visible: false, dataLabel: { visible: true, position: 'Top', format: '{value}', font: { color: '#ffffff' } } }}
                                cornerRadius={{ topLeft: 5, topRight: 5 }}
                                columnWidth={0.7}
                            />
                        </SeriesCollectionDirective>
                    </ChartComponent>
                </div>
                <div id="action-description">
                    <p>This example demonstrates the nitrogen fertilizer use per hectare of cropland using a column chart. The chart updates periodically to show different data sets.</p>
                </div>
                <div id="description">
                    <p>In this example, you can see how to render and configure a column chart. The chart updates its data dynamically based on intervals.</p>
                </div>
            </div>
        );
    }
}

export default UpdateColumnDataSource;

// syncfusionejs2_trial/Samples/Vue/src/chart/column-sorting.vue
<template>
    <div class="control-section">
        <div align='center'>
            <ejs-chart ref="chart" style='display:block' :theme='theme' :load='load' align='center'
                id='data-sorting-container' :title='title' :primaryXAxis='primaryXAxis' :primaryYAxis='primaryYAxis'
                :chartArea='chartArea' :width='width' :axisRangeCalculated='axisRangeCalculated' :pointRender='pointRender'>
                <e-series-collection>
                    <e-series :dataSource='updatedData' type='Column' xName='x' yName='y' :cornerRadius='cornerRadius'
                        columnWidth=0.7 :marker='marker' :animation='animation'> </e-series>
                </e-series-collection>
            </ejs-chart>
        </div>
        <div id="action-description">
            <p>
                This column chart demonstrates the dynamic sorting of data in real-time. The chart visualizes nitrogen
                fertilizer use per hectare of cropland, updating every few seconds to show sorted data from different
                datasets.
            </p>
        </div>
        <div id="description">
            <p>
                In this example, you can observe how the column chart updates dynamically with sorted data using the
                <code>setData</code> method. The data is sourced from multiple datasets, and the chart updates and sorts its
                data periodically to reflect the latest information.
            </p><br>
            <p style="font-weight: 500"><b>Injecting Module</b></p>
            <p>
                Chart component features are segregated into individual feature-wise modules. To use the column series, we
                need to inject the <code>ColumnSeries</code> module using <code>provide: { chart: [ColumnSeries] }</code>
                method.
            </p>
            <p>
                More information on the column series can be found in this
                <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/chart/chart-type/column"
                    aria-label="Navigate to the documentation for Column Chart in Vue Chart component">documentation
                    section</a>.
            </p>
        </div>
    </div>
</template>
  
<script>
import { Browser } from '@syncfusion/ej2-base';
import { ChartComponent, SeriesDirective, SeriesCollectionDirective, ColumnSeries, Category, DataLabel, sort } from "@syncfusion/ej2-vue-charts";
import { fabricColors, materialColors, bootstrapColors, highContrastColors, fluent2Colors, fluent2HighContrastColors } from './theme-color';

let selectedTheme = location.hash.split("/")[1];
selectedTheme = selectedTheme ? selectedTheme : "Material";
let theme = (selectedTheme.charAt(0).toUpperCase() + selectedTheme.slice(1))
    .replace(/-dark/i, "Dark")
    .replace(/contrast/i, 'Contrast')
    .replace(/-highContrast/i, 'HighContrast');

export default {
    components: {
        'ejs-chart': ChartComponent,
        'e-series-collection': SeriesCollectionDirective,
        'e-series': SeriesDirective
    },
    data: function () {
        return {
            theme: theme,
            updatedData: [
                { x: 'India', y: 97.21 },
                { x: 'France', y: 95.21 },
                { x: 'Indonesia', y: 62.74 },
                { x: 'Iceland', y: 61.71 },
                { x: 'United States', y: 57.97 },
                { x: 'Greece', y: 57.51 },
                { x: 'Iran', y: 55.31 },
                { x: 'Canada', y: 48.76 },
                { x: 'Finland', y: 48.50 },
                { x: 'Brazil', y: 45.13 }
            ],
            updatedData2: [
                { x: 'India', y: 102.54 },
                { x: 'France', y: 90.76 },
                { x: 'Indonesia', y: 64.61 },
                { x: 'Iceland', y: 70.95 },
                { x: 'United States', y: 61.52 },
                { x: 'Greece', y: 49.03 },
                { x: 'Iran', y: 33.05 },
                { x: 'Canada', y: 59.83 },
                { x: 'Finland', y: 43.13 },
                { x: 'Brazil', y: 55.56 }
            ],
            updatedData3: [
                { x: 'India', y: 99.33 },
                { x: 'France', y: 94.50 },
                { x: 'Indonesia', y: 64.86 },
                { x: 'Iceland', y: 77.86 },
                { x: 'United States', y: 62.14 },
                { x: 'Greece', y: 47.73 },
                { x: 'Iran', y: 39.97 },
                { x: 'Canada', y: 66.53 },
                { x: 'Finland', y: 43.15 },
                { x: 'Brazil', y: 50.02 }
            ],
            updatedData4: [
                { x: 'India', y: 98.85 },
                { x: 'France', y: 101.11 },
                { x: 'Indonesia', y: 60.72 },
                { x: 'Iceland', y: 71.09 },
                { x: 'United States', y: 60.97 },
                { x: 'Greece', y: 52.07 },
                { x: 'Iran', y: 37.99 },
                { x: 'Canada', y: 58.35 },
                { x: 'Finland', y: 43.41 },
                { x: 'Brazil', y: 58.61 }
            ],
            updatedData5: [
                { x: 'India', y: 100.02 },
                { x: 'France', y: 100.55 },
                { x: 'Indonesia', y: 62.84 },
                { x: 'Iceland', y: 89.05 },
                { x: 'United States', y: 59.46 },
                { x: 'Greece', y: 54.04 },
                { x: 'Iran', y: 42.58 },
                { x: 'Canada', y: 59.90 },
                { x: 'Finland', y: 46.18 },
                { x: 'Brazil', y: 65.06 }
            ],
            updatedData6: [
                { x: 'India', y: 102.54 },
                { x: 'France', y: 103.56 },
                { x: 'Indonesia', y: 60.23 },
                { x: 'Iceland', y: 94.00 },
                { x: 'United States', y: 59.39 },
                { x: 'Greece', y: 50.11 },
                { x: 'Iran', y: 34.23 },
                { x: 'Canada', y: 60.40 },
                { x: 'Finland', y: 44.73 },
                { x: 'Brazil', y: 50.04 }
            ],
            updatedData7: [
                { x: 'India', y: 98.84 },
                { x: 'France', y: 101.95 },
                { x: 'Indonesia', y: 60.86 },
                { x: 'Iceland', y: 89.51 },
                { x: 'United States', y: 58.26 },
                { x: 'Greece', y: 53.20 },
                { x: 'Iran', y: 34.28 },
                { x: 'Canada', y: 57.22 },
                { x: 'Finland', y: 42.99 },
                { x: 'Brazil', y: 51.68 }
            ],
            updatedData8: [
                { x: 'India', y: 100.41 },
                { x: 'France', y: 108.54 },
                { x: 'Indonesia', y: 56.44 },
                { x: 'Iceland', y: 107.98 },
                { x: 'United States', y: 57.75 },
                { x: 'Greece', y: 56.34 },
                { x: 'Iran', y: 35.53 },
                { x: 'Canada', y: 57.49 },
                { x: 'Finland', y: 43.32 },
                { x: 'Brazil', y: 64.56 }
            ],
            updatedData9: [
                { x: 'India', y: 104.45 },
                { x: 'France', y: 102.07 },
                { x: 'Indonesia', y: 61.19 },
                { x: 'Iceland', y: 97.05 },
                { x: 'United States', y: 59.53 },
                { x: 'Greece', y: 55.61 },
                { x: 'Iran', y: 41.84 },
                { x: 'Canada', y: 61.00 },
                { x: 'Finland', y: 44.94 },
                { x: 'Brazil', y: 66.34 }
            ],
            updatedData10: [
                { x: 'India', y: 100.89 },
                { x: 'France', y: 109.48 },
                { x: 'Indonesia', y: 60.33 },
                { x: 'Iceland', y: 108.85 },
                { x: 'United States', y: 58.82 },
                { x: 'Greece', y: 55.54 },
                { x: 'Iran', y: 34.77 },
                { x: 'Canada', y: 55.79 },
                { x: 'Finland', y: 45.03 },
                { x: 'Brazil', y: 61.27 }
            ],
            title: 'Nitrogen Fertilizer Use per Hectare of Cropland',
            primaryXAxis: {
                valueType: 'Category',
                majorGridLines: { width: 0 },
                border: { width: 0 },
                lineStyle: { width: 0 },
                majorTickLines: { width: 0 },
                labelRotation: -90
            },
            primaryYAxis: {
                interval: 20,
                title: 'Nitrogen Fertilizer Use (kg/ha)',
                labelFormat: '{value}',
                border: { width: 0 },
                lineStyle: { width: 0 },
                majorTickLines: { width: 0 }
            },
            chartArea: {
                border: {
                    width: 0
                }
            },
            width: Browser.isDevice ? '100%' : '75%',
            marker: { visible: false, dataLabel: { visible: true, position: 'Top', format: '{value}', font: { color: '#ffffff' } } },
            cornerRadius: { topLeft: 5, topRight: 5 },
            animation: { enable: true },
            yearIndex: 2,
            intervalId: null
        };
    },
    provide: {
        chart: [ColumnSeries, Category, DataLabel]
    },
    methods: {
        load: function (args) {
            this.updateClearInterval();
            this.intervalId = setInterval(() => {
                let container = document.getElementById('data-sorting-container');
                if (container && container.id === args.chart.element.id) {
                    let newData = (this['updatedData' + this.yearIndex] || []).map(item => ({
                        x: item.x,
                        y: item.y
                    }));
                    if (args.chart.series.length > 0) {
                        let newSource = sort(newData, ['y'], true);
                        args.chart.series[0].setData(newSource, 1400);
                    }
                    this.yearIndex = this.yearIndex < 10 ? this.yearIndex + 1 : 2;
                } else {
                    this.updateClearInterval();
                }
            }, 2000);
        },
        updateClearInterval() {
            if (this.intervalId) {
                clearInterval(this.intervalId);
                this.intervalId = null;
            }
        },
        axisRangeCalculated: function (args) {
            if (args.axis.name === 'primaryYAxis') {
                if (args.maximum > 120) {
                    args.interval = 30;
                }
                else {
                    args.interval = 20;
                }
            }
        },
        pointRender: function (args) {
            let selectedTheme = location.hash.split('/')[1];
            selectedTheme = selectedTheme ? selectedTheme : 'Material';
            if (selectedTheme && selectedTheme.indexOf('fabric') > -1) {
                args.fill = fabricColors[args.point.index % 10];
            } else if (selectedTheme === 'material') {
                args.fill = materialColors[args.point.index % 10];
            } else if (selectedTheme === 'highcontrast') {
                args.fill = highContrastColors[args.point.index % 10];
            } else if (selectedTheme === 'fluent2') {
                args.fill = fluent2Colors[args.point.index % 10];
            } else if (selectedTheme === 'fluent2-highcontrast' || selectedTheme === 'fluent2-dark') {
                args.fill = fluent2HighContrastColors[args.point.index % 10];
            } else {
                args.fill = bootstrapColors[args.point.index % 10];
            }
        }

    },

};
</script>

<style scoped>
.control-section {
    padding: 20px;
}
</style>
