// syncfusionejs2_trial/Samples/Vue/public/source/ai-treegrid/adaptive-datastructuring.vue
<template>
    <div class="control-pane">
      <div class="control-section">
        <img src="src/ai-treegrid/images/adaptive-datastructuring.gif" width="100%" height="100%" />
      </div>
      <AIToast />
      <div id="action-description">
        <p>
            This demo highlights the use of AI to structure and correct erroneous hierarchical data within a Tree Grid. The AI-powered prompt identifies and organizes data items into a hierarchical format by accurately establishing parent-child relationships, ensuring the data is properly nested and ready for display in the Tree Grid control.
        </p>
      </div>
      <div id="description">
        <p>
        Utilizing a specialized AI prompt, the system scans a dataset to identify and restructure hierarchical relationships between records. The AI meticulously corrects any misassigned relationships by adjusting the <code>ParentId</code> fields, aligning them with their respective top-level <code>CategoryId</code>. The resulting dataset, now properly organized, is then bound to the Tree Grid for a coherent and accurate display.
    </p>
    <p>
        Looking for the full Vue Tree Grid component overview, features, pricing, and documentation? Visit our <a target="_blank" href="https://www.syncfusion.com/vue-components/vue-tree-grid">Vue Tree Grid component</a> page.
    </p>
      </div>
    </div>
</template>

// syncfusionejs2_trial/Samples/React/src/ai-tree-grid/adaptive-datastructuring.tsx
import * as ReactDOM from 'react-dom';
import * as React from 'react';
import { SampleBase } from '../common/sample-base';
import { updateAISampleSection } from '../common/sample-base';
 /* custom code start*/
import AIToast from '../common/ai-toast';
/* custom code end*/

export class AdaptiveDataStructuring extends SampleBase<{}, {}> {
    componentDidMount() {
          updateAISampleSection(); 
    }

    render() {
        return (
            <div className='control-pane'>
                <div className='control-section'>
                    <img src={'src/ai-tree-grid/images/adaptive-datastructuring.gif'} width='100%' height='100%'></img>
                </div>

                <div id="action-description">
                    <p>
                        This demo highlights the use of AI to structure and correct erroneous hierarchical data within a Tree Grid. The AI-powered prompt identifies and organizes data items into a hierarchical format by accurately establishing parent-child relationships, ensuring the data is properly nested and ready for display in the Tree Grid component.
                    </p>
                    <p>To explore this and more Syncfusion React Smart AI integrations locally, check out our <a target='_blank'
                        href='' aria-label="Navigate to explore the syncfusion React AI Demos repository">GitHub
                        repository</a>.</p>
                </div>
                <div id='description'>
                    <p>
                        Utilizing a specialized AI prompt, the system scans a dataset to identify and restructure hierarchical relationships between records. The AI meticulously corrects any misassigned relationships by adjusting the <code>ParentId</code> fields, aligning them with their respective top-level <code>CategoryId</code>. The resulting dataset, now properly organized, is then bound to the Tree Grid for a coherent and accurate display.
                    </p>
                    <p>
                        Looking for the full React Tree Grid component overview, features, pricing, and documentation? Visit our <a target="_blank" href="https://www.syncfusion.com/react-components/react-tree-grid">React Tree Grid component</a> page.
                    </p>
                </div>
                <AIToast/> 
            </div>
        )
    }
}
