// syncfusionejs2_trial/Samples/React/src/breadcrumb/overflow-modes.jsx
import * as React from 'react';
import { BreadcrumbComponent, BreadcrumbItemDirective, BreadcrumbItemsDirective } from '@syncfusion/ej2-react-navigations';
import { ButtonComponent } from '@syncfusion/ej2-react-buttons';
import { getComponent } from '@syncfusion/ej2-base';
import { SampleBase } from '../common/sample-base';
import './overflow-modes.css';
export class OverflowModes extends SampleBase {
    btnClick() {
        let breadcrumb, breadcrumbInst, breadcrumbs = document.querySelector('.content-wrapper').getElementsByClassName("e-breadcrumb");
        for (let i = 0; i < breadcrumbs.length; i++) {
            breadcrumb = breadcrumbs[i];
            breadcrumbInst = getComponent(breadcrumb, 'breadcrumb');
            breadcrumbInst.activeItem = breadcrumbInst.items[breadcrumbInst.items.length - 1].text;
        }
    }
    render() {
        return (<div className='control-pane'>
        <div className="control-section">
          <div className="content-wrapper breadcrumb-control-wrapper">
            <div className="row material2">
              <div className="col-xs-12 col-sm-12 col-lg-12 col-md-12">
                <h5 style={{ display: "inline-block" }}>Overflow Mode - Hidden</h5>
                <ButtonComponent cssClass='e-small reset-btn' onClick={this.btnClick.bind(this)}>Reset State</ButtonComponent>
              </div>
            </div>
            <div className="row material2">
              <div className="col-xs-12 col-sm-12 col-lg-12 col-md-12">
                <BreadcrumbComponent enableNavigation={false} maxItems={3} overflowMode='Hidden'>
                  <BreadcrumbItemsDirective>
                    <BreadcrumbItemDirective text="Home" url="./"/>
                    <BreadcrumbItemDirective text="Breadcrumb" url="./breadcrumb"/>
                    <BreadcrumbItemDirective text="Default" url="./breadcrumb/default"/>
                    <BreadcrumbItemDirective text="Icons" url="./breadcrumb/icons"/>
                    <BreadcrumbItemDirective text="Navigation" url="./breadcrumb/navigation"/>
                    <BreadcrumbItemDirective text="Overflow" url="./breadcrumb/overflow"/>
                  </BreadcrumbItemsDirective>
                </BreadcrumbComponent>
              </div>
            </div>
            <div className="row material2">
              <div className="col-xs-12 col-sm-12 col-lg-12 col-md-12">
                <h5>Overflow Mode - Menu</h5>
              </div>
            </div>
            <div className="row material2">
              <div className="col-xs-12 col-sm-12 col-lg-12 col-md-12 e-bc-overflow">
                <BreadcrumbComponent enableNavigation={false} maxItems={3} overflowMode='Menu'>
                  <BreadcrumbItemsDirective>
                    <BreadcrumbItemDirective text="Home" url="./"/>
                    <BreadcrumbItemDirective text="Breadcrumb" url="./breadcrumb"/>
                    <BreadcrumbItemDirective text="Default" url="./breadcrumb/default"/>
                    <BreadcrumbItemDirective text="Icons" url="./breadcrumb/icons"/>
                    <BreadcrumbItemDirective text="Navigation" url="./breadcrumb/navigation"/>
                    <BreadcrumbItemDirective text="Overflow" url="./breadcrumb/overflow"/>
                  </BreadcrumbItemsDirective>
                </BreadcrumbComponent>
              </div>
            </div>
            <div className="row material2">
              <div className="col-xs-12 col-sm-12 col-lg-12 col-md-12">
                <h5>Overflow Mode - Collapsed</h5>
              </div>
            </div>
            <div className="row material2">
              <div className="col-xs-12 col-sm-12 col-lg-12 col-md-12">
              <BreadcrumbComponent enableNavigation={false} maxItems={3} overflowMode='Collapsed'>
                  <BreadcrumbItemsDirective>
                    <BreadcrumbItemDirective text="Home" url="./"/>
                    <BreadcrumbItemDirective text="Breadcrumb" url="./breadcrumb"/>
                    <BreadcrumbItemDirective text="Default" url="./breadcrumb/default"/>
                    <BreadcrumbItemDirective text="Icons" url="./breadcrumb/icons"/>
                    <BreadcrumbItemDirective text="Navigation" url="./breadcrumb/navigation"/>
                    <BreadcrumbItemDirective text="Overflow" url="./breadcrumb/overflow"/>
                  </BreadcrumbItemsDirective>
                </BreadcrumbComponent>
              </div>
            </div>
            <div className="row material2">
              <div className="col-xs-12 col-sm-12 col-lg-12 col-md-12">
                <h5>Overflow Mode - Wrap</h5>
              </div>
            </div>
            <div className="row material2">
              <div className="col-xs-12 col-sm-12 col-lg-12 col-md-12" aria-hidden='true'>
              <BreadcrumbComponent enableNavigation={false} maxItems={3} overflowMode='Wrap'>
                  <BreadcrumbItemsDirective>
                    <BreadcrumbItemDirective text="Home" url="./"/>
                    <BreadcrumbItemDirective text="Breadcrumb" url="./breadcrumb"/>
                    <BreadcrumbItemDirective text="Default" url="./breadcrumb/default"/>
                    <BreadcrumbItemDirective text="Icons" url="./breadcrumb/icons"/>
                    <BreadcrumbItemDirective text="Navigation" url="./breadcrumb/navigation"/>
                    <BreadcrumbItemDirective text="Overflow" url="./breadcrumb/overflow"/>
                  </BreadcrumbItemsDirective>
                </BreadcrumbComponent>
              </div>
            </div>
            <div className="row material2">
              <div className="col-xs-12 col-sm-12 col-lg-12 col-md-12">
                <h5>Overflow Mode - Scroll</h5>
              </div>
            </div>
            <div className="row material2">
              <div className="col-xs-12 col-sm-12 col-lg-12 col-md-12">
              <BreadcrumbComponent enableNavigation={false} maxItems={3} overflowMode='Scroll'>
                  <BreadcrumbItemsDirective>
                    <BreadcrumbItemDirective text="Home" url="./"/>
                    <BreadcrumbItemDirective text="Breadcrumb" url="./breadcrumb"/>
                    <BreadcrumbItemDirective text="Default" url="./breadcrumb/default"/>
                    <BreadcrumbItemDirective text="Icons" url="./breadcrumb/icons"/>
                    <BreadcrumbItemDirective text="Navigation" url="./breadcrumb/navigation"/>
                    <BreadcrumbItemDirective text="Overflow" url="./breadcrumb/overflow"/>
                  </BreadcrumbItemsDirective>
                </BreadcrumbComponent>
              </div>
            </div>
          </div>
        </div>
        <div id="action-description">
        <p>This sample demonstrates the different types of overflow mode such as <code>Hidden</code>, <code>Menu</code>, <code>Wrap</code>, <code>Collapsed</code>, and <code>Scroll</code> in the <b>Breadcrumb</b> component.</p>
       </div>
        <div id='description'>
        <p>Overflow mode limits the number of items to be displayed in the view when the breadcrumb's width exceeds the container width or <code>maxItems</code> property.</p>
        <p>The following overflow mode's were available in the <code>Breadcrumb</code> component.</p>
        <ul>
            <li><code>Hidden</code> - Specified maxItems count will be visible and the remaining items will be hidden. While clicking on the previous item, the hidden item will become visible.</li>
            <li><code>Collapsed</code> - Only the first and last items will be visible, and the remaining items will be hidden with collapsed icon. When the collapsed icon is clicked, all the items become visible.</li>
            <li><code>Menu</code> - Shows the number of breadcrumb items that can be accommodated within the container space, and creates a sub menu with the remaining items.</li>
            <li><code>Wrap</code> - Wraps the items on multiple lines when the Breadcrumb’s width exceeds the container space.</li>
            <li><code>Scroll</code> - Shows an HTML scroll bar when the Breadcrumb’s width exceeds the container space.</li>
            <li><code>None</code> - Shows all the items on a single line.</li>
        </ul>   
        <p>More information about Breadcrumb component can be found in this <a target='_blank' href="https://ej2.syncfusion.com/react/documentation/breadcrumb/overflow/">documentation section</a>.</p>
        </div>
      </div>);
    }
}

// syncfusionejs2_trial/Samples/Vue/public/source/breadcrumb/overflow-modes.vue
<template>
<div>
<div class="control-section">
        <div class="content-wrapper">
            <div class="row material2">
                <div class="col-xs-12 col-sm-12 col-lg-12 col-md-12">
                    <h5 style="display: inline-block">Overflow Mode - Hidden</h5>
                    <ejs-button id="reset" cssClass="reset-btn e-small" content="Reset State" v-on:click="btnClick"></ejs-button>
                </div>
            </div>
            <div class="row material2">
                <div class="col-xs-12 col-sm-12 col-lg-12 col-md-12">
                    <ejs-breadcrumb id="hidden-mode" :enableNavigation="false" :maxItems="3" overflowMode="Hidden">
                        <e-breadcrumb-items>
                            <e-breadcrumb-item text= 'Home' url= './'></e-breadcrumb-item>
                            <e-breadcrumb-item text= 'Breadcrumb' url= './breadcrumb'></e-breadcrumb-item>
                            <e-breadcrumb-item text= 'Default' url= './breadcrumb/default'></e-breadcrumb-item>
                            <e-breadcrumb-item text= 'Icons' url= './breadcrumb/icons'></e-breadcrumb-item>
                            <e-breadcrumb-item text= 'Navigations' url= './breadcrumb/navigations'></e-breadcrumb-item>
                            <e-breadcrumb-item text= 'Overflow' url= './breadcrumb/overflow'></e-breadcrumb-item>
                        </e-breadcrumb-items>
                    </ejs-breadcrumb>
                </div>
            </div>
            <div class="row material2">
                <div class="col-xs-12 col-sm-12 col-lg-12 col-md-12">
                    <h5>Overflow Mode - Menu</h5>
                </div>
            </div>
            <div class="row material2">
                <div class="col-xs-12 col-sm-12 col-lg-12 col-md-12">
                    <ejs-breadcrumb id="menu-mode" :enableNavigation="false" :maxItems="3" overflowMode="Menu">
                        <e-breadcrumb-items>
                            <e-breadcrumb-item text= 'Home' url= './'></e-breadcrumb-item>
                            <e-breadcrumb-item text= 'Breadcrumb' url= './breadcrumb'></e-breadcrumb-item>
                            <e-breadcrumb-item text= 'Default' url= './breadcrumb/default'></e-breadcrumb-item>
                            <e-breadcrumb-item text= 'Icons' url= './breadcrumb/icons'></e-breadcrumb-item>
                            <e-breadcrumb-item text= 'Navigations' url= './breadcrumb/navigations'></e-breadcrumb-item>
                            <e-breadcrumb-item text= 'Overflow' url= './breadcrumb/overflow'></e-breadcrumb-item>
                        </e-breadcrumb-items>
                    </ejs-breadcrumb>
                </div>
            </div>
            <div class="row material2">
                <div class="col-xs-12 col-sm-12 col-lg-12 col-md-12">
                    <h5>Overflow Mode - Collapsed</h5>
                </div>
            </div>
            <div class="row material2">
                <div class="col-xs-12 col-sm-12 col-lg-12 col-md-12">
                    <ejs-breadcrumb id="collapsed-mode" :enableNavigation="false" :maxItems="3" overflowMode="Collapsed">
                        <e-breadcrumb-items>
                            <e-breadcrumb-item text= 'Home' url= './'></e-breadcrumb-item>
                            <e-breadcrumb-item text= 'Breadcrumb' url= './breadcrumb'></e-breadcrumb-item>
                            <e-breadcrumb-item text= 'Default' url= './breadcrumb/default'></e-breadcrumb-item>
                            <e-breadcrumb-item text= 'Icons' url= './breadcrumb/icons'></e-breadcrumb-item>
                            <e-breadcrumb-item text= 'Navigations' url= './breadcrumb/navigations'></e-breadcrumb-item>
                            <e-breadcrumb-item text= 'Overflow' url= './breadcrumb/overflow'></e-breadcrumb-item>
                        </e-breadcrumb-items>
                    </ejs-breadcrumb>
                </div>
            </div>
            <div class="row material2">
                <div class="col-xs-12 col-sm-12 col-lg-12 col-md-12">
                    <h5>Overflow Mode - Wrap</h5>
                </div>
            </div>
            <div class="row material2">
                <div class="col-xs-12 col-sm-12 col-lg-12 col-md-12" aria-hidden= 'true'>
                    <ejs-breadcrumb id="wrap-mode" :enableNavigation="false" :maxItems="3" overflowMode="Wrap">
                        <e-breadcrumb-items>
                            <e-breadcrumb-item text= 'Home' url= './'></e-breadcrumb-item>
                            <e-breadcrumb-item text= 'Breadcrumb' url= './breadcrumb'></e-breadcrumb-item>
                            <e-breadcrumb-item text= 'Default' url= './breadcrumb/default'></e-breadcrumb-item>
                            <e-breadcrumb-item text= 'Icons' url= './breadcrumb/icons'></e-breadcrumb-item>
                            <e-breadcrumb-item text= 'Navigations' url= './breadcrumb/navigations'></e-breadcrumb-item>
                            <e-breadcrumb-item text= 'Overflow' url= './breadcrumb/overflow'></e-breadcrumb-item>
                        </e-breadcrumb-items>
                    </ejs-breadcrumb>
                </div>
            </div>
            <div class="row material2">
                <div class="col-xs-12 col-sm-12 col-lg-12 col-md-12">
                    <h5>Overflow Mode - Scroll</h5>
                </div>
            </div>
            <div class="row material2">
                <div class="col-xs-12 col-sm-12 col-lg-12 col-md-12">
                    <ejs-breadcrumb id="scroll-mode" :enableNavigation="false" :maxItems="4" overflowMode="Scroll">
                        <e-breadcrumb-items>
                            <e-breadcrumb-item text= 'Home' url= './'></e-breadcrumb-item>
                            <e-breadcrumb-item text= 'Breadcrumb' url= './breadcrumb'></e-breadcrumb-item>
                            <e-breadcrumb-item text= 'Default' url= './breadcrumb/default'></e-breadcrumb-item>
                            <e-breadcrumb-item text= 'Icons' url= './breadcrumb/icons'></e-breadcrumb-item>
                            <e-breadcrumb-item text= 'Navigations' url= './breadcrumb/navigations'></e-breadcrumb-item>
                            <e-breadcrumb-item text= 'Overflow' url= './breadcrumb/overflow'></e-breadcrumb-item>
                        </e-breadcrumb-items>
                    </ejs-breadcrumb>
                </div>
            </div>
        </div>
    </div>

<div id="action-description">
    <p>This sample demonstrates the different types of overflow mode such as <code>Hidden</code>, <code>Menu</code>, <code>Wrap</code>, <code>Collapsed</code>, and <code>Scroll</code> in the <b>Breadcrumb</b> component.</p>
</div>
<div id="description">
<p>Overflow mode limits the number of items to be displayed in the view when the breadcrumb's width exceeds the container width or <code>maxItems</code> property.</p>
    <p>The following overflow mode's were available in the <code>Breadcrumb</code> component.</p>
    <ul>
        <li><code>Hidden</code> - Specified maxItems count will be visible and the remaining items will be hidden. While clicking on the previous item, the hidden item will become visible.</li>
        <li><code>Collapsed</code> - Only the first and last items will be visible, and the remaining items will be hidden with collapsed icon. When the collapsed icon is clicked, all the items become visible.</li>
        <li><code>Menu</code> - Shows the number of breadcrumb items that can be accommodated within the container space, and creates a sub menu with the remaining items.</li>
        <li><code>Wrap</code> - Wraps the items on multiple lines when the Breadcrumbs width exceeds the container space.</li>
        <li><code>Scroll</code> - Shows an HTML scroll bar when the Breadcrumbs width exceeds the container space.</li>
        <li><code>None</code> - Shows all the items on a single line.</li>
    </ul>
    <p>More information about <code>Breadcrumb</code> component can be found in this <a target='_blank' href="https://ej2.syncfusion.com/vue/documentation/breadcrumb/overflow/">documentation section</a>.</p>
</div>
</div>
</template>

<!-- custom code start -->
<style scoped>
     .content-wrapper {
        width: 90%;
        margin: 0 auto;
        min-width: 85px;
    }
    .content-wrapper div.row {
        padding: 15px 0px;
    }
    .content-wrapper div.row:nth-child(even) {
        padding-top: 0;
    }
    @media only screen and (max-width: 480px) {
        .content-wrapper {
            width: 92%;
        }
        .col-xs-12,
        .col-xs-4,
        .col-xs-12 {
            padding: 10px 5px;
            width: 100%;
        }
        .content-wrapper div.row {
            padding: 0px;
        }
    }
    .tailwind .e-breadcrumb,
    .tailwind-dark .e-breadcrumb {
        margin-left: -12px;
    }
    .material .e-breadcrumb,
    .material-dark .e-breadcrumb {
        margin-left: -8px;
    }
    .fabric .e-breadcrumb,
    .fabric-dark .e-breadcrumb,
    .highcontrast .e-breadcrumb {
        margin-left: -4px;
    }
    #reset {
        float: right;
        margin: 5px 2px 5px 0;
    }
   </style>
   <!-- custom code end -->

<script>
import { BreadcrumbComponent, BreadcrumbItemDirective, BreadcrumbItemsDirective } from "@syncfusion/ej2-vue-navigations";
import { ButtonComponent } from "@syncfusion/ej2-vue-buttons";
import { getComponent } from '@syncfusion/ej2-base';

export default {
  components: {
    'ejs-breadcrumb': BreadcrumbComponent,
    'e-breadcrumb-item': BreadcrumbItemDirective,
    'e-breadcrumb-items': BreadcrumbItemsDirective,
    'ejs-button': ButtonComponent
  },
  data: function() {
    return {
      
    };
  },
  methods: {
    btnClick: function() {
        var breadcrumb, breadcrumbInst, breadcrumbs = document.querySelector('.content-wrapper').getElementsByClassName("e-breadcrumb");
        for (var i = 0; i < breadcrumbs.length; i++) {
            breadcrumb = breadcrumbs[i];
            breadcrumbInst = getComponent(breadcrumb, 'breadcrumb');
            breadcrumbInst.activeItem = breadcrumbInst.items[breadcrumbInst.items.length - 1].text;
        }
    }
  }
}
</script>
