// syncfusionejs2_trial/Samples/Vue/source/query-builder/mongo-sql.vue
<template>
    <div class="control-section">
        <div class="top-right-element">
            <ejs-dropdownbutton :items="items" cssClass="e-caret-hide" :select="onSelect">Import</ejs-dropdownbutton>
        </div>
        <ejs-dialog id="dialog" ref="Dialog" :header="header" :width="width" :height="height" :isModal="true" :buttons="buttons" :visible="visible" :content="dlgContent" :beforeOpen="beforeOpen" :animationSettings="animateSettings" :showCloseIcon="showCloseIcon"></ejs-dialog>
        <div class="col-lg-12 querybuilder-control">
            <ejs-querybuilder id="querybuilder" :dataSource="dataSource" ref="querybuilder" :rule="importRules" width="100%" :ruleChange="updateContentTemplate" :created="onQrybldrCreated">
                <e-columns>
                    <e-column field='EmployeeID' label='Employee ID' type='number' />
                    <e-column field='FirstName' label='First Name' type='string' />
                    <e-column field='LastName' label='Last Name' type='string' />
                    <e-column field='Age' label='Age' type='number' />
                    <e-column field='IsDeveloper' label='Is Developer' type='boolean' />
                    <e-column field='PrimaryFramework' label='Primary Framework' type='string' />
                    <e-column field='HireDate' label='Hire Date' type='date' format='MM/dd/yyyy' />
                    <e-column field='Country' label='Country' type='string' />
                </e-columns>
            </ejs-querybuilder>
            <div class="e-query-preview">
                <ejs-tab id="defaultTab" ref="tabObj" :created="tabCreated" :selected="changeTab">
                    <e-tabitems>
                        <e-tabitem :header="headertext[0]" content='#preview'></e-tabitem>
                        <e-tabitem :header="headertext[1]" content='#mongopreview'></e-tabitem>
                    </e-tabitems>
                </ejs-tab>
                <div class="preview-content" id="preview-content">
                    <div class="preview" id='preview' style='display: none' @mouseenter="handleMouseEnter" @mouseleave="handleMouseLeave" >
                        <div class="e-preview-options">
                            <label>Format Info:</label>
                            <ejs-radiobutton label="Inline" cssClass='e-custom-radio-btn' name="state" value="Inline" checked="true" :change="change"></ejs-radiobutton>
                            <ejs-radiobutton label="Parameter" cssClass="e-custom-radio-btn" name="state" value="Parameter" :change="change"></ejs-radiobutton>
                            <ejs-radiobutton label="Named Parameter" cssClass="e-custom-radio-btn" name="state" value="NamedParameter" :change="change"></ejs-radiobutton>
                            <div class="copy-tooltip" style='display: none' @click="copyClipboard">
                                <ejs-tooltip id="tooltipClick" opensOn='Click' content='Copied to clipboard'>
                                    <div class="e-icons copycode"></div>
                                </ejs-tooltip>
                            </div>
                        </div>
                        <textarea :readonly="isReadOnly" class="e-text-area-content e-sql-content"></textarea>
                    </div>
                    <div class="preview" id='mongopreview' style='display: none' @mouseenter="handleMouseEnter" @mouseleave="handleMouseLeave" >
                        <div class="e-mongo-preview-options">
                            <div class="copy-tooltip" style='display: none' @click="copyClipboard">
                                <ejs-tooltip id="tooltipClick" opensOn='Click' content='Copied to clipboard'>
                                    <div class="e-icons copycode"></div>
                                </ejs-tooltip>
                            </div>
                        </div>
                        <textarea :readonly="isReadOnly" class="e-text-area-content e-mongo-content"></textarea>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="action-description">
        <p>This sample demonstrates the Query Builder component by showing different types of queries such as SQL and MongoDB. The query preview can be changed using the tab component. Queries can be imported to the Query Builder using the import dropdown button.</p>
    </div>
    <div id="description">
        <p>
            In this demo, Query Builder features  include exporting and importing the query as an SQL query and MongoDB queries. MongoDB Query Builder is a tool that allows users to search for error logs in a MongoDB database. It provides a user-friendly interface for constructing and executing queries and allows users to filter, sort, and export the results for further analysis.
        </p>
        <p>
            In mobile mode, the component is shown vertically.
        </p>
        <p>
            The following methods were used in this sample to perform mongo and SQL query related changes.
        </p>
        <ul>
            <li>setMongoQuery</li>
            <li>getMongoQuery</li>
            <li>setParameterizedSQL</li>
            <li>getParameterizedSQL</li>
            <li>setParameterizedNamedSQL</li>
            <li>getParameterizedNamedSQL</li>
        </ul>
        <p>
            More information about Query Builder can be found in this <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/query-builder/getting-started/">documentation</a> section.
        </p>
    </div>
</template>

<!-- custom code start -->
<style>
.e-query-builder {
  margin: 0 auto;
}
.e-query-preview {
  margin-top: 10px !important;
  border: 1px solid #e5e7eb;
  border-radius: 4px;
  height: 300px;
  margin-bottom: 10px;
}
#dlgContent {
    height: 260px !important;
    width: 100% !important;
    overflow-x: hidden;
    padding: 10px !important;
}
.e-query-preview .e-tab {
    height: 200px;
}
.e-query-preview .e-tab .e-content {
    margin: 10px;
}
.e-query-preview .e-mongo-preview-options {
    height: 54px;
}

.e-query-preview .e-preview-options {
    height: 54px;
}

.e-custom-radio-btn {
    margin-left: 20px;
}

.e-text-area-content {
  margin: 10px;
  overflow: auto;
  border: none;
  width: 97% !important;
}
.e-text-area-content:focus-visible {
  outline: none;
}
.e-text-area-content:focus-visible {
  outline: none;
}
.top-right-element {
  margin-bottom: 10px;
  height: 32px;
}
.top-right-element .e-dropdown-btn {
  float: right;
   margin-right: 20px;
}
.e-query-preview .preview-content {
  margin-top: 10px;
}
.e-query-preview .e-sql-content,
.e-query-preview .e-mongo-content {
  margin: 10px;
  border: none;
  height: 160px;
  width: 98%;
}
.e-query-preview .copycode::before {
    content: '\e77c';
    font-size: 25px;
}
.e-query-preview .copy-tooltip {
    height: 32px;
    width: 32px;
    position: absolute;
    cursor: pointer;
    right: 12px;
    top: 12px;
    background: #f4f4f4;
    border-radius: 2px;
}

.e-query-preview .copy-tooltip.e-control.e-tooltip:hover {
    background: #D8D8D8;
}

.e-query-preview .e-icons.copycode {
    padding-left: 3px;
    padding-top: 4px;
    color: rgba(0, 0, 0, .54);
}
#dlgSpan.error {
    color: red;
    padding-left: 0px;
}
@media only screen and (max-width: 700px) {
    .e-query-preview .e-sql-content,
    .e-query-preview .e-mongo-content {
        height: 160px;
    }

    .e-query-preview .copy-tooltip {
        display: block !important;
    }
}

.material-dark .mongo-text-area,
.material-dark .e-query-preview .e-sql-content,
.material-dark .e-query-preview .e-mongo-content,
.material3-dark .mongo-text-area,
.material3-dark .e-query-preview .e-sql-content,
.material3-dark .e-query-preview .e-mongo-content,
.bootstrap5\.3-dark .mongo-text-area,
.bootstrap5\.3-dark .e-query-preview .e-sql-content,
.bootstrap5\.3-dark .e-query-preview .e-mongo-content,
.fabric-dark .mongo-text-area,
.fabric-dark .e-query-preview .e-sql-content,
.fabric-dark .e-query-preview .e-mongo-content,
.tailwind-dark .mongo-text-area,
.tailwind-dark .e-query-preview .e-sql-content,
.tailwind-dark .e-query-preview .e-mongo-content,
.bootstrap-dark .mongo-text-area,
.bootstrap-dark .e-query-preview .e-sql-content,
.bootstrap-dark .e-query-preview .e-mongo-content,
.highcontrast .mongo-text-area,
.highcontrast .e-query-preview .e-sql-content,
.highcontrast .e-query-preview .e-mongo-content,
.fluent2-dark .mongo-text-area,
.fluent2-dark .e-query-preview .e-sql-content,
.fluent2-dark .e-query-preview .e-mongo-content,
.fluent2-highcontrast .mongo-text-area,
.fluent2-highcontrast .e-query-preview .e-sql-content,
.fluent2-highcontrast .e-query-preview .e-mongo-content {
    background-color: #1f1f1f;
}

.bootstrap5\.3-dark .e-query-preview .e-icons.copycode,
.material3-dark .e-query-preview .e-icons.copycode,
.material-dark .e-query-preview .e-icons.copycode,
.fabric-dark .e-query-preview .e-icons.copycode,
.tailwind-dark .e-query-preview .e-icons.copycode,
.bootstrap-dark .e-query-preview .e-icons.copycode,
.highcontrast .e-query-preview .e-icons.copycode,
.fluent2-dark .e-query-preview .e-icons.copycode,
.fluent2-highcontrast .e-query-preview .e-icons.copycode {
    padding-bottom: 3px;
    color: white;
}

.tailwind3-dark #dlgContent,
.tailwind3-dark #e-text-area-content {
    background: transparent;
}
</style>
<!-- custom code end -->

<script>
import { QueryBuilderComponent, QueryBuilder, ColumnDirective, ColumnsDirective, QueryLibrary } from "@syncfusion/ej2-vue-querybuilder";
import { DropDownButtonComponent } from '@syncfusion/ej2-vue-splitbuttons';
import { DialogPlugin, DialogComponent, TooltipComponent } from '@syncfusion/ej2-vue-popups';
import { TabComponent, TabItemDirective, TabItemsDirective } from '@syncfusion/ej2-vue-navigations';
import { RadioButtonComponent } from '@syncfusion/ej2-vue-buttons';
import { Browser, getComponent } from '@syncfusion/ej2-base';
import dataSource from './data-source.json';

QueryBuilder.Inject(QueryLibrary);

export default {
    data: function() {
    return {
      isReadOnly: true,
      queryType: 'inline',
      currentvalue: {
        value: '',
        rule: '',
      },
      header: 'User details',
      headertext: [
        { text: "SQL" },
        { text: "MongoDB" }
      ],
      currentIndex: 0,
      importRules:  {
        condition: "and",
        rules: [
            { label: "First Name", field: "FirstName", type: "string", operator: "startswith", value: "Andre" },
            { label: "Last Name", field: "LastName", type: "string", operator: "in", value: ['Davolio', 'Buchanan'] },
            { label: "Age", field: "Age", type: "number", operator: "greaterthan", value: 29 },
            {
                condition: "or", rules: [
                    { label: "Is Developer", field: "IsDeveloper", type: "boolean", operator: "equal", value: true },
                    { label: "Primary Framework", field: "PrimaryFramework", type: "string", operator: "equal", value: "React" }
                ]
            },
            { label: "Hire Date", field: "HireDate", type: "date", operator: "between", value: ['11/28/2023', '11/28/2023'] },
        ],
      },
      animateSettings: { effect: 'Zoom' },
      width:'700px',
      height:'420px',
      content: '',
      dlgContent:
        "<textarea class='mongo-text-area' id='dlgContent'></textarea>"+"<span id='dlgSpan' :style='{ visibility: 'hidden'}'>Invalid Query</span>",
      showCloseIcon: true,
      visible: false,
      buttons: [
        {
          buttonModel: { isPrimary: false, content: 'Cancel' },
          click: function () {
            this.hide();
          },
        },
        {
          buttonModel: { isPrimary: true, content: 'Import' },
          click: this.importQuery
        },
      ],
      items: [
        {
          text: 'Import Mongo Query',
        },
        {
          text: 'Import Inline Sql',
        },
        {
          text: 'Import Parameter Sql',
        },
        {
          text: 'Import Named Parameter Sql',
        },
      ],
      animationSettings: { effect: 'Zoom' },
      model_header: 'User details',
      isModal: true,
      dataSource: dataSource.employeeData,
      values: ['Mr.', 'Mrs.']
    };
    },
    components: { 
        'ejs-querybuilder': QueryBuilderComponent,
        'ejs-dropdownbutton': DropDownButtonComponent,
        'ejs-dialog': DialogComponent,
        'ejs-tab': TabComponent,
        'e-columns': ColumnsDirective,
        'ejs-radiobutton': RadioButtonComponent,
        'e-column': ColumnDirective,
        'e-tabitems': TabItemsDirective,
        'e-tabitem': TabItemDirective,
        'ejs-tooltip': TooltipComponent
    },
    provide: {
        // Injecting QueryLibrary module
        querybuilder: [QueryLibrary]
    },
    methods: {
        onQrybldrCreated: function() {
            if(Browser.isDevice) {
             this.$refs.querybuilder.$el.ej2_instances[0].summaryView = true;
            }
        },
        change: function (args) {
            this.queryType = args.value.toLowerCase();
            this.updateSQLContent();
        },
        updateMongoContentTemplate () {
            var validRule = this.$refs.querybuilder.ej2Instances.getValidRules(this.$refs.querybuilder.ej2Instances.rule);
            var mongoQuery = JSON.parse(this.$refs.querybuilder.ej2Instances.getMongoQuery(validRule));
            this.content = JSON.stringify(mongoQuery, null, 4);
            (document.getElementsByClassName('e-text-area-content')[1]).value = this.content;
        },
        tabCreated: function () {
            setTimeout(() => {
                this.updateSQLContent();
            }, 100);
        },
        updateSQLContent () {
            var content;
            var qbrule = this.$refs.querybuilder.ej2Instances.getValidRules(this.$refs.querybuilder.ej2Instances.rule);
            switch (this.queryType) {
                case 'inline':
                    this.content = this.$refs.querybuilder.ej2Instances.getSqlFromRules(qbrule);
                    break;
                case 'parameter':
                    this.convertParameterSql(qbrule);
                    break;
                default:
                    this.convertNamedParameterSql(qbrule);
                    break;
                }
            (document.getElementsByClassName('e-text-area-content')[0]).value = this.content;
        },
        convertParameterSql (qbrule) {
            this.content = JSON.stringify(this.$refs.querybuilder.ej2Instances.getParameterizedSql(qbrule), null, 4)
        },
        convertNamedParameterSql (qbrule) {
            this.content = JSON.stringify(this.$refs.querybuilder.ej2Instances.getParameterizedNamedSql(qbrule), null, 4)
        },
        importQuery () {
            try {
                var textAreacontent = document.getElementById('dlgContent');
                if (this.currentvalue.rule != 'sql') {
                    var textAreaValue = JSON.parse(textAreacontent.value);
                }
                switch (this.currentvalue.rule) {
                    case 'mongo':
                        this.$refs.querybuilder.ej2Instances.setMongoQuery(textAreacontent.value);
                        break;
                    case 'namedparameter':
                        this.$refs.querybuilder.ej2Instances.setParameterizedNamedSql(JSON.parse(textAreacontent.value));
                        break;
                    case 'parameter':
                        this.$refs.querybuilder.ej2Instances.setParameterizedSql(JSON.parse(textAreacontent.value));
                        break;
                    case 'sql':
                        this.$refs.querybuilder.ej2Instances.setRulesFromSql(textAreacontent.value, true);
                        break;
                    default:
                       break;
                }
                this.updateContentTemplate();
                this.$refs.Dialog.hide();
            } catch (error) {
                var errorElem = document.getElementById('dlgSpan');
                if (!errorElem.classList.contains("error")) {
                    errorElem.style.visibility = 'visible';
                    errorElem.classList.add("error");
                }
            }
        },
        beforeOpen: function (args) {
            var dlgContentElement = document.getElementById('dlgContent');
            var errorElem = document.getElementById('dlgSpan');
            if (dlgContentElement) {
                dlgContentElement.value = this.currentvalue.value;
                this.$refs.Dialog.$el.ej2_instances[0].header = this.currentvalue.header;
                errorElem.style.visibility = 'hidden';
                if (errorElem.classList.contains("error")) {
                    errorElem.classList.remove("error");
                }
            }
        },
        changeTab: function (args) {
            this.currentIndex = args.selectedIndex;
            setTimeout(() => {
               this.updateContentTemplate();
            }, 100);
        },
        updateContentTemplate () {
            switch (this.currentIndex) {
                case 0:
                    this.updateSQLContent();
                    break;
                case 1:
                    this.updateMongoContentTemplate();
                    break;
            }
        },
        copyClipboard: function (args) {
           navigator.clipboard.writeText(this.content);
           setTimeout(function () {
               (getComponent(args.target.closest('.e-tooltip'), 'tooltip')).close();
            }, 1000);
        },
        handleMouseEnter() {
            var elem = document.getElementsByClassName("copy-tooltip");
            for (var i = 0; i < elem.length; i++) {
                if (this.$refs.tabObj.ej2Instances.selectedItem == i) {
                    elem[i].style.display = 'block';
                }
            }
        },
        handleMouseLeave() {
            var elem = document.getElementsByClassName("copy-tooltip");
            for (var i = 0; i < elem.length; i++) {
                if (this.$refs.tabObj.ej2Instances.selectedItem == i) {
                    elem[i].style.display = 'none';
                }
            }
        },
        onSelect: function (args) {
            var validRule = this.$refs.querybuilder.ej2Instances.getValidRules(this.$refs.querybuilder.ej2Instances.rule);
            switch (args.item.text) {
                case 'Import Mongo Query':
                    var mongoQuery = JSON.parse(this.$refs.querybuilder.ej2Instances.getMongoQuery(validRule));
                    mongoQuery = JSON.stringify(mongoQuery, null, 4);
                    this.currentvalue.value = mongoQuery;
                    this.currentvalue.rule = 'mongo';
                    this.currentvalue.header = 'Mongo Query';
                    this.$refs.Dialog.show();
                break;
                case 'Import Inline Sql':
                    this.currentvalue.value =
                    this.$refs.querybuilder.ej2Instances.getSqlFromRules(validRule);
                    this.currentvalue.rule = 'sql';
                    this.currentvalue.header = 'SQL';
                    this.$refs.Dialog.show();
                break;
                case 'Import Parameter Sql':
                    this.currentvalue.value = JSON.stringify(
                    this.$refs.querybuilder.ej2Instances.getParameterizedSql(validRule), null, 4);
                    this.currentvalue.rule = 'parameter';
                    this.currentvalue.header = 'Parameter SQL';
                    this.$refs.Dialog.show();
                break;
                case 'Import Named Parameter Sql':
                    this.currentvalue.value = JSON.stringify(
                    this.$refs.querybuilder.ej2Instances.getParameterizedNamedSql(validRule), null, 4);
                    this.currentvalue.rule = 'namedparameter';
                    this.currentvalue.header = 'NamedParameter SQL';
                    this.$refs.Dialog.show();
                    break;
                default:
                break;
            }
        },
    }
};
</script>

// syncfusionejs2_trial/Samples/React/src/query-builder/mongo-sql.tsx
import * as ReactDOM from 'react-dom';
import { render } from 'react-dom';
import * as React from 'react';
import { QueryBuilderComponent, QueryLibrary, ColumnsModel, RuleModel } from '@syncfusion/ej2-react-querybuilder';
import { getComponent, closest } from '@syncfusion/ej2-base';
import { ButtonComponent, RadioButtonComponent } from '@syncfusion/ej2-react-buttons';
import { DropDownListComponent } from '@syncfusion/ej2-react-dropdowns';
import { SampleBase } from '../common/sample-base';
import './query-preview.css';
import { ItemModel, MenuEventArgs, TabComponent, TabItemDirective, TabItemsDirective } from '@syncfusion/ej2-react-navigations';
import { AnimationSettingsModel, DialogComponent, TooltipComponent } from '@syncfusion/ej2-react-popups';
import { employeeData } from './data-source';
import { DropDownButtonComponent } from '@syncfusion/ej2-react-splitbuttons';
import * as CodeMirror from 'codemirror';

QueryBuilderComponent.Inject(QueryLibrary);

const frameworkTemplate = (props) => {
    let ds = ["React", "Angular", "Vue", "TypeScript", "JavaScript"];
    let state = Object.assign({}, props);
    const args = state;
    const frameworkChange = (event) => {
        let qryBldrObj: any = getComponent(document.getElementById('querybuilder'), 'query-builder');
        let elem = document.getElementById(args.ruleID).querySelector('.e-rule-value');
        qryBldrObj.notifyChange(event.value, elem, 'value');
    }
    return (<div><DropDownListComponent dataSource={ds} value={args.rule.value} change={frameworkChange} /></div>);
};
export class Template extends SampleBase<{}, {}> {
    public headertext = [
        { text: "SQL" },
        { text: "MongoDB" }
    ];
    public items: ItemModel[] = [
        {
            text: 'Import Mongo Query'
        },
        {
            text: 'Import Inline Sql'
        },
        {
            text: 'Import Parameter Sql'
        },
        {
            text: 'Import Named Parameter Sql'
        }
    ];
    public mongoQuery: string = '{';
    public queryType: string = 'inline';
    public qryBldrObj: QueryBuilderComponent;
    public dialogInstance: DialogComponent;
    public animationSettings: AnimationSettingsModel;
    public currentvalue: any = {
        value: '',
        rule: ''
    };
    public dialogHeader: string;
    public tabObj: TabComponent;
    public currentIndex: number = 0;
    public content: string;
    public importRules: RuleModel;
    public columnData: ColumnsModel[];
    constructor(args) {
        super(args)
        this.columnData = [
            { field: "EmployeeID", label: "Employee ID", type: "number" },
            { field: "FirstName", label: "First Name", type: "string" },
            { field: "LastName", label: "Last Name", type: "string" },
            { field: "Age", label: "Age", type: "number" },
            { field: "IsDeveloper", label: "Is Developer", type: "boolean" },
            { field: "PrimaryFramework", label: "Primary Framework", type: "string", template: frameworkTemplate },
            { field: "HireDate", label: "Hire Date", type: "date", format: "MM/dd/yyyy" },
            { field: "Country", label: "Country", type: "string" },
        ];
        this.importRules = {
            condition: "and",
            rules: [
                { label: "First Name", field: "FirstName", type: "string", operator: "startswith", value: "Andre" },
                { label: "Last Name", field: "LastName", type: "string", operator: "in", value: ['Davolio', 'Buchanan'] },
                { label: "Age", field: "Age", type: "number", operator: "greaterthan", value: 29 },
                {
                    condition: "or", rules: [
                        { label: "Is Developer", field: "IsDeveloper", type: "boolean", operator: "equal", value: true },
                        { label: "Primary Framework", field: "PrimaryFramework", type: "string", operator: "equal", value: "React" }
                    ]
                },
                { label: "Hire Date", field: "HireDate", type: "date", operator: "between", value: ["11/22/2023", "11/30/2023"] },
            ],
        };
    }
    SQLTemplate = () => {
        const isInline = this.queryType === "inline";
        const isParameter = this.queryType === "parameter";
        const isNamedParameter = this.queryType === "namedParameter";
        return (
            <div className="preview-content" onClick={this.handleMouseEnter} onMouseEnter={this.handleMouseEnter} onMouseLeave={this.handleMouseLeave}>
                <div className="e-preview-options">
                    <label>Format Info:</label>
                    <RadioButtonComponent cssClass="e-radio-option" change={this.change} label="Inline" checked={isInline} name="state" value="Inline"></RadioButtonComponent>
                    <RadioButtonComponent cssClass="e-radio-option" checked={isParameter} change={this.change} label="Parameter" name="state" value="Parameter"></RadioButtonComponent>
                    <RadioButtonComponent cssClass="e-radio-option" checked={isNamedParameter} change={this.change} label="Named Parameter" name="state" value="NamedParameter"></RadioButtonComponent>
                    <div className="copy-tooltip" style={{ display: 'none' }} onClick={this.copyClipboard}>
                        <TooltipComponent opensOn="Click" content="Copied to clipboard">
                            <div className="e-icons copycode"></div>
                        </TooltipComponent>
                    </div>
                </div>
                <textarea className="e-sql-content" style={{ display: 'none' }}
                />
            </div>
        );
    }
    MongoDBTemplate = () => {
        return (
            <div className="preview-content" onClick={this.handleMouseEnter} onMouseEnter={this.handleMouseEnter} onMouseLeave={this.handleMouseLeave}>
                <div className="e-preview-options">
                    <div className="copy-tooltip" style={{ display: 'none' }} onClick={this.copyClipboard}>
                        <TooltipComponent opensOn="Click" content="Copied to clipboard">
                            <div className="e-icons copycode"></div>
                        </TooltipComponent>
                    </div>
                </div>
                <textarea className="e-mongo-content" style={{ display: 'none' }} />
            </div>
        );
    };
    tabCreated = (args: any) => {
        setTimeout(() => {
            this.updateSQLContentTemplate();
        }, 100);
    }
    changeTab = (args: any) => {
        this.currentIndex = args.selectedIndex;
        setTimeout(() => {
            this.updateContentTemplate();
        }, 100);
    }
    updateContentTemplate = () => {
        switch (this.currentIndex) {
            case 0:
                this.updateSQLContentTemplate();
                break;
            case 1:
                this.updateMongoContentTemplate();
                break;
        }
    }
    updateMongoContentTemplate = () => {
        let codeMirrorEditor: any;
        let validRule = this.qryBldrObj.getValidRules(this.qryBldrObj.rule);
        let mongoQuery = JSON.parse(this.qryBldrObj.getMongoQuery(validRule));
        mongoQuery = JSON.stringify(mongoQuery, null, 4);
        this.content = mongoQuery;
        /* custom code start */
        this.clearHighlight();
        codeMirrorEditor = CodeMirror.fromTextArea(document.getElementsByClassName('e-mongo-content')[0] as any, {
            mode: 'javascript',
            readOnly: true,
            theme: 'default' // Set your desired theme here
        });
        codeMirrorEditor.setValue(this.content);
        /* custom code end */
        if (!codeMirrorEditor) {
            document.getElementsByClassName('e-mongo-content')[0].textContent = this.content;
            (document.getElementsByClassName('e-mongo-content')[0] as HTMLElement).style.display = 'block';
        }
    }
    change = (args: any) => {
        this.queryType = args.value.toLowerCase();
        this.updateSQLContentTemplate();
    };
    updateSQLContentTemplate = () => {
        let codeMirrorEditor: any;
        this.content = this.updateSQLContent();
        /* custom code start */
        this.clearHighlight();
        codeMirrorEditor = CodeMirror.fromTextArea(document.getElementsByClassName('e-sql-content')[0] as any, {
            readOnly: true,
            lineWrapping: true,
            theme: 'default', // Set your desired theme here
        });
        codeMirrorEditor.setValue(this.content);
        /* custom code end */
        if (!codeMirrorEditor) {
            document.getElementsByClassName('e-sql-content')[0].textContent = this.content;
            (document.getElementsByClassName('e-sql-content')[0] as HTMLElement).style.display = 'block';
        }
    }
    updateSQLContent = () => {
        let content: any;
        let qbrule: any = this.qryBldrObj.getValidRules(this.qryBldrObj.rule);
        let sqlJSON: any;
        switch (this.queryType) {
            case 'inline':
                content = this.qryBldrObj.getSqlFromRules(qbrule);;
                break;
            case 'parameter':
                content = this.convertParameterSql(qbrule);
                break;
            default:
                content = this.convertNamedParameterSql(qbrule);
                break;
        }
        return content;
    }
    convertParameterSql = (qbrule: any) => {
        let content = JSON.stringify(this.qryBldrObj.getParameterizedSql(qbrule), null, 4);
        return content;
    }
    convertNamedParameterSql = (qbrule: any) => {
        let content: string = JSON.stringify(this.qryBldrObj.getParameterizedNamedSql(qbrule), null, 4);
        return content;
    }
    /* custom code start */
    handleMouseEnter = () => {
        let elem: any = document.getElementsByClassName("copy-tooltip");
        for (var i: number = 0; i < elem.length; i++) {
            if (this.tabObj.selectedItem == i) {
                elem[i].style.display = 'block';
            }
        }
    }
    handleMouseLeave = () => {
        let elem: any = document.getElementsByClassName("copy-tooltip");
        for (var i: number = 0; i < elem.length; i++) {
            if (this.tabObj.selectedItem == i) {
                elem[i].style.display = 'none';
            }
        }
    }
    /* custom code end */

    copyClipboard = (args: any) => {
        navigator.clipboard.writeText(this.content);
        setTimeout(function () {
            (getComponent(args.target.closest('.e-tooltip'), 'tooltip') as any).close();
        }, 1000);
    }
    /* custom code start */
    clearHighlight = () => {
        let codeMirrorElem: any = document.getElementsByClassName('e-query-preview')[0].querySelectorAll('.CodeMirror');
        for (let i = codeMirrorElem.length - 1; i >= 0; i--) {
            codeMirrorElem[i].remove();
        }
    }
    /* custom code end */
    updateRule = () => {
        this.updateContentTemplate();
    }
    // Handler used to reposition the tooltip on page scroll
    dialogContent = () => {
        return (<div>
            <textarea className="mongo-text-area" id="content-area"></textarea>
            <span id="dlgSpan" style={{ visibility: 'hidden' }}>Invalid Query</span>
        </div>);
    }
    importQuery = () => {
        try {
            let textAreacontent: HTMLTextAreaElement = document.getElementById('content-area') as HTMLTextAreaElement;
            if (this.currentvalue.rule != 'sql') {
                let textAreaValue: any = JSON.parse(textAreacontent.value);
            }
            switch (this.currentvalue.rule) {
                case 'mongo':
                    this.qryBldrObj.setMongoQuery(textAreacontent.value);
                    break;
                case 'namedparameter':
                    this.qryBldrObj.setParameterizedNamedSql(JSON.parse(textAreacontent.value));
                    break;
                case 'parameter':
                    this.qryBldrObj.setParameterizedSql(JSON.parse(textAreacontent.value));
                    break;
                case 'sql':
                    this.qryBldrObj.setRulesFromSql(textAreacontent.value, true);
                    break;
                default:
                    break;
            }
            this.updateRule();
            this.dialogInstance.hide();
        } catch (error) {
            let errorElem: HTMLElement = document.getElementById('dlgSpan') as HTMLElement;
            if (!errorElem.classList.contains("error")) {
                errorElem.style.visibility = 'visible';
                errorElem.classList.add("error");
            }
        }
    }
    buttons = [
        {
            buttonModel: {
                content: 'Cancel',
                cssClass: 'e-flat',
            },
            click: () => {
                this.dialogInstance.hide();
            },
        },
        {
            buttonModel: {
                content: 'Import',
                cssClass: 'e-flat',
                isPrimary: true,
            },
            click: () => {
                this.importQuery();
            },
        },
    ];
    dialogOpen = () => {
        let dlgContentElement: any = document.getElementById('content-area');
        let errorElem: HTMLElement = document.getElementById('dlgSpan');
        if (dlgContentElement && this.currentvalue) {
            dlgContentElement.value = this.currentvalue.value;
            this.dialogInstance.header = this.dialogHeader;
            errorElem.style.visibility = 'hidden';
            if (errorElem.classList.contains("error")) {
                errorElem.classList.remove("error");
            }
        }
    }
    onSelect = (args: MenuEventArgs) => {
        let validRule: RuleModel = this.qryBldrObj.getValidRules(this.qryBldrObj.rule);
        switch (args.item.text) {
            case 'Import Mongo Query':
                let mongoQuery = JSON.parse(this.qryBldrObj.getMongoQuery(validRule));
                mongoQuery = JSON.stringify(mongoQuery, null, 4);
                this.currentvalue.value = mongoQuery;
                this.currentvalue.rule = 'mongo';
                this.dialogHeader = "Mongo Query";
                this.dialogInstance.show();
                break;
            case 'Import Inline Sql':
                this.currentvalue.value = this.qryBldrObj.getSqlFromRules(validRule);
                this.currentvalue.rule = 'sql';
                this.dialogHeader = "SQL";
                this.dialogInstance.show();
                break;
            case 'Import Parameter Sql':
                this.currentvalue.value = JSON.stringify(this.qryBldrObj.getParameterizedSql(validRule), null, 4);
                this.currentvalue.rule = 'parameter';
                this.dialogHeader = "Parameter SQL";
                this.dialogInstance.show();
                break;
            default:
                this.currentvalue.value = JSON.stringify(this.qryBldrObj.getParameterizedNamedSql(validRule), null, 4);
                this.currentvalue.rule = 'namedparameter';
                this.dialogHeader = "NamedParameter SQL";
                this.dialogInstance.show();
                break;
        }
    }    
    render() {
        return (
            <div className='control-pane'>
                <div className='control-section'>
                    <div className="top-right-element">
                        <DropDownButtonComponent id="element" items={this.items} cssClass='e-caret-hide' select={this.onSelect}>Import</DropDownButtonComponent>
                    </div>
                    <div className='col-lg-12 control-section'>
                        <div className="App">
                            <DialogComponent id='dialog' width='700px' height='420px' isModal={true} animationSettings={this.animationSettings} header={"JSON"} visible={false} beforeOpen={this.dialogOpen} closeOnEscape={false} showCloseIcon={true} buttons={this.buttons} ref={dialog => this.dialogInstance = dialog}>
                                <div>{this.dialogContent()}</div>
                            </DialogComponent>
                        </div>
                        <QueryBuilderComponent id="querybuilder" dataSource={employeeData} columns={this.columnData} rule={this.importRules} ref={(scope) => { this.qryBldrObj = scope; }} showButtons={{ lockGroup: true }} ruleChange={this.updateRule}></QueryBuilderComponent>
                        <div className="e-query-preview">
                            <TabComponent id='defaultTab' ref={(scope) => { this.tabObj = scope; }} selected={this.changeTab} created={this.tabCreated}>
                                <TabItemsDirective>
                                    <TabItemDirective header={this.headertext[0]} content={this.SQLTemplate} />
                                    <TabItemDirective header={this.headertext[1]} content={this.MongoDBTemplate} />
                                </TabItemsDirective>
                            </TabComponent>
                        </div>
                    </div>
                </div>
                <div id='action-description'>
                    <p>This sample demonstrates the Query Builder component by showing different types of queries such as SQL and MongoDB . The query preview can be changed using the tab component. Queries can be imported to the Query Builder using the import dropdown button.</p>
                </div>
                <div id='description'>
                    <p>
                        In this demo, Query Builder features  include exporting and importing the query as an SQL query and MongoDB queries. MongoDB Query Builder is a tool that allows users to search for error logs in a MongoDB database. It provides a user-friendly interface for constructing and executing queries and allows users to filter, sort, and export the results for further analysis.
                    </p>
                    <p>
                        The following methods were used in this sample to perform mongo and SQL query related changes.
                    </p>
                    <ul>
                        <li>setMongoQuery</li>
                        <li>getMongoQuery</li>
                        <li>setParameterizedSQL</li>
                        <li>getParameterizedSQL</li>
                        <li>setParameterizedNamedSQL</li>
                        <li>getParameterizedNamedSQL</li>
                    </ul>
                    <p>
                        More information about Query Builder can be found in this
                        <a target='_blank' href='https://ej2.syncfusion.com/react/documentation/query-builder/getting-started/'>
                            documentation section</a>.
                    </p>
                </div>
            </div>
        );
    }
}
