// syncfusionejs2_trial/Samples/React/src/circular-gauge/sleep-tracker.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.SleepTracker = void 0;
var React = require("react");
var ej2_react_circulargauge_1 = require("@syncfusion/ej2-react-circulargauge");
var sample_base_1 = require("../common/sample-base");
var SAMPLE_CSS = "\n    .control-fluid {\n\t\tpadding: 0px !important;\n    }";
var SleepTracker = /** @class */ (function (_super) {
    __extends(SleepTracker, _super);
    function SleepTracker() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    SleepTracker.prototype.load = function (args) {
        // custom code start
        var selectedTheme = location.hash.split('/')[1];
        selectedTheme = selectedTheme ? selectedTheme : 'Material';
        args.gauge.theme = ((selectedTheme.charAt(0).toUpperCase() +
            selectedTheme.slice(1)).replace(/-dark/i, 'Dark').replace(/-high/i, 'High').replace(/contrast/i, 'Contrast').replace(/5.3/i, '5'));
        // custom code end
    };
    SleepTracker.prototype.axisLabelRender = function (args) {
        if (args.value == 3 || args.value == 6 || args.value == 9 || args.value == 12) {
            args.text = args.value.toString();
        }
        else {
            args.text = "";
        }
    };
    SleepTracker.prototype.render = function () {
        var _this = this;
        return (React.createElement("main", null,
            React.createElement("div", { className: 'control-pane' },
                React.createElement("style", null, SAMPLE_CSS),
                React.createElement("div", { className: 'control-section' },
                    React.createElement(ej2_react_circulargauge_1.CircularGaugeComponent, { load: this.load.bind(this), axisLabelRender: this.axisLabelRender.bind(this), id: 'custom-labels', ref: function (gauge) { return _this.gauge = gauge; }, background: 'transparent' },
                        React.createElement(ej2_react_circulargauge_1.Inject, { services: [ej2_react_circulargauge_1.Annotations] }),
                        React.createElement(ej2_react_circulargauge_1.AxesDirective, null,
                            React.createElement(ej2_react_circulargauge_1.AxisDirective, { startAngle: 0, endAngle: 0, radius: '70%', minimum: 0, maximum: 12, majorTicks: {
                                    width: 2, height: 12, interval: 1, offset: 4
                                }, lineStyle: { width: 0 }, minorTicks: {
                                    width: 1, height: 7, interval: 0.2, offset: 4
                                }, labelStyle: {
                                    hiddenLabel: 'First',
                                    font: {
                                        fontFamily: 'inherit'
                                    }
                                } },
                                React.createElement(ej2_react_circulargauge_1.PointersDirective, null,
                                    React.createElement(ej2_react_circulargauge_1.PointerDirective, { type: "Marker", value: 4.7, markerShape: 'Image', radius: '97%', markerWidth: 28, markerHeight: 28, imageUrl: "src/circular-gauge/images/sun-icon.png", animation: {
                                            enable: false
                                        } }),
                                    React.createElement(ej2_react_circulargauge_1.PointerDirective, { type: "Marker", value: 9, markerShape: 'Image', radius: '98%', markerWidth: 28, markerHeight: 28, imageUrl: "src/circular-gauge/images/moon-icon.png", animation: {
                                            enable: false
                                        } })),
                                React.createElement(ej2_react_circulargauge_1.RangesDirective, null,
                                    React.createElement(ej2_react_circulargauge_1.RangeDirective, { start: 0, end: 4.7, startWidth: 4, endWidth: 4, color: '#6453D0' }),
                                    React.createElement(ej2_react_circulargauge_1.RangeDirective, { start: 12, end: 9, startWidth: 4, endWidth: 4, color: '#6453D0' }),
                                    React.createElement(ej2_react_circulargauge_1.RangeDirective, { start: 4.7, end: 9, startWidth: 4, endWidth: 4, color: '#d7d3ed' })),
                                React.createElement(ej2_react_circulargauge_1.AnnotationsDirective, null,
                                    React.createElement(ej2_react_circulargauge_1.AnnotationDirective, { description: 'Mon, 5 Apr', content: '<div style="font-size:15px;border-radius: 20px;border: 2px solid gray;padding: 5px 4px 5px;width: 93%;text-align: center;margin-left: 67px;">Mon, 5 Apr</div>', angle: 342, radius: '129%', zIndex: '1' }),
                                    React.createElement(ej2_react_circulargauge_1.AnnotationDirective, { content: '<div style="font-size:15px;margin-left:25px">07 hrs 43 mins</div>', description: '07 hrs 43 mins', angle: 185, radius: '120%', zIndex: '1' }),
                                    React.createElement(ej2_react_circulargauge_1.AnnotationDirective, { content: '<div style="font-size:15px;margin-left: 34px;">Sleep Time</div>', description: 'Sleep time', angle: 185, radius: '140%', zIndex: '1' }),
                                    React.createElement(ej2_react_circulargauge_1.AnnotationDirective, { content: '<div style="color:#6453D0;font-size:15px;margin-top: 54px;margin-left:28px"><p style="text-align: center;">4 Apr</p><p style="margin-top: -10px;">9:00 PM</p></div>', description: '4 Apr 9:00 PM', angle: 285, radius: '60%', zIndex: '1' }),
                                    React.createElement(ej2_react_circulargauge_1.AnnotationDirective, { content: '<div style="color:#6453D0;margin-top: -8px;"> - </div>', description: '-', angle: 0, radius: '0%', zIndex: '1' }),
                                    React.createElement(ej2_react_circulargauge_1.AnnotationDirective, { content: '<div style="color:#6453D0;font-size:15px;margin-left: -15px;margin-top: 56px;"><p style="text-align: center;">5 Apr </p><p style="margin-top: -10px;">4:43 AM</p></div>', description: '5 Apr 4:43 AM', angle: 70, radius: '50%', zIndex: '1' }))))))),
            React.createElement("section", { id: "action-description", "aria-label": "Description of Circular Gauge sample" },
                React.createElement("p", null, "This sample represents the number of hours slept by a person using a sleep tracker. The sleep tracker also displays the start and end time of each sleep cycle.")),
            React.createElement("section", { id: "description", "aria-label": "Description of the Circular Gauge features demonstrated in this sample" },
                React.createElement("p", null, "In this example, you can see how to make the circular gauge look like a sleep tracker. Additionally, the date, start and end time, and duration of sleep are all displayed."),
                React.createElement("p", null,
                    "More information on the circular gauge can be found in this ",
                    React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/circular-gauge/getting-started/" }, "documentation section"),
                    "."))));
    };
    return SleepTracker;
}(sample_base_1.SampleBase));
exports.SleepTracker = SleepTracker;

// syncfusionejs2_trial/Samples/Vue/source/circular-gauge/sleep-tracker.vue
<template>
  <main><div>
     <div class="control-section">
        <ejs-circulargauge :load='load' :background='background' style='display:block' align='center' id='gauge' :axisLabelRender='axisLabelRender'>
            <e-axes>
                <e-axis :radius='gaugeRadius' :startAngle='startAngle' :endAngle='endAngle' :majorTicks='majorTicks' :lineStyle='lineStyle' :minorTicks='minorTicks' :minimum=0 :maximum=12 :labelStyle='labelStyle' :annotations="annotations" :ranges='ranges'>
                    <e-pointers>
                    <e-pointer :value='value1' :radius='pointerRadius1' :type='type' :markerShape='markerShape' :markerWidth='markerWidth' :markerHeight='markerHeight' :imageUrl='image1' :animation='animation'></e-pointer>
                    <e-pointer :value='value2' :radius='pointerRadius2' :type='type' :markerShape='markerShape' :markerWidth='markerWidth' :markerHeight='markerHeight' :imageUrl='image2' :animation='animation' ></e-pointer>
                    </e-pointers>
                </e-axis>
            </e-axes>
        </ejs-circulargauge>
      </div>
</div>
<section id="action-description" aria-label="Description of Circular Gauge sample">
    <p>
        This sample represents the number of hours slept by a person using a sleep tracker. The sleep tracker also
        displays the start and end time of each sleep cycle.
    </p>
</section>
<section id="description" aria-label="Description of the Circular Gauge features demonstrated in this sample">
    <p>
        In this example, you can see how to make the circular gauge look like a sleep tracker. Additionally, the date,
        start and end time, and duration of sleep are all displayed.
    </p>
    <p>
        More information on the circular gauge can be found in this <a target="_blank"
            href="https://ej2.syncfusion.com/vue/documentation/circular-gauge/getting-started/">documentation
            section</a>.
    </p>
</section>
</main>
</template>
<script>

import { CircularGaugeComponent, AxesDirective, AxisDirective, PointerDirective, PointersDirective, Annotations } from "@syncfusion/ej2-vue-circulargauge";
import { Browser } from "@syncfusion/ej2-base";

export default {
   data:function(){
    return{
            gaugeRadius: '70%',
            startAngle: 0,
            background:'transparent',
            endAngle: 0,
            majorTicks: {
                width: 2,
                height: 12,
                interval: 1,
                offset: 4
            },
            lineStyle: { width: 0 },
            minorTicks: {
                 width: 1,
                 height: 7,
                 interval: 0.2,
                 offset: 4
            },
            labelStyle: {
                hiddenLabel: 'First',
                font: {
                    fontFamily: 'inherit'
                }
            },
            type:'Marker',
            value1: 4.7,
            value2:9,
            markerShape:'Image',
            pointerRadius1: '97%',
            pointerRadius2:'98%',
            markerHeight:28,
            markerWidth:28,           
            image1:'src/circular-gauge/images/sun-icon.png',
            image2:'src/circular-gauge/images/moon-icon.png',
            animation :
            {
             enable:false
            },
            ranges: [
                { start: 0, end: 4.7, color:'#6453D0' , startWidth:4 , endWidth:4},
                { start: 12, end: 9, color:'#6453D0',  startWidth:4 , endWidth:4 },
                { start: 4.7, end: 9, color:'#d7d3ed',  startWidth:4 , endWidth:4 }
                ],
            annotations: [
            {
                   description:'Mon, 5 Apr',
                   content:'<div style="font-size:15px;border-radius: 20px;border: 2px solid gray;padding: 5px 4px 5px;width: 93%;text-align: center;margin-left: 67px;">Mon, 5 Apr</div>',
                   angle:342, radius:'129%', zIndex:'1'
            },
            {
                description:'07 hrs 43 mins',
                content:'<div style="color:#6453D0;font-size:15px;margin-top: 54px;margin-left:28px"><p style="text-align: center;">4 Apr</p><p style="margin-top: -10px;">9:00 PM</p></div>',
                angle:285, radius:'60%', zIndex:'1'
            },
             {
                description:'Sleep time',
                content:'<div style="font-size:15px;margin-left:25px">07 hrs 43 mins</div>' , angle:185,
                radius:'120%', zIndex:'1'
            },
            {
                description:'4 Apr 9:00 PM',
                content:'<div style="font-size:15px;margin-left: 34px;">Sleep Time</div>', angle:185,
                radius:'140%', zIndex:'1'
            },
            {
                description:'-',
                content:'<div style="color:#6453D0;margin-top: -8px;"> - </div>',
                angle:0, radius:'0%', zIndex:'1'
            },
            {
                description:'5 Apr 4:43 AM',
                content:'<div style="color:#6453D0;font-size:15px;margin-left: -15px;margin-top: 56px;"><p style="text-align: center;">5 Apr </p><p style="margin-top: -10px;">4:43 AM</p></div>',
                angle:70, radius:'50%', zIndex:'1'
            }
            ],
    }
   },
   components: {
        'ejs-circulargauge': CircularGaugeComponent,
        'e-axis': AxisDirective,
        'e-axes': AxesDirective,
        'e-pointer': PointerDirective,
        'e-pointers': PointersDirective,
    },
    provide: {
    circulargauge: [Annotations]
   },

   methods: {
    load: function(args) {
    /* custom code start */
      let selectedTheme = location.hash.split("/")[1];
      selectedTheme = selectedTheme ? selectedTheme : "Material";
      args.gauge.theme =
        (selectedTheme.charAt(0).toUpperCase() +
            selectedTheme.slice(1)).replace(/-dark/i, 'Dark').replace(/-high/i, 'High').replace(/contrast/i, 'Contrast').replace(/5.3/i, '5');
    /* custom code end */
    },
    axisLabelRender: function (args) {
        if (args.value == 3 || args.value == 6 || args.value == 9 || args.value == 12) {
                args.text = args.value.toString();
        }
        else {
                args.text = "";
        }
    }
  }
}
</script>
