// syncfusionejs2_trial/Samples/React/src/speech-to-text/use-case.jsx
import { SpeechToTextComponent } from '@syncfusion/ej2-react-inputs';
import * as React from 'react';
import './use-case.css';
import { ChatUIComponent } from '@syncfusion/ej2-react-interactive-chat';
import { SampleBase } from '../common/sample-base';
export class Default extends SampleBase {
    speechToTextObj;
    chatUIObj;
    msgIdx = -1;
    isIndicatorVisible = false;
    emptyChatTemplate = () => {
        return (<div className="empty-chat">
                <span className="e-icons e-multiple-comment"></span>
                No transcript available. Start speaking to generate a transcript.
            </div>);
    };
    typingIndicatorTemplate = () => {
        return (<div className="e-typing-indicator ">
                <span className="e-user-text">Transcripting</span> 
                <div className="e-indicator-wrapper">
                    <span className="e-indicator"></span>
                    <span className="e-indicator">
                    </span><span className="e-indicator">
                    </span>
                </div>
            </div>);
    };
    buttonSettings = {
        stopIconCss: 'e-icons e-listen-icon'
    };
    onTranscriptChange = (args) => {
        var existingMsg = this.chatUIObj.messages[this.msgIdx];
        if (existingMsg) {
            this.chatUIObj.updateMessage({ text: args.transcript }, existingMsg.id);
            this.chatUIObj.scrollToBottom();
        }
        else {
            var newMsg = { id: 'msg-' + (this.msgIdx + 1), text: args.transcript, author: { id: 'testing-user', user: 'Testing User' } };
            this.chatUIObj.addMessage(newMsg);
        }
        // Show typing indicator only if it’s not visible
        if (!this.isIndicatorVisible) {
            this.chatUIObj.typingUsers = [{ id: 'testing-user', user: 'Testing User' }];
            this.isIndicatorVisible = true;
        }
        // Final transcript
        if (!args.isInterimResult) {
            this.msgIdx + 1;
            this.speechToTextObj.transcript = '';
            this.chatUIObj.typingUsers = [];
            this.isIndicatorVisible = false;
        }
    };
    // Event handler for listening start
    onListeningStart = () => {
        var sttElement = document.querySelector('#speechToText');
        this.msgIdx = this.chatUIObj.messages.length;
        sttElement.classList.add('stt-listening-state');
        this.updateStatus('Listening... Speak now...');
    };
    // Event handler for listening stop
    onListeningStop = (args) => {
        var sttElement = document.querySelector('#speechToText');
        sttElement.classList.remove('stt-listening-state');
        this.chatUIObj.typingUsers = [];
        if (args.isInteracted)
            this.updateStatus('Click the mic button to start speaking...');
    };
    // Event handler for errors
    onErrorHandler = (args) => {
        this.updateStatus(args.errorMessage);
        if (args.error === 'unsupported-browser') {
            this.speechToTextObj.disabled = true;
        }
    };
    // Function to updates the speech recognition status message
    updateStatus = (status) => {
        document.querySelector('.speech-recognition-status').innerText = status;
    };
    render() {
        return (<div className="control-pane">
                <div className="control-section">
                    <div className="usecase-speechToText-section e-message">
                        <div className="stt-container">
                            <SpeechToTextComponent id="speechToText" ref={(speechtotext) => { this.speechToTextObj = speechtotext; }} buttonSettings={this.buttonSettings} transcriptChanged={this.onTranscriptChange} onStart={this.onListeningStart} onStop={this.onListeningStop} onError={this.onErrorHandler} cssClass={"usecase-stt-btn"}/>
                            <span className="speech-recognition-status">Click the mic button to start speaking...</span>
                        </div>
                        <div className="transcript-container">
                            <ChatUIComponent id="transcript-content" ref={(chatui) => { this.chatUIObj = chatui; }} showHeader={false} showFooter={false} timeStampFormat={"MMM d, h:mm a"} autoScrollToBottom={true} emptyChatTemplate={this.emptyChatTemplate} typingUsersTemplate={this.typingIndicatorTemplate}/>
                        </div>
                    </div>
                </div>
                <div id="action-description">
                    <p>
                        This sample demonstrates a live transcription feature that converts spoken words into text in real-time. Click the microphone button to start speaking, and the transcribed text will appear in the ChatUI component as a conversation with timestamps.
                    </p>
                </div>
                
                <div id="description">
                    <p>
                        The Speech-to-Text component captures audio input and transcribes it dynamically, updating the transcript in the <code>ChatUI</code> component. Each spoken segment is displayed as an individual message with a timestamp, ensuring a structured conversation format.
                    </p>
                    <p>
                        The integration with <code>ChatUI</code> allows real-time updates, maintaining the natural flow of conversation. This setup enhances readability and interaction, making it easier to follow and review the transcription.
                    </p>
                </div>
            </div>);
    }
}

// syncfusionejs2_trial/Samples/Vue/src/speech-to-text/use-case.vue
<template>
    <div class="control-section">
        <div class="usecase-speechToText-section e-message">
            <div class="stt-container">
                <!-- Microphone button for Speech-to-Text -->
                <ejs-speechtotext id="speechToText" ref="speechToTextObj" cssClass="usecase-stt-btn" :buttonSettings='buttonSettings' @transcriptChanged="onTranscriptChange" @onStart="onListeningStart" @onStop="onListeningStop" @onError="onErrorHandler" ></ejs-speechtotext>
                <span class="speech-recognition-status">Click the mic button to start speaking...</span>
            </div>
            <div class="transcript-container">
                <!-- Transcription output -->
                <ejs-chatui id="transcript-content" ref="chatUIObj" :showHeader="showHeader" :showFooter="showFooter" :timeStampFormat="timeStampFormat" :autoScrollToBottom="autoScrollToBottom" emptyChatTemplate="emptyChatTemplate" typingUsersTemplate="typingIndicatorTemplate">
                    <template v-slot:emptyChatTemplate="">
                        <div class="empty-chat">
                            <span class="e-icons e-multiple-comment"></span>
                            No transcript available. Start speaking to generate a transcript.
                        </div>
                    </template>
                    <template v-slot:typingIndicatorTemplate="">
                        <div class="e-typing-indicator ">
                            <span class="e-user-text">Transcripting</span> 
                            <div class="e-indicator-wrapper">
                                <span class="e-indicator"></span>
                                <span class="e-indicator">
                                </span><span class="e-indicator">
                                </span>
                            </div>
                        </div>
                    </template>
                </ejs-chatui>
            </div>
        </div>
    </div>
    <div id="action-description">
        <p>
            This sample demonstrates a live transcription feature that converts spoken words into text in real-time. Click the microphone button to start speaking, and the transcribed text will appear in the ChatUI component as a conversation with timestamps.
        </p>
    </div>

    <div id="description">
        <p>
            The Speech-to-Text component captures audio input and transcribes it dynamically, updating the transcript in the <code>ChatUI</code> component. Each spoken segment is displayed as an individual message with a timestamp, ensuring a structured conversation format.
        </p>
        <p>
            The integration with <code>ChatUI</code> allows real-time updates, maintaining the natural flow of conversation. This setup enhances readability and interaction, making it easier to follow and review the transcription.
        </p>
    </div>
</template>

<script>
import { SpeechToTextComponent } from "@syncfusion/ej2-vue-inputs";
import { ChatUIComponent } from '@syncfusion/ej2-vue-interactive-chat';

export default {
    data : function(){
        return{
            buttonSettings: {
                stopIconCss: 'e-icons e-listen-icon'
            },
            user: { id: 'testing-user', user: 'Testing User' },
            msgIdx: -1,
            isIndicatorVisible: false,
            showHeader: false,
            showFooter: false,
            timeStampFormat: 'MMM d, h:mm a',
            autoScrollToBottom: true
        };
    },
    components: {
        "ejs-speechtotext": SpeechToTextComponent,
        "ejs-chatui": ChatUIComponent
    },
    methods: {
        onTranscriptChange: function(args) {
            var chatObj = this.$refs.chatUIObj.ej2Instances;
            var existingMsg  =  chatObj.messages[this.msgIdx];
            if(existingMsg ) {
                chatObj.updateMessage({ text: args.transcript }, existingMsg.id);
                chatObj.scrollToBottom();
            } else {
                var newMsg  = { id: 'msg-' + (this.msgIdx + 1), text: args.transcript, author: this.user };
                chatObj.addMessage(newMsg);
            }
        
            if (!this.isIndicatorVisible) {
                chatObj.typingUsers = [this.user];
                this.isIndicatorVisible = true;
            }
        
            // Final transcript
            if (!args.isInterimResult) {
                this.msgIdx++;
                this.$refs.speechToTextObj.ej2Instances.transcript = '';
                chatObj.typingUsers = [];
                this.isIndicatorVisible = false;
            }
        },
        onListeningStart: function(){
            var sttElement = document.querySelector('#speechToText');
            this.msgIdx = this.$refs.chatUIObj.ej2Instances.messages.length;
            sttElement.classList.add('stt-listening-state');
            this.updateStatus('Listening... Speak now...');
        },
        onListeningStop: function(args) {
            var sttElement = document.querySelector('#speechToText');
            sttElement.classList.remove('stt-listening-state');
            this.$refs.chatUIObj.ej2Instances.typingUsers = [];
            if (args.isInteracted)
                this.updateStatus('Click the mic button to start speaking...');
        },
        onErrorHandler: function(args) {
            this.updateStatus(args.errorMessage);
            if (args.error === 'unsupported-browser') {
                this.$refs.speechToTextObj.ej2Instances.disabled = true;
            }
        },
        updateStatus: function(status) {
            document.querySelector('.speech-recognition-status').innerText = status;
        }
    }
}
</script>

<style>
    .usecase-speechToText-section,
    .e-bigger .usecase-speechToText-section {
        width: 90%;
        height: 55vh;
        margin: 0 auto;
        padding: 0;
        display: flex;
    }

    .usecase-speechToText-section #transcript-content {
        border: none;
        border-top-right-radius: 8px;
        border-bottom-right-radius: 8px;
    }

    .usecase-speechToText-section .stt-container {
        width: 70%;
        height: 100%;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        gap: 40px;
    }

    .usecase-speechToText-section #speechToText.usecase-stt-btn {
        width: 100px;
        height: 100px;
        position: relative;
    }

    .usecase-speechToText-section .usecase-stt-btn .e-btn-icon,
    .e-bigger .usecase-speechToText-section .usecase-stt-btn .e-btn-icon {
        font-size: 50px;
    }

    .usecase-speechToText-section .transcript-container {
        width: 30%;
        height: 100%;
    }

    /* Create wave effect using pseudo-elements */
    .usecase-stt-btn::before,
    .usecase-stt-btn::after {
        content: "";
        position: absolute;
        top: 50%;
        left: 50%;
        width: 100%;
        height: 100%;
        border-radius: 50%;
        background: #9b9b9b;
        transform: translate(-50%, -50%) scale(1);
        opacity: 0;
        pointer-events: none;
    }

    .usecase-speechToText-section .stt-listening-state::before {
        animation: stt-wave-ring 1.5s infinite ease-out;
    }

    .usecase-speechToText-section .stt-listening-state::after {
        animation: stt-wave-ring 1.5s 0.75s infinite ease-out; /* Slight delay for second wave */
    }

    @keyframes stt-wave-ring {
        0% {
            transform: translate(-50%, -50%) scale(1);
            opacity: 0.8;
        }
        100% {
            transform: translate(-50%, -50%) scale(2);
            opacity: 0;
        }
    }

    .usecase-speechToText-section .empty-chat {
        width: 90%;
        display: flex;
        justify-content: center;
        align-items: center;
        font-size: 15px;
        flex-direction: column;
        gap: 10px;
        text-align: center;
        margin: auto;
    }

    .usecase-speechToText-section .empty-chat .e-multiple-comment {
        font-size: 50px;
    }

    .usecase-speechToText-section #transcript-content.e-chat-ui .e-message-group {
        max-width: 95%;
    }

    @media only screen and (max-width: 850px) {
        .usecase-speechToText-section, 
        .e-bigger .usecase-speechToText-section {
            flex-direction: column;
            height: 70vh;
        }
        .usecase-speechToText-section .transcript-container {
            width: 100%;
            height: 70vh;
            overflow: scroll;
        }
        .usecase-speechToText-section .stt-container {
            width: 100%;
            height: 55%;
        }
    }
</style>
