// syncfusionejs2_trial/Samples/React/src/circular-gauge/legend.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.Circle = void 0;
var React = require("react");
var property_pane_1 = require("../common/property-pane");
var ej2_react_circulargauge_1 = require("@syncfusion/ej2-react-circulargauge");
var sample_base_1 = require("../common/sample-base");
var ej2_react_dropdowns_1 = require("@syncfusion/ej2-react-dropdowns");
var ej2_react_buttons_1 = require("@syncfusion/ej2-react-buttons");
var SAMPLE_CSS = "\n    .legendPadding {\n        padding-top: 0px; margin-left: 0px; margin-top: 3px; padding-left:10px\n    }\n    .e-view.fluent2 #property .legendPadding, .e-view.fluent2-dark #property .legendPadding {\n        padding-top: 0px; margin-left: 0px !important; margin-top: 3px; padding-left:0px !important;\n    }\n    .e-view.fluent2-highcontrast #property .legendPadding {\n        margin-left: -8px !important;\n    }\n    ";
var Circle = /** @class */ (function (_super) {
    __extends(Circle, _super);
    function Circle() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        _this.loaded = false;
        _this.positionlist = [
            { value: 'Bottom' },
            { value: 'Top' },
            { value: 'Left' },
            { value: 'Right' },
            { value: 'Auto' }
        ];
        _this.alignlist = [
            { value: 'Center' },
            { value: 'Far' },
            { value: 'Near' }
        ];
        _this.shapelist = [
            { value: 'Circle', text: 'Circle' },
            { value: 'Rectangle', text: 'Rectangle' },
            { value: 'Triangle', text: 'Triangle' },
            { value: 'Diamond', text: 'Diamond' },
            { value: 'InvertedTriangle', text: 'Inverted Triangle' }
        ];
        return _this;
    }
    Circle.prototype.position = function () {
        this.gauge.legendSettings.position = this.positionElement.value;
    };
    Circle.prototype.alignment = function () {
        this.gauge.legendSettings.alignment = this.alignElement.value;
    };
    Circle.prototype.shape = function () {
        this.gauge.legendSettings.shape = this.dropElement.value;
    };
    Circle.prototype.load = function (args) {
        // custom code start
        var selectedTheme = location.hash.split('/')[1];
        selectedTheme = selectedTheme ? selectedTheme : 'Material';
        args.gauge.theme = ((selectedTheme.charAt(0).toUpperCase() +
            selectedTheme.slice(1)).replace(/-dark/i, 'Dark').replace(/-high/i, 'High').replace(/contrast/i, 'Contrast').replace(/5.3/i, '5'));
        // custom code end
    };
    Circle.prototype.onChartLoad = function (args) {
        var _this = this;
        if (!this.loaded) {
            this.loaded = true;
            this.legendPosition = new ej2_react_dropdowns_1.DropDownList({
                index: 0,
                width: 130,
                change: function () {
                    var position = _this.legendPosition.value.toString();
                }
            });
            this.legendPosition.appendTo('#legendPosition');
        }
    };
    Circle.prototype.enableToggleLegend = function (args) {
        this.gauge.legendSettings.toggleVisibility = args.checked;
    };
    Circle.prototype.enableLegend = function (args) {
        this.gauge.legendSettings.visible = args.checked;
        this.gauge.refresh();
    };
    Circle.prototype.render = function () {
        var _this = this;
        return (React.createElement("main", null,
            React.createElement("div", { className: 'control-pane' },
                React.createElement("div", { className: 'control-section row' },
                    React.createElement("div", { className: 'col-lg-8' },
                        React.createElement("style", null, SAMPLE_CSS),
                        React.createElement(ej2_react_circulargauge_1.CircularGaugeComponent, { load: this.load.bind(this), background: 'transparent', id: 'range-container', loaded: this.onChartLoad.bind(this), title: 'Measure of wind speed in km/h', titleStyle: { fontFamily: 'inherit' }, legendSettings: {
                                visible: true, position: "Bottom",
                                textStyle: {
                                    fontFamily: 'inherit',
                                    size: '12px'
                                }
                            }, ref: function (gauge) { return _this.gauge = gauge; } },
                            React.createElement(ej2_react_circulargauge_1.Inject, { services: [ej2_react_circulargauge_1.Annotations, ej2_react_circulargauge_1.Legend] }),
                            React.createElement(ej2_react_circulargauge_1.AxesDirective, null,
                                React.createElement(ej2_react_circulargauge_1.AxisDirective, { startAngle: 210, endAngle: 150, radius: '80%', minimum: 0, maximum: 120, majorTicks: {
                                        color: '#9E9E9E', height: 16, interval: 20
                                    }, lineStyle: { width: 2 }, minorTicks: {
                                        height: 8, interval: 10
                                    }, labelStyle: {
                                        position: 'Inside', useRangeColor: false,
                                        font: {
                                            fontFamily: 'inherit'
                                        }
                                    } },
                                    React.createElement(ej2_react_circulargauge_1.RangesDirective, null,
                                        React.createElement(ej2_react_circulargauge_1.RangeDirective, { start: 0, end: 5, color: '#ccffff', radius: '110%', legendText: 'Light Air' }),
                                        React.createElement(ej2_react_circulargauge_1.RangeDirective, { start: 5, end: 11, color: '#99ffff', radius: '110%', legendText: 'Light Breeze' }),
                                        React.createElement(ej2_react_circulargauge_1.RangeDirective, { start: 11, end: 19, color: '#99ff99', radius: '110%', legendText: 'Gentle Breeze' }),
                                        React.createElement(ej2_react_circulargauge_1.RangeDirective, { start: 19, end: 28, color: '#79ff4d', radius: '110%', legendText: 'Moderate Breeze' }),
                                        React.createElement(ej2_react_circulargauge_1.RangeDirective, { start: 28, end: 49, color: '#c6ff1a', radius: '110%', legendText: 'Strong Breeze' }),
                                        React.createElement(ej2_react_circulargauge_1.RangeDirective, { start: 49, end: 74, color: '#e6ac00', radius: '110%', legendText: 'Gale' }),
                                        React.createElement(ej2_react_circulargauge_1.RangeDirective, { start: 74, end: 102, color: '#ff6600', radius: '110%', legendText: 'Storm' }),
                                        React.createElement(ej2_react_circulargauge_1.RangeDirective, { start: 102, end: 120, color: '#ff0000', radius: '110%', legendText: 'Hurricane Force' })),
                                    React.createElement(ej2_react_circulargauge_1.PointersDirective, null,
                                        React.createElement(ej2_react_circulargauge_1.PointerDirective, { value: 70, radius: '60%', pointerWidth: 8, animation: { enable: true }, cap: {
                                                radius: 7
                                            }, needleTail: { length: '18%' } })))))),
                    React.createElement("div", { className: 'col-lg-4 property-section' },
                        React.createElement(property_pane_1.PropertyPane, { title: 'Properties' },
                            React.createElement("table", { id: 'property', role: 'none', title: 'Properties', className: 'property-panel-table', style: { width: '100%', marginLeft: '-10px' } },
                                React.createElement("tbody", null,
                                    React.createElement("tr", { style: { height: '50px' } },
                                        React.createElement("td", { style: { width: '20%' } },
                                            React.createElement("div", { id: 'enablePointer', style: { fontSize: "14px" } }, "Show Legend")),
                                        React.createElement("td", { style: { width: '40%' } },
                                            React.createElement("div", { className: 'legendPadding' },
                                                React.createElement(ej2_react_buttons_1.CheckBoxComponent, { id: 'enable', checked: true, change: this.enableLegend.bind(this) })))),
                                    React.createElement("tr", { style: { height: '50px' } },
                                        React.createElement("td", { style: { width: '20%' } },
                                            React.createElement("div", { id: 'enable', style: { fontSize: "14px" } }, "Show range when the legend item is toggled")),
                                        React.createElement("td", { style: { width: '40%' } },
                                            React.createElement("div", { className: 'legendPadding' },
                                                React.createElement(ej2_react_buttons_1.CheckBoxComponent, { id: 'enableToggle', checked: true, change: this.enableToggleLegend.bind(this) })))),
                                    React.createElement("tr", { style: { height: '50px' } },
                                        React.createElement("td", null,
                                            React.createElement("div", { id: 'position', style: { fontSize: "14px" } }, "Position")),
                                        React.createElement("td", null,
                                            React.createElement("div", { style: { paddingLeft: '20px' } },
                                                React.createElement(ej2_react_dropdowns_1.DropDownListComponent, { width: "100%", index: 0, change: this.position.bind(this), ref: function (d) { return _this.positionElement = d; }, dataSource: this.positionlist, fields: { text: 'value', value: 'value' } })))),
                                    React.createElement("tr", { style: { height: '50px' } },
                                        React.createElement("td", null,
                                            React.createElement("div", { id: 'range', style: { fontSize: "14px" } }, "Alignment")),
                                        React.createElement("td", null,
                                            React.createElement("div", { style: { paddingLeft: '20px' } },
                                                React.createElement(ej2_react_dropdowns_1.DropDownListComponent, { width: "100%", index: 0, change: this.alignment.bind(this), ref: function (d) { return _this.alignElement = d; }, dataSource: this.alignlist, fields: { text: 'value', value: 'value' } })))),
                                    React.createElement("tr", { style: { height: '50px' } },
                                        React.createElement("td", null,
                                            React.createElement("div", { id: 'pointColor', style: { fontSize: "14px" } }, "Shape")),
                                        React.createElement("td", null,
                                            React.createElement("div", { style: { paddingLeft: '20px' } },
                                                React.createElement(ej2_react_dropdowns_1.DropDownListComponent, { width: "100%", index: 0, change: this.shape.bind(this), ref: function (d) { return _this.dropElement = d; }, dataSource: this.shapelist, fields: { text: 'text', value: 'value' } })))))))))),
            React.createElement("section", { id: "action-description", "aria-label": "Description of Circular Gauge sample" },
                React.createElement("p", null, "This sample directs the visualization of moving wind types based on their speed via the legend of the circular gauge component. The visibility, shape, alignment, and position of the legend can all be customized.")),
            React.createElement("section", { id: "description", "aria-label": "Description of the Circular Gauge features demonstrated in this sample" },
                React.createElement("p", null,
                    "The legend provides useful information for interpreting what the circular gauge's axis range displays, and it can be represented in a variety of colors, shapes, and other identifiers depending on the data. To do so, use the ",
                    React.createElement("a", { target: '_blank', href: 'https://ej2.syncfusion.com/react/documentation/api/circular-gauge/legendSettingsModel/' }, "legendSettings"),
                    " and its properties."),
                React.createElement("p", null,
                    "More information on the legend can be found in this ",
                    React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/circular-gauge/gauge-legend/" }, "documentation section"),
                    "."))));
    };
    return Circle;
}(sample_base_1.SampleBase));
exports.Circle = Circle;

// syncfusionejs2_trial/Samples/Vue/src/circular-gauge/legend.vue
<template>
    <main><div>
        <div class="col-md-8 control-section">
        <div class="content-wrapper">
            <ejs-circulargauge ref="circulargauge" :background='background' :load='load' style='display:block' align='center' id='legend-container' :legendSettings='legendSettings' :title='title' :titleStyle='titleStyle'>
                <e-axes>
                    <e-axis :startAngle='startAngle' :endAngle='endAngle' :lineStyle='lineStyle' :labelStyle='labelStyle'  :ranges='ranges' :majorTicks='majorTicks' :minorTicks='minorTicks' :radius='radius1' minimum=0 maximum=120 >
                        <e-pointers>
                            <e-pointer :value='value' :radius='radius' :pointerWidth='pointerWidth' :needleTail='needleTail' :animation='animation'></e-pointer>
                        </e-pointers>
                    </e-axis>
                </e-axes>
            </ejs-circulargauge>
        </div>
    </div>
<br>
    <div class="col-md-4 property-section">
                    <table role="none" id="property" title="Properties" style="width: 100%; margin-left: -20px;">
                    <colgroup>
                        <col span="1" style="width: 50%;">
                        <col span="1" style="width: 50%;">
                    </colgroup>
                    <tbody>
                            <tr style="height: 50px">
                                <td>
                                    <div style="font-size:14px;margin-top: -2px"> Show legend </div>
                                </td>
                                <td style="width: 30%;">
                                    <div style="padding-top: 7px;padding-left: 0px;">
                                    <ejs-checkbox  id="enable" ref="enable"  :change='changeEnableLegend' checked=true></ejs-checkbox>
                                    </div>
                                </td>
                            </tr>
                            <tr style="height: 50px">
                                <td>
                                    <div style="width: 90%;font-size: 14px"> Show range when the legend item is toggled </div>
                                </td>
                                <td style="width: 30%;">
                                    <div style="padding-top: 0px;padding-left: 0px;margin-top: 10px">
                                    <ejs-checkbox  id="enabletoggle" ref="enabletoggle" :change='changeEnableToggle' checked=true></ejs-checkbox>
                                    </div>
                                </td>
                            </tr>
                            <tr style="height: 50px">
                                <td>
                                    <div style="font-size:14px"> Position </div>
                                </td>
                                <td>
                                    <div>
                                    <ejs-dropdownlist id='position' ref="legendPos" :dataSource='positiondata' index=0  :width='positionwidth' :change='changePosition'></ejs-dropdownlist>                      
                                    </div>
                                </td>
                            </tr>
                            <tr style="height: 50px">
                                <td>
                                    <div style="font-size:14px"> Alignment </div>
                                </td>
                                <td>
                                    <div>
                                    <ejs-dropdownlist id='alignment' ref="legendAlignment" :dataSource='alignmentdata' index=0  :width='alignmentwidth' :change='changeAlignment'></ejs-dropdownlist>                      
                                    </div>
                                </td>
                            </tr>
                        <tr style="height: 50px">
                                <td>
                                    <div style="font-size:14px"> Shape </div>
                                </td>
                                <td>
                                    <div>
                                    <ejs-dropdownlist id='shape' ref="legendShape" :dataSource='shapedata' :fields='shapefields' index=0  :width='shapewidth' :change='changeShape'></ejs-dropdownlist>                      
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
    </div>
</div>
<section id="action-description" aria-label="Description of Circular Gauge sample">
    <p>
        This sample directs the visualization of moving wind types based on their speed via the legend of the circular
        gauge component. The visibility, shape, alignment, and position of the legend can all be customized.
    </p>
</section>
        <section id="description" aria-label="Description of the Circular Gauge features demonstrated in this sample">
            <p>
                The legend provides useful information for interpreting what the circular gauge's axis range displays,
                and it can be represented in a variety of colors, shapes, and other identifiers depending on the data.
                To do so, use the <a target="_blank"
                    href="https://ej2.syncfusion.com/vue/documentation/api/circular-gauge/legendSettingsModel/">legendSettings</a>
                and its properties.
            </p>
            <p>
                More information on the legend can be found in this <a target="_blank"
                    href="https://ej2.syncfusion.com/vue/documentation/circular-gauge/gauge-legend/">documentation
                    section</a>.
            </p>
        </section>
</main>
</template>
<style scoped>
.property-panel-content td {
    padding-top: 0px;
}
</style>
<script>

import { CircularGaugeComponent, Legend, AxisDirective, AxesDirective, PointerDirective, PointersDirective } from "@syncfusion/ej2-vue-circulargauge";
import { DropDownListComponent } from '@syncfusion/ej2-vue-dropdowns';
import { CheckBoxComponent } from '@syncfusion/ej2-vue-buttons';

export default {
data:function(){
    return{
            title: 'Measure of wind speed in Km/h',
            background:'transparent',
            titleStyle: {                
                fontFamily: 'inherit'       
            },
            legendSettings: { 
                visible: true,
                position: 'Bottom',
                textStyle: {
                    fontFamily: 'inherit',
                    size: '12px'
                }
            },
            startAngle: 210,
            endAngle: 150,
            lineStyle: { width: 2 },
            labelStyle: {
                position: 'Inside', useRangeColor: false,
                font: { fontFamily: 'inherit' }
            },
            majorTicks: {
                height: 16, color: '#9E9E9E', interval: 20
            },
            minorTicks: {
                height: 8, interval: 10
            },
            radius1: '80%',
            minimum: 0,
            maximum: 120,
            pointerWidth: 8,
            radius: '60%',
            value: 70,
            animation: { enable: true },
            needleTail:  { length: '18%' },
            ranges: [
                { start: 0, end: 5, color:'#ccffff', radius: '110%', legendText: 'Light Air'},
                { start: 5, end: 11, color:'#99ffff', radius: '110%', legendText: 'Light Breeze' },
                { start: 11, end: 19, color:'#99ff99', radius: '110%', legendText: 'Gentle Breeze' },
                { start: 19, end: 28, color:'#79ff4d', radius: '110%', legendText: 'Moderate Breeze' },
                { start: 28, end: 49, color:'#c6ff1a', radius: '110%', legendText: 'Strong Breeze' },
                { start: 49, end: 74, color:'#e6ac00', radius: '110%', legendText: 'Gale' },
                { start: 74, end: 102, color:'#ff6600', radius: '110%', legendText: 'Storm' },
                { start: 102, end: 120, color:'#ff0000', radius: '110%', legendText: 'Hurricane Force' },
                ],
            positiondata:['Bottom', 'Top', 'Left', 'Right', 'Auto'],
            positionwidth: '100%',
            alignmentdata:['Center', 'Far', 'Near'],
            alignmentwidth:'100%',
            shapedata:[
            { Id:'Circle', level:'Circle'},
            { Id:'Rectangle', level:'Rectangle'},
            { Id:'Triangle', level:'Triangle'},
            { Id:'Diamond', level:'Diamond'},
            { Id:'InvertedTriangle', level:'Inverted triangle'}
            ],
            shapefields:{ text: 'level', value: 'Id' },
            shapewidth:'100%'
    }
},
components: {
    'ejs-circulargauge': CircularGaugeComponent,
    'e-axis': AxisDirective,
    'e-axes': AxesDirective,
    'e-pointer': PointerDirective,
    'e-pointers': PointersDirective,
    'ejs-dropdownlist': DropDownListComponent,
    'ejs-checkbox': CheckBoxComponent
},
provide: {
    circulargauge: [Legend]
},
methods: {
    changePosition:function(){
            this.$refs.circulargauge.ej2Instances.legendSettings.position = this.$refs.legendPos.ej2Instances.value;
    },
    changeAlignment:function(){
             this.$refs.circulargauge.ej2Instances.legendSettings.alignment = this.$refs.legendAlignment.ej2Instances.value;
    },
    changeShape:function(){
            this.$refs.circulargauge.ej2Instances.legendSettings.shape = this.$refs.legendShape.ej2Instances.value;
    },
    changeEnableLegend:function(e){
        this.$refs.circulargauge.ej2Instances.legendSettings.visible = e.checked;
        this.$refs.circulargauge.ej2Instances.refresh();
    },
    changeEnableToggle:function(e){
        this.$refs.circulargauge.ej2Instances.legendSettings.toggleVisibility = e.checked;
    },
    load: function(args) {
    /* custom code start */
      let selectedTheme = location.hash.split("/")[1];
      selectedTheme = selectedTheme ? selectedTheme : "Material";
      args.gauge.theme =
        (selectedTheme.charAt(0).toUpperCase() +
            selectedTheme.slice(1)).replace(/-dark/i, 'Dark').replace(/-high/i, 'High').replace(/contrast/i, 'Contrast').replace(/5.3/i, '5');
    /* custom code end */
    }
}
}
</script>
