// syncfusionejs2_trial/Samples/Vue/public/source/image-editor/file-restrict.vue
<template>
    <div class="control-section">
      <div style="text-align: center;">
        <div class="e-img-editor-dropdown-container">
        <label>Size AS</label><br />
          <ejs-dropdownbutton id="dropdownbtn" :content="defaultUnit" :items="units" :select="onSelect" :beforeItemRender="beforeItemRender"></ejs-dropdownbutton>
        </div>
        <div class="e-img-editor-numeric-textbox-container">
          <label>Minimum Size</label>
          <br/>
          <ejs-numerictextbox id="minFileSize" :value="minFileSize" :min="minFileSize" :style="{ width: '150px' }" :change="updateMinFileSize"></ejs-numerictextbox>
        </div>
        <div class="e-img-editor-numeric-textbox-container">
          <label>Maximum Size</label>
          <br/>
          <ejs-numerictextbox id="maxFileSize" :value="maxFileSize" :min="minFileSize" :style="{ width: '150px' }" :change="updateMaxFileSize"></ejs-numerictextbox>
        </div>
        <div class="e-img-editor-dropdown-container">
          <label>Allowed Extensions</label><br/>
          <ejs-multiselect id="allowedExtensions" :style="{ width: '225px' }" :dataSource="fileExtensionsList" :fields="fields" mode="CheckBox" showSelectAll="true" :value="allowedExtensions" :change="updateAllowedExtensions"></ejs-multiselect>
        </div>
      </div>
      <div class="e-img-editor-sample">
        <ejs-imageeditor
          :theme="themeValue"
          id="image-editor"
          ref="imgObj"
          :uploadSettings="uploadSettings"
          :created="onCreated"
        ></ejs-imageeditor>
      </div>
      <div id="action-description">
            <p>This sample demonstrates the file restriction feature in the Image Editor component, allowing customization of
        file extensions, minimum and maximum file sizes, and drag-and-drop functionality.</p>
      </div>
      <div id="description">
          <p>
            This sample highlights the enhanced configuration capabilities of the Image Editor component through the
            <b>uploadSettings</b> property. The following features are included:
          </p>
          <ul>
            <li><b>File Extensions</b>: Use a multi-select dropdown with checkboxes to dynamically choose the allowed file
            extensions. Supported values include <code>jpeg</code>, <code>jpg</code>, <code>png</code>,
            <code>svg</code>, <code>webp</code>, and <code>bmp</code>.</li>
            <li><b>File Size</b>: Numeric textboxes to set minimum and maximum file sizes dynamically.</li>
            <li><b>Dynamic Updates</b>: Changes made to the numeric textboxes or the dropdown options immediately reflect in the component's <code>uploadSettings</code>.</li>
            <li><b>Upload Settings</b>: Predefined settings include:
                <ul>
                    <li><b>Allowed Extensions</b>: <code>.jpeg</code>, <code>.png</code>, <code>.svg</code>, <code>.webp</code>, <code>.bmp</code></li>
                    <li><b>Minimum File Size</b>: 1 KB</li>
                    <li><b>Maximum File Size</b>: 100 KB</li>
                </ul>
            </li>
          </ul>
          <p>
            More information about Image Editor can be found in this <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/image-editor/getting-started/">documentation</a> section.
          </p>
      </div>
    </div>
</template>

<script>
import { ImageEditorComponent } from "@syncfusion/ej2-vue-image-editor";
import { MultiSelectComponent, CheckBoxSelection } from "@syncfusion/ej2-vue-dropdowns";
import { DropDownButtonComponent } from "@syncfusion/ej2-vue-splitbuttons";
import { NumericTextBoxComponent } from "@syncfusion/ej2-vue-inputs";
import { getComponent } from "@syncfusion/ej2-base";

export default {
  name: "FileRestrict",
  components: {
    "ejs-dropdownbutton": DropDownButtonComponent,
    "ejs-imageeditor": ImageEditorComponent,
    "ejs-multiselect": MultiSelectComponent,
    "ejs-numerictextbox": NumericTextBoxComponent,
  },
  data() {
    return {
      theme: 'Bootstrap5',
      defaultUnit: "KB",
      minFileSize: 1,
      maxFileSize: 100,
      allowedExtensions: [".jpeg", ".jpg", ".png", ".svg", ".webp", ".bmp"], // Default extensions
      fileExtensionsList: [
        { Name: "JPEG", Value: ".jpeg" },
        { Name: "JPG", Value: ".jpg" },
        { Name: "PNG", Value: ".png" },
        { Name: "SVG", Value: ".svg" },
	      { Name: "WebP", Value: ".webp" },
        { Name: "BMP", Value: ".bmp" }
      ],
      fields: { text: "Name", value: "Value" },
      uploadSettings: {
        minFileSize: 1,
        maxFileSize: 1.5,
        allowedExtensions: ".jpeg, .jpg, .png, .svg, .webp, .bmp",
      },
      units: [
        { text: "MB" },
        { text: "KB" },
      ]
    };
  },
  methods: {
    onCreated() {
      this.updateUploadSettings();
    },
    updateMinFileSize(args) {
      if (args && args.value >= 0) {
        this.minFileSize = args.value;
        this.updateUploadSettings();
      }
    },
    updateMaxFileSize(args) {
      if (args && args.value >= this.minFileSize) {
        this.maxFileSize = args.value;
        this.updateUploadSettings();
      }
    },
    updateAllowedExtensions(args) {
        if (args.value.length === 0) {
          this.allowedExtensions = ".jpeg, .jpg, .png, .svg, .webp, .bmp";
        } else {
          this.allowedExtensions = args.value;
        }
        this.updateUploadSettings();
    },
    updateUploadSettings() {
      this.uploadSettings.minFileSize = this.convertToBytes(this.minFileSize);
      this.uploadSettings.maxFileSize = this.convertToBytes(this.maxFileSize);
      this.uploadSettings.allowedExtensions = this.allowedExtensions.join(", ");
      if (this.$refs.imgObj) {
        let imgEditor = getComponent(document.getElementById('image-editor'), 'image-editor');
        imgEditor.uploadSettings = this.uploadSettings;
        imgEditor.dataBind();
      }
    },
    onSelect(args) {
      this.defaultUnit = args.item.text;
      this.updateUploadSettings();
    },
    beforeItemRender(args) {
      if (args.item.text === this.defaultUnit) {
        args.element.classList.add('e-selected');
      }
    },
    convertToBytes(value) {
      return value * (this.defaultUnit === "MB" ? 1024 * 1024 : 1024);
    }
  },
  provide: {
    multiselect: [CheckBoxSelection],
  },
  computed: {
    themeValue: {
        get: function () {
            return this.theme;
        },
        set: function (theme) {
            this.theme = theme
        }
    }
  },
  /* custom code start */
  mounted() {
    this.hasOpenedOnce = false;
    this.sidebarChangeHandler = (event) => {
      if (event.name === 'open') {
        if (this.hasOpenedOnce) return;
        this.hasOpenedOnce = true;
      }
      this.$refs.imgObj.ej2Instances.update();
    };
    this.$nextTick(() => {
      const sidebarEle = document.getElementById('left-sidebar');
      const instance = sidebarEle.ej2_instances[0];
      instance.removeEventListener('open', this.sidebarChangeHandler);
      instance.addEventListener('open', this.sidebarChangeHandler);
      instance.removeEventListener('change', this.sidebarChangeHandler);
      instance.addEventListener('change', this.sidebarChangeHandler);
    });
  }
  /* custom code end */
};
</script>

<style>
.e-img-editor-numeric-textbox-container, 
.e-img-editor-dropdown-container {
    display: inline-block;
    margin-right: 30px;
    text-align: left;
}

.e-img-editor-sample {
    height: 80vh;
    width: 100%;
    margin-top: 18px;
}

.control-wrapper {
	height: 100%;
}

.e-image-editor {
  margin: 0 auto;
}

.e-img-editor-dropdown-container #dropdownbtn {
  font-weight: 400;
}

@media only screen and (max-width: 700px) {
  .e-img-editor-sample {
    height: 75vh;
    width: 100%;
  }
  .e-img-editor-dropdown-container,
  .e-img-editor-numeric-textbox-container {
      display: block;
      margin-right: 0;
      margin-bottom: 20px;
      text-align: center;
  }
}
</style>

// syncfusionejs2_trial/Samples/React/src/image-editor/file-restrict.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.FileRestrict = void 0;
var React = require("react");
var ej2_react_image_editor_1 = require("@syncfusion/ej2-react-image-editor");
var ej2_react_dropdowns_1 = require("@syncfusion/ej2-react-dropdowns");
var ej2_react_splitbuttons_1 = require("@syncfusion/ej2-react-splitbuttons");
var ej2_react_inputs_1 = require("@syncfusion/ej2-react-inputs");
var sample_base_1 = require("../common/sample-base");
require("./file-restrict.css");
ej2_react_dropdowns_1.MultiSelectComponent.Inject(ej2_react_dropdowns_1.CheckBoxSelection);
var FileRestrict = /** @class */ (function (_super) {
    __extends(FileRestrict, _super);
    function FileRestrict() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        _this.minFileSize = 1;
        _this.maxFileSize = 100;
        _this.allowedExtensions = ".jpeg, .jpg, .png, .svg, .webp, .bmp";
        _this.fileSizeUnit = 'MB';
        _this.fileExtensionsList = [
            { Name: "JPEG", Value: ".jpeg" },
            { Name: "JPG", Value: ".jpg" },
            { Name: "PNG", Value: ".png" },
            { Name: "SVG", Value: ".svg" },
            { Name: "WebP", Value: ".webp" },
            { Name: "BMP", Value: ".bmp" }
        ];
        _this.units = [
            { text: "MB" },
            { text: "KB" },
        ];
        _this.updateUploadSettings = function () {
            if (_this.imgObj) {
                _this.imgObj.uploadSettings = {
                    minFileSize: _this.convertToBytes(_this.minFileSize),
                    maxFileSize: _this.convertToBytes(_this.maxFileSize),
                    allowedExtensions: _this.allowedExtensions
                };
                _this.imgObj.dataBind();
            }
        };
        _this.onSelect = function (e) {
            _this.fileSizeUnit = e.item.text;
            _this.updateUploadSettings();
        };
        _this.beforeItemRender = function (e) {
            if (e.itemData.text === _this.fileSizeUnit) {
                e.element.classList.add('e-selected');
            }
        };
        _this.onCreated = function () {
            _this.updateUploadSettings();
        };
        return _this;
    }
    FileRestrict.prototype.convertToBytes = function (value) {
        return value * (this.fileSizeUnit === "MB" ? 1024 * 1024 : 1024);
    };
    FileRestrict.prototype.render = function () {
        var _this = this;
        return (React.createElement("div", { className: "control-pane" },
            React.createElement("div", { className: "control-section" },
                React.createElement("div", { className: "row" },
                    React.createElement("div", { className: "col-lg-12 control-section" },
                        React.createElement("div", { style: { textAlign: 'center' } },
                            React.createElement("div", { className: "e-img-editor-dropdown-container" },
                                React.createElement("label", null, "Size As"),
                                React.createElement("br", null),
                                React.createElement(ej2_react_splitbuttons_1.DropDownButtonComponent, { id: "dropdownbtn", items: this.units, content: this.fileSizeUnit, select: this.onSelect, beforeItemRender: this.beforeItemRender })),
                            React.createElement("div", { className: "e-img-editor-numeric-textbox-container" },
                                React.createElement("label", null, "Minimum Size"),
                                React.createElement("br", null),
                                React.createElement(ej2_react_inputs_1.NumericTextBoxComponent, { value: this.minFileSize, min: this.minFileSize, width: "180px", change: function (e) {
                                        _this.minFileSize = e.value;
                                        _this.updateUploadSettings();
                                    } })),
                            React.createElement("div", { className: "e-img-editor-numeric-textbox-container" },
                                React.createElement("label", null, "Maximum Size"),
                                React.createElement("span", null, " (in Bytes)"),
                                React.createElement("br", null),
                                React.createElement(ej2_react_inputs_1.NumericTextBoxComponent, { value: this.maxFileSize, min: this.minFileSize, width: "180px", change: function (e) {
                                        _this.maxFileSize = e.value;
                                        _this.updateUploadSettings();
                                    } })),
                            React.createElement("div", { className: "e-img-editor-dropdown-container" },
                                React.createElement("label", null, "Allowed File Extensions"),
                                React.createElement("br", null),
                                React.createElement(ej2_react_dropdowns_1.MultiSelectComponent, { dataSource: this.fileExtensionsList, fields: { text: 'Name', value: 'Value' }, mode: "CheckBox", showSelectAll: true, value: this.allowedExtensions.split(', '), change: function (e) {
                                        if (e.value.length === 0) {
                                            _this.allowedExtensions = ".jpeg, .jpg, .png, .svg, .webp, .bmp";
                                        }
                                        else {
                                            _this.allowedExtensions = e.value.join(', ');
                                        }
                                        _this.updateUploadSettings();
                                    } }))),
                        React.createElement("div", { className: "e-img-editor-sample" },
                            React.createElement(ej2_react_image_editor_1.ImageEditorComponent, { id: "image-editor", ref: function (img) { _this.imgObj = img; }, uploadSettings: {
                                    minFileSize: this.convertToBytes(this.minFileSize),
                                    maxFileSize: this.convertToBytes(this.maxFileSize),
                                    allowedExtensions: this.allowedExtensions
                                }, created: this.onCreated }))))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null, "This sample demonstrates the file restriction feature in the Image Editor component, allowing customization of file extensions, minimum and maximum file sizes, and drag-and-drop functionality.")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null,
                    "This sample highlights the enhanced configuration capabilities of the Image Editor component through the ",
                    React.createElement("b", null, "uploadSettings"),
                    " property. The following features are included:"),
                React.createElement("ul", null,
                    React.createElement("li", null,
                        React.createElement("b", null, "File Extensions"),
                        ": Use a multi-select dropdown with checkboxes to dynamically choose the allowed file extensions. Supported values include ",
                        React.createElement("code", null, "jpeg"),
                        ", ",
                        React.createElement("code", null, "jpg"),
                        ", ",
                        React.createElement("code", null, "png"),
                        ", ",
                        React.createElement("code", null, "svg"),
                        ", ",
                        React.createElement("code", null, "webp"),
                        ", and ",
                        React.createElement("code", null, "bmp"),
                        "."),
                    React.createElement("li", null,
                        React.createElement("b", null, "File Size"),
                        ": Numeric textboxes to set minimum and maximum file sizes dynamically."),
                    React.createElement("li", null,
                        React.createElement("b", null, "Dynamic Updates"),
                        ": Changes made to the numeric textboxes or the dropdown options immediately reflect in the component's ",
                        React.createElement("code", null, "uploadSettings"),
                        "."),
                    React.createElement("li", null,
                        React.createElement("b", null, "Upload Settings"),
                        ": Predefined settings include:",
                        React.createElement("ul", null,
                            React.createElement("li", null,
                                React.createElement("b", null, "Allowed Extensions"),
                                ": ",
                                React.createElement("code", null, ".jpeg"),
                                ", ",
                                React.createElement("code", null, ".png"),
                                ", ",
                                React.createElement("code", null, ".svg"),
                                ", ",
                                React.createElement("code", null, ".webp"),
                                ", ",
                                React.createElement("code", null, ".bmp")),
                            React.createElement("li", null,
                                React.createElement("b", null, "Minimum File Size"),
                                ": 1 KB"),
                            React.createElement("li", null,
                                React.createElement("b", null, "Maximum File Size"),
                                ": 100 KB")))))));
    };
    return FileRestrict;
}(sample_base_1.SampleBase));
exports.FileRestrict = FileRestrict;
