// syncfusionejs2_trial/Samples/Vue/src/diagram/shape-gallery.vue
<template>
  <div class="control-section">
    <div style="width: 100%">
      <ejs-diagram
        ref="diagramObject"
        style="display: block"
        id="diagram"
        :width="width"
        :height="height"
        :nodes="nodes"
        :getNodeDefaults="getNodeDefaults"
        :snapSettings="snapSettings"
      ></ejs-diagram>
    </div>
    <div id="action-description">
      <p>
        This sample illustrates basic built-in shapes, such as basic shapes,
        flow shapes, and BPMN shapes.
      </p>
    </div>
    <div id="description">
      <p>
        This example shows how to define built-in shapes that are used to
        visualize geometric information, work flow, or a business flow diagrams.
        The <code>shape</code> property can be used to define the category of
        built-in shapes. Additionally, the <code>type</code> property of the
        <code>shape</code> allows you to choose the type of the shape.
      </p>
      <p style="font-weight: 500">Injecting Module</p>

      <p>
        The diagram component’s features are segregated into individual
        feature-wise modules. To use the BPMN shapes, inject
        <code>BpmnDiagrams</code> module using
        <code>provide: { diagram: [BpmnDiagrams] }</code> method.
      </p>
      <br />
    
    <p>Looking for the full Vue Diagram component overview, features, pricing, and documentation? Visit the <a href="https://www.syncfusion.com/vue-components/vue-diagram" target="_blank">Vue Diagram</a> page.</p>
</div>
  </div>
</template>

<script>
import {
  DiagramComponent,
  Diagram,
  BpmnDiagrams,
} from "@syncfusion/ej2-vue-diagrams";
import { Node, SnapConstraints } from "@syncfusion/ej2-vue-diagrams";
import {
  DropDownListComponent,
  ChangeEventArgs as DropDownChangeEventArgs,
} from "@syncfusion/ej2-vue-dropdowns";

// Function to create shape model objects
function createBasicShapeModel(shape, content) {
  return {
    shape: { type: "Basic", shape: shape },
    annotations: [{ content: content }],
  };
}

//Initialzise basic shape models
let basicShapeModel = [{
    shape: { type: "Text", content: "Basic Shapes" },
    style: {fontSize: 16,fill: "None",fontFamily: "sans-serif",bold:true,strokeWidth: 0,}},
  createBasicShapeModel("Rectangle", "Rectangle"),
  createBasicShapeModel("Ellipse", "Ellipse"),
  createBasicShapeModel("Triangle", "Triangle"),
  createBasicShapeModel("Plus", "Plus"),
  createBasicShapeModel("Star", "Star"),
  createBasicShapeModel("Pentagon", "Pentagon"),
  createBasicShapeModel("Heptagon", "Heptagon"),
  createBasicShapeModel("Octagon", "Octagon"),
  createBasicShapeModel("Trapezoid", "Trapezoid"),
  createBasicShapeModel("Decagon", "Decagon"),
  createBasicShapeModel("RightTriangle", "Right Triangle"),
  createBasicShapeModel("Parallelogram", "Parallelogram"),
];

// Function to create flow shape model objects
function createFlowShapeModel(shape, content) {
  return {
    shape: { type: "Flow", shape: shape },
    annotations: [{ content: content }]
  };
}

// To Initialize Flow shape models
let flowShapeModel = [
  {
  shape: { type: "Text", content: "Flow Shapes" },
  style: {fontSize: 16,fill: "None",fontFamily: "sans-serif",bold: true,strokeWidth: 0}
  },
  createFlowShapeModel("Terminator", "Terminator"),
  createFlowShapeModel("Process", "Process"),
  createFlowShapeModel("Decision", "Decision"),
  createFlowShapeModel("Document", "Document"),
  createFlowShapeModel("PreDefinedProcess", "Predefined Process"),
  createFlowShapeModel("PaperTap", "Paper Tape"),
  createFlowShapeModel("DirectData", "Direct Data"),
  createFlowShapeModel("SequentialData", "Direct Data"),
  createFlowShapeModel("Sort", "Sort"),
  createFlowShapeModel("MultiDocument", "Multi-Document"),
  createFlowShapeModel("Collate", "Collate"),
  createFlowShapeModel("SummingJunction", "Summing Junction"),
  createFlowShapeModel("Or", "Or"),
  createFlowShapeModel("InternalStorage", "Internal Storage"),
  createFlowShapeModel("Extract", "Extract"),
  createFlowShapeModel("ManualOperation", "Manual Operation"),
  createFlowShapeModel("Merge", "Merge"),
  createFlowShapeModel("OffPageReference", "Off-Page Reference"),
  createFlowShapeModel("SequentialAccessStorage", "Sequential Access Storage"),
  createFlowShapeModel("Data", "Data"),
  createFlowShapeModel("Card", "Card")
];

// Function to create BPMN shapes
function createBpmnShapeModel(shape, content, event=undefined) {
    return {
        shape: { type: 'Bpmn', shape: shape, event: event },
        annotations: [{ content: content }]
    };
}

// To Initialize Flow shape models
let bpmnShapeModel = [
    {
      shape: { type: "Text", content: "BPMN Shapes" },
      style: {fontSize: 16,fill: "none",fontFamily: "sans-serif",bold: true,strokeWidth: 0,},
    },
    createBpmnShapeModel('Event', 'Start Event', { event: 'Start', trigger: 'None' }),
    createBpmnShapeModel('Event', 'Intermediate Event', { event: 'Intermediate', trigger: 'None' }),
    createBpmnShapeModel('Event', 'End Event', { event: 'End', trigger: 'None' }),
    createBpmnShapeModel('Gateway', 'Gateway'),
    createBpmnShapeModel('Activity', 'Task', { activity: 'Task' }),
    {shape: {type: "Bpmn",shape: "Activity",activity: { activity: "SubProcess",
        subProcess: {
          type: "Transaction",
          transaction: {
            success: { visible: false },
            failure: { visible: false },
            cancel: { visible: false },
          }}}
     },
     annotations: [{ content: "Transaction" }],
    },
    createBpmnShapeModel('Message', 'Message'),
    createBpmnShapeModel('DataObject', 'Data Object'),
    createBpmnShapeModel('DataSource', 'Data Source'),
    createBpmnShapeModel('Group', 'Group'),
    createBpmnShapeModel('TextAnnotation', 'Text Annotation')
];


export default {
  components: {
    "ejs-diagram": DiagramComponent,
    "ejs-dropdownlist": DropDownListComponent,
  },
  data: function () {
    return {
      width: "100%",
      height: "800px",
      snapSettings: { constraints: SnapConstraints.None },
      nodes: getNodes(),
      //Defines the default node and connector properties
      getNodeDefaults: (node, diagram) => {
        return node;
      },
    };
  },
  provide: {
    diagram: [BpmnDiagrams],
  },
  mounted: function () {
    let diagram = this.$refs.diagramObject.ej2Instances;
    diagram.fitToPage();
  },
};

function getNodes() {

  var nodes = basicShapeModel.concat(flowShapeModel).concat(bpmnShapeModel);
  var offsetx = 60;
  var offsety = 60;
  var count = 1;
  const shapeTypeHeight = {
    Process: 20,
    Terminator: 20,
    Decision: 35,
    Document: 30,
    DirectData: 30,
    MultiDocument: 30,
    PreDefinedProcess: 30
  };
    nodes.forEach(node => {
    node.width = 40;
    node.height = 40;
    if (node.shape && node.shape.type === "Flow") {
      let shapeType = node.shape.shape;
      node.height = shapeTypeHeight[shapeType] || 40; // Default height if not found in lookup
     
    }
    node.offsetX = offsetx;
    node.offsetY = offsety;

    if (node.shape && !(node.shape.type === "Text") && node.annotations) {
      var label = node.annotations[0];
      label.verticalAlignment = "Top";
      label.offset = { y: 1 };
      label.margin = { top: 10 };

      offsetx += 90;
      //After 10 nodes 11th node will go next line
      if (count % 10 === 0) {
        offsety = offsety + 100;
        offsetx = 60;
      }
      count++;
    }
    if (node.shape && node.shape.type === "Text") {
      offsetx = 60;
      offsety += 50;
      count = 1;
      node.width = 150;
      node.height = 100;
      node.offsetX = 90;
      if (!(node.shape.content === "Basic Shapes")) {
        node.offsetX = 90;
        node.offsetY = offsety + 50;
        offsety +=  100;
      }
    }
  });
  return nodes;
}
</script>

// syncfusionejs2_trial/Samples/React/src/diagram/shape-gallery.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
var __spreadArray = (this && this.__spreadArray) || function (to, from, pack) {
    if (pack || arguments.length === 2) for (var i = 0, l = from.length, ar; i < l; i++) {
        if (ar || !(i in from)) {
            if (!ar) ar = Array.prototype.slice.call(from, 0, i);
            ar[i] = from[i];
        }
    }
    return to.concat(ar || Array.prototype.slice.call(from));
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShapeGallery = void 0;
var React = require("react");
var ej2_react_diagrams_1 = require("@syncfusion/ej2-react-diagrams");
var sample_base_1 = require("../common/sample-base");
// Function to create a text node
var createTextNode = function (content) { return ({
    shape: { type: "Text", content: content },
    constraints: ej2_react_diagrams_1.NodeConstraints.PointerEvents,
    style: {
        fontSize: 16,
        fill: "None",
        fontFamily: "sans-serif",
        bold: true,
        strokeWidth: 0
    }
}); };
// Function to create a shape node
var createShapeNode = function (type, shape, content, additionalProps) { return ({
    shape: __assign({ type: type, shape: shape }, additionalProps),
    annotations: [{ content: content }]
}); };
// Basic shape models
var basicShapes = [
    "Rectangle", "Ellipse", "Triangle", "Plus", "Star", "Pentagon",
    "Heptagon", "Octagon", "Trapezoid", "Decagon", "RightTriangle", "Parallelogram"
];
var basicShapeModels = __spreadArray([
    createTextNode("Basic Shapes")
], basicShapes.map(function (shape) { return createShapeNode("Basic", shape, shape); }), true);
// Flow shape models
var flowShapes = [
    { shape: "Terminator", content: "Terminator" },
    { shape: "Process", content: "Process" },
    { shape: "Decision", content: "Decision" },
    { shape: "Document", content: "Document" },
    { shape: "PreDefinedProcess", content: "Predefined Process" },
    { shape: "PaperTap", content: "Paper Tape" },
    { shape: "DirectData", content: "Direct Data" },
    { shape: "SequentialData", content: "Sequential Data" },
    { shape: "Sort", content: "Sort" },
    { shape: "MultiDocument", content: "Multi-Document" },
    { shape: "Collate", content: "Collate" },
    { shape: "SummingJunction", content: "Summing Junction" },
    { shape: "Or", content: "Or" },
    { shape: "InternalStorage", content: "Internal Storage" },
    { shape: "Extract", content: "Extract" },
    { shape: "ManualOperation", content: "Manual Operation" },
    { shape: "Merge", content: "Merge" },
    { shape: "OffPageReference", content: "Off-Page Reference" },
    { shape: "SequentialAccessStorage", content: "Sequential Access Storage" },
    { shape: "Data", content: "Data" },
    { shape: "Card", content: "Card" }
];
var flowShapeModels = __spreadArray([
    createTextNode("Flow Shapes")
], flowShapes.map(function (_a) {
    var shape = _a.shape, content = _a.content;
    return createShapeNode("Flow", shape, content);
}), true);
// BPMN shape models
var bpmnShapes = [
    { shape: "Event", content: "Start Event", event: { event: "Start", trigger: "None" } },
    { shape: "Event", content: "Intermediate Event", event: { event: "Intermediate", trigger: "None" } },
    { shape: "Event", content: "End Event", event: { event: "End", trigger: "None" } },
    { shape: "Gateway", content: "Gateway" },
    { shape: "Activity", content: "Task", activity: { activity: "Task" } },
    { shape: "Activity", content: "Transaction", activity: { activity: "SubProcess", subProcess: { type: "Transaction", transaction: { success: { visible: false }, failure: { visible: false }, cancel: { visible: false } } } } },
    { shape: "Message", content: "Message" },
    { shape: "DataObject", content: "Data Object" },
    { shape: "DataSource", content: "Data Source" },
    { shape: "Group", content: "Group" },
    { shape: "TextAnnotation", content: "Text Annotation" }
];
var bpmnShapeModels = __spreadArray([
    createTextNode("BPMN Shapes")
], bpmnShapes.map(function (_a) {
    var shape = _a.shape, content = _a.content, event = _a.event, activity = _a.activity, subProcess = _a.subProcess;
    return createShapeNode("Bpmn", shape, content, { event: event, activity: activity, subProcess: subProcess });
}), true);
var allShapeModels = __spreadArray(__spreadArray(__spreadArray([], basicShapeModels, true), flowShapeModels, true), bpmnShapeModels, true);
var diagramInstance;
var ShapeGallery = /** @class */ (function (_super) {
    __extends(ShapeGallery, _super);
    function ShapeGallery() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    ShapeGallery.prototype.rendereComplete = function () {
        diagramInstance.fitToPage({ mode: "Height" });
    };
    ShapeGallery.prototype.render = function () {
        return (React.createElement("div", { className: "control-panel" },
            React.createElement("div", { className: "control-section" },
                React.createElement("div", { style: { width: "100%" } },
                    React.createElement(ej2_react_diagrams_1.DiagramComponent, { id: "diagram", ref: function (diagram) { return (diagramInstance = diagram); }, width: "100%", height: "800px", snapSettings: { constraints: ej2_react_diagrams_1.SnapConstraints.None }, nodes: getNodes(), 
                        //Defines the default node and connector properties
                        getNodeDefaults: function (obj, diagram) {
                            return obj;
                        } },
                        React.createElement(ej2_react_diagrams_1.Inject, { services: [ej2_react_diagrams_1.DataBinding, ej2_react_diagrams_1.BpmnDiagrams] })))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null, "This sample illustrates basic built-in shapes, such as basic shapes, flow shapes, and BPMN shapes.")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null,
                    "This example shows how to define built-in shapes that are used to visualize geometric information, work flow, or a business flow diagrams. The ",
                    React.createElement("code", null, "shape"),
                    " property can be used to define the category of built-in shapes. Additionally, the",
                    React.createElement("code", null, "type"),
                    " property of the ",
                    React.createElement("code", null, "shape"),
                    " allows you to choose the type of the shape."),
                React.createElement("p", { style: { fontWeight: 500 } }, "Injecting Module"),
                React.createElement("p", null,
                    "The diagram component\u2019s features are segregated into individual feature-wise modules. To use the BPMN shapes, inject",
                    React.createElement("code", null, "BpmnDiagrams"),
                    " module into ",
                    React.createElement("code", null, "services"),
                    "."),
                React.createElement("br", null),
                React.createElement("p", null,
                    "Looking for the full React Diagram component overview, features, pricing, and documentation? Visit the ",
                    React.createElement("a", { href: "https://www.syncfusion.com/react-components/react-diagram", target: "_blank" }, "React Diagram"),
                    " page."))));
    };
    return ShapeGallery;
}(sample_base_1.SampleBase));
exports.ShapeGallery = ShapeGallery;
// To set default values for different types of nodes.
function getNodes() {
    var nodes = allShapeModels;
    var offsetx = 60;
    var offsety = 50;
    var count = 1;
    var updateFlowShapeHeight = function (shapeType) {
        switch (shapeType) {
            case 'Process':
            case 'Terminator':
            case 'Document':
            case 'DirectData':
            case 'MultiDocument':
            case 'PreDefinedProcess':
                return 30;
            case 'Decision':
                return 35;
            default:
                return 40;
        }
    };
    nodes.forEach(function (node) {
        node.width = 40;
        node.height = 40;
        if (node.shape.type === 'Flow') {
            node.height = updateFlowShapeHeight(node.shape.shape);
        }
        node.offsetX = offsetx;
        node.offsetY = offsety;
        if (node.shape.type !== 'Text') {
            node.annotations[0].verticalAlignment = 'Top';
            node.annotations[0].offset = { y: 1 };
            node.annotations[0].margin = { top: 8 };
            offsetx += 90;
            if (count % 10 === 0) {
                offsety += 100;
                offsetx = 60;
            }
            count++;
        }
        else {
            offsetx = 60;
            offsety += 50;
            count = 1;
            node.width = 150;
            node.height = 50;
            node.offsetX = 90;
            if (node.shape.content !== 'Basic Shapes') {
                node.offsetY = offsety + 50;
                offsety += 100;
            }
        }
    });
    return nodes;
}
