// syncfusionejs2_trial/Samples/Vue/source/rich-text-editor/file-browser.vue
<template>
    <div>
        <div class="control-section">
            <div class="control-section">
                <div class="control-wrapper">
                    <div class="sample-container">
                        <div class="default-section">
                            <ejs-richtexteditor ref="rteObj" :toolbarSettings="toolbarSettings" :fileManagerSettings="fileManagerSettings">
                                <p>Rich Text Editor allows inserting images from online sources as well as the local computers where you want to insert the image in your content.</p>
                                <p><b>Get started Quick Toolbar to click on the image</b></p>
                                <p>It is possible to add custom style on the selected image inside the RichTextEditor through the quick toolbar.</p>
                                <img id="rteImageID" style="width:300px; height:300px;transform: rotate(0deg);" alt="Logo" src="./images/RTEImage-Feather.png">
                            </ejs-richtexteditor>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div id="action-description">
            <p>This sample demonstrates the option to insert the image into the RichTextEditor content using FileManager. Click the open folder button from the toolbar item to insert the image.</p>
        </div>

        <div id="description">
            <p>The FileManager feature provides an option to insert the image into the editor and its supports various cloud service.
                It supports all the basic file operations such as create, rename, delete, cut, copy, paste, upload, download and so on.
            </p>

            <p><b>Injecting Module:</b></p>
            <p>RichTextEditor features are segregated into individual feature-wise modules. To use FileManager tool, 
                we need to inject FileManager module into provider section.</p>

            <p><b>Note:</b> File Manager’s upload functionality is restricted in online demo.</p>
        </div>
    </div>
</template>

<script>
import { RichTextEditorComponent, Toolbar, Image, Link, HtmlEditor, QuickToolbar, FileManager, PasteCleanup, Table, Video, Audio, ClipBoardCleanup, AutoFormat } from "@syncfusion/ej2-vue-richtexteditor";

let hostUrl = 'https://services.syncfusion.com/vue/production/';

export default {
    components: {
      'ejs-richtexteditor': RichTextEditorComponent
    },
    data: function() {
        return {
            toolbarSettings: {
                items: ['FileManager', 'Image']
            },
            fileManagerSettings: {
                enable: true,
                ajaxSettings: {
                    url: hostUrl + 'api/RichTextEditor/FileOperations',
                    getImageUrl: hostUrl + 'api/RichTextEditor/GetImage',
                    uploadUrl: hostUrl + 'api/RichTextEditor/Upload',
                    downloadUrl: hostUrl + 'api/RichTextEditor/Download'
                }
            }
        };
    },
    provide: {
        richtexteditor:[Toolbar, Image,  Link, HtmlEditor, QuickToolbar, FileManager, PasteCleanup, Table, Video, Audio, ClipBoardCleanup, AutoFormat]
    }
}
</script>

// syncfusionejs2_trial/Samples/React/src/rich-text-editor/file-browser.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.FileBrowser = void 0;
var React = require("react");
var ej2_react_richtexteditor_1 = require("@syncfusion/ej2-react-richtexteditor");
var ej2_react_richtexteditor_2 = require("@syncfusion/ej2-react-richtexteditor");
var sample_base_1 = require("../common/sample-base");
var FileBrowser = /** @class */ (function (_super) {
    __extends(FileBrowser, _super);
    function FileBrowser() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        _this.hostUrl = 'https://services.syncfusion.com/react/production/';
        _this.toolbarSettings = {
            items: ['FileManager', 'Image']
        };
        _this.fileManagerSettings = {
            enable: true,
            ajaxSettings: {
                url: _this.hostUrl + 'api/RichTextEditor/FileOperations',
                getImageUrl: _this.hostUrl + 'api/RichTextEditor/GetImage',
                uploadUrl: _this.hostUrl + 'api/RichTextEditor/Upload',
                downloadUrl: _this.hostUrl + 'api/RichTextEditor/Download'
            }
        };
        return _this;
    }
    FileBrowser.prototype.render = function () {
        return (React.createElement("div", { className: 'control-pane' },
            React.createElement("div", null,
                React.createElement("div", { className: 'control-section', id: "rteAPI" },
                    React.createElement("div", { className: 'rte-control-section' },
                        React.createElement(ej2_react_richtexteditor_1.RichTextEditorComponent, { toolbarSettings: this.toolbarSettings, fileManagerSettings: this.fileManagerSettings },
                            React.createElement("p", null, "Rich Text Editor allows inserting images from online sources as well as the local computers where you want to insert the image in your content."),
                            React.createElement("p", null,
                                React.createElement("b", null, "Get started Quick Toolbar to click on the image")),
                            React.createElement("p", null, "It is possible to add custom style on the selected image inside the RichTextEditor through the quick toolbar."),
                            React.createElement("img", { id: 'rteImageID', style: { width: '300px', height: '300px', transform: 'rotate(0deg)' }, alt: "Logo", src: "./src/rich-text-editor/images/RTEImage-Feather.png" }),
                            React.createElement(ej2_react_richtexteditor_1.Inject, { services: [ej2_react_richtexteditor_1.HtmlEditor, ej2_react_richtexteditor_1.Toolbar, ej2_react_richtexteditor_1.Image, ej2_react_richtexteditor_1.Link, ej2_react_richtexteditor_1.QuickToolbar, ej2_react_richtexteditor_2.FileManager, ej2_react_richtexteditor_1.PasteCleanup, ej2_react_richtexteditor_1.Table, ej2_react_richtexteditor_1.Video, ej2_react_richtexteditor_1.Audio, ej2_react_richtexteditor_1.ClipBoardCleanup, ej2_react_richtexteditor_1.AutoFormat] }))))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null, "This sample demonstrates the option to insert the image into the RichTextEditor content using FileManager. Click the open folder button from the toolbar item to insert the image.")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null, "The FileManager feature provides an option to insert the image into the editor and its supports various cloud service. It supports all the basic file operations such as create, rename, delete, cut, copy, paste, upload, download and so on."),
                React.createElement("p", null,
                    React.createElement("b", null, "Injecting Module:")),
                React.createElement("p", null, "RichTextEditor features are segregated into individual feature-wise modules. To use FileManager tool, we need to inject FileManager module into the service"),
                React.createElement("p", null,
                    React.createElement("b", null, "Note:"),
                    " File Manager\u2019s upload functionality is restricted in online demo."))));
    };
    return FileBrowser;
}(sample_base_1.SampleBase));
exports.FileBrowser = FileBrowser;
