// syncfusionejs2_trial/Samples/Vue/src/tree-grid/checkbox-column.vue
<template>
<div class="col-lg-12 control-section">
    <div aria-label="Task List with Checkbox">
        <ejs-treegrid :dataSource='data' childMapping='subtasks' :treeColumnIndex='1' :height='400' :autoCheckHierarchy= 'true' aria-label="Task List with Checkbox">
            <e-columns>
                <e-column field='taskID' headerText='Task ID' width='70' textAlign='Right'></e-column>
                <e-column field='taskName' headerText='Task Name' width='200' :showCheckbox='true'></e-column>
                <e-column field='startDate' headerText='Start Date' width='90' format="yMd" textAlign='Right'></e-column>
                <e-column field='endDate' headerText='End Date' width='90' format="yMd" textAlign='Right'></e-column>
                <e-column field='duration' headerText='Duration' width='80' textAlign='Right'></e-column>
                <e-column field='progress' headerText='Progress' width='80' textAlign='Right'></e-column>
                <e-column field='priority' headerText='Priority' width='90'></e-column>
            </e-columns>
        </ejs-treegrid>
    </div>

    <div id="action-description">
    <p>
        This sample demonstrates the checkbox column selection functionality of Tree Grid. Click on any parent record checkbox then the child record checkboxes will get selected and parent record checkbox will get selected while checking all of its child items.
    </p>
</div>

<div id="description">
    <p>The Tree Grid component can be rendered with checkbox on existing column and also this can be enabled by <code>showCheckbox</code> property as true in columns API.
    </p>
    <p>
        For hierarchy selection between the records, we need to enable the <code>autoCheckHierarchy</code> property.
    </p>
    <p>
       While using Tree Grid in a touch device, you have an option to select the checkboxes by tapping on the checkbox.
    </p>
    <p>
        More information on the paging configuration can be found in this <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/treegrid/columns/columns#checkbox-column">documentation section</a>.
    </p>
    <p>
        Looking for the full Vue Tree Grid component overview, features, pricing, and documentation? Visit our <a target="_blank" href="https://www.syncfusion.com/vue-components/vue-tree-grid">Vue Tree Grid component</a> page.
    </p>
</div>

</div>
</template>
<!-- custom code start -->
<style>
.e-bigger.bootstrap5 .e-treegrid .e-hierarchycheckbox .e-frame, .e-bigger.bootstrap5-dark .e-treegrid .e-hierarchycheckbox .e-frame{
    height: 16px;
    width: 16px;
}
</style>
<!-- custom code end -->
<script lang="ts">
import { TreeGridComponent, ColumnDirective, ColumnsDirective, Page } from "@syncfusion/ej2-vue-treegrid";
import { sampleData } from "./data-source";

export default {
  components: {
    'ejs-treegrid': TreeGridComponent,
    'e-column': ColumnDirective,
    'e-columns': ColumnsDirective
  },  
  data: () => {
    return {
      data: sampleData,
    };
  },
  provide: {
      treegrid: [ Page ]
    },

}
</script>

// syncfusionejs2_trial/Samples/React/src/treegrid/checkbox-column.tsx
import * as ReactDOM from 'react-dom';
import * as React from 'react';
import { TreeGridComponent, ColumnsDirective, ColumnDirective } from '@syncfusion/ej2-react-treegrid';
import { sampleData } from './data';
import { SampleBase } from '../common/sample-base';

const SAMPLE_CSS = `
.e-bigger.bootstrap5 .e-treegrid .e-hierarchycheckbox .e-frame, 
.e-bigger.bootstrap5-dark .e-treegrid .e-hierarchycheckbox .e-frame {
  height: 17px;
  width: 17px;
}
.e-bigger.bootstrap4 .e-treegrid .e-hierarchycheckbox .e-frame {
  height: 18px;
  width: 18px;
}`;

export class CheckboxColumn extends SampleBase<{}, {}> {

  render() {
    return (
      <div className='control-pane'>
        <div className='control-section'>
          <style>
            {SAMPLE_CSS}
          </style>
          <TreeGridComponent dataSource={sampleData} treeColumnIndex={1} childMapping='subtasks' height='410'
            autoCheckHierarchy={true}>
            <ColumnsDirective>
              <ColumnDirective field='taskID' headerText='Task ID' width='60' textAlign='Right'></ColumnDirective>
              <ColumnDirective field='taskName' headerText='Task Name' width='200' showCheckbox={true}></ColumnDirective>
              <ColumnDirective field='startDate' headerText='Start Date' width='90' format='yMd' textAlign='Right' />
              <ColumnDirective field='endDate' headerText='End Date' width='90' format='yMd' textAlign='Right' />
              <ColumnDirective field='duration' headerText='Duration' width='90' textAlign='Right' />
              <ColumnDirective field='progress' headerText='Progress' width='90' textAlign='Right' />
            </ColumnsDirective>
          </TreeGridComponent>
        </div>
        <div id="action-description">
          <p>This sample demonstrates the checkbox column selection functionality of Tree Grid. Click on any parent record checkbox then the child record checkboxes will get selected and
        parent record checkbox will get selected while checking all of its child items.</p>
        </div>
        <div id='description'>
          <p>
            The Tree Grid component can be rendered with checkbox on existing column and also this
            can be enabled by <code>showCheckbox</code> property as true in columns API.
          </p>
          <p>
            For hierarchy selection between the records, we need to enable the <code>autoCheckHierarchy</code> property.
          </p>  
          <p>
              While using Tree Grid in a touch device, you have an option to select the checkboxes by tapping on the checkbox.
         </p>
          <p>
              More information on the checkbox selection configuration can be found in this <a target="_blank" href="https://ej2.syncfusion.com/react/documentation/treegrid/columns/columns#checkbox-column">documentation section</a>.
          </p>
          <p>
            Looking for the full React Tree Grid component overview, features, pricing, and documentation? Visit our <a target="_blank" href="https://www.syncfusion.com/react-components/react-tree-grid">React Tree Grid component</a> page.
          </p>
        </div>
      </div>
    )
  }
}
