// syncfusionejs2_trial/Samples/React/src/treegrid/autowrap.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.AutoWrap = void 0;
var React = require("react");
var ej2_react_treegrid_1 = require("@syncfusion/ej2-react-treegrid");
var data_1 = require("./data");
var sample_base_1 = require("../common/sample-base");
var SAMPLE_CSS = "\n    .e-bigger .e-treegrid .e-treegridexpand,\n    .e-bigger .e-treegrid .e-treegridcollapse {\n        width: 18px;\n    }";
var AutoWrap = /** @class */ (function (_super) {
    __extends(AutoWrap, _super);
    function AutoWrap() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    AutoWrap.prototype.render = function () {
        return (React.createElement("div", { className: "control-pane" },
            React.createElement("style", null, SAMPLE_CSS),
            React.createElement("div", { className: "control-section" },
                React.createElement(ej2_react_treegrid_1.TreeGridComponent, { dataSource: data_1.wrapData, treeColumnIndex: 1, allowPaging: true, allowSorting: true, childMapping: "subtasks", allowTextWrap: true, height: '400', pageSettings: { pageSize: 11 }, allowFiltering: true, filterSettings: { type: 'Excel', hierarchyMode: 'Parent' } },
                    React.createElement(ej2_react_treegrid_1.ColumnsDirective, null,
                        React.createElement(ej2_react_treegrid_1.ColumnDirective, { field: "taskID", headerText: "Task ID", width: "140", textAlign: "Right" }),
                        React.createElement(ej2_react_treegrid_1.ColumnDirective, { field: "taskName", headerText: "Title", width: "240" }),
                        React.createElement(ej2_react_treegrid_1.ColumnDirective, { field: "description", headerText: "Description (Comprehensive Objectives for Deliverables)", width: "370" }),
                        React.createElement(ej2_react_treegrid_1.ColumnDirective, { field: "employeeName", headerText: "Assigned To", width: "180" }),
                        React.createElement(ej2_react_treegrid_1.ColumnDirective, { field: "priority", headerText: "Priority", width: "150", textAlign: "Center" }),
                        React.createElement(ej2_react_treegrid_1.ColumnDirective, { field: "status", headerText: "Status", width: "130", textAlign: "Center" }),
                        React.createElement(ej2_react_treegrid_1.ColumnDirective, { field: "startDate", headerText: "Start Date", width: "160", type: "date", format: "yMd", textAlign: "Right" }),
                        React.createElement(ej2_react_treegrid_1.ColumnDirective, { field: "endDate", headerText: "End Date", width: "160", type: "date", format: "yMd", textAlign: "Right" })),
                    React.createElement(ej2_react_treegrid_1.Inject, { services: [ej2_react_treegrid_1.Page, ej2_react_treegrid_1.Filter, ej2_react_treegrid_1.Sort] }))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null, "This sample demonstrates the Tree Grid with the text wrap option enabled for both headers and cell content. This setting ensures that long header text and cell values are fully visible by wrapping onto multiple lines instead of being truncated with an ellipsis. ")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null,
                    "In this demo, the ",
                    React.createElement("strong", null, "\"Title\""),
                    " and ",
                    React.createElement("strong", null, "\"Description\""),
                    " columns exceeds the available width, so its header and cell content are wrapped across multiple lines for better readability. Text wrapping is enabled by setting the Tree Grid's ",
                    React.createElement("code", null,
                        React.createElement("a", { "aria-label": "API link for documentation", target: "_blank", className: "code", href: "https://ej2.syncfusion.com/react/documentation/api/treegrid/index-default#allowtextwrap" }, "allowTextWrap")),
                    "property to ",
                    React.createElement("strong", null, "true"),
                    ", which automatically applies wrapping to both header and cell content."),
                React.createElement("p", null,
                    "More information about text wrap can be found in this",
                    React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/treegrid/cell/cell#autowrap-the-treegrid-content" }, "documentation"),
                    " section."),
                React.createElement("p", null,
                    "Looking for the full React Tree Grid component overview, features, pricing, and documentation? Visit our ",
                    React.createElement("a", { target: "_blank", href: "https://www.syncfusion.com/react-components/react-tree-grid" }, "React Tree Grid component"),
                    " page."))));
    };
    return AutoWrap;
}(sample_base_1.SampleBase));
exports.AutoWrap = AutoWrap;

// syncfusionejs2_trial/Samples/Vue/src/tree-grid/autowrap.vue
<template>
    <div class="control-section">
        <div id="action-description">
            <p>This sample demonstrates the Tree Grid with the text wrap option enabled
                for both headers and cell content. This setting ensures that long header
                text and cell values are fully visible by wrapping onto multiple lines
                instead of being truncated with an ellipsis. </p>
        </div>
        <div id="description">
            <p>In this demo, the <strong>"Title"</strong> and <strong>"Description"</strong> columns
                exceeds the available width, so its header and cell content are wrapped
                across multiple lines for better readability. Text wrapping is enabled
                by setting the Tree Grid's
                <code><a aria-label="API link for documentation"
                target="_blank" class="code"
                href="https://ej2.syncfusion.com/vue/documentation/api/treegrid/index-default#allowtextwrap">allowTextWrap</a></code>
                property to <strong>true</strong>, which automatically applies wrapping
                to both header and cell content.</p>
            <p>
                More information about text wrap can be found in this
                <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/treegrid/cell/auto-wrap">
                    documentation
                </a>section.
            </p>
            <p>
                Looking for the full Vue Tree Grid component overview, features, pricing, and documentation? Visit our <a target="_blank" href="https://www.syncfusion.com/vue-components/vue-tree-grid">Vue Tree Grid component</a> page.
            </p>
        </div>
        <div>
            <ejs-treegrid :dataSource='data' childMapping='subtasks' :allowTextWrap='true' :height='400'
                :allowSorting='true' :treeColumnIndex='1' :allowPaging='true' :pageSettings='pageSettings'
                :allowFiltering='true' :filterSettings='filterSettings'>
                <e-columns>
                    <e-column field='taskID' headerText='Task ID' textAlign='Right' width='140'></e-column>
                    <e-column field='taskName' headerText='Title' width='240'></e-column>
                    <e-column field='description' headerText='Description (Comprehensive Objectives for Deliverables)'
                        width='370'></e-column>
                    <e-column field='employeeName' headerText='Assigned To' width='180'></e-column>
                    <e-column field='priority' headerText='Priority' width='150' textAlign='Center'></e-column>
                    <e-column field='status' headerText='Status' width='130' textAlign='Center'></e-column>
                    <e-column field='startDate' headerText='Start Date' width='160' format="yMd"
                        textAlign='Right'></e-column>
                    <e-column field='endDate' headerText='End Date' width='160' format="yMd"
                        textAlign='Right'></e-column>
                </e-columns>
            </ejs-treegrid>
        </div>
    </div>
</template>
<!-- custom code start -->
<style>
.e-bigger.bootstrap5 .e-treegrid .e-treegridexpand,
.e-bigger.bootstrap5 .e-treegrid .e-treegridcollapse,
.e-bigger.bootstrap5-dark .e-treegrid .e-treegridexpand,
.e-bigger.bootstrap5-dark .e-treegrid .e-treegridcollapse {
    width: 18px;
}
</style>
<!-- custom code end -->
<script lang="ts">
import { TreeGridComponent, ColumnDirective, ColumnsDirective, Page, Filter, Sort } from "@syncfusion/ej2-vue-treegrid";
import { wrapData } from "./data-source";
 
export default {
    components: {
        'ejs-treegrid': TreeGridComponent,
        'e-column': ColumnDirective,
        'e-columns': ColumnsDirective
    },
    data: () => {
        return {
            data: wrapData,
            filterSettings: { type: 'Excel', hierarchyMode: 'Parent' },
            pageSettings: { pageCount: 4, pageSize: 10 }
        };
    },
    provide: {
        treegrid: [Page, Filter, Sort]
    },
    methods: {
    }
 
}
</script>
