// syncfusionejs2_trial/Samples/React/src/rich-text-editor/auto-save.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.AutoSave = void 0;
/**
 * Rich Text Editor Auto Save sample
 */
var React = require("react");
var ej2_react_richtexteditor_1 = require("@syncfusion/ej2-react-richtexteditor");
var sample_base_1 = require("../common/sample-base");
require("./auto-save.css");
var ej2_react_buttons_1 = require("@syncfusion/ej2-react-buttons");
var ej2_base_1 = require("@syncfusion/ej2-base");
var property_pane_1 = require("../common/property-pane");
var AutoSave = /** @class */ (function (_super) {
    __extends(AutoSave, _super);
    function AutoSave(props) {
        var _this = _super.call(this, props) || this;
        // Rich Text Editor items list
        _this.items = ['Bold', 'Italic', 'Underline', '|', 'Formats', 'Alignments', 'Blockquote',
            'OrderedList', 'UnorderedList', '|', 'CreateLink', 'Image', '|', 'SourceCode', 'Undo', 'Redo'];
        //Rich Text Editor ToolbarSettings
        _this.toolbarSettings = {
            items: _this.items
        };
        _this.savingRef = function (element) {
            _this.savingEle = element;
        };
        _this.savedRef = function (element) {
            _this.savedEle = element;
        };
        return _this;
    }
    AutoSave.prototype.updateStatus = function () {
        var _this = this;
        this.savingEle.style.display = 'block';
        this.savedEle.style.display = 'none';
        setTimeout(function () {
            if (!(0, ej2_base_1.isNullOrUndefined)(_this.savingEle) && !(0, ej2_base_1.isNullOrUndefined)(_this.savedEle)) {
                _this.savingEle.style.display = 'none';
                _this.savedEle.style.display = 'block';
            }
        }, 500);
    };
    AutoSave.prototype.onChange = function (e) {
        var _this = this;
        if (e.checked) {
            this.rteObj.saveInterval = 5000;
        }
        else {
            this.rteObj.saveInterval = 0;
            setTimeout(function () {
                _this.savingEle.style.display = 'none';
                _this.savedEle.style.display = 'none';
            }, 500);
        }
    };
    AutoSave.prototype.render = function () {
        var _this = this;
        return (React.createElement("div", { className: 'control-pane' },
            React.createElement("div", { className: 'col-lg-8' },
                React.createElement("div", { className: 'control-section', id: "rteAPI" },
                    React.createElement("div", { className: 'rte-control-section' },
                        React.createElement(ej2_react_richtexteditor_1.RichTextEditorComponent, { id: "autoSaveRTE", ref: function (richtexteditor) { _this.rteObj = richtexteditor; }, enablePersistence: true, placeholder: 'Start to type a content to save', saveInterval: 5000, toolbarSettings: this.toolbarSettings, change: this.updateStatus.bind(this) },
                            React.createElement("h2", null, "Welcome to the Rich Text Editor Demo!\uD83D\uDCDD"),
                            React.createElement("p", { style: { textAlign: 'start' } }, "Experience the power of modern content editing with advanced formatting, media embedding, and many other features. You can explore this demo for yourself."),
                            React.createElement("h5", null, "Explore the Possibilities! \uD83D\uDE80"),
                            React.createElement("ul", null,
                                React.createElement("li", null,
                                    React.createElement("b", null, "Highly customizable"),
                                    " - You can configure the toolbar, enable/disable features, and fine-tune the editing experience to match your needs."),
                                React.createElement("li", null,
                                    React.createElement("b", null, "Seamless content pasting"),
                                    " - Copy and paste from Microsoft Word, Outlook, or other editors or sources while preserving formatting, styles, and structure."),
                                React.createElement("li", null,
                                    React.createElement("b", null, "Import Word documents"),
                                    " - Convert ",
                                    React.createElement("b", null, "DOCX"),
                                    React.createElement("b", null, " files"),
                                    " into editable HTML content inside the editor using the Import from Word feature."),
                                React.createElement("li", null,
                                    React.createElement("b", null, "One-click Export"),
                                    " - Save your document as ",
                                    React.createElement("b", null, "PDF"),
                                    " \uD83D\uDCC4 or ",
                                    React.createElement("b", null, "Word (DOCX)"),
                                    " \uD83D\uDCDD with just a single click."),
                                React.createElement("li", null,
                                    React.createElement("b", null, "@Mentions"),
                                    " - Type ",
                                    React.createElement("span", { className: "e-mention-chip" },
                                        React.createElement("a", { href: "mailto:albert@gmail.com", title: "albert@gmail.com" }, "@Albert")),
                                    " to see available suggestions and tag users in your content."),
                                React.createElement("li", null,
                                    React.createElement("b", null, "Image Management"),
                                    " - Use the File Manager to browse, upload, and manage images within the editor.")),
                            React.createElement("p", null,
                                React.createElement("br", null)),
                            React.createElement("h5", null, "Powerful Features!"),
                            React.createElement("p", null,
                                "A quick overview of the essential features of the Rich Text Editor.",
                                React.createElement("br", null)),
                            React.createElement("table", { className: "e-rte-table", style: { width: '61.0405%', minWidth: '0px', height: '82px' } },
                                React.createElement("thead", null,
                                    React.createElement("tr", null,
                                        React.createElement("th", { style: { width: '29.9807%' } },
                                            "Feature",
                                            React.createElement("br", null)),
                                        React.createElement("th", { style: { width: '70.0193%' } },
                                            "Description",
                                            React.createElement("br", null)))),
                                React.createElement("tbody", null,
                                    React.createElement("tr", null,
                                        React.createElement("td", { style: { width: '29.981%' } },
                                            "Text Formatting",
                                            React.createElement("br", null)),
                                        React.createElement("td", { style: { width: '70.0193%' } },
                                            "Bold, Italic, Underline, Strikethrough, and more.",
                                            React.createElement("br", null))),
                                    React.createElement("tr", null,
                                        React.createElement("td", { style: { width: '29.9807%' } },
                                            "Lists & Indentation",
                                            React.createElement("br", null)),
                                        React.createElement("td", { style: { width: '70.019%' } },
                                            "Ordered, unordered, nested lists.",
                                            React.createElement("br", null))),
                                    React.createElement("tr", null,
                                        React.createElement("td", { style: { width: '29.9807%' } },
                                            "Tables",
                                            React.createElement("br", null)),
                                        React.createElement("td", { style: { width: '70.019%' } },
                                            "Insert and edit tables with styling.",
                                            React.createElement("br", null))),
                                    React.createElement("tr", null,
                                        React.createElement("td", { style: { width: '29.9807%' } },
                                            "Media Embedding",
                                            React.createElement("br", null)),
                                        React.createElement("td", { style: { width: '70.019%' } },
                                            "Images, videos, and iframes.",
                                            React.createElement("br", null))),
                                    React.createElement("tr", null,
                                        React.createElement("td", { style: { width: '29.9807%' } },
                                            "Mentions",
                                            React.createElement("br", null)),
                                        React.createElement("td", { style: { width: '70.019%' } },
                                            "Tag users and add comments",
                                            React.createElement("br", null))))),
                            React.createElement("p", null,
                                React.createElement("br", null)),
                            React.createElement("h5", null, "Effortless Image Handling!"),
                            React.createElement("p", null,
                                "Insert, resize, align, and manage images seamlessly within the editor.",
                                React.createElement("br", null)),
                            React.createElement("p", { style: { textAlign: 'center' } },
                                React.createElement("img", { alt: "Sky with sun", src: "https://cdn.syncfusion.com/ej2/richtexteditor-resources/RTE-Overview.png", width: "400", height: "200", className: "e-rte-image e-imgcenter" })),
                            React.createElement("p", null,
                                React.createElement("br", null)),
                            React.createElement("p", { style: { textAlign: 'center' } },
                                React.createElement("b", null, "\"Great writing begins with a great editor.\""),
                                React.createElement("b", null, " \u270D\uFE0F"),
                                " ",
                                React.createElement("br", null)),
                            React.createElement(ej2_react_richtexteditor_1.Inject, { services: [ej2_react_richtexteditor_1.Link, ej2_react_richtexteditor_1.Image, ej2_react_richtexteditor_1.HtmlEditor, ej2_react_richtexteditor_1.Toolbar, ej2_react_richtexteditor_1.QuickToolbar, ej2_react_richtexteditor_1.PasteCleanup, ej2_react_richtexteditor_1.Table, ej2_react_richtexteditor_1.Video, ej2_react_richtexteditor_1.Audio, ej2_react_richtexteditor_1.ClipBoardCleanup, ej2_react_richtexteditor_1.AutoFormat] }),
                            React.createElement(ej2_react_richtexteditor_1.Inject, { services: [ej2_react_richtexteditor_1.Link, ej2_react_richtexteditor_1.Image, ej2_react_richtexteditor_1.HtmlEditor, ej2_react_richtexteditor_1.Toolbar, ej2_react_richtexteditor_1.QuickToolbar, ej2_react_richtexteditor_1.PasteCleanup, ej2_react_richtexteditor_1.Table, ej2_react_richtexteditor_1.Video, ej2_react_richtexteditor_1.Audio, ej2_react_richtexteditor_1.ClipBoardCleanup, ej2_react_richtexteditor_1.AutoFormat] })),
                        React.createElement("div", { id: 'statusEle', className: 'current-status' },
                            React.createElement("div", { id: 'saving', ref: this.savingRef, style: { display: 'none' } },
                                React.createElement("div", { className: "e-icons e-icon-refresh" }, " "),
                                React.createElement("p", { className: 'status-text' }, " Saving changes")),
                            React.createElement("div", { id: 'saved', ref: this.savedRef, style: { display: 'none' } },
                                React.createElement("span", { className: "e-icons e-icon-tick" }, " "),
                                React.createElement("p", { className: 'status-text' }, "Changes saved")))))),
            React.createElement("div", { className: 'col-lg-4 property-section', id: "rteAPIProperty" },
                React.createElement(property_pane_1.PropertyPane, { title: 'Properties' },
                    React.createElement("label", { htmlFor: "checked", style: { padding: "10px 72px 10px 0" } }, " Auto Save "),
                    React.createElement(ej2_react_buttons_1.SwitchComponent, { id: "checked", ref: function (scope) { _this.switchObj = scope; }, change: this.onChange.bind(this), checked: true }))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null, "Demonstrates how to save the Rich Text Editor\u2019s content automatically with periodic interval. When you type or edit the content, it will be saved automatically by every 5 seconds. ")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null, "The Rich Text Editor provides options to save its content automatically using the \u2018saveInterval\u2019 property. By default, the save interval time has 10 seconds from built-in support, but it can be customizable as per the application needs. The interval is calculated based on editing the content and does not considered on idle state."),
                React.createElement("p", null, "We have configured save interval as 5 seconds in this example. You can save the content in server also using this \u2018auto save\u2019 option."),
                React.createElement("p", null, "When you disable this 'Auto Save' option in a sample, the value will be saved on focus-out from the editor."),
                React.createElement("p", null, "Rich Text Editor content will be automatically saved when you focus out the editor."))));
    };
    return AutoSave;
}(sample_base_1.SampleBase));
exports.AutoSave = AutoSave;

// syncfusionejs2_trial/Samples/Vue/source/rich-text-editor/auto-save.vue
<template>
<div>
<div class="col-lg-8 control-section">
    <div class="control-wrapper">
        <div class="sample-container">
            <div class="default-section">
        <ejs-richtexteditor ref="saveObj" :toolbarSettings="toolbarSettings" enablePersistence=true saveInterval=5000 placeholder="Start to type a content to save" :change="updateStatus">
          <h2>Welcome to the Rich Text Editor Demo!📝</h2><p style="text-align: start;">Experience the power of modern content editing with advanced formatting, media embedding, and many other features. You can explore this demo for yourself.</p><h5>Explore the Possibilities! 🚀</h5><ul><li><b>Highly customizable</b> -&nbsp;You can configure the toolbar, enable/disable features, and fine-tune the editing experience to match your needs.</li><li><b>Seamless content pasting</b> -&nbsp;Copy and paste from Microsoft Word, Outlook, or other editors or sources while preserving formatting, styles, and structure.</li><li><b>Import Word documents</b> -&nbsp;Convert <b>DOCX</b><b> files</b> into editable HTML content inside the editor using the Import from Word feature.</li><li><b>One-click Export</b> -&nbsp;Save your document as <b>PDF</b> 📄 or <b>Word (DOCX)</b> 📝 with just a single click.</li><li><b>@Mentions</b> -&nbsp;Type&nbsp;<span class="e-mention-chip"><a href="mailto:albert@gmail.com" title="albert@gmail.com">@Albert</a></span> to see available suggestions and tag users in your content.</li><li><b>Image Management</b> -&nbsp;Use the File Manager to browse, upload, and manage images within the editor.</li></ul><p><br/></p><h5>Powerful Features!</h5><p>A quick overview of the essential features of the Rich Text Editor.<br/></p><table class="e-rte-table" style="width: 61.0405%; min-width: 0px; height: 82px;"><thead style="height: 31.7073%;"><tr style="height: 31.7073%;"><th class="" style="width: 29.9807%;">Feature<br/></th><th class="" style="width: 70.0193%;">Description<br/></th></tr></thead><tbody><tr style="height: 34.1463%;"><td class="" style="width: 29.981%;">Text Formatting<br/></td><td style="width: 70.0193%;" class="">Bold, Italic, Underline, Strikethrough, and more.<br/></td></tr><tr style="height: 34.1463%;"><td style="width: 29.9807%;" class="">Lists &amp; Indentation<br/></td><td style="width: 70.019%;" class="">Ordered, unordered, nested lists.<br/></td></tr><tr><td style="width: 29.9807%;">Tables<br/></td><td style="width: 70.019%;" class="">Insert and edit tables with styling.<br/></td></tr><tr><td style="width: 29.9807%;">Media Embedding<br/></td><td style="width: 70.019%;" class="">Images, videos, and iframes.<br/></td></tr><tr><td style="width: 29.9807%;">Mentions<br/></td><td style="width: 70.019%;" class="">Tag users and add comments<br/></td></tr></tbody></table><p><br/></p><h5>Effortless Image Handling!</h5><p>Insert, resize, align, and manage images seamlessly within the editor.<br/></p><p style="text-align: center;"><img alt="Sky with sun" src="https://cdn.syncfusion.com/ej2/richtexteditor-resources/RTE-Overview.png" width="400" height="200" style="" class="e-rte-image e-imgcenter" /></p><p><br/></p><p style="text-align: center;"><b>"Great writing begins with a great editor."</b><b> ✍️</b> <br/></p>
        </ejs-richtexteditor>  
         <div id='statusEle' class='current-status'>
                    <div id='saving' v-if="Saving">
                        <div class="e-icons e-icon-refresh"> </div>
                        <p class='status-text'> Saving changes</p>
                    </div>
                    <div id='saved' v-if="Saved">
                        <span class="e-icons e-icon-tick"> </span>
                        <p class='status-text'>Changes saved</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-lg-4 property-section">
    <div title="Properties" id="property">
        <div class='toggle-btn'>
            <label for="checked" style="padding: 10px 70px 10px 0"> Auto Save </label>
            <ejs-switch id="checked" :change="onChange" :checked="true"></ejs-switch>
        </div>
    </div>
</div>
<div id="action-description">
    <p>Demonstrates how to save the Rich Text Editor’s content automatically with periodic interval. When you type or edit the content, it will be saved automatically by every 5 seconds. </p>
</div>

<div id="description">
    <p>The Rich Text Editor provides options to save its content automatically using the `saveInterval` property. By default, the save interval time has 10 seconds from built-in support, but it can be customizable as per the application needs. The interval
        is calculated based on editing the content and does not considered on idle state.
    </p>
    <p>We have configured save interval as 5 seconds in this example. You can save the content in server also using this `auto save` option.</p>
    <p>When you disable this `Auto Save` option in a sample, the value will be saved on focus-out from the editor.</p>
    <p>Rich Text Editor content will be automatically saved when you focus out the editor.</p>
</div>

</div>
</template>
<style scoped>
.control_wrapper {
    max-width: 500px;
    margin: auto;
    border: 1px solid #dddddd;
    border-radius: 3px;
}

.control-section {
    overflow: auto;
    padding-bottom: 10px;
    position: relative;
}

    .current-status {
        float: right;
        padding: 11px;
        margin-right: 22px;
        font-size: 12px;
        display: inline-block;
    }
    
    .e-icons.e-icon-refresh::before {
        content: "\e606";
    }
    
    .btn-text {
        display: inline;
        padding: 2px 35px 2px 64px;
    }
    
    .e-icons.e-icon-tick::before {
        content: "\e614";
    }
    
    .status-text {
        padding: 4px;
    }
    
    .e-icon-refresh {
        width: 10px;
        display: inline-block;
        animation: spin 2s linear infinite;
    }
    
    @keyframes spin {
        0% {
            transform: rotate(0deg);
        }
        100% {
            transform: rotate(360deg);
        }
    }
    
    .bootstrap4 .e-icons.e-icon-refresh::before {
        content: "\e710";
    }
    
    .bootstrap4 .e-icons.e-icon-tick::before {
        content: "\e718";
    }

    .tailwind .e-icons.e-icon-refresh::before,
    .tailwind-dark .e-icons.e-icon-refresh::before,
    .tailwind3 .e-icons.e-icon-refresh::before,
    .tailwind3-dark .e-icons.e-icon-refresh::before {
        content: "\e711";
    }

    .tailwind .e-icons.e-icon-tick::before,
    .tailwind-dark .e-icons.e-icon-tick::before,
    .tailwind3 .e-icons.e-icon-tick::before,
    .tailwind3-dark .e-icons.e-icon-tick::before {
        content: "\e75d";
    }

    .bootstrap5 .e-icons.e-icon-refresh::before,
    .bootstrap5-dark .e-icons.e-icon-refresh::before,
    .bootstrap5\.3 .e-icons.e-icon-refresh::before,
    .bootstrap5\.3-dark .e-icons.e-icon-refresh::before,
    .fluent .e-icons.e-icon-refresh::before,
    .fluent-dark .e-icons.e-icon-refresh::before,
    .fluent2 .e-icons.e-icon-refresh::before,
    .fluent2-dark .e-icons.e-icon-refresh::before,
    .material3 .e-icons.e-icon-refresh::before,
    .material3-dark .e-icons.e-icon-refresh::before  {        
        content: "\e706";
    }

    .bootstrap5 .e-icons.e-icon-tick::before,
    .bootstrap5-dark .e-icons.e-icon-tick::before,
    .bootstrap5\.3 .e-icons.e-icon-tick::before,
    .bootstrap5\.3-dark .e-icons.e-icon-tick::before,
    .fluent .e-icons.e-icon-tick::before,
    .fluent-dark .e-icons.e-icon-tick::before,
    .fluent2 .e-icons.e-icon-tick::before,
    .fluent2-dark .e-icons.e-icon-tick::before,
    .material3 .e-icons.e-icon-tick::before,
    .material3-dark .e-icons.e-icon-tick::before {        content: "\e774";
    }

    .status-text {
        font-size: 14px;
        display: inline-block;
    }
</style>
<script>
import { RichTextEditorComponent, Toolbar, Link, Image, Count, HtmlEditor, QuickToolbar, PasteCleanup, Table, Video, Audio, ClipBoardCleanup, AutoFormat } from "@syncfusion/ej2-vue-richtexteditor";
import { SwitchComponent } from "@syncfusion/ej2-vue-buttons";
export default {
  components: {
    'ejs-richtexteditor': RichTextEditorComponent,
    'ejs-switch': SwitchComponent
  },
  data: function () {
    return {
      toolbarSettings: {
        items: ['Bold', 'Italic', 'Underline', '|', 'Formats', 'Alignments', 'Blockquote',
          'OrderedList', 'UnorderedList', '|', 'CreateLink', 'Image', '|', 'SourceCode', 'Undo', 'Redo']
      },
      Saving: false,
      Saved: false
    };
  },
  methods: {
    updateStatus: function () {
      this.Saving = true;
      this.Saved = false;
      setTimeout(() => {
        this.Saving = false;
        this.Saved = true;
      }, 500);
    },
    onChange: function (e) {
      var proxy = this;
      if (e.checked) {
        proxy.$refs.saveObj.ej2Instances.saveInterval = 5000;
      } else {
        proxy.$refs.saveObj.ej2Instances.saveInterval = 0;
        setTimeout(() => {
          this.Saving = false;
          this.Saved = false;
        }, 500);
      }
    }
  },
  provide: {
    richtexteditor: [Toolbar, Link, Image, Count, HtmlEditor, QuickToolbar, PasteCleanup, Table, Video, Audio, ClipBoardCleanup, AutoFormat]
  }
}
</script>
