// syncfusionejs2_trial/Samples/React/src/heatmap-chart/color-range.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.ColorRange = void 0;
var React = require("react");
var ej2_react_heatmap_1 = require("@syncfusion/ej2-react-heatmap");
var data = require("./color-range-sample-data.json");
var sample_base_1 = require("../common/sample-base");
var property_pane_1 = require("../common/property-pane");
var ej2_react_buttons_1 = require("@syncfusion/ej2-react-buttons");
// custom code start
var SAMPLE_CSS = "\n#control-container {\n    padding: 0px !important;\n}\n#source{\n    float: right; margin-right: 10p\n}";
// custom code end
var ColorRange = /** @class */ (function (_super) {
    __extends(ColorRange, _super);
    function ColorRange() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    ColorRange.prototype.fixed = function (args) {
        this.heatmap.paletteSettings.type = 'Fixed';
        this.heatmap.dataBind();
    };
    ColorRange.prototype.gradient = function (args) {
        this.heatmap.paletteSettings.type = 'Gradient';
        this.heatmap.dataBind();
    };
    ColorRange.prototype.render = function () {
        var _this = this;
        return (React.createElement("main", null,
            React.createElement("div", null,
                React.createElement("div", { className: 'col-md-9 control-section' },
                    React.createElement("style", null, SAMPLE_CSS),
                    React.createElement(ej2_react_heatmap_1.HeatMapComponent, { id: 'heatmap-container', ref: function (t) { return _this.heatmap = t; }, titleSettings: {
                            text: 'U.S. Government Energy Consumption by Agency (Trillion Btu)',
                            textStyle: {
                                fontWeight: '500',
                                fontStyle: 'Normal',
                                fontFamily: 'inherit',
                                size: '15px',
                            }
                        }, xAxis: {
                            labels: ['2005', '2006', '2007', '2008', '2009', '2010',
                                '2011', '2012', '2013', '2014', '2015'],
                            labelIntersectAction: 'None',
                            labelRotation: 45,
                            textStyle: {
                                fontFamily: 'inherit'
                            }
                        }, yAxis: {
                            labels: ['Agriculture', 'Energy', 'Administration', 'Health', 'Interior',
                                'Justice', 'NASA', 'Transportation'],
                            textStyle: {
                                fontFamily: 'inherit'
                            }
                        }, dataSource: data.colorRangeSample, paletteSettings: {
                            palette: [
                                { startValue: 5, endValue: 15, minColor: '#FFFFDA', maxColor: '#EDF8B6' },
                                { startValue: 15, endValue: 20, minColor: '#CAE8B4', maxColor: '#78D1BD' },
                                { startValue: 20, endValue: 31.7, minColor: '#36BCC6', maxColor: '#208FC6' },
                            ],
                            type: 'Gradient'
                        }, cellSettings: {
                            border: { width: 0 },
                            showLabel: false
                        }, tooltipSettings: {
                            textStyle: {
                                fontFamily: 'inherit'
                            }
                        }, legendSettings: {
                            textStyle: {
                                fontFamily: 'inherit'
                            }
                        }, load: this.load.bind(this) },
                        React.createElement(ej2_react_heatmap_1.Inject, { services: [ej2_react_heatmap_1.Legend, ej2_react_heatmap_1.Tooltip] }))),
                React.createElement("div", { className: "col-md-3 property-section" },
                    React.createElement(property_pane_1.PropertyPane, { title: 'Properties' },
                        React.createElement("table", { id: 'property', role: 'none', title: 'Properties', className: 'property-panel-table', style: { width: '100%', marginLeft: -10 } },
                            React.createElement("tbody", null,
                                React.createElement("tr", { style: { height: '50px' } },
                                    React.createElement("td", { style: { width: '60%' } },
                                        React.createElement("div", null, "Palette Type:")),
                                    React.createElement("td", { style: { width: '40%' } },
                                        React.createElement("div", { className: 'row' },
                                            React.createElement(ej2_react_buttons_1.RadioButtonComponent, { id: 'fixed', label: 'Fixed', name: 'paletteType', value: "Fixed", change: this.fixed.bind(this) })),
                                        React.createElement("div", { className: 'row' },
                                            React.createElement(ej2_react_buttons_1.RadioButtonComponent, { id: 'gradient', checked: true, label: 'Gradient', name: 'paletteType', value: "Gradient", change: this.gradient.bind(this) }))))))))),
            React.createElement("section", { id: "action-description", "aria-label": "Description of HeatMap sample" },
                React.createElement("p", null, "This sample visualizes the energy consumption in trillion British thermal units (btu) by the various public sectors in US government over the years. The data label is disabled in this sample, the tooltip displays the data point values.  In property panel, the options are available to change palette type in Heatmap by means of radio button.")),
            React.createElement("section", { id: "description", "aria-label": "Description of the HeatMap features demonstrated in this sample" },
                React.createElement("p", null,
                    "This example explains how to provide a specific color for specific range in heatmap. The ",
                    React.createElement("a", { href: "https://ej2.syncfusion.com/react/documentation/api/heatmap/paletteCollectionModel/#startvalue", target: "_blank" }, " startValue "),
                    " and ",
                    React.createElement("a", { href: "https://ej2.syncfusion.com/react/documentation/api/heatmap/paletteCollectionModel/#endvalue", target: "_blank" }, " endValue "),
                    " properties are used to define the range start and end values. The ",
                    React.createElement("a", { href: "https://ej2.syncfusion.com/react/documentation/api/heatmap/paletteCollectionModel/#mincolor", target: "_blank" }, " minColor "),
                    " and ",
                    React.createElement("a", { href: "https://ej2.syncfusion.com/react/documentation/api/heatmap/paletteCollectionModel/#maxcolor", target: "_blank" }, " maxColor "),
                    " properties represent the colors of given range."),
                React.createElement("p", null, "The tooltip is enabled in this example. To see the tooltip in action, hover the mouse over an item or tap an item on touch-enabled devices."),
                React.createElement("br", null),
                React.createElement("p", null,
                    React.createElement("b", null, "Injecting Module")),
                React.createElement("p", null,
                    "Heatmap component features are separated into discrete feature-based modules. To use a tooltip and the legend, inject the ",
                    React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/heatmap-chart/tooltip" }, "Tooltip"),
                    " and ",
                    React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/heatmap-chart/legend" }, "Legend"),
                    " module using the ",
                    React.createElement("code", null, '<Inject services={[Tooltip, Legend]} />'),
                    " method."))));
    };
    ColorRange.prototype.load = function (args) {
        // custom code start
        var selectedTheme = location.hash.split('/')[1];
        selectedTheme = selectedTheme ? selectedTheme : 'Material';
        args.heatmap.theme = (selectedTheme.charAt(0).toUpperCase() + selectedTheme.slice(1)).replace(/-dark/i, 'Dark').replace(/-high/i, 'High').replace(/contrast/i, 'Contrast').replace(/5.3/i, '5');
        // custom code end
        if (args.heatmap.element.offsetWidth < 500) {
            args.heatmap.xAxis.labelRotation = 0;
            args.heatmap.xAxis.labelIntersectAction = 'Trim';
        }
        else {
            args.heatmap.xAxis.labelRotation = 45;
            args.heatmap.xAxis.labelIntersectAction = 'None';
        }
    };
    ;
    return ColorRange;
}(sample_base_1.SampleBase));
exports.ColorRange = ColorRange;

// syncfusionejs2_trial/Samples/Vue/source/heatmap/color-range.vue
<template>
<main><div>
    <div class="control-section col-lg-9">
        <div>
        <div class="content-wrapper" style='width:99%'>
        <ejs-heatmap id='container' ref='heatmap' :titleSettings='titleSettings' :xAxis='xAxis' :yAxis='yAxis' :dataSource='dataSource' :cellSettings='cellSettings' :paletteSettings='paletteSettings' :load='load'></ejs-heatmap>
        </div>
        </div>
    </div>
    <div class="col-lg-3 property-section">
        <table role="none" id="property" title="Properties" style="width: 100%">
            <tbody>
                <tr style="height: 50px">
                    <td style="width: 60%">
                        <div>Palette Type:</div>
                    </td>
                    <td style="width: 40%;">
                        <div class="row">
                            <ejs-radiobutton id='fixed' ref='fixedType' label="Fixed" name="paletteType" value="Fixed"  :change='paletteChange'></ejs-radiobutton>
                        </div>
                        <div class="row">
                            <ejs-radiobutton id='gradient' ref='graidentType' label="Gradient" name="paletteType" value="Gradient" checked="true" :change='paletteChange'></ejs-radiobutton>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<section id="action-description" aria-label="Description of HeatMap sample">
    <p>
        This sample visualizes the energy consumption in trillion British thermal units (btu) by the various public sectors in US government over the years. The data label is disabled in this sample, the tooltip displays the data point values.  In property panel, the options are available to change palette type in Heatmap by means of radio button.
    </p>
</section>
<section id="description" aria-label="Description of the HeatMap features demonstrated in this sample">
    <p>
        This example explains how to provide a specific color for specific range in heatmap. The <code> startValue </code> and <code> endValue </code> properties are used to define the range start and end values. The <code> minColor </code> and <code> maxColor </code> properties represent the colors of given range.    </p>
    <p>
        Tooltip is enabled in this example, to see the tooltip in action, hover a point or tap on a point in touch enabled devices.
    </p>
    <br>
    <p><b>Injecting Module</b></p>
    <p>
      Heatmap component features are separated into discrete feature-based modules. To use a tooltip and the legend, inject the <a target="_blank"
      href="https://ej2.syncfusion.com/vue/documentation/heatmap-chart/tooltip">Tooltip</a> and <a target="_blank"
      href="https://ej2.syncfusion.com/vue/documentation/heatmap-chart/legend">Legend</a> modules using the <code>provide:{ heatmap:[Tooltip, Legend] }</code> method.
    </p>
</section>
</main>
</template>
<script>
import Vue from 'vue';
import { HeatMapPlugin, Tooltip, Legend } from "@syncfusion/ej2-vue-heatmap";
import { RadioButtonPlugin, CheckBoxPlugin } from "@syncfusion/ej2-vue-buttons";
Vue.use(HeatMapPlugin);
Vue.use(RadioButtonPlugin, CheckBoxPlugin);
export default Vue.extend({
data:function(){
return{
        titleSettings: {
           text: 'U.S. Government Energy Consumption by Agency (Trillion Btu)',
            textStyle: {
                fontWeight: '500',
                fontStyle: 'Normal',
                size: '15px',
            }
        },
         xAxis: {
            labels: ['2005', '2006', '2007', '2008', '2009', '2010',
                '2011', '2012', '2013', '2014', '2015'],
            labelRotation: 45,
            labelIntersectAction: 'None'
        },
        yAxis: {
            labels: ['Agriculture', 'Energy', 'Administration', 'Health', 'Interior',
                'Justice', 'NASA', 'Transportation']
        },
        dataSource: [
            [17.2, 24.6, 18.4, 9.6, 8.6, 18.8, 10.3, 5.0],
            [15.8, 29.9, 15.2, 31.3, 18.1, 5.5, 10.2, 14.6],
            [17.8, 25.5, 19.1, 12.9, 7.5, 30.7, 12.6, 5.6],
            [7.3, 20.1, 18.8, 20.3, 6.1, 9.0, 29.8, 7.7],
            [7.8, 30.5, 19.6, 10.8, 7.9, 15.5, 5.2, 14.3],
            [5.8, 31.7, 17.8, 10.4, 17.3, 15.7, 9.1, 7.7],
            [11.3, 29.1, 19.5, 11.5, 6.3, 12.9, 10.1, 6.7],
            [13.7, 31.3, 15.3, 6.2, 7.7, 16.1, 18.9, 12.6],
            [9.3, 29.9, 16.4, 14.5, 5.2, 12.3, 18.7, 7.3],
            [16.3, 27.4, 27.0, 5.5, 16.2, 12.6, 8.3, 15.2],
            [7.2, 20.1, 16.9, 9.0, 7.6, 16.2, 8.4, 29.0]
        ],
        cellSettings: { border: { width: 0 }, showLabel: false },
        paletteSettings: {
            palette: [{ startValue: 5, endValue: 15, minColor: '#FFFFDA', maxColor: '#EDF8B6' },
            { startValue: 15, endValue: 20, minColor: '#CAE8B4', maxColor: '#78D1BD' },
            { startValue: 20, endValue: 31.7, minColor: '#36BCC6', maxColor: '#208FC6' },
            ],
            type: 'Gradient'
        }
}
},
provide:{
    heatmap:[Tooltip, Legend]
},
methods: {
    load: function(args) {
      let selectedTheme = location.hash.split("/")[1];
      selectedTheme = selectedTheme ? selectedTheme : "Material";
      args.heatmap.theme =
        (selectedTheme.charAt(0).toUpperCase() + selectedTheme.slice(1)).replace(/-dark/i, "Dark").replace(/-high/i, 'High').replace(/contrast/i, 'Contrast').replace(/5.3/i, '5');
    },
    paletteChange : function()
    {
        this.$refs.heatmap.ej2Instances.paletteSettings.type = this.$refs.fixedType.ej2Instances.checked ? 'Fixed' : 'Gradient';
    },
  }
})
</script>
