// syncfusionejs2_trial/Samples/React/src/maps/marker-cluster.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.MarkerCluster = void 0;
/**
 * Marker cluster map sample
 */
var React = require("react");
var ej2_react_maps_1 = require("@syncfusion/ej2-react-maps");
var sample_base_1 = require("../common/sample-base");
var data = require("./map-data/marker-cluster.json");
var worldMap = require("./map-data/world-map.json");
var datasource = data;
var SAMPLE_CSS = "\n    .control-fluid {\n\t\tpadding: 0px !important;\n    }";
var MarkerCluster = /** @class */ (function (_super) {
    __extends(MarkerCluster, _super);
    function MarkerCluster() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    MarkerCluster.prototype.render = function () {
        return (React.createElement("main", null,
            React.createElement("div", { className: 'control-panel' },
                React.createElement("style", null, SAMPLE_CSS),
                React.createElement("div", { className: 'control-section' },
                    React.createElement(ej2_react_maps_1.MapsComponent, { id: "maps", load: this.load, useGroupingSeparator: true, format: 'n', zoomSettings: {
                            enable: true
                        }, titleSettings: {
                            text: 'Top 50 largest cities in the World',
                            textStyle: {
                                size: '16px'
                            }
                        } },
                        React.createElement(ej2_react_maps_1.Inject, { services: [ej2_react_maps_1.Marker, ej2_react_maps_1.MapsTooltip, ej2_react_maps_1.Zoom] }),
                        React.createElement(ej2_react_maps_1.LayersDirective, null,
                            React.createElement(ej2_react_maps_1.LayerDirective, { shapeData: worldMap, shapeSettings: {
                                    fill: '#C1DFF5'
                                }, markerClusterSettings: {
                                    allowClustering: true,
                                    shape: 'Image',
                                    height: 40,
                                    width: 40,
                                    labelStyle: { color: 'white' },
                                    imageUrl: 'src/maps/images/cluster.svg'
                                } },
                                React.createElement(ej2_react_maps_1.MarkersDirective, null,
                                    React.createElement(ej2_react_maps_1.MarkerDirective, { visible: true, dataSource: datasource.cluster, shape: 'Image', imageUrl: 'src/maps/images/ballon.png', tooltipSettings: {
                                            visible: true,
                                            valuePath: 'area',
                                            template: '<div id="template" style="width: 140px;opacity: 90%;background: rgba(53, 63, 76, 0.90);box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.40);padding:10px;border: 1px #abb9c6;border-radius: 4px;">' +
                                                '<div style="font-size:13px;color:#ffffff;font-weight: 500;"><center>${city}</center></div>' +
                                                '<hr style="margin-top: 2px;margin-bottom:5px;border:0.5px solid #DDDDDD">' +
                                                '<div><span style="font-size:13px;color:#cccccc">Rank : </span><span style="font-size:13px;color:#ffffff;font-weight: 500;">${Rank}</span></div>' +
                                                '<div><span style="font-size:13px;color:#cccccc">Area : </span><span style="font-size:13px;color:#ffffff;font-weight: 500;">${area} sq kms</span></div></div>',
                                        }, height: 20, width: 20, animationDuration: 0 })))))),
                React.createElement("div", { style: { float: 'right', marginRight: '10px' } },
                    "Source:",
                    React.createElement("a", { href: "http://www.citymayors.com/statistics/largest-cities-population-125.html", target: "_blank" }, "www.citymayors.com"))),
            React.createElement("section", { id: "action-description", "aria-label": "Description of Maps sample" },
                React.createElement("p", null, "This sample illustrates the world's top 50 cities by showing the markers in their locations and clustering the markers to avoid intersecting. ")),
            React.createElement("section", { id: "description", "aria-label": "Description of the Maps features demonstrated in this sample" },
                React.createElement("p", null, "In this example, you can see how to display multiple markers in the same region without intersecting each other. If a marker intersects, it will be clustered and the total number of markers will be displayed over the cluster. When zooming in, the number of clusters will be decreased, and the individual marker will be displayed. When zooming out, markers that intersect will again be clustered. You can use the \"clusterSettings\" property in \"layer\" to enable marker clustering."),
                React.createElement("p", null, "Tooltip is enabled in this example. To see the tooltip in action, hover the mouse over a marker or tap a marker in touch-enabled devices."),
                React.createElement("br", null),
                React.createElement("p", { style: { fontWeight: 500 } }, "Injecting Module"),
                React.createElement("p", null,
                    "Maps component features are segregated into individual feature-wise modules. To use a marker and cluster, inject the ",
                    React.createElement("code", null, "Marker"),
                    " module using the ",
                    React.createElement("code", null, "Maps.Inject(Marker)"),
                    " method."))));
    };
    MarkerCluster.prototype.load = function (args) {
        // custom code start
        var selectedTheme = location.hash.split('/')[1];
        selectedTheme = selectedTheme ? selectedTheme : 'Material';
        args.maps.theme = ((selectedTheme.charAt(0).toUpperCase() +
            selectedTheme.slice(1)).replace(/-dark/i, 'Dark').replace(/-high/i, 'High').replace(/contrast/i, 'Contrast').replace(/5.3/i, '5'));
        // custom code end
    };
    ;
    return MarkerCluster;
}(sample_base_1.SampleBase));
exports.MarkerCluster = MarkerCluster;

// syncfusionejs2_trial/Samples/Vue/public/source/maps/marker-cluster.vue
<template>
<main><div>
<div class="control-section">
<ejs-maps id='container' :load='load' :titleSettings='titleSettings' :zoomSettings='zoomSettings' :useGroupingSeparator='useGroupingSeparator' format='n'>
    <e-layers>
        <e-layer :shapeData='shapeData' :shapeSettings='shapeSettings' :markerClusterSettings='markerClusterSettings' :markerSettings='markerSettings'></e-layer>
    </e-layers>
</ejs-maps>
   
    <div style="float: right; margin-right: 10px;">Source:
           <a href="http://www.citymayors.com/statistics/largest-cities-area-125.html"
            target="_blank">www.citymayors.com</a>

         </div>
</div>
<div id="template" style="display:none">
    <div class="toolback">
                <div class="listing2">
                    <span style="text-align: center;">
                        ${city}                                            
                    </span>
                </div>
                <hr style="margin-top: 2px;margin-bottom:5px;border:0.5px solid #DDDDDD">                    
                <div>
                    <span class="listing1">Rank : </span><span class="listing2">${Rank}</span>
                </div>
                <div>
                    <span class="listing1">Area : </span><span class="listing2">${area} sq kms</span>
                </div> 
    </div>
</div>
</div>
<section id="action-description" aria-label="Description of Maps sample">
        <p>
            This sample illustrates the world's top 50 cities by showing the markers in their locations and clustering the markers to avoid intersecting.
       </p>
    </section>
    <section id="description" aria-label="Description of the Maps features demonstrated in this sample">
        <p>
          In this example, you can see how to display multiple markers in the same region without intersecting each other. If a marker intersects, 
          it will be clustered and the total number of markers will be displayed over the cluster. 
          When zooming in, the number of clusters will be decreased, and the individual marker will be displayed. 
          When zooming out, markers that intersect will again be clustered. You can use the "clusterSettings" property 
          in "layer" to enable marker clustering.
    
        </p>
        <p>
        Tooltip is enabled in this example. To see the tooltip in action, hover the mouse over a marker or tap a marker in touch enabled devices.
        </p>
        <p style="font-weight: 500">Injecting Module</p>
        <p>
        Maps component features are segregated into individual feature-wise modules. To use a marker and cluster, inject the Marker module using the Maps.Inject(Marker) method.
        </p>
       
    </section>

</main>
</template>
<style scoped>
    .toolback {
       border-radius: 4px;
       border: 1px #abb9c6;
       background: rgba(53, 63, 76, 0.90);
       box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.40);
       padding-bottom: 10px;
       padding-top: 10px;
       padding-left: 10px;
       padding-right: 10px;
       width: 140px;
   }
   .listing1 {
        font-size:13px;
        color:#cccccc
   }
   .listing2 {
        font-size:13px;
        color:#ffffff;
        font-weight: 500;
   }
</style>
<script>
import { MapsComponent, LayersDirective, LayerDirective, Marker, MapsTooltip, ILoadEventArgs, MapsTheme, Zoom } from '@syncfusion/ej2-vue-maps';
import { topPopulation } from '../maps/map-data/marker-location';
import { cluster } from '../maps/map-data/marker-cluster';
import { worldMap } from '../maps/map-data/world-map';

export default {
components: {
    'ejs-maps': MapsComponent,
    'e-layers': LayersDirective,
    'e-layer': LayerDirective
},
data:function(){
    return{
        useGroupingSeparator: true,
        zoomSettings: {
            enable: true
        },
        titleSettings: {
            text: 'Top 50 largest cities in the World',
            textStyle: {
                size: '16px',
                fontFamily: 'Segoe UI'
            }
        },
        shapeData: worldMap,
        shapeSettings: {
                    fill: '#C1DFF5'
        },
        markerClusterSettings: {
             allowClustering: true,
             shape: 'Image',
             height: 40,
             width: 40,
             labelStyle : { color: 'white'},
             imageUrl: 'src/maps/images/cluster.svg'
        },
        markerSettings: [
                    {
                        dataSource: cluster,
                        visible: true,
                        shape: 'Image',
                        imageUrl: 'src/maps/images/ballon.png',
                        height:20,
                        width:20,
                        animationDuration:0,
                        tooltipSettings: {
                            visible: true,
                            valuePath: 'area',
                            template:'#template'
                        }
                    },
        ]
    }
},
provide: {
    maps: [Marker, MapsTooltip, Zoom]
},
/* custom code start */
methods:{
   load: function(args) {
      let selectedTheme = location.hash.split("/")[1];
      selectedTheme = selectedTheme ? selectedTheme : "Material";
      args.maps.theme =
        (selectedTheme.charAt(0).toUpperCase() +
            selectedTheme.slice(1)).replace(/-dark/i, 'Dark').replace(/-high/i, 'High').replace(/contrast/i, 'Contrast').replace(/5.3/i, '5');
    } 
}
/* custom code end */
}
</script>
