// syncfusionejs2_trial/Samples/React/src/treegrid/filter-menu.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.FilterMenu = void 0;
var React = require("react");
var ej2_react_dropdowns_1 = require("@syncfusion/ej2-react-dropdowns");
var ej2_react_treegrid_1 = require("@syncfusion/ej2-react-treegrid");
var data_1 = require("./data");
var sample_base_1 = require("../common/sample-base");
var property_pane_1 = require("../common/property-pane");
var FilterMenu = /** @class */ (function (_super) {
    __extends(FilterMenu, _super);
    function FilterMenu() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        _this.filterType = [
            { text: 'Menu', value: 'Menu' },
            { text: 'Excel', value: 'Excel' }
        ];
        _this.modes = [
            { text: 'Parent', value: 'Parent' },
            { text: 'Child', value: 'Child' },
            { text: 'Both', value: 'Both' },
            { text: 'None', value: 'None' },
        ];
        return _this;
    }
    FilterMenu.prototype.onChange = function (sel) {
        var type = sel.value.toString();
        this.treegridInstance.filterSettings.type = type;
        this.treegridInstance.clearFiltering();
    };
    FilterMenu.prototype.onChange2 = function (sel) {
        var mode = sel.value.toString();
        this.treegridInstance.filterSettings.hierarchyMode = mode;
        this.treegridInstance.clearFiltering();
    };
    FilterMenu.prototype.render = function () {
        var _this = this;
        return (React.createElement("div", { className: 'control-pane' },
            React.createElement("div", { className: 'control-section' },
                React.createElement("div", { className: 'col-md-9' },
                    React.createElement(ej2_react_treegrid_1.TreeGridComponent, { dataSource: data_1.sampleData, ref: function (treegrid) { return _this.treegridInstance = treegrid; }, treeColumnIndex: 1, childMapping: 'subtasks', height: '350', allowPaging: true, allowFiltering: true, filterSettings: { type: 'Menu', hierarchyMode: 'Parent' } },
                        React.createElement(ej2_react_treegrid_1.ColumnsDirective, null,
                            React.createElement(ej2_react_treegrid_1.ColumnDirective, { field: 'taskID', headerText: 'Task ID', width: '90', textAlign: 'Right' }),
                            React.createElement(ej2_react_treegrid_1.ColumnDirective, { field: 'taskName', headerText: 'Task Name', width: '180' }),
                            React.createElement(ej2_react_treegrid_1.ColumnDirective, { field: 'startDate', headerText: 'Start Date', width: '90', format: 'yMd', textAlign: 'Right' }),
                            React.createElement(ej2_react_treegrid_1.ColumnDirective, { field: 'duration', headerText: 'Duration', width: '90', textAlign: 'Right' })),
                        React.createElement(ej2_react_treegrid_1.Inject, { services: [ej2_react_treegrid_1.Filter, ej2_react_treegrid_1.Page] }))),
                React.createElement("div", { className: 'col-md-3 property-section' },
                    React.createElement(property_pane_1.PropertyPane, { title: 'Properties' },
                        React.createElement("table", { id: 'property', title: 'Properties', className: 'property-panel-table', style: { width: '100%' } },
                            React.createElement("tbody", null,
                                React.createElement("tr", null,
                                    React.createElement("td", null,
                                        React.createElement("div", { style: { paddingTop: '10px' } }, " Filter Type ")),
                                    React.createElement("td", { style: { width: '70%' } },
                                        React.createElement("div", null,
                                            React.createElement(ej2_react_dropdowns_1.DropDownListComponent, { width: "110px", id: "seltype", change: this.onChange.bind(this), dataSource: this.filterType, value: "Menu" })))),
                                React.createElement("tr", null,
                                    React.createElement("td", null,
                                        React.createElement("div", { style: { paddingTop: '10px' } }, " Hierarchy Mode ")),
                                    React.createElement("td", { style: { width: '70%' } },
                                        React.createElement("div", null,
                                            React.createElement(ej2_react_dropdowns_1.DropDownListComponent, { width: "110px", id: "selmode", change: this.onChange2.bind(this), dataSource: this.modes, value: "Parent" }))))))))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null, " This sample demonstrates the way of filtering Tree Grid columns using menu and excel filter UI. In this sample, click the filtering icon from column header to show filter UI for a particular column. You can change the filter type from the properties panel.")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null,
                    "The filtering feature enables the user to view the reduced amount of records based on filter criteria. It can be enabled by setting ",
                    React.createElement("code", null, "allowFiltering"),
                    " property as true."),
                React.createElement("p", null, "Tree Grid supports the following filter types. They are "),
                React.createElement("ul", null,
                    React.createElement("li", null,
                        React.createElement("code", null, "FilterBar")),
                    React.createElement("li", null,
                        React.createElement("code", null, "Menu")),
                    React.createElement("li", null,
                        React.createElement("code", null, "Excel"))),
                "you can change the filter type by setting ",
                React.createElement("code", null, "filterSettings->type"),
                React.createElement("p", null, "Tree Grid provides support for a set of filtering modes with hierarchyMode property. The below are the type of filter mode available in Tree Grid. "),
                React.createElement("ul", null,
                    React.createElement("li", null,
                        React.createElement("code", null, "Parent"),
                        " - This is the default filter hierarchy mode in Tree Grid.The filtered records are displayed with its parent records, if the filtered records not have any parent record then the filtered record only displayed."),
                    React.createElement("li", null,
                        React.createElement("code", null, "Child"),
                        " - The filtered records are displayed with its child record, if the filtered records do not have any child record then only the filtered records are displayed."),
                    React.createElement("li", null,
                        React.createElement("code", null, "Both"),
                        " - The filtered records are displayed with its both parent and child record. If the filtered records do not have any parent and child record then only the filtered records are displayed."),
                    React.createElement("li", null,
                        React.createElement("code", null, "None"),
                        " - Only the filtered records are displayed.")),
                React.createElement("p", null,
                    "The Tree Grid now supports improved ",
                    React.createElement("code", null, "in"),
                    " and ",
                    React.createElement("code", null, "not in"),
                    " filter operators, allowing users to filter multiple values within the same column. When the menu filter is enabled, a Syncfusion DropDownList component with checkboxes appears to select the ",
                    React.createElement("code", null, "in"),
                    " or ",
                    React.createElement("code", null, "not in"),
                    " operators."),
                React.createElement("p", null, " In this demo, filter menu enabled by default, you can switch to other hierarchy mode of filtering by using dropdown."),
                React.createElement("p", null, "Injecting Module:"),
                React.createElement("p", null,
                    "Tree Grid features are segregated into individual feature-wise modules. To use filtering feature, we need to inject",
                    React.createElement("code", null, "Filter"),
                    " module into the ",
                    React.createElement("code", null, "services"),
                    "."),
                React.createElement("p", null,
                    "More information filter configuration can be found in this ",
                    React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/treegrid/filtering/filter-menu" }, "documentation section"),
                    "."),
                React.createElement("p", null,
                    "Looking for the full React Tree Grid component overview, features, pricing, and documentation? Visit our ",
                    React.createElement("a", { target: "_blank", href: "https://www.syncfusion.com/react-components/react-tree-grid" }, "React Tree Grid component"),
                    " page."))));
    };
    return FilterMenu;
}(sample_base_1.SampleBase));
exports.FilterMenu = FilterMenu;

// syncfusionejs2_trial/Samples/Vue/source/tree-grid/filtermenu.vue
<template>
<div class="control-section">
      <div class="col-md-9 control-section">
           <ejs-treegrid ref='treegrid' :dataSource='data' childMapping='subtasks' :height='350' :allowFiltering='true' :filterSettings='filterSettings' :treeColumnIndex='1' :allowPaging= 'true' :pageSettings='pageSettings'>
            <e-columns>
                <e-column field='taskID' headerText='Task ID' textAlign='Right' width='100'></e-column>
                <e-column field='taskName' headerText='Task Name' width='190'></e-column>
                <e-column field='startDate' headerText=' Start Date' textAlign='Right' format='yMd' type='date' width='125'></e-column>
                <e-column field='duration' headerText='Duration' textAlign='Right'  width='110'></e-column>
            </e-columns>
        </ejs-treegrid>
      </div>
      <div>
        <div class="col-md-3 property-section">
            <table id="property" title="Properties" style="width: 100%">
                <br/><br/>
                <tr style="height: 50px">
                    <td>
                        <div>Filter Type</div>
                    </td>
                    <td style="width: 70%; padding-left:10%">
                        <ejs-dropdownlist id='element' width='110px' :dataSource='typedata' value='Menu' :fields='typefields' :change="onTypechange"></ejs-dropdownlist>
                    </td>
                </tr>
                <tr style="height: 50px">
                    <td>
                        <div>Hierarchy Mode</div>
                    </td>
                    <td style="width: 70%; padding-left:10%">
                        <ejs-dropdownlist id='ddlelement' width='110px' :dataSource='ddldata' value='Parent' :fields='ddlfields' :change="onChange"></ejs-dropdownlist>
                    </td>
                </tr>
            </table>
        </div>
    </div>

    <div id="action-description">
    <p>
            This sample demonstrates the way of filtering Tree Grid columns using menu and excel filter UI. In this sample, click the filtering
            icon from column header to show filter UI for a particular column. You can change the filter type from the properties
            panel.
    </p>
</div>
    <div id="description">
    <p>The filtering feature enables the user to view the reduced amount of records based on filter criteria. It can be enabled
        by setting <code>allowFiltering
        </code> property as true. </p>
    <p>Tree Grid supports the following filter types. They are </p>
            <ul>
                <li><code>FilterBar</code></li>
                <li><code>Menu</code></li>
                <li><code>Excel</code></li>
            </ul>
            you can change the filter type by setting <code>filterSettings->type</code>

    <p>Tree Grid provides support for a set of filtering modes with <code>hierarchyMode</code> property. The below are the type of filter mode available in Tree Grid. </p>
    <ul>
        <li><code>Parent</code> - This is the default filter hierarchy mode in Tree Grid. 
        The filtered records are displayed with its parent records, if the filtered records not have any parent record then the filtered record only displayed.</li>
        <li><code>Child</code> - The filtered records are displayed with its child record, if the filtered records do not have any child record then only the filtered records are displayed.</li>
        <li><code>Both</code> - The filtered records are displayed with its both parent and child record.
        If the filtered records do not have any parent and child record then only the filtered records are displayed.</li>
        <li><code>None</code> - Only the filtered records are displayed.</li>
    </ul>
     <p>The Tree Grid now supports improved <code>in</code> and <code>not in</code> filter operators, allowing users to filter multiple values within the same column. When the menu filter is enabled, a Syncfusion DropDownList component with checkboxes appears to select the <code>in</code> or <code>not in</code> operators.</p>     
     <p style="font-weight: 500">Injecting Module:</p>
        <p>
            Tree Grid features are segregated into individual feature-wise modules. To use Filtering feature, we need to inject
            <code>
            Filter
            </code> module into the <code>provide</code> section.
        </p>
    <p>In this demo, you can type the value in the filterbar and press enter to filter particular column or select the value from filterbar template of Duration column.</p>
    <br/>
    <p>
        More information on the filter configuration can be found in this <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/treegrid/filtering/filter-menu">documentation section</a>.
    </p>
    <p>
        Looking for the full Vue Tree Grid component overview, features, pricing, and documentation? Visit our <a target="_blank" href="https://www.syncfusion.com/vue-components/vue-tree-grid">Vue Tree Grid component</a> page.
    </p>
</div> 
</div>
</template>

<script lang="ts">
import { TreeGridComponent, ColumnDirective, ColumnsDirective, Page, Filter } from "@syncfusion/ej2-vue-treegrid";
import { DropDownListComponent, ChangeEventArgs} from "@syncfusion/ej2-vue-dropdowns";
import { sampleData } from "./data-source";

export default {
  components: {
    'ejs-treegrid': TreeGridComponent,
    'e-column': ColumnDirective,
    'e-columns': ColumnsDirective,
    'ejs-dropdownlist': DropDownListComponent
  },  
  data: () => {
    return {
      data: sampleData,
      pageSettings: { pageCount: 4, pageSize: 10 },
      ddlfields: { text: 'type', value: 'Id' },
      typefields: { text: 'type', value: 'Id' },
      filterSettings: { type: 'Menu', hierarchyMode: 'Parent' },
       ddldata: [
        { Id: 'Parent', type: 'Parent' },
        { Id: 'Child', type: 'Child' },
        { Id: 'Both', type: 'Both' },
        { Id: 'None', type: 'None' }],
       typedata: [
        { Id: 'Menu', type: 'Menu' },
        { Id: 'Excel', type: 'Excel' },]
    };
  },
  provide: {
      treegrid: [ Page, Filter ]
    },
   methods:{
       onChange: function(e: ChangeEventArgs): void {
        let value: string = <string>e.value;
        ((this as any).$refs.treegrid).ej2Instances.filterSettings.hierarchyMode = value;
        ((this as any).$refs.treegrid).clearFiltering();    
    },
    	onTypechange: function(e: ChangeEventArgs): void {
        let value: string = <string>e.value;
        ((this as any).$refs.treegrid).ej2Instances.filterSettings.type = value;
        ((this as any).$refs.treegrid).clearFiltering();    
    }
  }
}
</script>
