// syncfusionejs2_trial/Samples/React/src/chart/stacked-step-area.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.StackedStepArea = exports.data1 = exports.data = void 0;
/**
 * Sample for Stacked Step Area series
 */
var React = require("react");
var ej2_react_charts_1 = require("@syncfusion/ej2-react-charts");
var sample_base_1 = require("../common/sample-base");
var ej2_base_1 = require("@syncfusion/ej2-base");
exports.data = [{ x: 2000, y: 416 }, { x: 2001, y: 490 }, { x: 2002, y: 470 }, { x: 2003, y: 500 },
    { x: 2004, y: 449 }, { x: 2005, y: 470 }, { x: 2006, y: 437 }, { x: 2007, y: 458 },
    { x: 2008, y: 500 }, { x: 2009, y: 473 }, { x: 2010, y: 520 }, { x: 2011, y: 520 }];
exports.data1 = [{ x: 2000, y: 180 }, { x: 2001, y: 240 }, { x: 2002, y: 370 }, { x: 2003, y: 200 },
    { x: 2004, y: 229 }, { x: 2005, y: 210 }, { x: 2006, y: 337 }, { x: 2007, y: 258 },
    { x: 2008, y: 300 }, { x: 2009, y: 173 }, { x: 2010, y: 220 }, { x: 2011, y: 220 }];
var SAMPLE_CSS = "\n    .control-fluid {\n\t\tpadding: 0px !important;\n    }";
var StackedStepArea = /** @class */ (function (_super) {
    __extends(StackedStepArea, _super);
    function StackedStepArea() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        _this.opacity = 0.5;
        return _this;
    }
    StackedStepArea.prototype.render = function () {
        return (React.createElement("div", { className: 'control-pane' },
            React.createElement("style", null, SAMPLE_CSS),
            React.createElement("div", { className: 'control-section' },
                React.createElement(ej2_react_charts_1.ChartComponent, { id: 'charts', style: { textAlign: "center" }, primaryXAxis: {
                        valueType: 'Double',
                        majorGridLines: { width: 0 },
                        edgeLabelPlacement: 'Shift'
                    }, load: this.load.bind(this), primaryYAxis: {
                        title: 'Production (Billion as kWh)',
                        valueType: 'Double',
                        labelFormat: '{value}B',
                        lineStyle: { width: 0 },
                        majorTickLines: { width: 0 },
                        minorTickLines: { width: 0 },
                    }, width: ej2_base_1.Browser.isDevice ? '100%' : '75%', legendSettings: { enableHighlight: true }, chartArea: { border: { width: 0 } }, loaded: this.onChartLoad.bind(this), title: 'Electricity- Production' },
                    React.createElement(ej2_react_charts_1.Inject, { services: [ej2_react_charts_1.StackingStepAreaSeries, ej2_react_charts_1.Legend, ej2_react_charts_1.Highlight] }),
                    React.createElement(ej2_react_charts_1.SeriesCollectionDirective, null,
                        React.createElement(ej2_react_charts_1.SeriesDirective, { dataSource: exports.data, xName: 'x', yName: 'y', name: 'Renewable', type: 'StackingStepArea', fill: "#56CCF2", opacity: 0.5, border: { width: 2.5 } }),
                        React.createElement(ej2_react_charts_1.SeriesDirective, { dataSource: exports.data1, xName: 'x', yName: 'y', name: 'Non-Renewable', type: 'StackingStepArea', opacity: 0.5, fill: "#2F80ED", border: { width: 2.5 } })))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null, "This sample visualizes the data about electricity production using stacked stepped area chart.")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null,
                    "In this example, you can see how to render and configure the Stacked StepArea chart. ",
                    React.createElement("code", null, "marker"),
                    " and ",
                    React.createElement("code", null, "dataLabel"),
                    " are used to represent individual data and its value."),
                React.createElement("p", null,
                    React.createElement("b", null, "Injecting Module")),
                React.createElement("p", null,
                    "Chart component features are segregated into individual feature-wise modules. To use stacking step area series, we need to inject",
                    React.createElement("code", null, "StackingStepArea"),
                    " module into ",
                    React.createElement("code", null, "services"),
                    "."),
                React.createElement("p", null,
                    "More information on the stacked step area series can be found in this \u00A0",
                    React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/chart/chart-types/stacked-step-area", "aria-label": "Navigate to the documentation for Stacked Step Area Chart in React Chart component" }, "documentation section"),
                    "."))));
    };
    StackedStepArea.prototype.onChartLoad = function (args) {
        var chart = document.getElementById('charts');
        chart.setAttribute('title', '');
    };
    ;
    StackedStepArea.prototype.load = function (args) {
        var selectedTheme = location.hash.split('/')[1];
        selectedTheme = selectedTheme ? selectedTheme : 'Fluent2';
        args.chart.theme = (selectedTheme.charAt(0).toUpperCase() + selectedTheme.slice(1)).replace(/-dark/i, "Dark").replace(/contrast/i, 'Contrast').replace(/-highContrast/i, 'HighContrast');
    };
    ;
    return StackedStepArea;
}(sample_base_1.SampleBase));
exports.StackedStepArea = StackedStepArea;

// syncfusionejs2_trial/Samples/Vue/public/source/chart/stacked-step-area.vue
<template>
  <div class="control-section">
    <div align="center">
      <ejs-chart
        style="display:block"
        align="center"
        :theme="theme"
        id="chartcontainer"
        :title="title"
        :primaryXAxis="primaryXAxis"
        :primaryYAxis="primaryYAxis"
        :chartArea="chartArea"
        :width="width"
        :legendSettings='legend'
      >
        <e-series-collection>
          <e-series
            :dataSource="seriesData"
            type="StackingStepArea"
            xName="x"
            yName="y"
            name="Renewable"
            :opacity="opacity"
            fill="#56CCF2"
            :border='border'
          ></e-series>
          <e-series
            :dataSource="seriesData1"
            type="StackingStepArea"
            xName="x"
            yName="y"
            name="Non-Renewable"
            :opacity="opacity"
            fill="#2F80ED"
            :border='border'
          ></e-series>
        </e-series-collection>
      </ejs-chart>
    </div>
    <div id="action-description">
      <p>This sample visualizes the data about electricity production using stacked stepped area chart.</p>
    </div>
    <div id="description">
      <p>
        In this example, you can see how to render and configure the stacked step area chart. This series forms the
        step area progress, by connecting points through vertical and horizontal lines with area filled. You can use <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/api/chart/border/" aria-label="Navigate to the border property reference for Vue Chart component">border</a> and <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/api/chart/seriesModel/#fill" aria-label="Navigate to the fill property reference for Vue Chart Series">fill</a> properties to customize the stacked step area. Both <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/api/chart/marker/" aria-label="Navigate to the documentation for Data Markers in Vue Chart component">marker</a> and <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/api/chart/dataLabel/" aria-label="Navigate to the documentation for dataLabel in Vue Chart component">dataLabel</a> are used to represent individual data and its value.
      </p>
      
      <p style="font-weight: 500"><b>Injecting Module</b></p>
      <p>
        Chart component features are segregated into individual feature-wise modules. To use stacked step area series, we need to inject
        <code>StackingStepAreaSeries</code> module using
        <code>provide: { chart: [StackingStepAreaSeries] }</code> method.
      </p>
      <p>
        More information about the stacked step area series can be found in this
        <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/chart/chart-type/stacked-step-area" aria-label="Navigate to the documentation for Stacked Step Area Chart in Vue Chart component">documentation section</a>.
      </p>
    </div>
  </div>
</template>
<style scoped>
</style>
<script>
import { Browser } from "@syncfusion/ej2-base";
import {
  ChartComponent,
  SeriesDirective,
  SeriesCollectionDirective,
  StackingStepAreaSeries,
  Legend,
  Highlight
} from "@syncfusion/ej2-vue-charts";

import { loadChartTheme } from "./theme-color";
let theme = loadChartTheme();

export default {
  components: {
    'ejs-chart': ChartComponent,
    'e-series-collection': SeriesCollectionDirective,
    'e-series': SeriesDirective
  },
  data: function() {
    return {
      theme: theme,
      seriesData: [
        { x: 2000, y: 416 },
        { x: 2001, y: 490 },
        { x: 2002, y: 470 },
        { x: 2003, y: 500 },
        { x: 2004, y: 449 },
        { x: 2005, y: 470 },
        { x: 2006, y: 437 },
        { x: 2007, y: 458 },
        { x: 2008, y: 500 },
        { x: 2009, y: 473 },
        { x: 2010, y: 520 },
        { x: 2011, y: 509 }
      ],

      seriesData1: [
        { x: 2000, y: 180 },
        { x: 2001, y: 240 },
        { x: 2002, y: 370 },
        { x: 2003, y: 200 },
        { x: 2004, y: 229 },
        { x: 2005, y: 210 },
        { x: 2006, y: 337 },
        { x: 2007, y: 258 },
        { x: 2008, y: 300 },
        { x: 2009, y: 173 },
        { x: 2010, y: 220 },
        { x: 2011, y: 220 }
      ],
      //Initializing Primary X Axis
      primaryXAxis: {
        valueType: "Double",
        majorGridLines: { width: 0 },
        edgeLabelPlacement: "Shift"
      },

      //Initializing Primary Y Axis
      primaryYAxis: {
        title: "Production (Billion as kWh)",
        valueType: "Double",
        labelFormat: "{value}B",
        lineStyle: { width: 0 },
        majorTickLines: { width: 0 }
      },
      chartArea: {
        border: {
          width: 0
        }
      },
      width: Browser.isDevice ? '100%' : '75%',
      legend: {enableHighlight : true},
      title: "Electricity- Production",
      opacity: 0.5,
      border: { width: 2.5 }
    };
  },
  provide: {
    chart: [StackingStepAreaSeries, Legend, Highlight]
  },
  methods: {}
};
</script>
