// syncfusionejs2_trial/Samples/Vue/public/source/schedule/cell-template.vue
<template>
    <div class="schedule-vue-sample">
        <div class="col-md-12 control-section">
            <div class="content-wrapper">
                <ejs-schedule id='Schedule' height="650px" :selectedDate='selectedDate' :cssClass='cssClass' :currentView='currentView' :cellTemplate="'cellTemplate'" :eventSettings='eventSettings'>
                    <template v-slot:cellTemplate="{ data }">
                        <div v-if="data.type === 'monthCells' && getCellContent(data.date) !== '' ">
                            <div class="templatewrap">
                                <p v-html=getCellContent(data.date)></p>
                            </div>
                        </div>
                    </template>
                    <e-views>
                        <e-view option="Month"></e-view>
                    </e-views>
                </ejs-schedule>
            </div>
        </div>

        <div id="action-description">
            <p>This demo illustrates how to customize the background of the specific date cells by adding images and custom
                text to it by using the cell template option.
            </p>
        </div>

        <div id="description">
            <p>
                In this demo, the
                <code>cellTemplate</code> option which accepts the template string is used to customize the cell background
                with specific images and appropriate text on the given date values.
            </p>
            <p>Looking for the full Vue Scheduler component overview, features, pricing, and documentation? Visit our <a href="https://www.syncfusion.com/vue-components/vue-scheduler">Vue Scheduler</a> page.</p>
        </div>

    </div>
</template>
<style>
    .schedule-vue-sample .schedule-celltemplate.e-schedule .e-month-view .e-work-cells {
        position: relative;
    }

    .schedule-vue-sample .schedule-celltemplate.e-schedule .templatewrap {
        text-align: center;
        position: absolute;
        width: 100%;
    }

    .schedule-vue-sample .schedule-celltemplate.e-schedule .templatewrap img {
        width: 30px;
        height: 30px;
    }

    .schedule-vue-sample .schedule-celltemplate.e-schedule .caption {
        overflow: hidden;
        text-overflow: ellipsis;
        vertical-align: middle;
    }
</style>
<script>
    import { ScheduleComponent, ViewDirective, ViewsDirective, Month, Resize, DragAndDrop } from '@syncfusion/ej2-vue-schedule';
    import { extend } from '@syncfusion/ej2-base';
    
    export default {
        components: {
          'ejs-schedule': ScheduleComponent,
          'e-view': ViewDirective,
          'e-views': ViewsDirective
        },
        data: function () {
            return {
                selectedDate: new Date(2021, 11, 15),
                currentView: 'Month',
                cssClass: 'schedule-celltemplate',
                eventSettings: { dataSource: extend([], null, true) },
            }
        },
        methods: {
            getCellContent: function (date) {
                if (date.getMonth() === 10 && date.getDate() === 23) {
                    return '<img src="source/schedule/images/thanksgiving-day.svg" alt="Thanksgiving day" /><div class="caption">Thanksgiving day</div>';
                } else if (date.getMonth() === 11 && date.getDate() === 9) {
                    return '<img src="source/schedule/images/get-together.svg" alt="Party time"/><div class="caption">Party time</div>';
                } else if (date.getMonth() === 11 && date.getDate() === 13) {
                    return '<img src="source/schedule/images/get-together.svg" alt="Party time"/><div class="caption">Party time</div>';
                } else if (date.getMonth() === 11 && date.getDate() === 22) {
                    return '<img src="source/schedule/images/birthday.svg" alt="Happy birthday"/><div class="caption">Happy birthday</div>';
                } else if (date.getMonth() === 11 && date.getDate() === 24) {
                    return '<img src="source/schedule/images/christmas-eve.svg" alt="Christmas Eve"/><div class="caption">Christmas Eve</div>';
                } else if (date.getMonth() === 11 && date.getDate() === 25) {
                    return '<img src="source/schedule/images/christmas.svg" alt="Christmas Day"/><div class="caption">Christmas Day</div>';
                } else if (date.getMonth() === 0 && date.getDate() === 1) {
                    return '<img src="source/schedule/images/newyear.svg" alt="New year"/><div class="caption">New Year\'s Day</div>';
                } else if (date.getMonth() === 0 && date.getDate() === 14) {
                    return '<img src="source/schedule/images/get-together.svg" alt="Get together"/><div class="caption">Get together</div>';
                }
                return '';
            }
        },
        provide: {
            schedule: [Month, Resize, DragAndDrop]
        }
    }

</script>

// syncfusionejs2_trial/Samples/React/src/schedule/cell-template.tsx
import * as ReactDOM from 'react-dom';
import * as React from 'react';
import { ScheduleComponent, ViewsDirective, ViewDirective, Month, Inject, Resize, DragAndDrop } from '@syncfusion/ej2-react-schedule';
import './cell-template.css';
import { SampleBase } from '../common/sample-base';
import { extend } from '@syncfusion/ej2-base';

/**
 * Schedule cell template sample
 */

export class CellTemplate extends SampleBase<{}, {}> {
  private data: Record<string, any>[] = extend([], null, true) as Record<string, any>[];
  private getCellContent(date: Date) {
    if (date.getMonth() === 10 && date.getDate() === 23) {
      return '<img src= "src/schedule/images/thanksgiving-day.svg" alt="Thanksgiving day"/><div className="caption">Thanksgiving day</div>';
    } else if (date.getMonth() === 11 && date.getDate() === 9) {
      return '<img src="src/schedule/images/get-together.svg" alt="Party time"/><div className="caption">Party time</div>';
    } else if (date.getMonth() === 11 && date.getDate() === 13) {
      return '<img src="src/schedule/images/get-together.svg" alt="Party time"/><div className="caption">Party time</div>';
    } else if (date.getMonth() === 11 && date.getDate() === 22) {
      return '<img src="src/schedule/images/birthday.svg" alt="Happy birthday"/><div className="caption">Happy birthday</div>';
    } else if (date.getMonth() === 11 && date.getDate() === 24) {
      return '<img src="src/schedule/images/christmas-eve.svg" alt="Christmas Eve"/><div className="caption">Christmas Eve</div>';
    } else if (date.getMonth() === 11 && date.getDate() === 25) {
      return '<img src="src/schedule/images/christmas.svg" alt="Christmas Day"/><div className="caption">Christmas Day</div>';
    } else if (date.getMonth() === 0 && date.getDate() === 1) {
      return '<img src="src/schedule/images/newyear.svg" alt="New year"/><div className="caption">New Year\'s Day</div>';
    } else if (date.getMonth() === 0 && date.getDate() === 14) {
      return '<img src="src/schedule/images/get-together.svg" alt="Get together"/><div className="caption">Get together</div>';
    } else {
      return '';
    }
  }
  private cellTemplate(props): JSX.Element {
    if (props.type === "monthCells") {
      return (<div className="templatewrap" dangerouslySetInnerHTML={{ __html: this.getCellContent(props.date) }}></div>);
    }
    return;
  }
  render() {
    return (
      <div className='schedule-control-section'>
        <div className='col-lg-12 control-section'>
          <div className='control-wrapper'>
            <ScheduleComponent cssClass='cell-template' width='100%' height='650px' selectedDate={new Date(2021, 11, 15)}
              cellTemplate={this.cellTemplate.bind(this)} eventSettings={{ dataSource: this.data }}>
              <ViewsDirective>
                <ViewDirective option='Month' />
              </ViewsDirective>
              <Inject services={[Month, Resize, DragAndDrop]} />
            </ScheduleComponent>
          </div>
        </div>
        <div id='action-description'>
          <p>This demo illustrates how to customize the background of the specific date cells by adding images and custom text to it by
            using the cell template option.</p>
        </div>
        <div id='description'>
          <p>
            In this demo, the <code>cellTemplate</code> option which accepts the template string is used to customize the cell
            background with specific images and appropriate text on the given date values.
          </p>
          <p>
            Looking for the full React Scheduler component overview, features, pricing, and documentation? Visit our <a target="_blank" href="https://www.syncfusion.com/react-components/react-scheduler">React Scheduler</a> component page.
          </p>
        </div>
      </div>
    );
  }
}
