// syncfusionejs2_trial/Samples/Vue/source/schedule/timeline-resourcegrouping.vue
<template>
    <div class="schedule-vue-sample">
        <div class="col-md-12 control-section">
            <div class="content-wrapper">
                <ejs-schedule id='Schedule' height="650px" :selectedDate='selectedDate' :currentView='currentView' :workDays='workDays' :eventSettings='eventSettings'
                    :group='group'>
                    <e-views>
                        <e-view option="TimelineDay"></e-view>
                        <e-view option="TimelineWeek"></e-view>
                        <e-view option="TimelineWorkWeek"></e-view>
                        <e-view option="TimelineMonth"></e-view>
                        <e-view option="Agenda"></e-view>
                    </e-views>
                    <e-resources>
                        <e-resource field='ProjectId' title='Choose Project' name='Projects' :dataSource='projectResourceDataSource' textField='text'
                            idField='id' colorField='color'>
                        </e-resource>
                        <e-resource field='TaskId' title='Employee' name='Employees' :dataSource='employeeDataSource' :allowMultiple='allowMultiple'
                            textField='text' idField='id' groupIDField='groupId' colorField='color'>
                        </e-resource>
                    </e-resources>    
                </ejs-schedule>
            </div>
        </div>
        <div id="action-description">
            <p>
                This demo showcases how the multiple resources are grouped as well as how the events are portrayed in timeline view layouts.
            </p>
        </div>
        <div id="description">
            <p>
                In the timeline view, each row depicts a single resource whereas in vertical views, each resource are grouped parallelly
                as columns. Here, the resource grouping follows the tree-view like hierarchical grouping structure and can contain
                any level of child resources. In this sample, we have used two level hierarchy, where the
                <code>PROJECT 1</code> and
                <code>PROJECT 2</code> are the parent level and the
                <code>development</code> and
                <code>testing</code> are child level resources which are defined using the
                <code>resources</code> property. They are grouped in layout by making use of the
                <code>group</code> property and its order of grouping depends on the order of names passed onto the
                <code>resources</code> option within
                <code>group</code>.
            </p>
            <p>
                Also, the colors defined for the child level resources will get applied to the events of those resources by default. In case,
                if the colors of parent level needs to be applied to those child events, then it is necessary to define the
                <code>resourceColorField</code> option within the
                <code>eventSettings</code> property with the parent level resource name value.
            </p>
            <p>Looking for the full Vue Scheduler component overview, features, pricing, and documentation? Visit our <a href="https://www.syncfusion.com/vue-components/vue-scheduler">Vue Scheduler</a> page.</p>
        </div>
    </div>
</template>
<style>
    .schedule-vue-sample .e-schedule:not(.e-device) .e-agenda-view .e-content-wrap table td:first-child {
        width: 90px;
    }

    .schedule-vue-sample .e-schedule .e-agenda-view .e-resource-column {
        width: 100px;
    }
</style>

<script>
    import { resourceData, timelineResourceData } from './datasource';
    import { ScheduleComponent, ViewDirective, ViewsDirective, ResourceDirective, ResourcesDirective, Agenda, TimelineViews, TimelineMonth, Resize, DragAndDrop } from "@syncfusion/ej2-vue-schedule";
    
    export default {
        components: {
          'ejs-schedule': ScheduleComponent,
          'e-view': ViewDirective,
          'e-views': ViewsDirective,
          'e-resource': ResourceDirective,
          'e-resources': ResourcesDirective
        },
        data: function () {
            return {
                eventSettings: {
                    dataSource: this.generateData()
                },
                selectedDate: new Date(2023, 0, 4),
                currentView: 'TimelineWeek',
                workDays: [0, 1, 2, 3, 4, 5],
                allowMultiple : true,
                group: {
                    resources: ['Projects', 'Employees']
                },
                projectResourceDataSource: [
                    { text: 'PROJECT 1', id: 1, color: '#cb6bb2' },
                    { text: 'PROJECT 2', id: 2, color: '#56ca85' },
                    { text: 'PROJECT 3', id: 3, color: '#df5286' }
                ],
                employeeDataSource: [
                    { text: 'Nancy', id: 1, groupId: 1, color: '#df5286' },
                    { text: 'Steven', id: 2, groupId: 1, color: '#7fa900' },
                    { text: 'Robert', id: 3, groupId: 2, color: '#ea7a57' },
                    { text: 'Smith', id: 4, groupId: 2, color: '#5978ee' },
                    { text: 'Michael', id: 5, groupId: 3, color: '#df5286' },
                    { text: 'Root', id: 6, groupId: 3, color: '#00bdae' }
                ],
            }
        },
        provide: {
            schedule: [Agenda, TimelineViews, TimelineMonth, Resize, DragAndDrop]
        },
        methods: {
            generateData: function () {
                var collections = [];
                var dataCollections = [resourceData, timelineResourceData];
                for (var i = 0; i < dataCollections.length; i++) {
                    collections = collections.concat(dataCollections[i]);
                }
                return collections;
            }
        }
    }
</script>

// syncfusionejs2_trial/Samples/React/src/schedule/timeline-resource-grouping.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.TimelineGrouping = void 0;
var React = require("react");
var ej2_react_schedule_1 = require("@syncfusion/ej2-react-schedule");
require("./timeline-resource-grouping.css");
var ej2_base_1 = require("@syncfusion/ej2-base");
var sample_base_1 = require("../common/sample-base");
var dataSource = require("./datasource.json");
/**
 * schedule timeline resource grouping sample
 */
var TimelineGrouping = /** @class */ (function (_super) {
    __extends(TimelineGrouping, _super);
    function TimelineGrouping() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        _this.data = (0, ej2_base_1.extend)([], dataSource.resourceData.concat(dataSource.timelineResourceData), null, true);
        _this.workDays = [0, 1, 2, 3, 4, 5];
        _this.projectData = [
            { text: 'PROJECT 1', id: 1, color: '#cb6bb2' },
            { text: 'PROJECT 2', id: 2, color: '#56ca85' },
            { text: 'PROJECT 3', id: 3, color: '#df5286' }
        ];
        _this.categoryData = [
            { text: 'Nancy', id: 1, groupId: 1, color: '#df5286' },
            { text: 'Steven', id: 2, groupId: 1, color: '#7fa900' },
            { text: 'Robert', id: 3, groupId: 2, color: '#ea7a57' },
            { text: 'Smith', id: 4, groupId: 2, color: '#5978ee' },
            { text: 'Michael', id: 5, groupId: 3, color: '#df5286' },
            { text: 'Root', id: 6, groupId: 3, color: '#00bdae' }
        ];
        return _this;
    }
    TimelineGrouping.prototype.render = function () {
        return (React.createElement("div", { className: 'schedule-control-section' },
            React.createElement("div", { className: 'col-lg-12 control-section' },
                React.createElement("div", { className: 'control-wrapper' },
                    React.createElement(ej2_react_schedule_1.ScheduleComponent, { cssClass: 'timeline-resource-grouping', width: '100%', height: '650px', selectedDate: new Date(2023, 0, 4), currentView: 'TimelineWeek', workDays: this.workDays, eventSettings: { dataSource: this.data }, group: { resources: ['Projects', 'Categories'] } },
                        React.createElement(ej2_react_schedule_1.ResourcesDirective, null,
                            React.createElement(ej2_react_schedule_1.ResourceDirective, { field: 'ProjectId', title: 'Choose Project', name: 'Projects', allowMultiple: false, dataSource: this.projectData, textField: 'text', idField: 'id', colorField: 'color' }),
                            React.createElement(ej2_react_schedule_1.ResourceDirective, { field: 'TaskId', title: 'Category', name: 'Categories', allowMultiple: true, dataSource: this.categoryData, textField: 'text', idField: 'id', groupIDField: 'groupId', colorField: 'color' })),
                        React.createElement(ej2_react_schedule_1.ViewsDirective, null,
                            React.createElement(ej2_react_schedule_1.ViewDirective, { option: 'TimelineDay' }),
                            React.createElement(ej2_react_schedule_1.ViewDirective, { option: 'TimelineWeek' }),
                            React.createElement(ej2_react_schedule_1.ViewDirective, { option: 'TimelineWorkWeek' }),
                            React.createElement(ej2_react_schedule_1.ViewDirective, { option: 'TimelineMonth' }),
                            React.createElement(ej2_react_schedule_1.ViewDirective, { option: 'Agenda' })),
                        React.createElement(ej2_react_schedule_1.Inject, { services: [ej2_react_schedule_1.TimelineViews, ej2_react_schedule_1.TimelineMonth, ej2_react_schedule_1.Agenda, ej2_react_schedule_1.Resize, ej2_react_schedule_1.DragAndDrop] })))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null, "This demo showcases how the multiple resources are grouped as well as how the events are portrayed in timeline view layouts.")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null,
                    "In the timeline view, each row depicts a single resource whereas in vertical views, each resource are grouped parallelly as columns. Here, the resource grouping follows the tree-view like hierarchical grouping structure and can contain any level of child resources. In this sample, we have used two level hierarchy, where the",
                    React.createElement("code", null, "PROJECT 1"),
                    " and",
                    React.createElement("code", null, "PROJECT 2"),
                    " are the parent level and the",
                    React.createElement("code", null, "development"),
                    " and",
                    React.createElement("code", null, "testing"),
                    " are child level resources which are defined using the",
                    React.createElement("code", null, "resources"),
                    " property. They are grouped in layout by making use of the",
                    React.createElement("code", null, "group"),
                    " property and its order of grouping depends on the order of names passed onto the",
                    React.createElement("code", null, "resources"),
                    " option within",
                    React.createElement("code", null, "group"),
                    "."),
                React.createElement("p", null,
                    "Also, the colors defined for the child level resources will get applied to the events of those resources by default. In case, if the colors of parent level needs to be applied to those child events, then it is necessary to define the",
                    React.createElement("code", null, "resourceColorField"),
                    " option within the",
                    React.createElement("code", null, "eventSettings"),
                    " property with the parent level resource name value."),
                React.createElement("p", null,
                    "Looking for the full React Scheduler component overview, features, pricing, and documentation? Visit our ",
                    React.createElement("a", { target: "_blank", href: "https://www.syncfusion.com/react-components/react-scheduler" }, "React Scheduler"),
                    " component page."))));
    };
    return TimelineGrouping;
}(sample_base_1.SampleBase));
exports.TimelineGrouping = TimelineGrouping;
