// syncfusionejs2_trial/Samples/React/src/grid/clipboard.jsx
import * as React from 'react';
import { DialogComponent } from '@syncfusion/ej2-react-popups';
import { GridComponent, ColumnsDirective, ColumnDirective, Page, Selection, Inject, Toolbar, Sort, Filter, Edit } from '@syncfusion/ej2-react-grids';
import { data } from './data';
import { SampleBase } from '../common/sample-base';
import './sample.css';
export class Clipboard extends SampleBase {
    selectionsettings = { type: 'Multiple' };
    filterSettings = { type: 'Excel' };
    editSettings = { allowEditing: true, allowAdding: true, allowDeleting: true };
    customeridRule = { required: true, minLength: 5 };
    orderidRules = { required: true, number: true };
    freightRules = { required: true, min: 0 };
    toolbarOptions = ['Add', 'Edit', 'Delete', 'Update', 'Cancel', { text: 'Copy', tooltipText: 'Copy', prefixIcon: 'e-copy', id: 'copy' }, { text: 'Copy With Header', tooltipText: 'Copy With Header', prefixIcon: 'e-copy', id: 'copyHeader' }];
    gridInstance;
    visible = false;
    animationSettings = { effect: 'None' };
    alertDialogInstance;
    alertButtons = [{
            // Click the footer buttons to hide the Dialog
            click: () => {
                this.alertDialogInstance.hide();
            },
            buttonModel: { content: 'OK', isPrimary: true }
        }];
    clickHandler(args) {
        if (this.gridInstance.getSelectedRecords().length > 0) {
            let withHeader = args.item.id === 'copyHeader' ? true : false;
            this.gridInstance.copy(withHeader);
        }
        else {
            this.alertDialogInstance.content = args.item.id === 'copyHeader' ? 'Atleast one row should be selected to copy with header' : 'Atleast one row should be selected to copy';
            this.alertDialogInstance.header = args.item.id === 'copyHeader' ? 'Copy with Header' : 'Copy';
            this.alertDialogInstance.show();
        }
    }
    render() {
        return (<div className='control-pane'>
                <div className='control-section'>
                    <GridComponent dataSource={data} ref={grid => this.gridInstance = grid} allowSorting={true} enableHover={false} allowPaging={true} pageSettings={{ pageCount: 5 }} selectionSettings={this.selectionsettings} editSettings={this.editSettings} allowFiltering={true} filterSettings={this.filterSettings} toolbar={this.toolbarOptions} toolbarClick={this.clickHandler.bind(this)}>
                        <ColumnsDirective>
                            <ColumnDirective field='OrderID' headerText='Order ID' width='140' textAlign='Right' validationRules={this.orderidRules} isPrimaryKey={true}></ColumnDirective>
                            <ColumnDirective field='CustomerName' headerText='Customer Name' width='150' validationRules={this.customeridRule}></ColumnDirective>
                            <ColumnDirective field='OrderDate' headerText='Order Date' format='yMd' width='170' editType='datepickeredit'></ColumnDirective>
                            <ColumnDirective field='Freight' headerText='Freight' width='120' format='C2' textAlign='Right' validationRules={this.freightRules} editType='numericedit'></ColumnDirective>
                            <ColumnDirective field='ShipCountry' headerText='Ship Country' width='130' editType='dropdownedit'></ColumnDirective>
                        </ColumnsDirective>
                        <Inject services={[Page, Selection, Toolbar, Sort, Edit, Filter]}/>
                    </GridComponent>
                </div>
                <DialogComponent id="alertDialog" header='Copy with Header' visible={this.visible} animationSettings={this.animationSettings} width='300px' content='Atleast one row should be selected to copy with header' ref={alertdialog => this.alertDialogInstance = alertdialog} target='.control-section' buttons={this.alertButtons}></DialogComponent>
                <div id="action-description">
                    <p>This sample demonstrates copy to clipboard functionality of the Grid component. Select rows and click Copy button from
        toolbar to copy content. To copy with header click Copy with header button from toolbar.
    </p>
                </div>
                <div id="description">
                    <p>Selected rows or cells data in the Grid can be copied into the clipboard using the Keyboard shortcuts and <code><a target="_blank" className="code" href="https://ej2.syncfusion.com/react/documentation/api/grid/#copy">copy
        </a></code> method.
            </p>
                    <p>In this demo, selected rows data can be copied into the clipboard using the below Keyboard shortcuts or toolbar interactions.</p>
                    <ul>
                        <li><code>Ctrl + C</code> - Selected rows or cells data without header.</li>
                        <li><code>Ctrl + Shift + H</code> - Selected rows or cells data with header.</li>
                    </ul>
                    <p>More information on the Clipboard feature can be found in this <a target="_blank" href="https://ej2.syncfusion.com/react/documentation/grid/clipboard.html">documentation section</a>.
            </p>
            <p>Looking for the full React Data Grid component overview, features, pricing, and documentation? Visit our 
            <a target="_blank" href="https://www.syncfusion.com/react-components/react-data-grid"> React Data Grid component</a> page.</p>
                </div>
            </div>);
    }
}

// syncfusionejs2_trial/Samples/Vue/public/source/grid/grid/clipboard.vue
<template>
    <div class="col-lg-12 control-section">
        <div id="action-description">
            <p>This sample demonstrates copy to clipboard functionality of the Grid component. Select rows and click
                Copy button from
                toolbar to copy content. To copy with header click Copy with header button from toolbar.
            </p>
        </div>
        <div>
            <div class="control-section">
                <ejs-grid ref='grid' id='Grid' :dataSource="data" :allowPaging='true' :enableHover="false"
                    :allowSelection="true" :selectionSettings="selectOptions" :toolbar='toolbar'
                    :toolbarClick='clickHandler' :allowSorting='true' :allowFiltering='true'
                    :filterSettings='filterSettings' :editSettings='editSettings'>
                    <e-columns>
                        <e-column field='OrderID' headerText='Order ID' width='120' textAlign='Right'
                            :isPrimaryKey='true' :validationRules='orderidrules'></e-column>
                        <e-column field='CustomerName' headerText='Customer Name' width='150'
                            :validationRules='customeridrules'></e-column>
                        <e-column field='OrderDate' headerText='Order Date' width='130' format="yMd" textAlign='Right'
                            editType='datepickeredit'></e-column>
                        <e-column field='Freight' headerText='Freight' width='120' format='C2' textAlign='Right'
                            editType='numericedit' :validationRules='freightrules'></e-column>
                        <e-column field='ShipCountry' headerText='Ship Country' width='130'
                            editType='dropdownedit'></e-column>
                    </e-columns>
                </ejs-grid>
            </div>
            <ejs-dialog :buttons='alertDlgButtons' ref="alertDialog" v-bind:visible="false" :header='alertHeader'
                :animationSettings='animationSettings' :content='alertContent' :showCloseIcon='showCloseIcon'
                :target='target' :width='alertWidth'>
            </ejs-dialog>
        </div>

        <div id="description">
            <p>Selected rows or cells data in the Grid can be copied into clipboard using the Keyboard shortcuts and
                <code><a target="_blank" class="code"
        href="https://ej2.syncfusion.com/vue/documentation/api/grid/#copy">copy
        </a></code> method.
            </p>
            <p>In this demo, selected rows data can be copied into clipboard using the below Keyboard shortcuts or
                toolbar interactions.</p>
            <ul>
                <li><code>Ctrl + C</code> - Selected rows or cells data without header.</li>
                <li><code>Ctrl + Shift + H</code> - Selected rows or cells data with header.</li>
            </ul>
            <p>More information on the Clipboard feature can be found in this
                <a target="_blank" href="http://ej2.syncfusion.com/vue/documentation/grid/clipboard.html">
                    documentation section</a>.
            </p>
            <p>
                Looking for the full Vue Data Grid component overview, features, pricing, and documentation? Visit our
                <a target="_blank" href="https://www.syncfusion.com/vue-components/vue-data-grid">
                    Vue Data Grid component</a> page.
            </p>
        </div>

    </div>
</template>
<script lang="ts">
import { GridComponent, ColumnDirective, ColumnsDirective, Toolbar, Edit, Filter, Page, Sort } from "@syncfusion/ej2-vue-grids";
import { ClickEventArgs } from "@syncfusion/ej2-vue-navigations";
import { orderDetails } from "./data-source";
import { DialogComponent } from '@syncfusion/ej2-vue-popups';

export default {
    components: {
        'ejs-grid': GridComponent,
        'e-column': ColumnDirective,
        'e-columns': ColumnsDirective,
        'ejs-dialog': DialogComponent
    },
    data: function () {
        return {
            alertHeader: 'Copy with Header',
            alertContent: 'Atleast one row should be selected to copy with header',
            showCloseIcon: false,
            target: '.control-section',
            alertWidth: '300px',
            animationSettings: { effect: 'None' },
            alertDlgButtons: [{ click: ((<any>this).alertDlgBtnClick as any), buttonModel: { content: 'OK', isPrimary: true } }],
            data: orderDetails,
            selectOptions: { type: 'Multiple' },
            filterSettings: { type: 'Excel' },
            editSettings: { allowEditing: true, allowAdding: true, allowDeleting: true },
            orderidrules: { required: true, number: true },
            customeridrules: { required: true, minLength: 5 },
            freightrules: { required: true, min: 0 },
            toolbar: ['Add', 'Edit', 'Delete', 'Update', 'Cancel', { text: 'Copy', tooltipText: 'Copy', prefixIcon: 'e-copy', id: 'copy' },
                { text: 'Copy With Header', tooltipText: 'Copy With Header', prefixIcon: 'e-copy', id: 'copyHeader' }]
        };
    },
    methods: {
        clickHandler: function (args: ClickEventArgs) {
            if (args.item.id === 'copy' || args.item.id === 'copyHeader') {
                if (((this as any).$refs.grid).getSelectedRecords().length > 0) {
                    let withHeader: boolean = args.item.id === 'copyHeader' ? true : false;
                    ((this as any).$refs.grid).copy(withHeader);
                } else {
                    (this as any).alertContent = args.item.id === 'copyHeader' ? 'Atleast one row should be selected to copy with header' : 'Atleast one row should be selected to copy';
                    (this as any).alertHeader = args.item.id === 'copyHeader' ? 'Copy with Header' : 'Copy';
                    ((this as any).$refs.alertDialog).show();
                }
            }
        },
        alertDlgBtnClick: function () {
            ((<any>this).$refs.alertDialog as any).ej2Instances.hide();
        },
    },
    provide: {
        grid: [Toolbar, Edit, Filter, Page, Sort]
    }
}
</script>
