// syncfusionejs2_trial/Samples/React/src/grid/master-details-export.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.HierarchyExport = void 0;
var React = require("react");
var ej2_react_grids_1 = require("@syncfusion/ej2-react-grids");
var data_1 = require("./data");
var sample_base_1 = require("../common/sample-base");
var HierarchyExport = /** @class */ (function (_super) {
    __extends(HierarchyExport, _super);
    function HierarchyExport() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        _this.secondChildGrid = {
            dataSource: data_1.customerData,
            queryString: 'CustomerID',
            columns: [
                { field: 'CustomerID', headerText: 'Customer ID', textAlign: 'Right', width: 75 },
                { field: 'ContactName', headerText: 'Contact Name', width: 100 },
                { field: 'Address', headerText: 'Address', width: 120 },
                { field: 'Country', headerText: 'Country', width: 100 }
            ]
        };
        _this.childGrid = {
            dataSource: data_1.hierarchyOrderdata,
            queryString: 'EmployeeID',
            allowPaging: true,
            pageSettings: { pageSize: 6, pageCount: 5 },
            columns: [
                { field: 'OrderID', headerText: 'Order ID', textAlign: 'Right', width: 120 },
                { field: 'ShipCity', headerText: 'Ship City', width: 120 },
                { field: 'Freight', headerText: 'Freight', width: 120 },
                { field: 'ShipName', headerText: 'Ship Name', width: 150 }
            ],
            childGrid: _this.secondChildGrid
        };
        return _this;
    }
    HierarchyExport.prototype.toolbarClick = function (args) {
        if (args.item.id === 'MasterDetailsExport_excelexport') {
            this.grid.excelExport({ hierarchyExportMode: 'All' });
        }
        if (args.item.id === 'MasterDetailsExport_pdfexport') {
            this.grid.pdfExport({ hierarchyExportMode: 'All' });
        }
    };
    HierarchyExport.prototype.render = function () {
        var _this = this;
        return (React.createElement("div", { className: 'control-pane' },
            React.createElement("div", { className: 'control-section' },
                React.createElement(ej2_react_grids_1.GridComponent, { id: 'MasterDetailsExport', ref: function (r) { return _this.grid = r; }, dataSource: data_1.employeeData, childGrid: this.childGrid, toolbar: ['PdfExport', 'ExcelExport'], allowPdfExport: true, allowExcelExport: true, toolbarClick: this.toolbarClick.bind(this) },
                    React.createElement(ej2_react_grids_1.ColumnsDirective, null,
                        React.createElement(ej2_react_grids_1.ColumnDirective, { field: 'EmployeeID', headerText: 'Employee ID', width: '125', textAlign: 'Right' }),
                        React.createElement(ej2_react_grids_1.ColumnDirective, { field: 'FirstName', headerText: 'Name', width: '125' }),
                        React.createElement(ej2_react_grids_1.ColumnDirective, { field: 'Title', headerText: 'Title', width: '180' }),
                        React.createElement(ej2_react_grids_1.ColumnDirective, { field: 'HireDate', headerText: 'Hire Date', width: '135', format: 'yMd', textAlign: 'Right' }),
                        React.createElement(ej2_react_grids_1.ColumnDirective, { field: 'ReportsTo', headerText: 'Reports To', width: '135', textAlign: 'Right' })),
                    React.createElement(ej2_react_grids_1.Inject, { services: [ej2_react_grids_1.DetailRow, ej2_react_grids_1.Toolbar, ej2_react_grids_1.PdfExport, ej2_react_grids_1.ExcelExport, ej2_react_grids_1.Page] }))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null, "This sample demonstrates the hierarchy Grid export feature. In this sample, you can export the hierarchy grid by clicking the corresponding export button from the grid's toolbar.")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null, "Grid supports client-side Hierarchy Grid exporting which allows you to export its data to the Excel and Pdf formats."),
                React.createElement("p", null,
                    "In this demo, ExcelExport and PdfExport items are defined in the toolbar. For these toolbar items, we have defined actions in toolbarClick event to export hierarchy Grid using the",
                    React.createElement("code", null,
                        React.createElement("a", { target: "_blank", className: "code", href: "https://ej2.syncfusion.com/react/documentation/api/grid#excelexport" }, "excelExport")),
                    ",",
                    React.createElement("code", null,
                        React.createElement("a", { target: "_blank", className: "code", href: "https://ej2.syncfusion.com/react/documentation/api/grid#pdfexport" }, "pdfExport")),
                    "methods and the grid will export using ",
                    React.createElement("code", null, "All"),
                    " mode."),
                "The hierarchy grid allows us to export the grid with following options,",
                React.createElement("ul", null,
                    React.createElement("li", null,
                        React.createElement("code", null, "Expanded"),
                        " - Exports only the visible child grids in expanded state."),
                    React.createElement("li", null,
                        React.createElement("code", null, "All"),
                        " - Exports the all the child grids in expanded state."),
                    React.createElement("li", null,
                        React.createElement("code", null, "None"),
                        " - Exports the child grids in collapse state.")),
                React.createElement("p", null,
                    "We can change the hierarchy grid's export option by using the ",
                    React.createElement("code", null, "hierarchyExportMode"),
                    " property."),
                React.createElement("p", { style: { fontWeight: 500 } }, "Injecting Module:"),
                React.createElement("p", null,
                    "Grid features are segregated into individual feature-wise modules. To use Hierarchy, PdfExport and ExcelExport Grid feature, we need to inject ",
                    React.createElement("code", null, "DetailRow"),
                    ", ",
                    React.createElement("code", null, "PdfExport"),
                    ", ",
                    React.createElement("code", null, "ExcelExport"),
                    " module into the ",
                    React.createElement("code", null, "services"),
                    "."),
                React.createElement("p", null,
                    "More information on the exporting configuration can be found in this",
                    React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/grid/pdf-export" }, "pdf-export"),
                    " and  ",
                    React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/grid/excel-export/excel-exporting" }, "excel-export"),
                    " documentation sections."),
                React.createElement("p", null,
                    "Looking for the full React Data Grid component overview, features, pricing, and documentation? Visit our",
                    React.createElement("a", { target: "_blank", href: "https://www.syncfusion.com/react-components/react-data-grid" }, " React Data Grid component"),
                    " page."))));
    };
    return HierarchyExport;
}(sample_base_1.SampleBase));
exports.HierarchyExport = HierarchyExport;

// syncfusionejs2_trial/Samples/Vue/public/source/grid/grid/master-details-export.vue
<template>
<div class="col-lg-12 control-section">
    <div id="action-description">
        <p>This sample demonstrates the hierarchy Grid export feature. In this sample, you can export the hierarchy grid by clicking the corresponding export button from the grid's toolbar.</p>
    </div>
    <div>
        <ejs-grid id='MasterDetailsExport' ref='grid' :dataSource="parentData" :childGrid="childGrid" :toolbar="['PdfExport', 'ExcelExport']" 
        :allowPdfExport='true' :allowExcelExport='true' :toolbarClick="toolbarClick">
            <e-columns>
                <e-column field='EmployeeID' headerText='Employee ID' width='120' textAlign='Right'></e-column>
                <e-column field='FirstName' headerText='Name' width='140'></e-column>
                <e-column field='Title' headerText='Title' width='170'></e-column>
                <e-column field='HireDate' headerText='Hired Date' width='120' format='yMd' textAlign='Right'></e-column>
                <e-column field='ReportsTo' headerText='Reports To' width='120' textAlign='Right'></e-column>
            </e-columns>
        </ejs-grid>
    </div>

    <div id="description">
            <p>Grid supports client-side Hierarchy Grid exporting which allows you to export its data to the Excel and Pdf formats.</p>
            <p>In this demo, ExcelExport and PdfExport items are defined in the toolbar. For these toolbar items, we have defined actions
                in toolbarClick event to export hierarchy Grid using the 
                <code><a target="_blank" class="code"
                href="https://ej2.syncfusion.com/vue/documentation/api/grid/#excelexport">excelExport</a></code>, 
                <code><a target="_blank" class="code"
                    href="https://ej2.syncfusion.com/vue/documentation/api/grid/#pdfexport">pdfExport</a></code>
            methods and the grid will export using <code>All</code> mode.</p>
        The hierarchy grid allows us to export the grid with following options,
        <ul>
            <li><code>Expanded</code> - Exports only the visible child grids in expanded state.</li>
            <li><code>All</code> - Exports the all the child grids in expanded state.</li>
            <li><code>None</code> - Exports the child grids in collapse state.</li>
        </ul>
        <p>
            We can change the hierarchy grid's export option by using the <code>hierarchyExportMode</code> property.
        </p>
        <p style="font-weight: 500">Injecting Module:</p>
        <p>
            Grid features are segregated into individual feature-wise modules.         
            To use Hierarchy, PdfExport and ExcelExport Grid feature, we need to inject <code>DetailRow</code>, <code>PdfExport</code>, <code>ExcelExportService</code>, and <code>Toolbar</code>into the <code>provide</code> section.
        </p>
        <p>
            More information on the exporting configuration can be found in this
            <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/grid/pdf-export">
            pdf-export</a> and  <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/grid/excel-export">
            excel-export</a> documentation sections.
        </p>
        <p>
            Looking for the full Vue Data Grid component overview, features, pricing, and documentation? Visit our
            <a target="_blank" href="https://www.syncfusion.com/vue-components/vue-data-grid">
                Vue Data Grid component</a> page.
        </p>

    </div>
</div>
</template>

<script lang="ts">
import { GridComponent, ColumnDirective, ColumnsDirective, DetailRow, Grid, PdfExport, ExcelExport, Toolbar } from "@syncfusion/ej2-vue-grids";
import { employeeData, orderDatas, customerData, hierarchyOrderdata } from "./data-source";
import { ClickEventArgs } from "@syncfusion/ej2-navigations";

export default {
  components: {
    'ejs-grid': GridComponent,
    'e-column': ColumnDirective,
    'e-columns': ColumnsDirective
  },
  data: () => {
    let secondLevelGrid = {
        dataSource: customerData,
        queryString: 'CustomerID',
        columns: [
            { field: 'CustomerID', headerText: 'Customer ID', width: 75 },
            { field: 'ContactName', headerText: 'Name', width: 100 },
            { field: 'Address', headerText: 'Address', width: 120 },
            { field: 'Country', headerText: 'Country', width: 100 }
        ]
    };

    return {
      parentData: employeeData,
      childGrid: {
            dataSource: hierarchyOrderdata,
            queryString: 'EmployeeID',
            columns: [
                { field: 'OrderID', headerText: 'Order ID', textAlign: 'Right', width: 120 },
                { field: 'ShipCity', headerText: 'Ship City', width: 120 },
                { field: 'Freight', headerText: 'Freight', width: 120, format: 'C2', textAlign: 'Right' },
                { field: 'ShipName', headerText: 'Ship Name', width: 150 }
            ],
            childGrid: secondLevelGrid
      }
    };
  },
  methods:{
      toolbarClick: function(args: ClickEventArgs) {
        if (args.item.id === 'MasterDetailsExport_excelexport') {
            ((this as any).$refs.grid).excelExport({hierarchyExportMode: 'All'});
        }
        if (args.item.id === 'MasterDetailsExport_pdfexport') {
            ((this as any).$refs.grid).pdfExport({hierarchyExportMode: 'All'});
        }
      }
  },
  provide: {
    grid: [DetailRow, Toolbar, PdfExport, ExcelExport]
  }
}
</script>
