// syncfusionejs2_trial/Samples/React/src/gantt/unscheduled-task.js
"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.UnscheduledTask = void 0;
var React = require("react");
var ej2_react_gantt_1 = require("@syncfusion/ej2-react-gantt");
var data_1 = require("./data");
var sample_base_1 = require("../common/sample-base");
require("./unscheduled.css");
var UnscheduledTask = /** @class */ (function (_super) {
    __extends(UnscheduledTask, _super);
    function UnscheduledTask() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        _this.taskFields = {
            id: 'TaskId',
            name: 'TaskName',
            startDate: 'StartDate',
            endDate: 'EndDate',
            duration: 'Duration',
        };
        _this.editSettings = {
            allowAdding: true,
            allowEditing: true,
        };
        _this.toolbar = [{ text: 'Insert task', tooltipText: 'Insert task at top', id: 'toolbarAdd', prefixIcon: 'e-add-icon tb-icons' }];
        _this.labelSettings = {
            leftLabel: 'TaskName',
            rightLabel: 'TaskType'
        };
        _this.splitterSettings = {
            columnIndex: 4
        };
        _this.columns = [
            { field: 'TaskId', width: 90 },
            { field: 'TaskName', width: 150 },
            { field: 'StartDate', width: 120 },
            { field: 'EndDate', width: 120 },
            { field: 'Duration', width: 90 }
        ];
        _this.projectStartDate = new Date('12/29/2024');
        _this.projectEndDate = new Date('02/14/2025');
        return _this;
    }
    UnscheduledTask.prototype.toolbarClickEvent = function () {
        var data = {
            Duration: null,
            StartDate: null,
            EndDate: null,
            TaskType: ''
        };
        this.ganttInstance.addRecord(data);
    };
    UnscheduledTask.prototype.render = function () {
        var _this = this;
        return (React.createElement("div", { className: 'control-pane' },
            React.createElement("div", { className: 'control-section' },
                React.createElement(ej2_react_gantt_1.GanttComponent, { id: 'Unscheduled', ref: function (gantt) { return _this.ganttInstance = gantt; }, dataSource: data_1.unscheduledData, taskFields: this.taskFields, height: '650px', taskbarHeight: 25, rowHeight: 46, editSettings: this.editSettings, allowSelection: true, toolbar: this.toolbar, labelSettings: this.labelSettings, highlightWeekends: true, allowUnscheduledTasks: true, toolbarClick: this.toolbarClickEvent.bind(this), splitterSettings: this.splitterSettings, columns: this.columns, projectStartDate: this.projectStartDate, projectEndDate: this.projectEndDate },
                    React.createElement(ej2_react_gantt_1.Inject, { services: [ej2_react_gantt_1.Toolbar, ej2_react_gantt_1.Edit, ej2_react_gantt_1.Selection, ej2_react_gantt_1.DayMarkers] }))),
            React.createElement("div", { id: "action-description" },
                React.createElement("p", null, "This sample visualizes the support for displaying unscheduled tasks in Gantt and adding empty rows using the custom toolbar button.")),
            React.createElement("div", { id: "description" },
                React.createElement("p", null,
                    "Unscheduled tasks are tasks in a project that are not scheduled with proper dates or duration at the commencement of the project. These tasks can be scheduled properly at any time during project implementation based on factors such as resource availability, dependent tasks, and more. This example shows how to display the unscheduled tasks in Gantt by enabling the ",
                    React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/api/gantt#allowunscheduledtasks" }, "allowUnscheduledTasks"),
                    " property. This also shows how to add an empty row in Gantt by using a custom toolbar button click action. By using the ",
                    React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/api/gantt/index-default#toolbarclick" }, "toolbarClick"),
                    " event and ",
                    React.createElement("code", null, "addRecord"),
                    " method, an empty row can be added at the top of the rows with undefined task details."),
                React.createElement("p", null,
                    "Gantt component features are segregated into individual feature-wise modules. To use a toolbar, selection and add features, we need to inject the ",
                    React.createElement("code", null, "Toolbar"),
                    ", ",
                    React.createElement("code", null, "Selection"),
                    " and ",
                    React.createElement("code", null, "Edit"),
                    " into the ",
                    React.createElement("code", null, "Inject Services"),
                    " section."),
                React.createElement("br", null),
                React.createElement("p", null,
                    "More information on the Essential",
                    React.createElement("sup", null, "\u00AE"),
                    " React Gantt Chart can be found in this ",
                    React.createElement("a", { target: "_blank", href: "https://ej2.syncfusion.com/react/documentation/gantt/scheduling-tasks#enable-unscheduled-tasks" }, "documentation section"),
                    "."))));
    };
    return UnscheduledTask;
}(sample_base_1.SampleBase));
exports.UnscheduledTask = UnscheduledTask;

// syncfusionejs2_trial/Samples/Vue/src/gantt/unscheduled-task.vue
<template>
  <div>
    <div class="control-section">
      <div class="content-wrapper">
        <ejs-gantt ref="unscheduleGantt" id="unscheduledGantt" :dataSource= "dataSource" :taskFields= "taskFields"
          :editSettings= "editSettings" :toolbar= "toolbar":height="height" :rowHeight="46" :taskbarHeight="25"
          :labelSettings= "labelSettings" :allowUnscheduledTasks= "allowUnscheduledTasks" :projectStartDate= "projectStartDate"
          :projectEndDate= "projectEndDate" :columns= "columns" :splitterSettings= "splitterSettings"
          v-on:toolbarClick= "toolbarClick">
        </ejs-gantt>
      </div>
    </div>
    <div id="action-description">
      <p>This sample visualizes the support for displaying unscheduled tasks in Gantt and adding empty rows using the custom toolbar button.</p>
    </div>

    <div id="description">
      <p>
        Unscheduled tasks are tasks in a project that are not scheduled with proper dates or duration at the commencement of the project. These tasks can be scheduled properly at any time during project implementation based on factors such as resource availability, dependent tasks, and more.
        This example shows how to display the unscheduled tasks in Gantt by enabling the <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/api/gantt#allowunscheduledtasks">allowUnscheduledTasks</a> property. This also shows how to add an empty row in Gantt by using a custom toolbar button click action. By using the <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/api/gantt#toolbarclick">toolbarClick</a> event and <code>addRecord</code> method, an empty row can be added at the top of the rows with undefined task details.
      </p>
      <p style="font-weight: 500">Injecting Module:</p>
      <p>
        Gantt component features are segregated into individual feature-wise modules. To use selection, toolbar and add support,
        inject the <code>Selection</code>, <code>Toolbar</code> and <code>Edit</code> modules using the <code>provide</code> section.
      </p>
      <p>More information on the Essential<sup>®</sup> Vue Gantt Chart can be found in this <a target="_blank" href="https://ej2.syncfusion.com/vue/documentation/gantt/scheduling-tasks#unscheduled-tasks">documentation section</a>.</p>
    </div>
  </div>
</template>
<script>
import { GanttComponent, Edit, Toolbar, Selection, DayMarkers } from "@syncfusion/ej2-vue-gantt";
import { unscheduledData } from "./data-source";

export default {
  components: {
    'ejs-gantt': GanttComponent
  },
  data: function() {
    return {
      dataSource: unscheduledData,
      taskFields: {
        id: 'TaskId',
        name: 'TaskName',
        startDate: 'StartDate',
        endDate: 'EndDate',
        duration: 'Duration',
      },
      editSettings: {
        allowAdding: true,
        allowEditing: true
      },
      toolbar: [{ text: 'Insert task', tooltipText: 'Insert task at top', id: 'toolbarAdd', prefixIcon: 'e-add-icon tb-icons' }],
      height: '650px',
      labelSettings: {
        leftLabel: 'TaskName',
        rightLabel: 'TaskType'
      },
      columns: [
        {field: 'TaskId', width: 90, },
        {field: 'TaskName', width: 100 },
        {field: 'StartDate', width: 180},
        {field: 'EndDate', width: 120 },
        {field: 'Duration', width: 150 }
      ],
      splitterSettings: {
        columnIndex: 4
      },
      allowUnscheduledTasks: true,
      highlightWeekends: true,
      projectStartDate: new Date('12/29/2024'),
      projectEndDate: new Date('02/14/2025'),
    };
  },
  provide: {
    gantt: [Edit, Toolbar, Selection, DayMarkers]
  },
  methods: {
    toolbarClick: function() {
      let data = {
          Duration: null,
          StartDate: null,
          EndDate: null,
          TaskType: ''
      };
      this.$refs.unscheduleGantt.addRecord(data);
    }
  }
}
</script>

<style scoped>
.e-add-icon:before {
  content: "\e836";
  font-size : 16px;
  font-family : "e-icons"
}
#unscheduledGantt ::v-deep  .e-add-icon:before {
  content: "\e506";
  font-size : 16px;
  font-family : "e-icons"
}
.bootstrap4 #unscheduledGantt ::v-deep  .e-add-icon:before {
  content: "\e783";
  font-size : 16px;
  font-family : "e-icons"
}
.bootstrap5 #unscheduledGantt ::v-deep  .e-add-icon:before,
.bootstrap5-dark #unscheduledGantt ::v-deep  .e-add-icon:before,
.tailwind #unscheduledGantt ::v-deep .e-add-icon:before,.tailwind-dark #unscheduledGantt ::v-deep .e-add-icon:before,
.material3-dark #unscheduledGantt ::v-deep .e-add-icon:before ,.material3 #unscheduledGantt ::v-deep .e-add-icon:before,
.tailwind3 #unscheduledGantt ::v-deep .e-add-icon:before,.tailwind3-dark #unscheduledGantt ::v-deep .e-add-icon:before {
  content: "\e836";
  font-size : 16px;
  font-family : "e-icons"
}
.fluent #unscheduledGantt ::v-deep .e-add-icon:before,
.fluent-dark #unscheduledGantt ::v-deep .e-add-icon:before,
.fluent2 #unscheduledGantt ::v-deep .e-add-icon:before,
.fluent2-highcontrast #unscheduledGantt ::v-deep .e-add-icon:before,
.fluent2-dark #unscheduledGantt ::v-deep .e-add-icon:before,
.bootstrap5_3 #Unscheduled ::v-deep .e-add-icon:before,
.bootstrap5_3-dark-lite #Unscheduled ::v-deep .e-add-icon:before,
.bootstrap5_3-dark #Unscheduled ::v-deep .e-add-icon:before, 
.bootstrap5_3-lite #Unscheduled ::v-deep .e-add-icon:before{
  content: "\e836" !important;
  font-size : 16px;
  font-family : "e-icons"
}

</style>
