// syncfusionejs2_trial/Samples/Vue/public/source/ai-querybuilder/ai-natural-language-query.vue
<template>
    <div class="control-pane">
      <div class="control-section">
        <div class="description-container e-card">
          <div class="e-card-header-title" style="font-weight: 600">AI Driven NL Querying in Query Builder</div>
          <div class="e-card-content">
            <p>
              The Natural Language Querying feature enables users to input queries in plain language, which the system then
              interprets to automatically generate the appropriate database queries. This simplifies the process of data
              retrieval, allowing users to obtain insights without needing to understand complex query syntax.
            </p>
          </div>
        </div>
        <div id="wrapper">
          <ejs-tab id="tab">
            <e-tab-items>
              <e-tab-item :header="headerText[0]" content="#prompt-ui"></e-tab-item>
              <e-tab-item :header="headerText[1]" content="#querybuilder-ui"></e-tab-item>
            </e-tab-items>
          </ejs-tab>
          <div id="prompt-ui">
            <div id="customTbarDialog">
              <span class="e-text">Instruct AI</span>
              <textarea id="text-area" aria-label="ai assistant query box" placeholder="find all users who lives in los angeles and have over 1000 credits"></textarea>
            </div>
          </div>
          <div style="display: none">
            <div id="querybuilder-ui">
              <ejs-querybuilder id="querybuilder" class="row" ref="qryBldrObj" :dataSource="users" :columns="columnData"></ejs-querybuilder>
            </div>
          </div>
          <div class="e-custom-elem">
            <ejs-button id="submit" iconCss="e-icons e-reset" @click="clicked" :isPrimary="true">Generate Query</ejs-button>
          </div>
          <div class="e-custom-elem">
            <span class="e-text">Results from your AI generated Query</span>
            <ejs-grid id="grid" ref="gridInstance" :dataSource="users" :allowPaging="true" :pageSettings="{ pageSize: 10 }" style="margin-top: 10px">
              <e-columns>
                <e-column field="id" headerText="ID" textAlign="Right" width="120"></e-column>
                <e-column field="name" headerText="Name" width="120"></e-column>
                <e-column field="email" headerText="Email" width="150"></e-column>
                <e-column field="address" headerText="Address" width="120"></e-column>
                <e-column field="city" headerText="City" width="120"></e-column>
                <e-column field="state" headerText="State" width="120"></e-column>
                <e-column field="credits" headerText="Credits" width="120"></e-column>
              </e-columns>
            </ejs-grid>
          </div>
        </div>
      </div>
    </div>
</template>

<script>
import { enableRipple, isNullOrUndefined } from '@syncfusion/ej2-base';
import { QueryBuilderComponent } from '@syncfusion/ej2-vue-querybuilder';
import { ButtonComponent } from '@syncfusion/ej2-vue-buttons';
import { TabComponent, TabItemDirective, TabItemsDirective } from '@syncfusion/ej2-vue-navigations';
import { ColumnDirective, ColumnsDirective, GridComponent } from '@syncfusion/ej2-vue-grids';
import { Query, Predicate } from '@syncfusion/ej2-data';
import { createSpinner, showSpinner, hideSpinner } from '@syncfusion/ej2-popups';
import { getAzureTextAIRequest } from '../common/openai';

enableRipple(true);

export default {
    name: 'NLQuerying',
    components: {
      'ejs-querybuilder': QueryBuilderComponent,
      'ejs-button': ButtonComponent,
      'ejs-tab': TabComponent,
      'e-tab-items': TabItemsDirective,
      'e-tab-item': TabItemDirective,
      'ejs-grid': GridComponent,
      'e-columns': ColumnsDirective,
      'e-column': ColumnDirective,
    },
    data() {
      return {
        headerText: [{ text: 'Natural Language Query' }, { text: 'Query Builder UI' }],
        columnData: [
          { field: 'id', label: 'ID', type: 'number' },
          { field: 'name', label: 'Name', type: 'string' },
          { field: 'email', label: 'Email', type: 'string' },
          { field: 'address', label: 'Address', type: 'string' },
          { field: 'city', label: 'City', type: 'string' },
          { field: 'state', label: 'State', type: 'string' },
          { field: 'credits', label: 'Credits', type: 'number' }
        ],
        users: []
      };
    },
    mounted() {
      createSpinner({
        target: document.getElementById('grid')
      });
      document.getElementById('text-area').value = 'find all users who lives in los angeles and have over 1000 credits';
      this.users = this.generateRandomUsers(20);
    },
    methods: {
      generateRandomUsers(count) {
        const names = ["John", "Jane", "Bob", "Alice", "Tom", "Sally", "Jim", "Mary", "Peter", "Nancy"];
        const cities = ["Los Angeles", "San Diego", "New York", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "Dallas", "San Jose"];
        const states = ["California", "New York", "Illinois", "Texas", "Arizona", "Pennsylvania"];
        const streets = ["Elm St", "Oak St", "Maple Ave", "Pine St", "Cedar St", "Birch St"];
        const emails = ["example.com", "test.com", "demo.com"];
        const users = [];

        for (let i = 0; i < count; i++) {
          const id = i + 1;
          const name = names[Math.floor(Math.random() * names.length)];
          const email = `${name.toLowerCase()}${id}@${emails[Math.floor(Math.random() * emails.length)]}`;
          const address = `${Math.floor(Math.random() * 10000)} ${streets[Math.floor(Math.random() * streets.length)]}`;
          const city = cities[Math.floor(Math.random() * cities.length)];
          const state = states[Math.floor(Math.random() * states.length)];
          const zipcode = `${Math.floor(10000 + Math.random() * 90000)}`;
          const credits = Math.floor(Math.random() * 2001);
          users.push({ id, name, email, address, city, state, zipcode, credits });
        }

        return users;
      },
      clicked() {
        showSpinner(document.getElementById('grid'));
        let textArea = "write SQL query to " + document.querySelector('#text-area').value + " from the single table without changing the given values";
        let aiOutput = getAzureTextAIRequest(textArea);
        aiOutput.then((result) => {
          let val = result.split("```sql")[1].split("WHERE ")[1].split(";\n")[0];
          val = val.replace("\n", "");
          this.$refs.qryBldrObj.setRulesFromSql(val);
          let predicate = this.$refs.qryBldrObj.getPredicate(this.$refs.qryBldrObj.getValidRules());
          let query;
          if (isNullOrUndefined(predicate)) {
            query = new Query();
          } else {
            query = new Query().where(predicate);
          }
          this.$refs.gridInstance.query = query;
          this.$refs.gridInstance.refresh();
          hideSpinner(document.getElementById('grid'));
        });
      }
    }
};
</script>

<style>
#wrapper {
    margin: 10px;
    border: 1px solid lightgray;
    border-radius: 4px;
}

#text-area{
    width: calc(100% - 22px);
    height: 100px;
    margin-top: 5px;
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 4px;
    resize: none;
}

.e-tab .e-content {
    padding: 16px;
}

.e-text {
    font-weight: bold;
    font-family: "Roboto", -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", sans-serif;
    font-size: 14px;
}

.e-custom-elem {
    margin-bottom: 16px;
    margin-left: 16px;
    width: calc(100% - 32px);
}
</style>

// syncfusionejs2_trial/Samples/React/src/ai-querybuilder/ai-natural-language-query.js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var ej2_base_1 = require("@syncfusion/ej2-base");
var ej2_react_querybuilder_1 = require("@syncfusion/ej2-react-querybuilder");
var ej2_react_buttons_1 = require("@syncfusion/ej2-react-buttons");
var ej2_react_navigations_1 = require("@syncfusion/ej2-react-navigations");
var ej2_react_grids_1 = require("@syncfusion/ej2-react-grids");
var ej2_data_1 = require("@syncfusion/ej2-data");
var ej2_popups_1 = require("@syncfusion/ej2-popups");
var react_1 = require("react");
require("./nl-querying.css");
var ai_service_1 = require("../common/ai-service");
(0, ej2_base_1.enableRipple)(true);
function AiNLQuerying() {
    (0, react_1.useEffect)(function () {
        (0, ej2_popups_1.createSpinner)({
            target: document.getElementById('grid')
        });
        document.getElementById('text-area').value = 'find all users who lives in los angeles and have over 1000 credits';
    }, []);
    var gridInstance;
    var qryBldrObj;
    var headerText = [{ text: 'Natural Language Query' }, { text: 'Query Builder UI' }];
    function generateRandomUsers(count) {
        var names = ["John", "Jane", "Bob", "Alice", "Tom", "Sally", "Jim", "Mary", "Peter", "Nancy"];
        var cities = ["Los Angeles", "San Diego", "New York", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "Dallas", "San Jose"];
        var states = ["California", "New York", "Illinois", "Texas", "Arizona", "Pennsylvania"];
        var streets = ["Elm St", "Oak St", "Maple Ave", "Pine St", "Cedar St", "Birch St"];
        var emails = ["example.com", "test.com", "demo.com"];
        var users = [];
        for (var i = 0; i < count; i++) {
            var id = i + 1;
            var name_1 = names[Math.floor(Math.random() * names.length)];
            var email = "".concat(name_1.toLowerCase()).concat(id, "@").concat(emails[Math.floor(Math.random() * emails.length)]);
            var address = "".concat(Math.floor(Math.random() * 10000), " ").concat(streets[Math.floor(Math.random() * streets.length)]);
            var city = cities[Math.floor(Math.random() * cities.length)];
            var state = states[Math.floor(Math.random() * states.length)];
            var zipcode = "".concat(Math.floor(10000 + Math.random() * 90000));
            var credits = Math.floor(Math.random() * 2001);
            users.push({ id: id, name: name_1, email: email, address: address, city: city, state: state, zipcode: zipcode, credits: credits });
        }
        return users;
    }
    var columnData = [
        { field: 'id', label: 'ID', type: 'number' },
        { field: 'name', label: 'Name', type: 'string' },
        { field: 'email', label: 'Email', type: 'string' },
        { field: 'address', label: 'Address', type: 'string' },
        { field: 'city', label: 'City', type: 'string' },
        { field: 'state', label: 'State', type: 'string' },
        { field: 'credits', label: 'Credits', type: 'number' }
    ];
    var users = generateRandomUsers(20);
    function clicked() {
        (0, ej2_popups_1.showSpinner)(document.getElementById('grid'));
        var textArea = "write SQL query to " + document.querySelector('#text-area').value + " from the single table without changing the given values";
        var aiOutput = (0, ai_service_1.serverAIRequest)({ messages: [{ role: 'user', content: textArea }] });
        aiOutput.then(function (result) {
            if (result) {
                if ((result === null || result === void 0 ? void 0 : result.indexOf("```sql")) !== -1) {
                    result = result.split("```sql")[1];
                }
                var val = result.split("WHERE ")[1].split(";\n")[0];
                val = val.replace("\n", "");
                qryBldrObj.setRulesFromSql(val);
                var predicate = qryBldrObj.getPredicate(qryBldrObj.getValidRules());
                var query = void 0;
                if ((0, ej2_base_1.isNullOrUndefined)(predicate)) {
                    query = new ej2_data_1.Query();
                }
                else {
                    query = new ej2_data_1.Query().where(predicate);
                }
                gridInstance.query = query;
                gridInstance.refresh();
                (0, ej2_popups_1.hideSpinner)(document.getElementById('grid'));
            }
            else {
                (0, ej2_popups_1.hideSpinner)(document.getElementById('grid'));
            }
        });
    }
    return (React.createElement("div", { className: 'control-pane' },
        React.createElement("div", { className: 'control-section' },
            React.createElement("div", { id: "ai-wrapper" },
                React.createElement(ej2_react_navigations_1.TabComponent, { id: "ai-tab" },
                    React.createElement(ej2_react_navigations_1.TabItemsDirective, null,
                        React.createElement(ej2_react_navigations_1.TabItemDirective, { header: headerText[0], content: '#prompt-ui' }),
                        React.createElement(ej2_react_navigations_1.TabItemDirective, { header: headerText[1], content: '#querybuilder-ui' }))),
                React.createElement("div", { id: "prompt-ui" },
                    React.createElement("div", { id: "customTbarDialog" },
                        React.createElement("span", { className: "ai-e-text" }, "Query"),
                        React.createElement("textarea", { id: "text-area", "aria-label": "ai assistant query box", placeholder: "find all users who lives in los angeles and have over 1000 credits" }))),
                React.createElement("div", { style: { display: "none" } },
                    React.createElement("div", { id: "querybuilder-ui" },
                        React.createElement(ej2_react_querybuilder_1.QueryBuilderComponent, { id: "querybuilder", className: "row", ref: function (querybuilder) { return qryBldrObj = querybuilder; }, dataSource: users, columns: columnData }))),
                React.createElement("div", { className: "e-custom-elem" },
                    React.createElement(ej2_react_buttons_1.ButtonComponent, { id: "submit", iconCss: 'e-icons e-play', onClick: clicked, isPrimary: true }, "Run Query")),
                React.createElement("div", { className: "e-custom-elem" },
                    React.createElement("span", { className: "ai-e-text" }, "Results from your AI generated Query"),
                    React.createElement(ej2_react_grids_1.GridComponent, { style: { marginTop: "10px" }, id: "grid", ref: function (grid) { return gridInstance = grid; }, dataSource: users, allowPaging: true, pageSettings: { pageSize: 10 } },
                        React.createElement(ej2_react_grids_1.ColumnsDirective, null,
                            React.createElement(ej2_react_grids_1.ColumnDirective, { field: 'id', headerText: 'ID', textAlign: 'Right', width: 120 }),
                            React.createElement(ej2_react_grids_1.ColumnDirective, { field: 'name', headerText: 'Name', width: 120 }),
                            React.createElement(ej2_react_grids_1.ColumnDirective, { field: 'email', headerText: 'Email', width: 150 }),
                            React.createElement(ej2_react_grids_1.ColumnDirective, { field: 'address', headerText: 'Address', width: 120 }),
                            React.createElement(ej2_react_grids_1.ColumnDirective, { field: 'city', headerText: 'City', width: 120 }),
                            React.createElement(ej2_react_grids_1.ColumnDirective, { field: 'state', headerText: 'State', width: 120 }),
                            React.createElement(ej2_react_grids_1.ColumnDirective, { field: 'credits', headerText: 'Credits', width: 120 })),
                        React.createElement(ej2_react_navigations_1.Inject, { services: [ej2_react_grids_1.Page] })))))));
}
exports.default = AiNLQuerying;
